### ISSUE TITLE
[Bug]: Screen takes longer to Refresh

### ISSUE THREAD

**Issue by Exnadella** [RedisInsight/RedisInsight#1006]
**Preconditions** (Any important steps we need to know)
The Size of the JSON Key is 141B and the length of the Key is 6972.  When we try to fetch the results inside the new RedisInsight Browser it takes a longer time more than 1 hrs to fetch all the results.

**Steps to reproduce** (How to reproduce what you found step by step)
We can enter any kay of this size and length, each key is only of the length "XXXXXX" - "X" but multiple keys.

**Actual behavior** (A short description of what you found)
The screen refreshes but no data is visible.

**Expected behavior** (A short description of what you expected to find)
The screen should display the JSON Document.

**Screenshots** (Paste or drag-and-drop a screenshot or a link to a recording)
![image](https://user-images.githubusercontent.com/22579094/184009804-8259d0f1-5075-4afe-b4df-4736873ef44a.png)

**Additional context** (Operating system, version of RedisInsight, Redis database version, Redis module version, database type, connection type, logs, or any other information)

Windows 11, RedisInsight-v2 (2.6.0), 6.2.3, RedisJSON  v 2.0.11,  RediSearch v 2.4.9, TLS Connection enabled, Redis DB is hosted on RedisLabs, on AWS Cloud us-east-1.  The total size of the DB is 57MB, Size of the DB is 100 MB with a limitation of 256 connections.  The performance of this key is always slow from the beginning when the size of the DB is 10 MB.

**Comment by Exnadella** [comment]
Even after 19 minutes, the key did not fetch any results.  Please find the attached screen shot.
![image](https://user-images.githubusercontent.com/22579094/184012099-937762d0-049b-4e43-96a1-fc24560c1aad.png)

I have executed the profiler and it has fetched the below log and it is fetching the key values inside the JSON.
![image](https://user-images.githubusercontent.com/22579094/184012598-e607f2ae-ea69-4908-89bb-279cbb7e7c45.png)
![image](https://user-images.githubusercontent.com/22579094/184012720-5784bbc9-f4c9-480e-a82e-efb447ae10a9.png)
![image](https://user-images.githubusercontent.com/22579094/184012632-ce7c61cb-73fe-4571-a067-6207ed798e84.png)

**Comment by ViktarStarastsenka** [comment]
hi @Exnadella , please try 2.50 (released today).
This case should be optimized.
Please re-open the ticket if the issue still reproduces.
