### ISSUE TITLE
how to select db?

### ISSUE THREAD

**Issue by anziguoer** [RedisInsight/RedisInsight#101]
1. how to select db? I can't find any ways to change other DB ?
2. I can't find close linked button.
![image](https://user-images.githubusercontent.com/6418340/145565005-92059213-5d7e-485a-b8eb-b3c1e8ccf62a.png)

**Comment by ViktorStarostenko** [comment]
Hi @anziguoer , do you want to return to the list of databases added to RI or select another logical database (change the database index) for this one?

**Comment by anziguoer** [comment]
I mean is how to select other database in version 2?

![image](https://user-images.githubusercontent.com/6418340/145661089-019bb81e-a398-41e7-869f-7510ddec1618.png)

**Comment by anziguoer** [comment]
> Hi @anziguoer , do you want to return to the list of databases added to RI or select another logical database (change the database index) for this one?

I mean is how to select other database in version 2?

![image](https://user-images.githubusercontent.com/6418340/145661089-019bb81e-a398-41e7-869f-7510ddec1618.png)

**Comment by ViktorStarostenko** [comment]
> I mean is how to select other database in version 2?

Currently, this database index for Browser can be specified only at the step of adding a database to RedsInsight v2 ("Database Index" field).
You can add another database with the same endpoint, but a different database index to work in Browser (more preferred way). But please notice that in this case, the default database index to work in CLI and Workbench is still 0.
Or, as a workaround, you can use the "Select" command in CLI - it will change the database index in CLI, but will not affect Browser (less preferred way).

Hope this helps.

**Comment by anziguoer** [comment]
> > I mean is how to select other database in version 2?
> 
> Currently, this database index for Browser can be specified only at the step of adding a database to RedsInsight v2 ("Database Index" field). You can add another database with the same endpoint, but a different database index to work in Browser (more preferred way). But please notice that in this case, the default database index to work in CLI and Workbench is still 0. Or, as a workaround, you can use the "Select" command in CLI - it will change the database index in CLI, but will not affect Browser (less preferred way).
> 
> Hope this helps.

Ok, thank you. What version is planned to add select Database functionality? thank you，  I very like the RedisInsight.

**Comment by ViktorStarostenko** [comment]
Hello @anziguoer, I believe that currently, the main flow is to add another database with the same endpoint, but with a different database index to work with, and just open another database if you need to work with another database index.

Could you please provide any use cases when this flow will not satisfy your purposes?

**Comment by nsnyder** [comment]
Came across this while trying to figure out how to change databases earlier today. IMO, it would be helpful to provide one or two flows.
1. Allow selecting different databases from a single endpoint (potentially with assignable names) OR
2. Allow copying an existing endpoint instead of adding a new one (so you don't have to re-enter the same information just to change the database index)

It's particularly confusing if you have an existing endpoint and find that you need to use a different database. You likely won't remember that the only place to set that is during initial setup. You might go to edit your connection to change it, and find the setting isn't there (as I did) only to be confused and go searching (and ending up here). Or you may suspect (as I did) that changing it from the CLI window will change where the UI searches.

One way or another, I think a bit of guidance for someone trying to figure out how to change their database in the UI would go a long way.

**Comment by ViktorStarostenko** [comment]
@nsnyder , thanks for the details, we will look into options to make the interaction with different database indices clearer.

**Comment by KangZhengF** [comment]
I love the RedisInsight very much! You are good guys to develop this tool for us. But I still you can add the select database feature in your next version. Thx!

**Comment by 838239178** [comment]
Does any plan to add this feature? 👍

**Comment by ViktarStarastsenka** [comment]
@KangZhengF , @838239178 , currently the only one way to change the logical database is to add another database with the same host and port. I understand that this is not the most convenient way, but will it work if you could quickly clone the database to not re-enter database credentials manually, change the logical database and then add the database with another logical database selected?
In this case you will need just to open another database.

**Comment by rocna** [comment]
Wow, that seems to be a work in progress. But selecting a database is much easier than adding one. Redis is very fast and most scenarios are shared by multiple programs to take full advantage of Redis performance. 👍

**Comment by ViktarStarastsenka** [comment]
@guillermosaez , not in the upcoming releases.
will the workaround with adding a new database (also using the "Clone database" feature to avoid manually adding the parameters) work for you?

**Comment by javaDer** [comment]
We need this feature too much

**Comment by erik-re** [comment]
As coming from different redis clients, it'd be very useful to have a list of databases (maybe even containing the number of sets in each db) in one connection, as other users have stated in this thread.

+1

**Comment by guillermosaez** [comment]
Hello @ViktarStarastsenka, that control doesn't show for me:
![image](https://user-images.githubusercontent.com/28726967/216008999-a82a994a-94ae-4fcb-b9b9-34392ba9e764.png)

**Comment by ViktarStarastsenka** [comment]
@guillermosaez , can you please run the `INFO KEYSPACE` and share the results?

**Comment by guillermosaez** [comment]
@ViktarStarastsenka 
![image](https://user-images.githubusercontent.com/28726967/216031979-8d9b868b-aebc-401c-849b-e9815cb676bb.png)

**Comment by ViktarStarastsenka** [comment]
@guillermosaez , can you please additionally run the "CONFIG GET DATABASES"?

**Comment by guillermosaez** [comment]
@ViktarStarastsenka 
![image](https://user-images.githubusercontent.com/28726967/216047659-b269c4af-bf89-4b62-9280-38bc68d0861f.png)

**Comment by ViktarStarastsenka** [comment]
@guillermosaez , currently, you do not have permission to run the `CONFIG` command, which is used to define if there are any database indexes.
We will enhance the logic in the next releases

**Comment by guillermosaez** [comment]
> @guillermosaez , currently, you do not have permission to run the `CONFIG` command, which is used to define if there are any database indexes. We will enhance the logic in the next releases

@ViktarStarastsenka thank you for clarification. As I can read [here](https://learn.microsoft.com/en-us/azure/azure-cache-for-redis/cache-configure#redis-commands-not-supported-in-azure-cache-for-redis), it seems the `CONFIG` command is disabled for "Azure cache for Redis", which is what I am using.
Is there any workaround?
