### ISSUE TITLE
[Bug]: Question: multiple different brew install sequence resulting in multiple redisinsights applications being installed

### ISSUE THREAD

**Issue by cequencer** [RedisInsight/RedisInsight#1014]
**Preconditions** (Any important steps we need to know)

I have a Mac running macOS Monterey version 12.4 (Apple Silicon M1) without any Redis components.  
My goal is to have the all the right Redis components and runtime stack to start developing Redis application.

**Steps to reproduce** (How to reproduce what you found step by step)

This is the sequence of steps I followed:
1. https://redis.com/blog/introducing-redisinsight-2/
2. `% brew install --cask redisinsight`
3. https://developer.redis.com/create/redis-stack/
4. `% brew tap redis-stack/redis-stack`
5. `% brew install --cask redis-stack`

**Actual behavior** (A short description of what you found)

After I followed the above sequence, I ended up with 2 redisinsights applications with the following names: `RedisInsight` and `RedisInsight-v2`.  I performed `Get Info` on each of the respective application to obtain more contextual data.

- `RedisInsight.app`
   - Version 2.6.0
   - Created: July 25, 2022 at 5:13 AM
- `RedisInsight-v2.app`
   - Version 2.4.0
   - Created: June 27, 2022 at 12:43 AM

**Expected behavior** (A short description of what you expected to find)

I am reading and follow installation instructions from 2 different sources.  
This is a question to understand what should the expected behavior to expect in this sequence.  
Since I don't know what is the expected behaviors, I can only provide assumption check questions:
1. should install `redis-stack` be aware of the general `redisinsight` install?
2. is `redisInsight` tightly coupled with `redis-stack`?  so any time I need to use `redis-stack` I have to use the corresponding version of the `redisInsight` that comes with `redis-stack`.

**Screenshots** (Paste or drag-and-drop a screenshot or a link to a recording)

Command Line history and output followed the above sequence:
```
% brew install --cask redisinsight
==> Downloading https://download.redisinsight.redis.com/latest/RedisInsight-v2-mac-arm64.dmg
######################################################################## 100.0%
Warning: No checksum defined for cask 'redisinsight', skipping verification.
==> Installing Cask redisinsight
==> Moving App 'RedisInsight-v2.app' to '/Applications/RedisInsight.app'
🍺  redisinsight was successfully installed!

% brew tap redis-stack/redis-stack
==> Tapping redis-stack/redis-stack
Cloning into '/opt/homebrew/Library/Taps/redis-stack/homebrew-redis-stack'...
remote: Enumerating objects: 130, done.
remote: Counting objects: 100% (130/130), done.
remote: Compressing objects: 100% (97/97), done.
remote: Total 130 (delta 50), reused 97 (delta 28), pack-reused 0
Receiving objects: 100% (130/130), 16.90 KiB | 752.00 KiB/s, done.
Resolving deltas: 100% (50/50), done.
Tapped 3 casks (16 files, 30.3KB).

% brew install --cask redis-stack
==> Downloading https://redismodules.s3.amazonaws.com/redis-stack/.donotremove
#=#=-#  #
==> Installing dependencies: openssl@3, libomp, redis-stack-server, redis-stack-redisinsight
==> Downloading https://ghcr.io/v2/homebrew/core/openssl/3/manifests/3.0.5
######################################################################## 100.0%
==> Downloading https://ghcr.io/v2/homebrew/core/openssl/3/blobs/sha256:d0cc00946bd11f14e1e0f94ce7c29ca63e7fdff96afb3f96951c14f4dbfc482e
==> Downloading from https://pkg-containers.githubusercontent.com/ghcr1/blobs/sha256:d0cc00946bd11f14e1e0f94ce7c29ca63e7fdff96afb3f96951c14f4dbfc482e?se=2022-08-11T18%3A15%3A00Z&sig=pxn0D1mqBDVQSCm
######################################################################## 100.0%
==> Installing openssl@3
==> Pouring openssl@3--3.0.5.arm64_monterey.bottle.tar.gz
🍺  /opt/homebrew/Cellar/openssl@3/3.0.5: 6,444 files, 27.9MB
==> Downloading https://ghcr.io/v2/homebrew/core/libomp/manifests/14.0.6
######################################################################## 100.0%
==> Downloading https://ghcr.io/v2/homebrew/core/libomp/blobs/sha256:b36b1393289e7d98fc03425b6c23a63c4f5e9290ecf0922d45e6fde2973ba8fb
==> Downloading from https://pkg-containers.githubusercontent.com/ghcr1/blobs/sha256:b36b1393289e7d98fc03425b6c23a63c4f5e9290ecf0922d45e6fde2973ba8fb?se=2022-08-11T18%3A20%3A00Z&sig=19kNaQ8%2BO33MT
######################################################################## 100.0%
==> Installing libomp
==> Pouring libomp--14.0.6.arm64_monterey.bottle.tar.gz
🍺  /opt/homebrew/Cellar/libomp/14.0.6: 7 files, 1.6MB
==> Downloading https://redismodules.s3.amazonaws.com/redis-stack/redis-stack-server-6.2.4-v1.monterey.arm64.zip
######################################################################## 100.0%
Warning: Cannot verify integrity of '91d9bc0fbb8aea9fdfcd40fed70abeda3493a9651d473eb795af2e9932d4eedb--redis-stack-server-6.2.4-v1.monterey.arm64.zip'.
No checksum was provided for this cask.
For your reference, the checksum is:
  sha256 "d1b8b77049d4fa8f89e7c1727d7bdcb8e3c3ff41e8af9d423118ecdb1421e5ad"
==> Installing Cask redis-stack-server
🍺  redis-stack-server was successfully installed!
==> Downloading https://s3.amazonaws.com/redisinsight.download/public/releases/2.4.0/redisstack/RedisInsight-v2-app-darwin.arm64.tar.gz
######################################################################## 100.0%
Warning: Cannot verify integrity of '760d33fa34e64835164540decd6fef09d02a082b78541a2a5c368e25a9670ebb--RedisInsight-v2-app-darwin.arm64.tar.gz'.
No checksum was provided for this cask.
For your reference, the checksum is:
  sha256 "ca30534826eb241803a9994708241bb02c7cf839ae015c186191749833407b2b"
==> Installing Cask redis-stack-redisinsight
==> Moving App 'RedisInsight-v2.app' to '/Applications/RedisInsight-v2.app'
🍺  redis-stack-redisinsight was successfully installed!
==> Installing Cask redis-stack
🍺  redis-stack was successfully installed!
```

**Additional context** (Operating system, version of RedisInsight, Redis database version, Redis module version, database type, connection type, logs, or any other information)

**Comment by ViktarStarastsenka** [comment]
hi, there was an issue with the version of RedisInsight-v2.app - it should be 2.6.0, not 2.4.0 (fixed now).
and you can use any version of RedisInsight to work with Redis Stack

**Comment by cequencer** [comment]
Thank you for fixing the version of RedisInsight-v2.app.
I did a `brew upgrade` and RedisInsight-v2.app is now on-par at 2.6.0 with RedisInsight.app.

Is there any difference between these 2 RedisInsight (Cask) apps that originates from 2 different homebew taps?  
I would like to just have 1 install of RedisInsight if at all possible.  Which cask should I uninstall without breaking any functionality or assumptions of the Redis stack?

**Comment by cequencer** [comment]
Thanks for the confirmation and suggestion.  

I uninstalled the standalone app and is now using the `--cask redis-stack` as suggested.

```
% brew uninstall --cask redisinsight
==> Uninstalling Cask redisinsight
==> Backing App 'RedisInsight.app' up to '/opt/homebrew/Caskroom/redisinsight/2.6.0/RedisInsight-v2.app'
==> Removing App '/Applications/RedisInsight.app'
==> Purging files for version 2.6.0 of Cask redisinsight

```

Now, the remaining RedisInsights instance is working as before.  
`/opt/homebrew/Caskroom/redisinsight/2.6.0/RedisInsight-v2.app`

Thank you for clearing up my assumption check questions.  
I am okay with closing this ticket as resolved.
