### ISSUE TITLE
Has anyone been able to successfully use RIAUTHPROMPT, RIAUTHTIMER env variables?

### ISSUE THREAD

**Issue by kubetin** [RedisInsight/RedisInsight#1021]
I can't seem to figure out how to use these correctly. I am still never prompted to authenticate

**Comment by GnaneshKunal** [comment]
Hey @kubetin,

Try running the following:
```
 docker run -it --net host -e RIAUTHPROMPT=t -e RIAUTHTIMER=1 redislabs/redisinsight:1.12.1
```

The above enables the idle timer of 1 minute. Let us know if you are still facing issues

**Comment by blars** [comment]
It seems like many of the environment variables mentioned are not working with the latest (possibly 2.0+) versions of redisinsight.  I was not able to get RIPROXYPATH working either until I switched to the redislabs/redisinsight:1.13.0 image.  It did not work with redislabs/redisinsight:latest.

**Comment by GnaneshKunal** [comment]
@kubetin @blars 

The feature is meant to be only for v1 and not v2. Please open a new issue for v2 if needed.
