### ISSUE TITLE
[Feature Request]: Support displaying MessagePack values

### ISSUE THREAD

**Issue by rsabirov** [RedisInsight/RedisInsight#106]
**Problem Description** In our product we are using MessagePack serialization for values stored in Redis, and currently RedisInsight doesn't support deserialization/displaying of such values. 

**How often do you encounter this problem** Every day :).

**Alternatives considered** Currently only one commercial tool is supporting displaying MessagePack values.

**Additional information** I think it should be supported for any place we can have values, i.e. Hashsets, Strings, Sets....

**Comment by ViktarStarastsenka** [comment]
@rsabirov , are there any use cases when you will need different formatters for one key? e.g. MessagePack for one Hash value and JSON for another value of the same Hash?

**Comment by rsabirov** [comment]
@ViktarStarastsenka in my case it was MessagePack for everything.

**Comment by ViktarStarastsenka** [comment]
hi @rsabirov , MessagePack is supported with 2.8.0 (released recently).
