### ISSUE TITLE
Grouping keys in treeview like RedisDesktopManager

### ISSUE THREAD

**Issue by CryptoTradee** [RedisInsight/RedisInsight#107]
Would like it to group keys together in a tree seperated by a character in the key

**Comment by ollopaci** [comment]
Hi @CryptoTradee. Thanks for raising this. The feature has been prioritised and is currently in design stage.

**Comment by CryptoTradee** [comment]
Ok great. Also make the grouping character customisable and can go down
multiple levels.

Cheers

**Comment by doggy8088** [comment]
@ollopaci Do you have roadmap for RedisInsight? Will this grouping keys feature available soon?

**Comment by ViktarStarastsenka** [comment]
Hello @CryptoTradee , @doggy8088 , the Tree view has been added with the latest release. You can download it here: https://redis.com/redis-enterprise/redis-insight/#insight-form

**Comment by CryptoTradee** [comment]
Thanks. However 3 things:
* Far too much space is used for the navigation of the keys and hence when you get to a hash value for instance, you cannot see much of the hash values. It would be better to remove that 2nd pane and navigate the keys on the far left panel instead. Sorry, Redis Desktop Manager is still better as it stands.
* I'd also make the tree view be default
* The character to group them is not customisable from what I see. No big deal for me now but would be nice.

**Comment by ViktarStarastsenka** [comment]
@CryptoTradee ,

You can manually resize the panels and customise their width to fit your purposes (just click and drag the borders). And you will have enough space to see the key type, key name, TTL and key size in the list of keys.
Does this cover your use cases?

The customisation of delimiters is prioritised and is planned to be released in April.

**Comment by CryptoTradee** [comment]
![Screenshot 2022-03-29 090338](https://user-images.githubusercontent.com/45982911/160501237-d89426ea-f264-4b30-ad30-24332aa16ddd.png)

No, this is so hard to read. I can't resize the field column and then cant even read the value. The 2nd panel is just wasting so much screen space that could be using to view the value. This is specially relevant for fields/hash

**Comment by ViktarStarastsenka** [comment]
Thanks, will think how to improve this.

**Comment by ViktarStarastsenka** [comment]
Hi @CryptoTradee, please check 2.0.6 - you can set custom delimiters in the Tree view here

**Comment by ViktarStarastsenka** [comment]
Also what do you think - if we add the "full screen" mode for the key values part and display Hash fields and values in full screen, will it fix your use case where you cannot read the value?
It will definitely help to read more characters.

**Comment by ViktarStarastsenka** [comment]
@CryptoTradee , can you please check 2.2.0? Here you can close key details to see the list of keys in full screen or open key details in full screen to see more information.
Let me know if this resolves your case.

**Comment by CryptoTradee** [comment]
I guess it's something but I'd still rather get rid of the middle panel.

**Comment by ViktarStarastsenka** [comment]
@CryptoTradee , with 2.6.0 (release yesterday) you can click the key value to expand it and see the full value.
Hope it helps. If not - please re-open the ticket.

**Comment by CryptoTradee** [comment]
Sorry, this is a small improvement however still very hard to read. Need to be able to resize the "field" column so can have more space for "Value" for hashes. The value is much longer than the FIeld right.

**Comment by CryptoTradee** [comment]
Also, please prioritise https://github.com/RedisInsight/RedisInsight/issues/472 as this is biggest thing needed now IMO

**Comment by ViktarStarastsenka** [comment]
@CryptoTradee , we are planning to add the JSON formatting with August (2.8.0) release.
