### ISSUE TITLE
Can you consider adding the function of editing database aliases?

### ISSUE THREAD

**Issue by zhuyouzhufu** [RedisInsight/RedisInsight#1093]
When using this redis visual interface, I tried to add a connection to see if I could connect to my redis server. When I connect successfully, I find that my alias is meaningless. I want to edit the database alias and find that there seems to be no such entry. This is not very good for the user's experience

**Comment by ViktarStarastsenka** [comment]
Hi @zhuyouzhufu , I assume you use RedisInsight V2, please follow these steps:
1. Open the database list
2. Click to edit the database
3. Click the database alias to change it (screen attached).

<img width="515" alt="Screenshot 2022-08-31 at 10 03 11" src="https://user-images.githubusercontent.com/99594890/187641451-c5d87e6c-f15a-48fd-8578-f03e4a02488c.png">

**Comment by zhuyouzhufu** [comment]
Thank you. I didn't find that this place is clickable. My version is v2
