### ISSUE TITLE
[Feature Request]: We need web app too

### ISSUE THREAD

**Issue by NoelJacob** [RedisInsight/RedisInsight#1094]
**Problem description** (Describe the problem you would like to solve with this feature request or suggested idea).
Electron is bloated. Please make a web app route too

**How often do you encounter this problem** (Describe how frequently this problem occurs).

**Alternatives considered** (Describe any alternative features or products you've considered).

**Additional information** (Add any other context or details here).

**Comment by sdrsdr** [comment]
I would rely like to see redisinsight2 usable in place of redisinsight1. We run the 1 series in our cloud infrastructure, withe firewalled ports and whatnot and the authorized users are connection to it via the web app, querying our cluster database there - something  that will be really hard to do with current electron app

**Comment by ViktarStarastsenka** [comment]
hi, let's track this request under this ticket - https://github.com/RedisInsight/RedisInsight/issues/448.
