### ISSUE TITLE
Can you consider adding a data format configuration option

### ISSUE THREAD

**Issue by zhuyouzhufu** [RedisInsight/RedisInsight#1096]
![image](https://user-images.githubusercontent.com/34908518/187646405-97cbe626-56a5-4d2d-9e9e-ea0df29fe4fe.png)

Problem description：
Can you consider adding a configuration option, which can set the default data format that the user needs to display. Otherwise, every time I want to see the data in JSON format, I have to go to the drop-down list and select it. It's ok if the data is small. If you want to see a large amount of data, this will be cumbersome

Client version：Windows V2

**Comment by ViktarStarastsenka** [comment]
@zhuyouzhufu , with 2.10.0 (will be released in September), RedisInsight will remember the formatter set even if you select another key.
