### ISSUE TITLE
[Feature Request]: Make binary available on GitHub

### ISSUE THREAD

**Issue by kilianc** [RedisInsight/RedisInsight#110]
**Problem description** (Describe the problem you would like to solve with this feature request or suggested idea).
In order to download the binary I need to fill up a form, give my personal phone number, and when the download finally starts you realize that is for the wrong os (`exe`).

**How often do you encounter this problem** (Describe how frequently this problem occurs).
n/a

**Alternatives considered** (Describe any alternative features or products you've considered).
n/a

**Additional information** (Add any other context or details here).
Even the question in this issue templates clearly come from a sales org and are rubbing people off the wrong way. It would be great, in classic open source spirit, to make multi-arch/platform available as part of the GitHub releases.

**Comment by ollopaci** [comment]
Thank you @kilianc for reporting this. We will look into ways on how to make this possible.

**Comment by DanJRWalsh** [comment]
+1 This would be a great addition

For those on Arch Linux (or a derivative, such as Manjaro or Endeavour), you can conveniently install Redis Insight via AUR under the package name [redisinsight](https://aur.archlinux.org/packages/redisinsight)

**Comment by LoganDark** [comment]
Just fill it with bogus info. That's what I did (phone number can be 000-000-0000, nothing else matters). Email can be `e@e.e`, etc.

**Comment by enricodias** [comment]
For me the form doesn't work at all. If just shows a page with the message "Thank you for your interest!" and no download link.

**Comment by SteinGaming** [comment]
The Package on AUR (https://aur.archlinux.org/packages/redisinsight) is currently outdated (on 2.0.6).
I flagged it as outdated, but it was updated 2 months ago.

**Comment by LoganDark** [comment]
> For me the form doesn't work at all. If just shows a page with the message "Thank you for your interest!" and no download link.

Maybe they changed it to email the provided address. Use firefox relay to generate a random shit, then you can delete the forwarder and avoid their marketing spam.

**Comment by enricodias** [comment]
> and avoid their marketing spam

Too late for that. I gave the real email in the first attempt in good faith. The download worked on chrome, though.

**Comment by ViktarStarastsenka** [comment]
@enricodias , thanks for reporting this, there was an issue with the download form, a new manual link has been added to avoid such cases.
<img width="775" alt="image" src="https://user-images.githubusercontent.com/99594890/180376197-599249b7-569f-4f79-8690-34b8a4f4ea76.png">

**Comment by ChaoticMonster** [comment]
Leaving the M1 Mac link with the intention to evaluate the outcome:

https://download.redisinsight.redis.com/latest/RedisInsight-v2-mac-arm64.dmg

If the outcome is adding an expiration hash to the link or removing my message, that's definitely a 🚩

I want to run `brew install --cask redis-insight` to install redis insight. No forms, no marketing spam.

**Comment by avaranze** [comment]
Removing the marketing form / spam to download builds would be nice, especially since the project doesn't build from source with the current instructions (including docker). I have to wonder if it's intentional to leave it broken.

**Comment by Jimbolino** [comment]
Windows:
https://download.redisinsight.redis.com/latest/RedisInsight-v2-win-installer.exe

Linux:
https://download.redisinsight.redis.com/latest/RedisInsight-v2-linux-x86_64.AppImage
https://download.redisinsight.redis.com/latest/RedisInsight-v2-linux-amd64.deb

MacOS:
https://download.redisinsight.redis.com/latest/RedisInsight-v2-mac-x64.dmg
https://download.redisinsight.redis.com/latest/RedisInsight-v2-mac-arm64.dmg

**Comment by ViktarStarastsenka** [comment]
additionally, RedisInsight is available on Microsoft Store, Apple Store, Snapcraft and FlatHub.
