### ISSUE TITLE
[Bug]:How do you start front end portion after you do a yarn build:web?

### ISSUE THREAD

**Issue by jamespauly** [RedisInsight/RedisInsight#1105]
**Actual behavior** (A short description of what you found)
How do you start front end portion after you do a yarn build:web?  I can find no way to start it without doing a compile every-time you run it.

RedisInsight 2.0

**Comment by zalenskiSofteq** [comment]
Hi @jamespauly, you can run front-end with 2 ways: **dev server** and **static**
Start dev server:
1. run `yarn start:web`
1. open localhost:8080 page

Run static front-end:
1. run `yarn build:web`
1. run back-end:
* go to `./redisinsight/api` folder
* run `yarn start:dev`
1. open localhost:5000 page

Does it help you?

**Comment by jamespauly** [comment]
That works and thanks
