### ISSUE TITLE
[Feature Request]:

### ISSUE THREAD

**Issue by ozziej** [RedisInsight/RedisInsight#111]
**Problem description** When using the filter options (set / hash / zset), there is no "clear filters" or "no filter" option. 

**How often do you encounter this problem** Always

**Alternatives considered** Need to restart the application or switch to version 1.11

**Additional information** Just add a filter option for "All" or "Clear filters" next to the filter drop down.

**Comment by ViktorStarostenko** [comment]
Hello @ozziej, you can remove the filter by clicking on the selected option one more time.

**Comment by ozziej** [comment]
@ViktorStarostenko Okay, thanks, but its really not obvious. I would still prefer having a "clear filter" button.

**Comment by ViktarStarastsenka** [comment]
Hi @ozziej , please check the latest version (2.0.6) - we have reworked filters.

**Comment by ozziej** [comment]
Cool, thanks! Just tried it out. Much better.
