### ISSUE TITLE
[Feature Request]: see result in hebrew language

### ISSUE THREAD

**Issue by akelmj** [RedisInsight/RedisInsight#1128]
Hi,

How to see results in hebrew ?

the search result in RedisInsight appear as:

![image](https://user-images.githubusercontent.com/8736967/188875828-ef75df9e-635e-4852-acf0-239d26b4746a.png)

thanks.

**Comment by ViktarStarastsenka** [comment]
hi @akelmj , enable the raw mode before running a command to see results in Hebrew in Workbench

<img width="880" alt="image" src="https://user-images.githubusercontent.com/99594890/188877184-efa1940a-33c0-4942-b0c3-5265e4f1b978.png">

**Comment by akelmj** [comment]
> hi @akelmj , enable the raw mode before running a command to see results in Hebrew in Workbench
> 
> <img alt="image" width="880" src="https://user-images.githubusercontent.com/99594890/188877184-efa1940a-33c0-4942-b0c3-5265e4f1b978.png">

Thank you.
