### ISSUE TITLE
[Bug]: Refresh-Rate interactive button bug

### ISSUE THREAD

**Issue by shiw-yang** [RedisInsight/RedisInsight#1146]
**Preconditions** (Any important steps we need to know)
Can't modify the time by clicking the confirm button. Only to press ENTER.
![image](https://user-images.githubusercontent.com/55988379/189870567-830408ad-5a60-4e18-8136-33352635fbcc.png)

**Steps to reproduce** (How to reproduce what you found step by step)
1. Connect to `Redis Sentinel`
2. Click the inverted triangle next to `Last refresh` and click the `Auto Refresh`
![image](https://user-images.githubusercontent.com/55988379/189871503-85837c71-7b0f-455b-9465-c48ac0754762.png)
3. Modify the `Refresh rate` and click ✔
4. You can reproduce this bug

**Actual behavior** (A short description of what you found)
Just want the `Refresh rate` modified correctly.

**Expected behavior** (A short description of what you expected to find)

**Screenshots** (Paste or drag-and-drop a screenshot or a link to a recording)

**Additional context** (Operating system, version of RedisInsight, Redis database version, Redis module version, database type, connection type, logs, or any other information)
Operating system : Windows 11
version : v2 2.8.0
Redis database version : unknown
database type : sentinel

**Comment by ViktarStarastsenka** [comment]
hi @shiw-yang , thanks for reporting this, will fix in the upcoming releases.

**Comment by ViktarStarastsenka** [comment]
@shiw-yang , please try with 2.10.0 (released today)

**Comment by shiw-yang** [comment]
hi @ViktarStarastsenka ,it's working. I will close the issues
