### ISSUE TITLE
[Feature Request]: Redis port filled when adding Database

### ISSUE THREAD

**Issue by naxels** [RedisInsight/RedisInsight#1156]
**Problem description** (Describe the problem you would like to solve with this feature request or suggested idea).
I just got the RedisInsight app, love it! however when adding all my databases (standalone) I had to fill the Redis Port
field everytime with the default Redis port.

It would be great if the Redis port field is filled with the default Redis port number 6379

**How often do you encounter this problem** (Describe how frequently this problem occurs).
Everytime I add a new Redis Database

**Alternatives considered** (Describe any alternative features or products you've considered).
Copy/paste the default port number 6379 every time

**Additional information** (Add any other context or details here).
Thank you for supporting this app :)

**Comment by oguzhanaygn** [comment]
Hi @naxels , which version are you using right now? While I'm adding my AWS Elasticache databases to RedisInsight, port field is being filled automatically as 6379, I'm using 1.13.0 on Docker which is the latest one. 

https://hub.docker.com/r/redislabs/redisinsight/tags

**Comment by naxels** [comment]
Hi, I'm running version Version 2.8.0 (2.8.0.59623) on macOS.

**Comment by ViktarStarastsenka** [comment]
hi @naxels , thanks for reporting this idea, it is indeed very convenient, I'll see what we can do here.

**Comment by DrzwiPercepcji** [comment]
PR: https://github.com/RedisInsight/RedisInsight/pull/1388.

**Comment by ViktarStarastsenka** [comment]
hi, this has been added with RedisInsight 2.16, thank you for your idea!
