### ISSUE TITLE
[Bug]: TTL cut off when minutes remain

### ISSUE THREAD

**Issue by naxels** [RedisInsight/RedisInsight#1168]
**Preconditions** (Any important steps we need to know)
none

**Steps to reproduce** (How to reproduce what you found step by step)
- Start RedisInsight
- Connect to a server

Additional step where it's also cut off:
- Click away the right side split (for when you click on an actual key)

**Actual behavior** (A short description of what you found)
When a TTL still has minutes, it shows it cut off.

This happens both in the split screen display as well as after removing the right side split.

**Expected behavior** (A short description of what you expected to find)
while there is enough screen real estate to either
show (time left)m (like with the seconds)
or if there is enough space, maybe show the full TTL (when not having side-by-side)

**Screenshots** (Paste or drag-and-drop a screenshot or a link to a recording)
<img width="79" alt="Screenshot 2022-09-19 at 10 09 23" src="https://user-images.githubusercontent.com/3195443/190975223-8da1b8f8-8ffe-4e42-af6a-f33146f7f8d9.png">

**Additional context** (Operating system, version of RedisInsight, Redis database version, Redis module version, database type, connection type, logs, or any other information)

OS: macOS
RedisInsight: Version 2.8.0 (2.8.0.59623)
Redis: 7.0.4

**Comment by ViktarStarastsenka** [comment]
hi @naxels , thanks for reporting the issue, we will fix it with the upcoming releases.

**Comment by naxels** [comment]
This seems to be fixed in the new 2.10 release :) thanks!

https://github.com/RedisInsight/RedisInsight/pull/1180
