### ISSUE TITLE
[Bug]:Why RedisInsight only displays keys in db0?

### ISSUE THREAD

**Issue by sunchaohhh** [RedisInsight/RedisInsight#1183]
Why RedisInsight only displays keys in db0?
My keys are in db1 and there is nowhere to inspect them!
![image](https://user-images.githubusercontent.com/57650588/191477554-8a4b70ed-5a74-40be-8243-1e39fcbc7295.png)

**Comment by ViktarStarastsenka** [comment]
hi @sunchaohhh , currently, to change a database index, you can add the same database connection (to quickly add it you can clone the existing one), and change the database index
<img width="515" alt="image" src="https://user-images.githubusercontent.com/99594890/191493067-85d931e1-7262-441f-84a0-03c0bff7326d.png">

**Comment by sunchaohhh** [comment]
Thanks,I've got it~

**Comment by hotoh** [comment]
Also have this question, why not provide a drop-down box to choose something like this
![image](https://github.com/RedisInsight/RedisInsight/assets/37929671/32739539-cb8e-4e9c-8b0e-25beb600543d)
