### ISSUE TITLE
[Bug]: Error pinging Redis Server

### ISSUE THREAD

**Issue by marcusricardoaguiar** [RedisInsight/RedisInsight#1190]
When using version 1.12, the connection works pretty good. However, when using version 1.13, when trying to ping the redis server, it is shown an error:

**Version 1.13:**
Connecting...

Pinging Redis server on <INSTANCE>:<PORT>...
error pinging Redis server

**Version 1.12:**
Connecting...

Pinging Redis server on <INSTANCE>:<PORT>...
Connected.
Ready to execute commands.

**Comment by GnaneshKunal** [comment]
Hey @marcusricardoaguiar can you send us the logs from (`redisinsight.log`) file?

**Comment by GnaneshKunal** [comment]
Also can you tell us more about your redis setup?

**Comment by marcusricardoaguiar** [comment]
> Hey @marcusricardoaguiar can you send us the logs from (`redisinsight.log`) file?

Hi @GnaneshKunal , where is this log file located? To setup redisinsight, I've just download the linux binary and run on a virtual machine.

**Comment by marcusricardoaguiar** [comment]
> Also can you tell us more about your redis setup?

I've been using Google Cloud Platform. The instance was created there and the redisinsight was launched on the same VPC.

**Comment by GnaneshKunal** [comment]
Hey @marcusricardoaguiar 

Here's how you can find the log file in your platform: https://docs.redis.com/latest/ri/using-redisinsight/troubleshooting/

**Comment by marcusricardoaguiar** [comment]
> Hey @marcusricardoaguiar
> 
> Here's how you can find the log file in your platform: https://docs.redis.com/latest/ri/using-redisinsight/troubleshooting/

Thanks @GnaneshKunal ! Log file attached.
[redisinsight.log](https://github.com/RedisInsight/RedisInsight/files/9626230/redisinsight.log)

**Comment by GnaneshKunal** [comment]
Hey @marcusricardoaguiar,

Can you set log level to DEBUG - https://docs.redis.com/latest/ri/installing/configurations/

Also, are you using multiple versions of Redisinsight at the same time? Are you in a proxy too?

**Comment by marcusricardoaguiar** [comment]
> 

Sure. I will do that. Actually, I've just ran the version 1.13 and it broke. Then, I downgraded to 1.12. I will try to create a new log file using only the version 1.13.

**Comment by marcusricardoaguiar** [comment]
Hi @GnaneshKunal , I've restarted my VM with DEBUG logs and recreated the file. Here we go!
[redisinsight.log](https://github.com/RedisInsight/RedisInsight/files/9628043/redisinsight.log)

**Comment by GnaneshKunal** [comment]
Hi @marcusricardoaguiar,


Are you using proxy? Can you set the trusted environment variable and test it - https://docs.redis.com/latest/ri/using-redisinsight/proxy/#trusted-origins

Try:
```
RITRUSTEDORIGINS=http://dev.redis.internal.biltrewards.com
```

**Comment by marcusricardoaguiar** [comment]
> Hi @marcusricardoaguiar,
> 
> Are you using proxy? Can you set the trusted environment variable and test it - https://docs.redis.com/latest/ri/using-redisinsight/proxy/#trusted-origins
> 
> Try:
> 
> ```
> RITRUSTEDORIGINS=http://dev.redis.internal.biltrewards.com
> ```

Awesome! That worked pretty fine. Thank you @GnaneshKunal !
