### ISSUE TITLE
[Bug]: Memory Analysis Issue

### ISSUE THREAD

**Issue by marcusricardoaguiar** [RedisInsight/RedisInsight#1221]
I've been trying to use Memory Analysis, however I'm getting issues when working with bigger files. When I try doing offline analysis with a small size it works fine. But, when using a bigger file (300MB), it is crashing and showing this error:

![image (4)](https://user-images.githubusercontent.com/8216333/193016916-fead6dad-8ee2-48a8-bb18-9a5d41640946.png)

**Comment by GnaneshKunal** [comment]
Hey @marcusricardoaguiar,

Is the redisinsight hosted here - http://playground.redis.internal.biltrewards.com/?

If then, you have to add the host to trust list by setting the following RedisInsight environment variable:
```
RITRUSTEDORIGINS=http://playground.redis.internal.biltrewards.com
```

Also can you give more information about the modules uses and their versions if possible. There seems to be an issue while analysing a module data present in the rdb.

**Comment by marcusricardoaguiar** [comment]
> Hey @marcusricardoaguiar,
> 
> Is the redisinsight hosted here - http://playground.redis.internal.biltrewards.com/?
> 
> If then, you have to add the host to trust list by setting the following RedisInsight environment variable:
> 
> ```
> RITRUSTEDORIGINS=http://playground.redis.internal.biltrewards.com
> ```
> 
> Also can you give more information about the modules uses and their versions if possible. There seems to be an issue while analysing a module data present in the rdb.

Hi @GnaneshKunal ,

Yes, I've been using RITRUSTEDORIGINS as you suggested.

Regarding the modules, I've tried `MODULE LIST` on redisinsight and none was shown. Is there other way of getting the modules list?

![image](https://user-images.githubusercontent.com/8216333/193588121-7c8a6113-7e41-48a3-8092-cbad2c8c7ace.png)

**Comment by GnaneshKunal** [comment]
@marcusricardoaguiar 

Reproduced the issue. Looking at this...

**Comment by GnaneshKunal** [comment]
Hey @marcusricardoaguiar,

We have worked on a fix.

Can you please test this build:
```
redislabs/redisinsight:memory-analysis-listpack-fix
```

Let me know if you need a different platform.

**Comment by marcusricardoaguiar** [comment]
> Hey @marcusricardoaguiar,
> 
> We have worked on a fix.
> 
> Can you please test this build:
> 
> ```
> redislabs/redisinsight:memory-analysis-listpack-fix
> ```
> 
> Let me know if you need a different platform.

Sorry @GnaneshKunal , but I don't have much experience with it. To run the redisinsight, I've just downloaded the binary on the following link and execute it:
https://redis.com/redis-enterprise/redis-insight/
How can I test this build? Thanks in advance!

**Comment by GnaneshKunal** [comment]
Which platform build do you need? I can provide Windows, Mac and Linux Build

**Comment by GnaneshKunal** [comment]
@marcusricardoaguiar 

Check this linux build

https://drive.google.com/file/d/1vqRiJU7kePzLFc8O6qSEIc7qbZZDMC50/view?usp=sharing

**Comment by marcusricardoaguiar** [comment]
Amazing!!! It worked pretty fine! Thank you so much for this @GnaneshKunal . Do you know when this fix will be official released?

**Comment by GnaneshKunal** [comment]
Hey @marcusricardoaguiar,

This is shipping in the very next release. Please use the above binary until then. Currently I can't give you a date but will notify here once the release is made.

**Comment by ViktarStarastsenka** [comment]
please re-open the ticket if it is still relevant for RedisInsight 1.13.1
