### ISSUE TITLE
[Bug]:Can't download the RedisInsight client. Download button does nothing

### ISSUE THREAD

**Issue by lboonekamp** [RedisInsight/RedisInsight#1224]
**Preconditions** (Any important steps we need to know)
NA

**Steps to reproduce** (How to reproduce what you found step by step)
Try and download the RedisInsight client from the provided download link in the documentation ([here](https://redis.com/redis-enterprise/redis-insight/#insight-form)). Tried Chrome and Edge.

**Actual behavior** (A short description of what you found)
You fill in the form as part of the download click Download, the button goes to a disabled state and says 'Please wait' then does nothing. Same scenario regardless of; selecting 1.X or trying a different browser.

**Expected behavior** (A short description of what you expected to find)
To be able to download the installer for the RedisInsight client.

**Screenshots** (Paste or drag-and-drop a screenshot or a link to a recording)
![image](https://user-images.githubusercontent.com/76415513/193129479-5083de0c-4ac9-4628-b7e2-41f2fdad1b10.png)

**Additional context** (Operating system, version of RedisInsight, Redis database version, Redis module version, database type, connection type, logs, or any other information)
Attempting to download RedisInsight 2.X for Windows

**Comment by ViktarStarastsenka** [comment]
hi @lboonekamp , this issue is caused by the JavaScript blockers by your browser.
what operating system do you use?

**Comment by lboonekamp** [comment]
> hi @lboonekamp , this issue is caused by the JavaScript blockers by your browser. what operating system do you use?

That's odd. Javascript isn't blocked by my browser or any policies. I'm just using Google Chrome on Windows.

**Comment by ViktarStarastsenka** [comment]
@lboonekamp , try this link:
https://s3.amazonaws.com/redisinsight.download/public/latest/RedisInsight-v2-win-installer.exe

**Comment by lboonekamp** [comment]
> @lboonekamp , try this link: https://s3.amazonaws.com/redisinsight.download/public/latest/RedisInsight-v2-win-installer.exe

That worked, thank you!
