### ISSUE TITLE
[Bug]: Window crashes when rendering infinite floating point value.

### ISSUE THREAD

**Issue by bpleon** [RedisInsight/RedisInsight#1226]
**Steps to reproduce**
1. Create a sorted set with a +inf value `zadd test +inf test`
2. View the sorted set in RedisInsight-v2

**Actual behavior**
Entire window goes blank.
Electron console shows:
```js
renderer.prod.js:2 TypeError: Cannot read properties of null (reading 'toString')
    at Object.render (renderer.prod.js:2:1916264)
    at Me (renderer.prod.js:2:1220457)
    at t.value (renderer.prod.js:2:1175027)
    at renderer.prod.js:2:1176955
    at Array.map (<anonymous>)
    at t.value (renderer.prod.js:2:1176927)
    at cellRangeRenderer (renderer.prod.js:2:1104513)
    at t.value (renderer.prod.js:2:1095224)
    at t.value (renderer.prod.js:2:1092478)
    at Da (renderer.prod.js:2:7186000)
```

**Expected behavior**
Shows the sorted set.

**Screenshots**
<img width="1428" alt="Screen Shot 2022-09-30 at 1 08 02 PM" src="https://user-images.githubusercontent.com/11726597/193163035-de85929e-8414-4b95-aef2-fced421888d5.png">
Then when I click on the key:
<img width="1808" alt="Screen Shot 2022-09-30 at 1 08 29 PM" src="https://user-images.githubusercontent.com/11726597/193163061-8de0551d-14bf-4953-abc2-2b2196ce7909.png">

**Additional context**
MacOS 12.6 (21G115)

RedisInsight-v2
Version 2.10.0 (2.10.0.62864)
AWS Redis Stack

**Comment by ViktarStarastsenka** [comment]
hi @bpleon , thanks for reporting it, looking into it.

**Comment by bpleon** [comment]
Looks like it's working as expected in 2.12.0
