### ISSUE TITLE
[Feature Request]: Ability to have multiple databases open at once

### ISSUE THREAD

**Issue by drrallen** [RedisInsight/RedisInsight#1240]
**Problem description** In previous Redis GUIs I have been used to having multiple redis clusters open at the same time. In Redis Insight I have to have multiple copies open or leave one database to look at another.

**How often do you encounter this problem** I am working with two redis clusters at the same time for one project, so this is currently a daily issue.

**Additional information** Would it be possible to add a tabbed interface for currently open database connections, making it easier to move between them without losing the current query in them on leaving?

**Comment by ViktarStarastsenka** [comment]
hi @drrallen , will it work if you open a new RedisInsight window for the second cluster? in this case, you will be able to work with two databases and your current query will not be lost.

**Comment by drrallen** [comment]
> hi @drrallen , will it work if you open a new RedisInsight window for the second cluster? in this case, you will be able to work with two databases and your current query will not be lost.

Hi @ViktarStarastsenka thank you for your comment. I can have multiple windows opened to work, but wondered if others would prefer a tabbed interface or even one which re-establishes connections to databases opened when the application was last closed...

**Comment by Subfire** [comment]
However, you still cannot open multiple keys at the same time
