### ISSUE TITLE
When listing keys using the brows key view there seems to be no way of switching database 

### ISSUE THREAD

**Issue by ixx532** [RedisInsight/RedisInsight#1242]
When using the the brows keys view I can not find a way to select what database to list the keys from? In the previous versions of there was a drop down menu where you could select the index of the database you want to list from.

**Comment by ViktarStarastsenka** [comment]
hi @ixx532 , when you add a database connection, there is the "Select Logical Database" control where you can specify the database index to work with, once the database connection added, currently, there is no way to change it (but you can quickly clone the database connection and change the index).

**Comment by ixx532** [comment]
Thanks! I will check it
