### ISSUE TITLE
[Feature Request]: JSON Formatter should use a monospaced font

### ISSUE THREAD

**Issue by koriolis** [RedisInsight/RedisInsight#1245]
**Problem description**
JSON format (and other structured formats) in the Browser uses a proportional font.
It should be using a monospaced font which is much better to scan the content (together with the already supported highlighting).
As it might not be consensual, maybe a settings option to be able to chose a different font from the installed fonts.

**How often do you encounter this problem**
Always

**Comment by ViktarStarastsenka** [comment]
@koriolis , the monospaced font is added with RedisInsight 2.28 (released today). Please re-open the ticket if the issue is still relevant.
