### ISSUE TITLE
[Feature Request]: ssh tunnel for redis connection

### ISSUE THREAD

**Issue by HowellYan** [RedisInsight/RedisInsight#126]

**Comment by barrychapman** [comment]
this would be great to have, cannot use the tool without it as all our redis instances are in a private subnet

**Comment by Tobikoehler89** [comment]
oh yes, a really necessary feature to avoid having to use other tools (like putty) for the tunnel

**Comment by ViktorStarostenko** [comment]
Hi @HowellYan, @barrychapman, @Tobikoehler89, thank you for raising this feature. Currently, this one has not been included in the upcoming releases, but we are open for contributions and really like to encourage that.
Added the corresponding label.

**Comment by nhaberl** [comment]
huge upvote for that feature, guess nobody has Redis really public available

**Comment by jianzi0307** [comment]
Is ssh tunneling already supported?

**Comment by ViktarStarastsenka** [comment]
hi @barrychapman , there is no SSH tunnel support for now, but I'll see what we can do here.

**Comment by GnaneshKunal** [comment]
@HowellYan @barrychapman @Tobikoehler89 @jianzi0307 

Wouldn't it be possible to open a tunnel outside Redisinsight and use the connections inside Redisinsight? This would simply work, right

https://serverfault.com/a/445172

**Comment by suiwenfeng** [comment]
@ViktarStarastsenka the feature looks like something already implemented as optional connection configuration in [Mongodb Compass](https://www.mongodb.com/docs/compass/current/connect/ssh-connection/).
if that`s right, you can assign this issue to me, i can submit a pull request for it.

**Comment by ViktarStarastsenka** [comment]
hi, added support for SSH tunnel on the form to add a new database connection in RedisInsight 2.18 (released today).
