### ISSUE TITLE
[Bug]:Unable to download linux variants from website ( https://redis.com/redis-enterprise/redis-insight/ )

### ISSUE THREAD

**Issue by sivavarma111** [RedisInsight/RedisInsight#1268]
**Preconditions** (Any important steps we need to know)

**Steps to reproduce** (How to reproduce what you found step by step)

**Actual behavior** (A short description of what you found)

**Expected behavior** (A short description of what you expected to find)

**Screenshots** (Paste or drag-and-drop a screenshot or a link to a recording)

**Additional context** (Operating system, version of RedisInsight, Redis database version, Redis module version, database type, connection type, logs, or any other information)

**Comment by sivavarma111** [comment]
@ViktarStarastsenka Thankyou for the link, but i was hoping to get a .deb file

**Comment by ViktarStarastsenka** [comment]
@sivavarma111 , here you go:
https://s3.amazonaws.com/redisinsight.download/public/latest/RedisInsight-v2-linux-amd64.deb

**Comment by ViktarStarastsenka** [comment]
it has been fixed
