### ISSUE TITLE
[Bug]: Entering "FT.CREATE" in the CLI blanks out the window

### ISSUE THREAD

**Issue by PsyonixMatt** [RedisInsight/RedisInsight#127]
**Preconditions** (Any important steps we need to know)
I found this while connecting to a Redis Enterprise Cloud instance with RediSearch 2 module installed, but I was also able to reproduce the issue connected to a totally separate open source instance without any modules installed. I don't think the connected instance matters for this issue.

**Steps to reproduce** (How to reproduce what you found step by step)
1. Connect to any instance.
2. Expand the CLI section.
3. Type in "FT.CREATE", and as soon as you type the last letter, the window goes blank and must be reloaded. This also occurs when pasting a command that starts with "FT.CREATE".

**Actual behavior** (A short description of what you found)
The tooltip/hint text for the FT.CREATE command seems to crash or otherwise blank out the entire window except the menus. The window can be reloaded (View --> Reload) with no ill effects. The tooltip text can be seen for a very brief instant before the window goes blank.
I tried restarting the app.
Other RediSearch commands seem to work properly, so it's something specific to the "FT.CREATE" command.
The RediSearch module does not need to be installed on the connected instance for this to occur.

**Expected behavior** (A short description of what you expected to find)
Typing the command FT.CREATE should not blank out the window, and should show tooltip/help information like all other commands.

**Screenshots** (Paste or drag-and-drop a screenshot or a link to a recording)
![image](https://user-images.githubusercontent.com/18539975/146476339-c8189d3d-0179-4b9f-9e35-49cfabc38ddb.png)

**Additional context** (Operating system, version of RedisInsight, Redis database version, Redis module version, database type, connection type, logs, or any other information)
**RI Version:** 2.0.2-preview
**Platform:** Windows 10 Pro for Workstations, **version** 20H2, **OS build** 19042.1348, **Experience:** Windows Feature Experience Pack 120.2212.3920.0

**Comment by PsyonixMatt** [comment]
Please let me know if this is not easily reproduced, and I can dig further into my setup and try provide more details!

**Comment by ViktorStarostenko** [comment]
Hi @PsyonixMatt , Thank you for raising this, we will look into this.

**Comment by ViktorStarostenko** [comment]
Also as a temporary workaround, you can run the "FT.Create" command in Workbench.

**Comment by ViktorStarostenko** [comment]
Hello @PsyonixMatt, please check the latest version (2.0.3) - the issue is fixed.

**Comment by PsyonixMatt** [comment]
Confirmed!  Thanks!

**Comment by PsyonixMatt** [comment]
Feel free to close -- I'm not sure if you were leaving open for your workflow.
