### ISSUE TITLE
[Bug]:Filter * not work correctly on large data

### ISSUE THREAD

**Issue by primadi** [RedisInsight/RedisInsight#128]
**Preconditions**
Redis database with large data

**Steps to reproduce**
Try Filter xxx:yyy:* return : No Result Found, but if we complete filter : xxx:yyy:10001, it return correctly.

It seems redisinsight load smallset of data, and do filter on loaded data, not on all existing database.

**Comment by ViktorStarostenko** [comment]
Hello @primadi, if you use a filter pattern ("*" in your example), RedisInsight scans 10 000 keys per iteration (this number is configurable on the Settings page), to scan an additional 10 000 keys, use the "Scan more" button at the bottom of the screen.
When you filter without any patterns, RedisInsight scans the entire database at once.

**Comment by primadi** [comment]
> Hello @primadi, if you use a filter pattern ("*" in your example), RedisInsight scans 10 000 keys per iteration (this number is configurable on the Settings page), to scan an additional 10 000 keys, use the "Scan more" button at the bottom of the screen. When you filter without any patterns, RedisInsight scans the entire database at once.

Thank you for explanation. Case Closed.
