### ISSUE TITLE
[Feature Request]: Pls, add ssh login. and import - export config connection

### ISSUE THREAD

**Issue by hao159** [RedisInsight/RedisInsight#1310]
Hi team,
Like the title.

Please add login via SSH because most DevOps don't have public service to the internet.

Add feature: Import-export config connection.

**Comment by ViktarStarastsenka** [comment]
hi @hao159 , SSH support is under consideration right now, but we are surely planning to add it.
Import-export will be delivered with 2.16 (late December), will the export/import of database connections (host, port, username/password, certificates) be enough for your use case?

**Comment by hao159** [comment]
should be considered about export (passwords or certificates) for security

**Comment by ViktarStarastsenka** [comment]
hi, Import database connections was added in December, SSH support has been added today with 2.18, and the Export database connections is on its way.
