### ISSUE TITLE
[Bug]: RedisInsight not allow set binary prefix for acl in cli

### ISSUE THREAD

**Issue by usrtax** [RedisInsight/RedisInsight#1370]
the image as below (with the same redis)
RedisInsight 2.12.0 (2.12.0.64844)

![image](https://user-images.githubusercontent.com/110233389/200115988-06fe9fa3-a0ad-446e-a3c3-02efea37b820.png)

<img width="646" alt="image" src="https://user-images.githubusercontent.com/110233389/200214885-f115eb3f-f2c5-4723-91d5-6f33d08d7a52.png">

**Comment by ViktarStarastsenka** [comment]
hi @usrtax , thanks for reporting it, we will look into this.

**Comment by ViktarStarastsenka** [comment]
@usrtax , please try RedisInsight 2.14 (release today)

**Comment by ViktarStarastsenka** [comment]
please re-open the ticket if this issue still reproduces
