### ISSUE TITLE
How can I have login page for Redis Insight?

### ISSUE THREAD

**Issue by arezvani** [RedisInsight/RedisInsight#1381]
I want to have login page for my Redis Insight in Kubernetes. Can anyone help me?

**Comment by deeaitche** [comment]
Maybe you can run your redisinsight behind a secure reverse proxy.

**Comment by ViktarStarastsenka** [comment]
@arezvani , indeed, a reverse proxy can help here. Please find some instructions to set up RedisInsight behind a reverse proxy:
https://github.com/RedisInsight/RedisInsight-reverse-proxy

**Comment by ViktarStarastsenka** [comment]
hi @arezvani , did you try setting up a reverse proxy?

**Comment by ViktarStarastsenka** [comment]
please re-open the ticket if it is still relevant.
