### ISSUE TITLE
[Bug]: not response when key's value size is over 4mb

### ISSUE THREAD

**Issue by DrizzlingCattus** [RedisInsight/RedisInsight#140]
**Preconditions** (Any important steps we need to know)
- make 4mb size of string type value

**Steps to reproduce** (How to reproduce what you found step by step)

![image](https://user-images.githubusercontent.com/4661295/146965682-cb690745-9f40-4023-aa6d-dac97b615185.png)
1. search 4mb string type value
2. click it

![image](https://user-images.githubusercontent.com/4661295/146965774-1045c51e-d52d-4cee-aba8-fee25d2d3afa.png)

then it response empty value, but cannot click anything.

![image](https://user-images.githubusercontent.com/4661295/146965809-b37a0328-ecb5-47b5-b7a9-74ee4155be3f.png)
 
soon, the screen goes white and freezes. However, it is possible to refresh with view>reload.

**Additional context** (Operating system, version of RedisInsight, Redis database version, Redis module version, database type, connection type, logs, or any other information)

- redinsight version: 2.0.2 preview
- redis version: 5.0.10
  - alpine docker image

**Comment by ViktorStarostenko** [comment]
Hi @DrizzlingCattus, thank you for reporting this. Currently, RedisInsight v2 uploads the entire value of String, so I think that in your case, the application tried to upload 4MB and ran into a lack of RAM.
Could you please provide more information about memory parameters?

**Comment by ViktorStarostenko** [comment]
Hello @DrizzlingCattus, is this issue still reproducible? If yes, could you please provide details about your memory parameters so we can investigate this further?
