### ISSUE TITLE
[Bug]: Unable to use with Predixy proxy

### ISSUE THREAD

**Issue by Dando-Real-ITA** [RedisInsight/RedisInsight#1409]
**Preconditions** (Any important steps we need to know)
The Proxy is used to connect to a Redis Cluster for simple clients.
redis-cli connection works

RESP.app that now is merged with RedisInsight is able to correctly connect, view and set keys

**Steps to reproduce** (How to reproduce what you found step by step)

- Create a Redis Cluster
- Create a Predixy Redis Proxy, configured to connect to the Cluster
- Add Predixy connection settings to RedisInsight
- Verify connection is established
- Try to open the database view

**Actual behavior** (A short description of what you found)

RedisInsight is able to do the initial connect in the My Redis databases view, but when I try to load the database, I get a black screen with console errors.

**Expected behavior** (A short description of what you expected to find)

UI should not crash and display data as a standalone redis connection ( proxy hides cluster/sentinel features )

**Screenshots** (Paste or drag-and-drop a screenshot or a link to a recording)
![image](https://user-images.githubusercontent.com/3657228/202456317-bf299972-9724-4ebb-8e20-9a2b233b0012.png)
![image](https://user-images.githubusercontent.com/3657228/202456808-9f408644-4f4b-470a-9cf5-dfc0b8937491.png)

**Additional context** (Operating system, version of RedisInsight, Redis database version, Redis module version, database type, connection type, logs, or any other information)

Windows 11
RedisInsight 2.12.0
No Modules
Proxied cluster database as standalone redis

**Comment by Dando-Real-ITA** [comment]
Hi,
I can now now see the view, but I still have problems loading keys
I can add a new key, and I can see the new key in RESP.app but not in RedisInsight
Also the CLI works from inside RedisInsight

I am using a custom [fork](https://github.com/Dando-Real-ITA/predixy) to support some of the commands requested

**Comment by ViktarStarastsenka** [comment]
@Dando-Real-ITA , please try 2.16.0 and re-open the ticket if the issue still reproduces.
