### ISSUE TITLE
[Bug]:Documentation around RediSearch 2.x Support

### ISSUE THREAD

**Issue by devinsburke** [RedisInsight/RedisInsight#1420]
One of the [RedisInsight github readme hightlights](https://github.com/RedisInsight/RedisInsight#redisinsight-highlights) is:

> Visualizations of your RediSearch index, queries, and aggregations

**Is this limited to RediSearch 1.x?** (With its 'hard' indices rather than the more integrated way 2.x handles indices)

When I connect the RedisInsight 2.x client to my instance with Redisearch 2.x, the app shows a responsively-styled 'RediSearch' module icon in the top right, though clicking it does nothing. However, there are no UI-based functions for RediSearch within the browser, sidebar, workbench, analysis tools, etc. The closest is syntax intellisense when using the CLI.

RedisInsight 1.x has support/visualization for RS 1.x but not 2.x. Is the same true of RedisInsight 2.x? **If so, I propose we update the GitHub readme to reflect that.**

**Comment by ViktarStarastsenka** [comment]
hi @devinsburke , you can see RediSearch visualizations when you run several RediSearch commands in Workbench (e.g. FT.INFO, FT.SEARCH, FT.AGGREGATE).
With the 2.14 release (which will be delivered in ~ a week) we will also add a dedicated RediSearch UI to Browser

**Comment by ViktarStarastsenka** [comment]
Also with the new RedisInsight 2.14, you can use a dedicated RediSearch UI in the Browser tool.
