### ISSUE TITLE
[Bug]: RedisInsight may not be compatible with pika?

### ISSUE THREAD

**Issue by vincentzchao** [RedisInsight/RedisInsight#1446]
**Preconditions** (Any important steps we need to know)
System: macOS Monterey 12.5.1 (Apple M1 Pro)
RedisInsight version: RedisInsight-v2-mac-arm64 (download from https://redis.com/redis-enterprise/redis-insight/)
Redis info:  
![image](https://user-images.githubusercontent.com/108948726/204179644-079cdba8-5852-41ab-a087-6b58c9a2aad5.png)
Pika repo: https://github.com/OpenAtomFoundation/pika

**Steps to reproduce** (How to reproduce what you found step by step)
Just add a Redis Database , and open it.
![image](https://user-images.githubusercontent.com/108948726/204180080-51387c97-5bc0-473e-91a6-30e2a30b73b5.png)
![image](https://user-images.githubusercontent.com/108948726/204180406-a7af86db-5233-4da9-b3b9-6dc2e37185ee.png)

I got this: 
![image](https://user-images.githubusercontent.com/108948726/204180194-4ecbd1b4-0e6e-4fb0-bcb7-36d070031916.png)

**Actual behavior** (A short description of what you found)
I got a black window without anything

**Expected behavior** (A short description of what you expected to find)
Enter into a normal window

**Screenshots** (Paste or drag-and-drop a screenshot or a link to a recording)

**Additional context** (Operating system, version of RedisInsight, Redis database version, Redis module version, database type, connection type, logs, or any other information)

**Comment by ViktarStarastsenka** [comment]
hi @vincentzchao , please try RedisInsight 2.14 (released today), RI will connect, but there still be some issues with pika database - for example, the list of keys will not be displayed (though you can find a key and work with it), because pika returns 0 with dbsize.

**Comment by vincentzchao** [comment]
Thanks！Will it be solved finally in the future?

**Comment by ViktarStarastsenka** [comment]
@vincentzchao , please try 2.16.0 - it should be fixed.
