### ISSUE TITLE
[Feature Request]: Select different database in Browser

### ISSUE THREAD

**Issue by eric-musliner** [RedisInsight/RedisInsight#1454]
**Problem description** (Describe the problem you would like to solve with this feature request or suggested idea).
There doesn't seem to be a way to change the database in the "Browser" to anything but database 0 in the native app version of RedisInsight-v2

**How often do you encounter this problem** (Describe how frequently this problem occurs).
Every time.

**Alternatives considered** (Describe any alternative features or products you've considered).
The older browser-based RedisInsight allows the ability to select different databases that exist in a redis instance

**Additional information** (Add any other context or details here).

**Comment by ViktarStarastsenka** [comment]
hi, currently (as a workaround), you can add a new database connection with another database index. Please use this ticket to track the progress for adding a dedicated control in Browser:
https://github.com/RedisInsight/RedisInsight/issues/466
