### ISSUE TITLE
[Bug]: Show me the blank page

### ISSUE THREAD

**Issue by SmileJQ** [RedisInsight/RedisInsight#1462]
**Preconditions** (Any important steps we need to know)

Configed host , port and password.
**Steps to reproduce** (How to reproduce what you found step by step)

**Actual behavior** (A short description of what you found)
When I click the server alias，RedisInsight show me a blank page.
![image](https://user-images.githubusercontent.com/44373149/204721071-64258c19-d413-435f-be65-6b32490dd4b9.png)

I try the same configration on Another Redis Desktop Manger, it's work.  So  I think my host, port, password are correct.
**Expected behavior** (A short description of what you expected to find)

**Screenshots** (Paste or drag-and-drop a screenshot or a link to a recording)

**Additional context** (Operating system, version of RedisInsight, Redis database version, Redis module version, database type, connection type, logs, or any other information)

**Comment by ViktarStarastsenka** [comment]
@SmileJQ , can you please specify database details (version, etc.)?
And please run the dbsize command (via redis-cli, for example).

**Comment by ViktarStarastsenka** [comment]
@SmileJQ , is this issue still relevant with RedisInsight 2.18?

**Comment by ViktarStarastsenka** [comment]
please re-open the ticket if it is still relevant
