### ISSUE TITLE
[Bug]: Tree view browser does not respect key prefix with large keys

### ISSUE THREAD

**Issue by process0** [RedisInsight/RedisInsight#1468]
**Preconditions**

Large number of keys (> 100k)

**Steps to reproduce** 

* Use Tree view to browse keys by a prefix 
* Key scan does not respect prefix, and may not return keys matching prefix (up to 10k)
* Load more keys does not guarantee scanning keys matching prefix

**Actual behavior** 

* Keys from prefix are not displayed
* Load more keys button may not respond

**Expected behavior**

* Keys matching prefix should be displayed

**Additional context**

Linux
Firefox
git master

**Comment by ViktarStarastsenka** [comment]
@process0 , can you please attach the screen as well? but please remove any sensitive data from it (like key names)

**Comment by ViktarStarastsenka** [comment]
@process0 , please try clicking the "Scan more" button since currently you have scanned only 10K keys.

**Comment by ViktarStarastsenka** [comment]
the "[SCAN](https://redis.io/commands/scan/)"command with the "MATCH" filter is used to iterate over the list of keys, so basically it means that if you want to see all the keys that match your request, you most probably need to scan the entire database.
Please try to click the "Scan more" button and, if "Scanned 10 000 / 184 495 keys" is not changed to "Scanned 20 000 / 184 495 keys", then:
1. Open the devtools
2. Reproduce the issue
3. Attach the error occurred

I'll try to help with this issue.

**Comment by ViktarStarastsenka** [comment]
as a workaround, you can go to Settings, open the Advanced section, and change the value to 200,000
