### ISSUE TITLE
[Bug]:SCAN autocomplete is misguiding

### ISSUE THREAD

**Issue by AnujaK** [RedisInsight/RedisInsight#1476]
Should show command as: 
`SCAN cursor [MATCH pattern] [COUNT count] [TYPE type]  `

At least MATCH is a must (count and type are a bit intuitive!)

<img width="856" alt="image" src="https://user-images.githubusercontent.com/1309080/205274148-90aa0843-db05-405b-a8de-5159591e7aae.png">

**Comment by ViktarStarastsenka** [comment]
hi @AnujaK , please check it with 2.24 (released today).
re-open the issue if it is still relevant.
