### ISSUE TITLE
[Bug]:Cuckoo Filter Delete Related Info should be Commented

### ISSUE THREAD

**Issue by AnujaK** [RedisInsight/RedisInsight#1478]
Click on "Delete an item" within Cuckoo Filter of RedisInsight.
Line#4 and Line#5, which are actually comments, appear without // . Hence, getting error on running. Those informative lines should be commented.

**Comment by ViktarStarastsenka** [comment]
thank you for reporting this, guides will be updated with the 2.16 release (planned to be released in late December).
