### ISSUE TITLE
[Feature Request]: Ability to edit connections instead of adding new ones

### ISSUE THREAD

**Issue by cbiggins** [RedisInsight/RedisInsight#1501]
**Problem description**
I use Lando as my dev environment which means everytime I launch the environment the port for Redis changes. Currently I can only add new connections rather than just editing an existing one with a new port. A simple inline editor for various connection details would make this process so much quicker and easier. The app is brilliant otherwise.

**How often do you encounter this problem**
Every day.

**Comment by ViktarStarastsenka** [comment]
hi @cbiggins , please try the "clone database" in the edit mode - here you will be able to quickly copy the existing database, but change the host.
Quick question - you use a local database that is not shared with other developers, right?

**Comment by ViktarStarastsenka** [comment]
@cbiggins , you can edit the port in existing connections with RedisInsight 2.20 (released today). Please re-open the ticket if it is still relevant.
