### ISSUE TITLE
[Bug]: Internal Server error message comes up if using a read/write user for access

### ISSUE THREAD

**Issue by CryptoTradee** [RedisInsight/RedisInsight#1512]
**Preconditions** (Any important steps we need to know)

**Steps to reproduce** (How to reproduce what you found step by step)
Create a user on Redis that only has Read/Write access
Connect to the database using that user
Click on any key and red "Internal Server error" message comes up constantly

**Actual behavior** (A short description of what you found)

**Expected behavior** (A short description of what you expected to find)

**Screenshots** (Paste or drag-and-drop a screenshot or a link to a recording)
![image](https://user-images.githubusercontent.com/45982911/208328466-0308c6ca-348e-4fbf-b4c8-6ce6cdc6916e.png)

**Additional context** (Operating system, version of RedisInsight, Redis database version, Redis module version, database type, connection type, logs, or any other information)

**Comment by ViktarStarastsenka** [comment]
@CryptoTradee , can you please provide more details about this issue?

**Comment by CryptoTradee** [comment]
![image](https://github.com/RedisInsight/RedisInsight/assets/45982911/2ed9ad25-28ac-4d8e-bfa9-c2be029f47e3)
![image](https://github.com/RedisInsight/RedisInsight/assets/45982911/14fee153-454e-422f-b384-9a976843cd32)

**Comment by ViktarStarastsenka** [comment]
@CryptoTradee , thank you
Need more information to investigate it deeper. Can you please run RedisInsight in debug mode and send the logs? But please remove any sensitive data from the logs before sending them (!)
an example of the command for Linux and macOS:
`LOG_LEVEL=debug LOGGER_OMIT_DATA=false`

**Comment by CryptoTradee** [comment]
Surely you can replicate it now if you follow the same steps. I'm not going to be doing that
