### ISSUE TITLE
[Bug]: The RedisInsight crash with streams messages that have large ids

### ISSUE THREAD

**Issue by yancoltro** [RedisInsight/RedisInsight#1531]
**Preconditions** (Any important steps we need to know)
Redis streams with message ID = 16718007739968750-641504120531689158

**Steps to reproduce** (How to reproduce what you found step by step)
Create a message with this payload
`{
  "data": {
    "messages": {
      "key": "16718007739968750-641504120531689158",
      "source": "t-producer",
      "target": "t-consumer",
      "timestamp": "1671800773996",
      "value": "{\"customer\":\"Customer 0\",\"email\":\"customer0@email.com\",\"data\":{\"someInfo\":\"someValue\"}}"
    },
    "timeout": 30000,
    "topic": "topic-event-handler"
  }
}`

**Actual behavior** (A short description of what you found)
The javascript behind cant handle this bignumber, the screen starts to crash

**Expected behavior** (A short description of what you expected to find)
Do not crash

**Screenshots** (Paste or drag-and-drop a screenshot or a link to a recording)
![Screenshot from 2022-12-23 10-11-31](https://user-images.githubusercontent.com/31298655/209341827-9209d0d6-9667-40d2-8247-9a1e8b529941.png)

**Additional context** (Operating system, version of RedisInsight, Redis database version, Redis module version, database type, connection type, logs, or any other information)

Linux Ubuntu 22.04
Redis Insight version: 2.14.0

**Comment by ViktarStarastsenka** [comment]
@yancoltro , thank you for reporting this bug, it will be fixed in the upcoming releases (planned for 2.20 in late February)

**Comment by ViktarStarastsenka** [comment]
hi @yancoltro , it will be fixed with 2.20 (planned for tomorrow)

**Comment by ViktarStarastsenka** [comment]
fixed with 2.20 (released today). Please re-open the ticket if it still relevant.
