### ISSUE TITLE
[Bug]: 403 error occurs on the redisinsight first page.

### ISSUE THREAD

**Issue by sdYoo** [RedisInsight/RedisInsight#1539]
**Preconditions** (Any important steps we need to know)
Hello!
I deployed Redisinsight on k8s using helm chart.
However, when connecting to the https domain, a 403 error occurs on the first page.
I declared the RITRUSTEDORIGINS variable in env of deployment.yaml and registered the domain, but the same error occurs.
Where should I declare RITRUSTEDORIGINS when using helm chart? deployment.yaml or ingress.yaml???

**Steps to reproduce** (How to reproduce what you found step by step)
Check 403 message in chrome developer tools

Status Code: 403 Forbidden

**Actual behavior** (A short description of what you found)
A If I click the OK button after checking all in the pop-up window, I cannot move to the next screen.
Check 403 message in chrome developer tools

**Expected behavior** (A short description of what you expected to find)
I added an environment variable by referring to the guide, but the same problem occurred

**Screenshots** (Paste or drag-and-drop a screenshot or a link to a recording)
1) helm chart version 
apiVersion: v2
description: A Helm chart for Kubernetes
name: redisinsight-chart
type: application
version: 0.1.0

2) chrome error 
EULA AND PRIVACY SETTINGS > Something went wrong submitting your preference.

chrome developer tool

Request URL: https://sandbox-redis-manager.xxxxx.com/api/eula-screen-settings/
Request Method: POST
Status Code: 403 Forbidden
Remote Address: 10.xxx.xx.145:443
Referrer Policy: same-origin

3) k8s deployment yaml
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: redisinsight
        app.kubernetes.io/name: redisinsight-chart
    spec:
      containers:
        - env:
            - name: RITRUSTEDORIGINS
              value: 'https://sandbox-redis-manager.xxxxx.com'
            - name: RILOGLEVEL
              value: ERROR
          image: 'docker-hub.xxxx.com/redislabs/redisinsight:1.12.1'
          imagePullPolicy: IfNotPresent
          name: redisinsight-chart
          ports:
            - containerPort: 8001
              name: http
              protocol: TCP
          resources:
            limits:
              cpu: '1'
              memory: 1Gi
            requests:
              cpu: '1'
              memory: 1Gi
          securityContext: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /db
              name: db
      dnsPolicy: ClusterFirst
      nodeSelector:
        wallga/node-group: management
        wallga/sandbox: 'true'
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: redisinsight-redisinsight-chart
      serviceAccountName: redisinsight-redisinsight-chart
      terminationGracePeriodSeconds: 30
      volumes:
        - emptyDir: {}
          name: db

4) redisinsight pod env

RILOGLEVEL=ERROR
NEXUS_REPOSITORY_MANAGER_SERVICE_PORT=8081
BOTKUBE_PORT_2113_TCP_PORT=2113
RITRUSTEDORIGINS=https://sandbox-redis-manager.xxxxx.com
NEXUS_REPOSITORY_MANAGER_SERVICE_PORT_NEXUS_UI=8081
JENKINS_MONEYBALL_JENKINS_PORT_8080_TCP_PROTO=tcp

**Additional context** (Operating system, version of RedisInsight, Redis database version, Redis module version, database type, connection type, logs, or any other information)

Helm chart version : redisinsight:1.12.1

**Comment by sdYoo** [comment]
Helm chart version : redisinsight:1.12.1

**Comment by GnaneshKunal** [comment]
Hey @sdYoo,


Can you add your remote address also in the trusted origins variable and check.

`10.xxx.xx.145:443`

**Comment by sdYoo** [comment]
hi @GnaneshKunal 

I added the virtual ip in two ways as shown below, but the same 403 error occurs.
Is there any other way to solve this problem???

1) using comma
    spec:
      containers:
        - env:
            - name: RITRUSTEDORIGINS
              value: >-
                https://sandbox-redis-manager.xxxxx.com,10.xxx.xx.145:443
            - name: RILOGLEVEL
              value: ERROR

2) using blank
    spec:
      containers:
        - env:
            - name: RITRUSTEDORIGINS
              value: >-
                https://sandbox-redis-manager.xxxxx.com
                10.xxx.xx.145:443
            - name: RILOGLEVEL
              value: ERROR

=====================
chrome develop tool...history

Request URL: https://sandbox-redis-manager.xxxxx.com/api/eula-screen-settings/
Request Method: POST
Status Code: 403 Forbidden
Remote Address: 10.xxx.xx.145:443
Referrer Policy: same-origin

**response header**
HTTP/1.1 403 Forbidden
Content-Type: application/json
Content-Length: 142
Connection: keep-alive
Allow: POST, OPTIONS
Cross-Origin-Opener-Policy: same-origin
Referrer-Policy: same-origin
X-Content-Type-Options: nosniff
X-Frame-Options: DENY

**Comment by sdYoo** [comment]
Hi @GnaneshKunal 

I solved the problem by applying the following.
Thank you so much!
 
-----------------
Add domain and vip to variable "RITRUSTEDORIGINS"

         - name: RITRUSTEDORIGINS
              value: >-
                https://sandbox-redis-manager.xxxxx.com,https://10.xxx.xx.145
