### ISSUE TITLE
[Feature Request]: Submitting to Flathub.org

### ISSUE THREAD

**Issue by proletarius101** [RedisInsight/RedisInsight#1545]
**Problem description** (Describe the problem you would like to solve with this feature request or suggested idea).

I'm submitting RedisInsight to Flathub.org: https://github.com/flathub/flathub/pull/3744 based on [your electron-builder manifest](https://github.com/RedisInsight/RedisInsight/blob/2ea633acaa78ceedd5f7b6936e567cf6d0b0f209/electron-builder.json#L97-L157). It will increase the exposure to Linux users. It would be nice to have your endorsement.

**Comment by ViktarStarastsenka** [comment]
hi @proletarius101 , thank you for your contribution!
