### ISSUE TITLE
[Bug]: Unable to add Redis server with 200+ symbols length password set

### ISSUE THREAD

**Issue by Feniksovich** [RedisInsight/RedisInsight#1546]
**Preconditions** (Any important steps we need to know)
Redis server has password which length is more than 200 symbols.

**Steps to reproduce** (How to reproduce what you found step by step)
1. Click "Add Redis Database" on the "My Redis databases" tab.
2. Try to fill password field with password that is over 200 symbols in length.
3. See that only first 200 characters fit into the password field.

**Actual behavior** (A short description of what you found)
The maximum allowed password length is 200 characters.

**Expected behavior** (A short description of what you expected to find)
No restrictions on password length or much than 200 characters.

**Screenshots** (Paste or drag-and-drop a screenshot or a link to a recording)
N\A

**Additional context** (Operating system, version of RedisInsight, Redis database version, Redis module version, database type, connection type, logs, or any other information)
RedisInsight v2.16.0

**Comment by ViktarStarastsenka** [comment]
@Feniksovich , please try it with RedisInsight 2.18.
re-open the ticket if the issue is still relevant.

**Comment by Feniksovich** [comment]
> @Feniksovich , please try it with RedisInsight 2.18. re-open the ticket if the issue is still relevant.

Works fine now :)
