### ISSUE TITLE
[Bug]: Cannot connect to Redis server in Azure

### ISSUE THREAD

**Issue by wshao12** [RedisInsight/RedisInsight#1548]
**Preconditions** (Any important steps we need to know)
We have redis instances in Azure cloud. I want to connect it using RedisInsight V2

**Steps to reproduce** (How to reproduce what you found step by step)
add host, port, and password, and a random database alias sting, leave username empty

**Actual behavior** (A short description of what you found)
Connection failed. 

**Expected behavior** (A short description of what you expected to find)
Connection success. 

**Screenshots** (Paste or drag-and-drop a screenshot or a link to a recording)
<img width="1296" alt="Screen Shot 2022-12-31 at 8 50 30 PM" src="https://user-images.githubusercontent.com/61670243/210161296-9b5eda75-5f02-4258-b5ea-95aeb90bd6d8.png">

**Additional context** (Operating system, version of RedisInsight, Redis database version, Redis module version, database type, connection type, logs, or any other information)
macbook pro redisinsight v2

**Comment by wshao12** [comment]
Failed connection to the redis database. | {"stack":[{"message":"getaddrinfo ENOTFOUND dracorex-engagement-redis.redis.cache.windows.netdracorex-engagement-redis.redis.cache.windows.net"}]}
 | Failed to add database. | {"stack":[{"message":"getaddrinfo ENOTFOUND dracorex-engagement-redis.redis.cache.windows.netdracorex-engagement-redis.redis.cache.windows.net"}]}
| Getting application settings. | {"stack":[]}
| Succeed to get application settings. | {"stack":[]}
| Creating new database. | {"stack":[]}

**Comment by arthosofteq** [comment]
@wshao12 Did you put host name twice? 
`dracorex-engagement-redis.redis.cache.windows.netdracorex-engagement-redis.redis.cache.windows.net`
`dracorex-engagement-redis.redis.cache.windows.net` + `dracorex-engagement-redis.redis.cache.windows.net`

Are you able to connect using `redis-cli`?

If it is not the case could you try to connect using test build from this message? https://github.com/RedisInsight/RedisInsight/issues/1339#issuecomment-1367791335

**Comment by wshao12** [comment]
Apologies. My computer keyboard has issue. I did not use host name twice. It is a copy/paste issue.
I can use a tool called StrongDM as proxy, then I can connect to it.   
hmm. I cannot connect to the server using redis-cli either: operation timed out

**Comment by wshao12** [comment]
I tried new version, same. could be our env issue.

**Comment by ViktarStarastsenka** [comment]
please re-open the ticket if it is still relevant

**Comment by mf182407** [comment]
i am running into the same issue. when connecting w the old redis desktop manager, i just used to auth w the primary access key. now it isnt available and asks for username and pw. is this not compatible w any azure cache for redis?

**Comment by mf182407** [comment]
@ViktarStarastsenka thanks for the reply. with the old redis desktop manager, it used to let you just access a saas redis cache (in my case azure hosted) by entering the access key. there isn't a username or password associated with this type, so when trying to connect to it now with new version, it doesn't work since there's no option for access key anymore. does that make sense?

**Comment by mf182407** [comment]
@uglide awesome, that worked. thanks for the help on this
