### ISSUE TITLE
[Bug]: Blank Screen Getting

### ISSUE THREAD

**Issue by dip-bypt** [RedisInsight/RedisInsight#1549]
**Actual behavior**
When I click on 1 Record than Screen gets fully blank and after that, I'm unable to work and need to restart the app.

**Expected behavior** (A short description of what you expected to find)
The screen shoud be show record details instead of a Blank screen

**Video Link**
https://screenapp.io/#/shared/c8f7408f-cfce-4305-b57e-ccd4160c2901

Operating system - MacOS
version of RedisInsight - V2
database type - Redis Database

**Comment by ViktarStarastsenka** [comment]
hi @dip-bypt , is there a chance to get the JSON with which you have this issue? (but please truncate all the sensitive info).

**Comment by dip-bypt** [comment]
> hi @dip-bypt , is there a chance to get the JSON with which you have this issue? (but please truncate all the sensitive info).

hi @ViktarStarastsenka here JSON in which I get the issue and I had stored it as **Post:0**
{
  "postID": "f7d89447-8a0b-41cc-8a86-1433654e3de1",
  "rePosted": 1,
  "likeCount": 0,
  "rePostCount": 0,
  "lang": null,
  "postContent": "test",
  "parentPost": "0a60f370-2742-4a52-8219-afdaef40f7e9",
  "tagPersons": "",
  "userID": "f8f4a111-c3a3-4cad-bdba-0876ade2cf77",
  "userName": "Rajinikanth",
  "firstName": "Shivaji",
  "middleInitial": "T",
  "lastName": "Gaekwad",
  "profileImageURL": "https://cloudfront.net/user/profile/1687051847423.jpg",
  "banner": "https://cloudfront.net/user/banner/1665055378817.jpg",
  "pollEndDate": null,
  "pollEndDay": null,
  "pollEndHour": null,
  "pollEndMin": null,
  "sortURL": "https://test.com/AcBWmZiy1apuE6na9",
  "accountType": 2,
  "organizationName": null,
  "createdAt": {
    "year": 2023,
    "month": 0,
    "dayOfMonth": 2,
    "hourOfDay": 7,
    "minute": 45,
    "second": 21
  }
}

**Comment by ViktarStarastsenka** [comment]
@dip-bypt , I have tried to reproduce with this JSON and it works fine, as I can see the JSON in the video is a different one (it has 2952 length).
Is it possible to get the original JSON (but without the sensitive data)?
also, can you please open DevTools and send the error from it after the issue is reproduced?

**Comment by ViktarStarastsenka** [comment]
@dip-bypt , please share the response to the rejson-rl/get, if this issue is still relevant.

**Comment by ViktarStarastsenka** [comment]
please re-open the ticket if the issue is still relevant
