### ISSUE TITLE
[Bug]: The browser is not auto refresh with new added or deleted keys

### ISSUE THREAD

**Issue by Yiftach** [RedisInsight/RedisInsight#1550]
In order to see the status of the keys in the dataset, we need to refresh the browser

**Comment by ViktarStarastsenka** [comment]
@K-Jo , I suggest displaying a newly added key at the top of the list of keys and:
1. if you upload more keys, there is a chance that the same key will be returned (but there is the same risk right now according to the documentation for the [SCAN](https://redis.io/commands/scan/) command, which says "A given element may be returned multiple times.")
2. If you refresh the list, the list of keys will be completely updated and, most probably, the key will not be displayed at the top.

**Comment by ViktarStarastsenka** [comment]
thanks for the request, newly added keys are automatically displayed at the top with RedisInsight 2.20 (released today).
