### ISSUE TITLE
[Bug]: typo in the workbench description of VSS

### ISSUE THREAD

**Issue by Yiftach** [RedisInsight/RedisInsight#1553]
E-Commerce Semantic Similarity: Recommending "semantically similar" products matching **a** description provided by end-user. 

In addition, I believe this section should be changed from:
"
There is a growing number of pre-trained Computer Vision and Natural Language processing models that allows you to generate a vector representation of images or long pieces of text. "

To:

"
A growing number of pre-trained Computer Vision and Natural Language processing models allows you to generate a vector representation of images, videos, audio, and text. "

**Comment by ViktarStarastsenka** [comment]
hi @Yiftach , thank you for noticing the typo and for your suggestions, the guides will be updated with the upcoming release.
