### ISSUE TITLE
[Feature Request]: view as protobuf for hash value

### ISSUE THREAD

**Issue by Notmeor** [RedisInsight/RedisInsight#1558]
**Problem description** (Describe the problem you would like to solve with this feature request or suggested idea).

wish to be able to view as protobuf for hash value.

**How often do you encounter this problem** (Describe how frequently this problem occurs).

**Alternatives considered** (Describe any alternative features or products you've considered).

**Additional information** (Add any other context or details here).

**Comment by ViktarStarastsenka** [comment]
hi @Notmeor , it is possible to view the values in protobuf. Please see the screen attached.

<img width="594" alt="image" src="https://user-images.githubusercontent.com/99594890/210605244-ff22d17a-6ab1-4bfc-a006-93da3c52a5f3.png">
