### ISSUE TITLE
[Bug]: not able to see "All the keys"

### ISSUE THREAD

**Issue by SakshiPrakashChalpe** [RedisInsight/RedisInsight#1566]
**Preconditions** (Any important steps we need to know)

**Steps to reproduce** (How to reproduce what you found step by step)

**Actual behavior** (A short description of what you found)

**Expected behavior** (A short description of what you expected to find)

**Screenshots** (Paste or drag-and-drop a screenshot or a link to a recording)

**Additional context** (Operating system, version of RedisInsight, Redis database version, Redis module version, database type, connection type, logs, or any other information)

**Comment by ViktarStarastsenka** [comment]
hi @SakshiPrakashChalpe , please provide more information about this case - you cannot see the list of keys or you cannot scan the entire database? something else?
