### ISSUE TITLE
[Bug]: docker image is not up to date

### ISSUE THREAD

**Issue by xfournet** [RedisInsight/RedisInsight#1597]
**Steps to reproduce**
See https://hub.docker.com/r/redislabs/redisinsight/tags

**Actual behavior**
Latest version is 1.13.1

**Expected behavior**
Latest version is 2.16.0 or more

**Comment by ViktarStarastsenka** [comment]
hi, this is the ticket for a new docker image: https://github.com/RedisInsight/RedisInsight/issues/519
