### ISSUE TITLE
Only English, don't you support switching languages

### ISSUE THREAD

**Issue by springboot4** [RedisInsight/RedisInsight#1607]
**Problem description** (Describe the problem you would like to solve with this feature request or suggested idea).

**How often do you encounter this problem** (Describe how frequently this problem occurs).

**Alternatives considered** (Describe any alternative features or products you've considered).

**Additional information** (Add any other context or details here).

**Comment by ViktarStarastsenka** [comment]
Hi @springboot4 , there is a ticket with the same topic - https://github.com/RedisInsight/RedisInsight/issues/1317, let's track the progress there.
currently, this is only English support
