### ISSUE TITLE
[Feature Request]: Favorite filters

### ISSUE THREAD

**Issue by erodriguezv** [RedisInsight/RedisInsight#1611]
**Problem description** (Describe the problem you would like to solve with this feature request or suggested idea).
No Problem, but nice to have.
It would be useful if we had a "favorites" section with favorite filters.

**How often do you encounter this problem** (Describe how frequently this problem occurs).
I have many keys and sometimes remembering the pattern of a key is difficult.

**Alternatives considered** (Describe any alternative features or products you've considered).

**Additional information** (Add any other context or details here).

**Comment by ViktarStarastsenka** [comment]
hi @erodriguezv , thanks for the suggestion. Do you think it will be enough if RedisInsight remembers 10 patterns previously used?

**Comment by ViktarStarastsenka** [comment]
@erodriguezv , with 2.20 RedisInsight will display up to 10 patterns previously used.
Please re-open the ticket if it is still relevant.
