### ISSUE TITLE
[Feature Request]: Ability to modify database alias after adding database

### ISSUE THREAD

**Issue by bastianpedersen** [RedisInsight/RedisInsight#1636]
**Problem description**.
Add ability to change database alias after adding a database.

**How often do you encounter this problem**.
Every time I want to do this.

**Alternatives considered**.
Deleting the database and re-creating it with the desired alias.

**Comment by ViktarStarastsenka** [comment]
hi @bastianpedersen , to edit the database alias, please go to the list of databases and click to edit the database connection - there you will be able to change it. 

<img width="534" alt="image" src="https://user-images.githubusercontent.com/99594890/214811300-02b535aa-6a97-4dab-a73f-4639872e2c5a.png">
