### ISSUE TITLE
[Bug]: Serialized PHP objects appear as plain text

### ISSUE THREAD

**Issue by semisedlak** [RedisInsight/RedisInsight#1646]
**Preconditions** (Any important steps we need to know)
Saving PHP Serialized Objects to redis.

**Steps to reproduce** (How to reproduce what you found step by step)
Simply create a PHP Class, serialize it and then store it to Redis. Then view it in RedisIngsight.

Sample serialized data:
`O:8:"stdClass":3:{s:3:"one";s:1:"1";s:3:"two";s:3:"...";s:5:"three";i:3;}
`

**Actual behavior** (A short description of what you found)
Showing only as a plain text with error "Failed to convert to PHP serialized"

**Expected behavior** (A short description of what you expected to find)
I expect for it to appear as JSON stucture.

**Screenshots** (Paste or drag-and-drop a screenshot or a link to a recording)
![Screenshot 2023-01-27 at 10 33 58](https://user-images.githubusercontent.com/1753633/215054156-670fb09c-4210-4aad-bceb-40bb9a606e38.png)

**Additional context** (Operating system, version of RedisInsight, Redis database version, Redis module version, database type, connection type, logs, or any other information)
MacOS Ventura 13.0.1 (22A400) (Apple M1), RedisInsight 2.16.0 (2.16.0.70400), redis 5.0.3, Docker image on localhost

**Comment by ViktarStarastsenka** [comment]
hi @semisedlak , this is the current limitation of the library we use - it does not unserialize classes.

**Comment by ViktarStarastsenka** [comment]
hi @semisedlak , this is fixed in RedisInsight 2.32 (released today).

**Comment by GnaneshKunal** [comment]
Hey @endelwar, can you please send the sample payload over for us to look further?

**Comment by endelwar** [comment]
Sure! It is a PHP user session generated by a Symfony 5.4 web application

```
_sf2_attributes|a:5:{s:25:"_csrf/https-public_search";s:43:"QYf77qo6sWlicekA_V5_-8uGULUtNLQ_1bxvQEGQJNQ";s:27:"_csrf/https-diventa_cliente";s:43:"qFuEUBTAJYepxrCLzKti9hxEyvRVvVxkGVM-uLUx4Jg";s:24:"_csrf/https-lavoraconnoi";s:43:"fk8i-AO8pO1p1zUzyPNTjEjQyYWGfcugb9q6-Ly4XII";s:26:"_security.main.target_path";s:38:"https://laboratorio.test/areariservata";s:24:"_csrf/https-authenticate";s:43:"EYqFBvGnKcB0yi5LNup7SE8hX5DpCsZrcDjECzRXagA";}_sf2_meta|a:3:{s:1:"u";i:1693819036;s:1:"c";i:1693819004;s:1:"l";i:604800;}
```


This is the JSON from screenshot
```json
{
  "_sf2_attributes": {
    "_csrf/https-public_search": "QYf77qo6sWlicekA_V5_-8uGULUtNLQ_1bxvQEGQJNQ",
    "_csrf/https-diventa_cliente": "qFuEUBTAJYepxrCLzKti9hxEyvRVvVxkGVM-uLUx4Jg",
    "_csrf/https-lavoraconnoi": "fk8i-AO8pO1p1zUzyPNTjEjQyYWGfcugb9q6-Ly4XII",
    "_security.main.target_path": "https://laboratorio.test/areariservata",
    "_csrf/https-authenticate": "EYqFBvGnKcB0yi5LNup7SE8hX5DpCsZrcDjECzRXagA"
  },
  "_sf2_meta": {
    "u": 1693819036,
    "c": 1693819004,
    "l": 604800
  }
}
```

**Comment by semisedlak** [comment]
I can confirm it works for me now.
