### ISSUE TITLE
[Bug]: Total Memory and Total Keys are 0 in RedisInsight-v2

### ISSUE THREAD

**Issue by relgames** [RedisInsight/RedisInsight#1649]
**Steps to reproduce**  
Open RedisInsight-v2 and connect to Redis, then check the top right corner.

**Actual behavior**  
Total Memory and Total Keys are 0.

**Expected behavior**  
Total Memory and Total Keys should show actual memory and keys.
It works fine in v1.

**Screenshots**  
v2:
<img width="581" alt="Screenshot 2023-01-27 at 11 38 24" src="https://user-images.githubusercontent.com/179605/215066994-9ab3f5a1-f799-45c3-b907-169a0c456380.png">
v1:
<img width="504" alt="Screenshot 2023-01-27 at 11 40 32" src="https://user-images.githubusercontent.com/179605/215067037-32171f72-8e02-4414-807b-86186ccea744.png">

**Additional context** Version 2.16.0 (2.16.0.70400)
RedisInsight-v2 Version 2.10.0 (2.10.0.62864)
Also tried with latest Version 2.16.0 (2.16.0.70400)
Redis 6.2.7

**Comment by ViktarStarastsenka** [comment]
hi @relgames , can you please does `INFO MEMORY` return the used_memory value?
and `INFO KEYSPACE`?

**Comment by ViktarStarastsenka** [comment]
@relgames , please re-open the issue if it is still relevant.

**Comment by relgames** [comment]
Hi, I thought I added a comment, but now I don't see it. Maybe I didn't save it. Posting again:
<img width="1283" alt="Screenshot 2023-01-31 at 12 58 09" src="https://user-images.githubusercontent.com/179605/216981950-8be6a85b-4a15-46b4-81e2-5b56475bacd7.png">

So both commands return data in the same session but UI shows 0.

**Comment by ViktarStarastsenka** [comment]
@relgames , can you please open dev tools and share the response for the overview?

**Comment by ViktarStarastsenka** [comment]
also, does this database have OSS Cluster API enabled or disabled?

**Comment by relgames** [comment]
@ViktarStarastsenka 
```
{"version":"6.2.7","totalKeys":0,"usedMemory":0,"connectedClients":74,"opsPerSecond":57,"networkInKbps":2,"networkOutKbps":2,"cpuUsagePercentage":0.3184799999871757}
```
<img width="1596" alt="Screenshot 2023-02-07 at 11 48 57" src="https://user-images.githubusercontent.com/179605/217224455-877566b9-e06f-4642-a3d3-37e728c925e2.png">

This Redis instance doesn't use Cluster but Sentinel. I also checked on a few other instances and numbers are displayed properly, just this one instance is not working.

**Comment by arthosofteq** [comment]
@relgames Hi! Could you please provide me `info replication` command output or entire `info` command output? I'm trying to understand on which step this metric was ignored by RedisInsight. Thank you in advance

**Comment by relgames** [comment]
@arthosofteq 

Your comment made me try something, so looks like the issue only happens on a slave instance.
I tried to connect to master and it showed fine.

Here are commands output on the slave:

info replication
```
# Replication
role:slave
master_host:redis-2.redis-cluster.xyz111-prod.svc.cluster.local
master_port:6379
master_link_status:up
master_last_io_seconds_ago:0
master_sync_in_progress:0
slave_read_repl_offset:513910992447
slave_repl_offset:513910992447
slave_priority:100
slave_read_only:1
replica_announced:1
connected_slaves:0
master_failover_state:no-failover
master_replid:da77fc6757e0fce8a9d71ab3184ccd21378dff7e
master_replid2:0000000000000000000000000000000000000000
master_repl_offset:513910992447
second_repl_offset:-1
repl_backlog_active:1
repl_backlog_size:1048576
repl_backlog_first_byte_offset:513909943872
repl_backlog_histlen:1048576
```
info
```
instantaneous_output_kbps:2.09
rejected_connections:0
sync_full:0
sync_partial_ok:0
sync_partial_err:0
expired_keys:146
expired_stale_perc:0.04
expired_time_cap_reached_count:0
expire_cycle_cpu_milliseconds:0
evicted_keys:0
keyspace_hits:44883926
keyspace_misses:833811
pubsub_channels:1
pubsub_patterns:0
latest_fork_usec:2154
total_forks:23246
migrate_cached_sockets:0
slave_expires_tracked_keys:0
active_defrag_hits:0
active_defrag_misses:0
active_defrag_key_hits:0
active_defrag_key_misses:0
tracking_total_keys:0
tracking_total_items:0
tracking_total_prefixes:0
unexpected_error_replies:0
total_error_replies:29
dump_payload_sanitizations:0
total_reads_processed:805599565
total_writes_processed:63505548
io_threaded_reads_processed:0
io_threaded_writes_processed:0

# Replication
role:slave
master_host:redis-2.redis-cluster.xyz111-prod.svc.cluster.local
master_port:6379
master_link_status:up
master_last_io_seconds_ago:0
master_sync_in_progress:0
slave_read_repl_offset:513928200106
slave_repl_offset:513928200106
slave_priority:100
slave_read_only:1
replica_announced:1
connected_slaves:0
master_failover_state:no-failover
master_replid:da77fc6757e0fce8a9d71ab3184ccd21378dff7e
master_replid2:0000000000000000000000000000000000000000
master_repl_offset:513928200106
second_repl_offset:-1
repl_backlog_active:1
repl_backlog_size:1048576
repl_backlog_first_byte_offset:513927151531
repl_backlog_histlen:1048576

# CPU
used_cpu_sys:13572.270850
used_cpu_user:15649.688515
used_cpu_sys_children:1729.362616
used_cpu_user_children:9471.994856
used_cpu_sys_main_thread:13398.223508
used_cpu_user_main_thread:15627.909577

# Modules

# Errorstats
errorstat_ERR:count=1
errorstat_LOADING:count=25
errorstat_NOAUTH:count=3

# Cluster
cluster_enabled:0

# Keyspace
db0:keys=5022,expires=159,avg_ttl=0
info replication

Mar 13, 17:42:01
133.656 ms




# Replication
role:slave
master_host:redis-2.redis-cluster.xyz111-prod.svc.cluster.local
master_port:6379
master_link_status:up
master_last_io_seconds_ago:0
master_sync_in_progress:0
slave_read_repl_offset:513910992447
slave_repl_offset:513910992447
slave_priority:100
slave_read_only:1
replica_announced:1
```

**Comment by arthosofteq** [comment]
@relgames yep. It is due to a role. Thank you for helping me investigate this. I'll check what we can do here

**Comment by ViktarStarastsenka** [comment]
@relgames , please try it with 2.22 (released today).
Re-open the ticket if the issue is still reproducible.

**Comment by relgames** [comment]
Thank you, I confirm it now displays memory and total keys correctly for slave instances.
