### ISSUE TITLE
[Feature Request]: Filter for pubsub channels 

### ISSUE THREAD

**Issue by dmytrokarpovych** [RedisInsight/RedisInsight#1671]
Hello 👋 
Thanks for the great tool 🙇 

**Problem description** (Describe the problem you would like to solve with this feature request or suggested idea).
I'm trying to monitor a particular pub-sub channel on redis
For now, "Pub/Sub" section output all messages from all channels.
It will be very useful to have some filtering for channels if it is possible

**How often do you encounter this problem** (Describe how frequently this problem occurs).

**Alternatives considered** (Describe any alternative features or products you've considered).

**Additional information** (Add any other context or details here).
![image](https://user-images.githubusercontent.com/54802508/215852068-289a4c4e-0f22-4c44-8fe5-304e1065e684.png)

**Comment by ViktarStarastsenka** [comment]
@dmytrokarpovych , thank you, this is a great idea to improve the pub/sub experience.
I'll keep track of this idea, though it will not be delivered in any upcoming releases since the plans are pretty tough.

**Comment by 0xRapid** [comment]
It took me 3 minutes to do it. It kind of amazes me that this feature request has been here for so long.
https://github.com/RedisInsight/RedisInsight/pull/3801

**Comment by ViktarStarastsenka** [comment]
hi, an option to subscribe to specific Pub/Sub patterns has been added with 2.58 (released today).
@0xRapid thank you for your contribution.

**Comment by PanMan** [comment]
Thanks @0xRapid ! This feature is super useful for us!
