### ISSUE TITLE
[Feature Request]: Delete key in bulk

### ISSUE THREAD

**Issue by sandyisone** [RedisInsight/RedisInsight#1672]
Delete multiple pieces of key at once

**Comment by ViktarStarastsenka** [comment]
hi @sandyisone , please use the bulk actions in Browser
<img width="608" alt="image" src="https://user-images.githubusercontent.com/99594890/216028061-d82cc8b2-d462-45cc-8c9f-b18e20b8c3bf.png">

**Comment by ViktarStarastsenka** [comment]
or do you mean multiple values of a key?

**Comment by sandyisone** [comment]
@ViktarStarastsenka Thank you for your help
