### ISSUE TITLE
[Feature Request]: New app icon for macOS

### ISSUE THREAD

**Issue by aaronjheng** [RedisInsight/RedisInsight#1676]
**Problem description** (Describe the problem you would like to solve with this feature request or suggested idea).

Please consider: https://developer.apple.com/design/human-interface-guidelines/foundations/app-icons#macos/

**How often do you encounter this problem** (Describe how frequently this problem occurs).

**Alternatives considered** (Describe any alternative features or products you've considered).

**Additional information** (Add any other context or details here).

**Comment by ViktarStarastsenka** [comment]
hi @aaronjheng , any specific point that you would like to see covered?

**Comment by aaronjheng** [comment]
Just the rounded-rectangle shape.

**Comment by hendrickson-tyler** [comment]
I would love to see this too. Admittedly a very minor thing, but a uniform icon would go a long way to make the app feel like a modern macOS app:
![image](https://user-images.githubusercontent.com/6372535/234917342-5585c77f-40b6-4664-a0b9-2589e87e3980.png)

**Comment by ViktarStarastsenka** [comment]
hi @hendrickson-tyler , thanks for the feedback, the icon was updated with 2.28 (released today).
Please re-open the ticket if you have any feedback about it.
