### ISSUE TITLE
[Feature Request]: Make Wiki page even more easy to use

### ISSUE THREAD

**Issue by prnam** [RedisInsight/RedisInsight#172]
**Problem description**
Wiki is not helpful w.r.t using clipboard to copy commands. 

**How often do you encounter this problem**
Whenever a contributor visits the wiki to pick the command from the page.

**Alternatives considered**
Select command by hold and drag OR use clipboard and simply ignore unnecessary comment on your  terminal

**Additional information**
We need to update Wiki page on [How to build and contribute](https://github.com/RedisInsight/RedisInsight/wiki/How-to-build-and-contribute) as below -

- [Installation section](https://github.com/RedisInsight/RedisInsight/wiki/How-to-build-and-contribute#installation), must combine the command since both are required and remove `$`

  ```node 
  yarn install && yarn --cwd redisinsight/api/ 
  ```

  👆 is achieved with this syntax  
  
  > \```node  
            yarn install && yarn --cwd redisinsight/api/  
      \```

- Rest of the code snippet must also remove unnecessary `#Production`, `#Development` & `$` and make it easier for us to use it. 

Cannot update ourself; since last update was done by @ollopaci , so looping you. 🙂

**Comment by ViktarStarastsenka** [comment]
fixed, thank you
