### ISSUE TITLE
[Bug]: crash when adding new connection: undefined symbol: ERR_set_mark

### ISSUE THREAD

**Issue by Jimbolino** [RedisInsight/RedisInsight#1720]
**Preconditions**
```
$ lsb_release -d
Description:	Ubuntu 22.04.1 LTS
```
```
wget -N https://download.redisinsight.redis.com/latest/RedisInsight-v2-linux-x86_64.AppImage
chmod +x RedisInsight-v2-linux-x86_64.AppImage
./RedisInsight-v2-linux-x86_64.AppImage
```

**Steps to reproduce** (How to reproduce what you found step by step)
- click "ADD REDIS DATABASE"
- select "Use SSH Tunnel"
- enter host username / password or copy paste private key from file (not sure why this is needed, just automatically use from ~/.ssh ?)
- click "Add Redis Database"

**Actual behavior**
app crashes with:
```
[98748:0210/002759.170255:ERROR:cert_verify_proc_builtin.cc(681)] CertVerifyProcBuiltin for localhost failed:
----- Certificate i=0 (CN=853e5fb23bc,OU=Redis GUI,O=Redisinsight) -----
ERROR: No matching issuer found


/tmp/.mount_RedisIgdTLPs/redisinsight --enable-crashpad: symbol lookup error: /tmp/.org.chromium.Chromium.lchwPZ: undefined symbol: ERR_set_mark
```

**Comment by ViktarStarastsenka** [comment]
hi @Jimbolino , thank you for reporting this, the fix will be available on 2.20 (late February)
