### ISSUE TITLE
[Bug]: env: python: No such file or directory

### ISSUE THREAD

**Issue by LoreYun** [RedisInsight/RedisInsight#1729]
I got this error message when run `yarn install` on macOS 12.6.3.
```
env: python: No such file or directory
make: *** [Release/sass.a] Error 127
gyp ERR! build error
```
Cause [macOS 12.3 has removed the Python 2 support](https://developer.apple.com/documentation/macos-release-notes/macos-12_3-release-notes#Python).
So, if macOS version > 12.3, you need install python, then create a link file to `/usr/local/bin/python`.
In my case, just exec `ln -s -f /usr/local/bin/python3 /usr/local/bin/python`.

I don't know which specific python version was needed, please consider specifying the correct version in the wiki.

**Comment by ViktarStarastsenka** [comment]
hi, please install python 3 or, if you already have it, add the alias python=python3 to your shell

**Comment by LoreYun** [comment]
> hi, please install python 3 or, if you already have it, add the alias python=python3 to your shell

Copy that, thank you.
