### ISSUE TITLE
[Bug]: `Key Type` in create form is misleading; proposal to use `Data Type`

### ISSUE THREAD

**Issue by prnam** [RedisInsight/RedisInsight#173]
**Preconditions**

 You just need to know how to open `Add Key` in Redis-Insight-Preview

**Steps to reproduce**

Connect to your instance using Redis-Insisght-Preview > Click on `+Key` button; an Add Key form opens up > You should be able see a label `Key Type*` along with other form labels and fields.

**Actual behavior**

`Key Type` is kind of misleading from what the official redis.io document classify it as. 

**Expected behavior**

In my opinion it should be called `Data Type` than `Key Type`.

**Screenshots**

![keys-or-data-types?](https://user-images.githubusercontent.com/68323012/147874240-f3ef2c81-eca1-4d72-aedb-8ac9626ff5b5.png)

**Additional context** 

RedisInsight-Preview-2.0.3

**Comment by ollopaci** [comment]
Thank @prnam for the observation. We will address this in the next release.

**Comment by prnam** [comment]
Hey @ollopaci,
Thank you for checking the issue. I was not really sure if any of the issues I raised would be accepted. 

Now that this one is accepted, wanted to know if it is open for me / anybody to contribute. Could not find any labels to know too; what indicates any of these are open to contribution?

**Comment by ollopaci** [comment]
Hi @prnam. Of course it is open for anyone to contribute. We actually would really like to encourage that. Taking your proposal and will create a corresponding label for this. Thank you!

**Comment by prnam** [comment]
Thank you for your timely response @ollopaci . I have raised the PR that will close this issue. Looking forward for CI approval for first time contributors, review and hoping everything will be good to merge 🤞

**Comment by prnam** [comment]
Okay, @ViktorStarostenko . Thank you for reviewing and sharing the decision. 🙂

I assume no action item from my end as such; you or the team will take necessary action on the issue and PR, right?

**Comment by ViktorStarostenko** [comment]
@prnam, yes, we will take care of them.
