### ISSUE TITLE
[Feature Request]: Ability to add `N` elements to `List` at the add key form

### ISSUE THREAD

**Issue by prnam** [RedisInsight/RedisInsight#174]
**Problem description** 

Scenario 1 : As user, I have default `N` elements that I want to push to left on `List`, using add key form
Scenario 2: As user, I have default `N` elements that I want to push to right on `List`, using add key form

**How often do you encounter this problem**
Every time I have N pre-selected elements to push to list ( all right / all left)

**Alternatives considered**

- Use add form through GUI, add follow this step:

    > Create first element in the add key form  > Now, open the `keyDetails` for that particular `List` and then click `+` icon > Select push to left / push to right and add value > Click 

- Use `LPUSH` or `RPUSH` command through `cli` component in GUI

**Additional information**

This is how it is now - 
<img width="659" alt="list-add-now" src="https://user-images.githubusercontent.com/68323012/147874078-294204f7-2275-451a-8200-5632839af63a.png">

This is how it is expected -
<img width="670" alt="list-bulk-push" src="https://user-images.githubusercontent.com/68323012/147874082-24d613cb-17e7-4a7b-8169-be971d16f9a0.png">

**Comment by ViktorStarostenko** [comment]
Hello @prnam, thank you for this idea, it is really useful, but this has not been included in the nearest releases. Though we are open to contributions.

**Comment by ViktarStarastsenka** [comment]
this is available in Redis Insight 2.60 (released today).
