### ISSUE TITLE
[Bug]:

### ISSUE THREAD

**Issue by iWuYc** [RedisInsight/RedisInsight#1748]
**Preconditions** (Any important steps we need to know)
![image](https://user-images.githubusercontent.com/13282051/219529672-c3045924-6fbf-4569-97ae-a2efdfbd6684.png)

key like this:  a:\\[

**Steps to reproduce** (How to reproduce what you found step by step)

**Actual behavior** (A short description of what you found)

**Expected behavior** (A short description of what you expected to find)

**Screenshots** (Paste or drag-and-drop a screenshot or a link to a recording)

**Additional context** (Operating system, version of RedisInsight, Redis database version, Redis module version, database type, connection type, logs, or any other information)

**Comment by ViktarStarastsenka** [comment]
hi @iWuYc , can you please provide steps to reproduce it?
I managed to create a key and everything works fine
<img width="691" alt="image" src="https://user-images.githubusercontent.com/99594890/219649354-975edea9-33b3-41a3-a36a-bdeb6994cc04.png">

**Comment by iWuYc** [comment]
![image-20230221131350765](https://user-images.githubusercontent.com/13282051/220254950-3b8da4e9-2b78-4373-ad82-6646e016e3ba.png)
![image](https://user-images.githubusercontent.com/13282051/220255715-36252f70-8622-421e-8e79-a335146f2aeb.png)

- I have redis cluster,the version was 3.2.8.
- Exec `set a:[1] test1` for add key 'a:[1]'
- And then I try to input 'a:[1]' into input-box(gui),can't find any result.
- So,I change the key 'a:\\[1\\]',it pop error `ERR unknown command 'memory'` like the  previously upload picture.Early version it was work,like 2.2.0.
![image](https://user-images.githubusercontent.com/13282051/220255559-b4ea0371-7929-4f84-b8a0-d76f220e1b92.png)
- But I can use 'CLI' run `get a:[1]` without '\\' character,it was work;
![image](https://user-images.githubusercontent.com/13282051/220255394-1caad0e7-1cfd-4f69-a48b-c72aaa874a6a.png)

**Comment by ViktarStarastsenka** [comment]
@iWuYc , `MEMORY USAGE` command is supported from Redis 4.0. This command is used to get the size of keys. - https://redis.io/commands/memory-usage/
You can update your database to the latest one to fix this issue - https://redis.io/download/.
