### ISSUE TITLE
[Bug]: Redis insight's GUI automatically saves the password when i apply password authentication in redis cli. One more thing if i login on one machine it automatically login to any of the device who will access its ip.

### ISSUE THREAD

**Issue by abdullah037** [RedisInsight/RedisInsight#1751]
**Preconditions** (Any important steps we need to know)

**Steps to reproduce** (How to reproduce what you found step by step)

**Actual behavior** (A short description of what you found)

**Expected behavior** (A short description of what you expected to find)

**Screenshots** (Paste or drag-and-drop a screenshot or a link to a recording)

**Additional context** (Operating system, version of RedisInsight, Redis database version, Redis module version, database type, connection type, logs, or any other information)

**Comment by ViktarStarastsenka** [comment]
@abdullah037 , can you please provide more details?
what is the case when a password is saved in RedisInsight when you apply password authentication in redis-cli?

**Comment by ViktarStarastsenka** [comment]
please check it with the latest version, and re-open the ticket if the issue still persists
