### ISSUE TITLE
[Bug]: Big Keys (more than 3MB) crash RedisInsight

### ISSUE THREAD

**Issue by faulander** [RedisInsight/RedisInsight#1771]
**Preconditions** (Any important steps we need to know)
have a key with more than 3mb

**Steps to reproduce** (How to reproduce what you found step by step)
see above

**Actual behavior** (A short description of what you found)
clicking on that key it loads the key, but stays on "empty" and crashes.

**Expected behavior** (A short description of what you expected to find)
loading of big keys should work

**Screenshots** (Paste or drag-and-drop a screenshot or a link to a recording)

**Additional context** (Operating system, version of RedisInsight, Redis database version, Redis module version, database type, connection type, logs, or any other information)

**Comment by ViktarStarastsenka** [comment]
hi @faulander , what data type do you use?

**Comment by faulander** [comment]
I use stringified json.

ViktarStarastsenka ***@***.***> schrieb am Mi. 22. Feb. 2023
um 20:47:

**Comment by ViktarStarastsenka** [comment]
hi @faulander , please try RedisInsight 2.36 (released today).
there you can either load the entire value (not recommended) or download the value into a file.
