### ISSUE TITLE
[Bug]:

### ISSUE THREAD

**Issue by ganesh-9030** [RedisInsight/RedisInsight#1785]
![image](https://user-images.githubusercontent.com/126464124/221540797-1b98014d-1094-4177-9146-4c84d6430fea.png)

while download application and after install getting this error after select agreement also

**Comment by ViktarStarastsenka** [comment]
hi @ganesh-9030 , thank you for reporting this issue. Can you please send logs? They are under your local user in the redisinsight-v2 folder.
But please remove any sensitive info from the.
