### ISSUE TITLE
[Bug]: Charts don't work with TS.RANGE queries

### ISSUE THREAD

**Issue by arank-primer** [RedisInsight/RedisInsight#1804]
**Preconditions** (Any important steps we need to know)
```
ts.range key - + aggregation sum 3600000
 ```
 The query works and returns the data, but it doesn't render a chart.

A chart should be rendered, but it is not.
<img width="882" alt="Screenshot 2023-03-03 at 23 58 19" src="https://user-images.githubusercontent.com/126838312/222857193-f6310325-008d-46ac-ba63-074aa581239c.png">

If you change to text instead of chart, it shows the data. 

<img width="876" alt="Screenshot 2023-03-03 at 23 58 30" src="https://user-images.githubusercontent.com/126838312/222857199-d4f245c6-41ba-42d3-b3bb-634135ad5aaf.png">

**Steps to reproduce** (How to reproduce what you found step by step)
Query timeseries using ts.range command - ts.mrange queries still work

**Actual behavior** (A short description of what you found)
Chart doesn't render - in the console you see:
```
TypeError: Cannot read properties of undefined (reading 'map')
    at x (index.js:3526:32437)
    at index.js:3526:31245
    at Array.map (<anonymous>)
    at r (index.js:3526:31180)
    at index.js:3526:30677
    at bM (index.js:9:6670)
    at to.unstable_runWithPriority (index.js:1:11944)
    at Zc (index.js:5:38565)
    at kc (index.js:9:6134)
    at dy (index.js:7:10803)
    
```

**Expected behavior** (A short description of what you expected to find)
Chart to render

**Screenshots** (Paste or drag-and-drop a screenshot or a link to a recording)

**Additional context** (Operating system, version of RedisInsight, Redis database version, Redis module version, database type, connection type, logs, or any other information)
Mac OS Big Sur 11.4
Redis Insights version 2.20

**Comment by GnaneshKunal** [comment]
Hey @arank-primer,

A fix for the same has been raised. For now, use the uppercase version of the command till the next release.
