### ISSUE TITLE
[Feature Request]:The urgent requirement feature is deleted in batches

### ISSUE THREAD

**Issue by qinyou10621** [RedisInsight/RedisInsight#1810]
Many times we need to delete data in batches by asterisk matching， I think this feature is very important

**Comment by ViktarStarastsenka** [comment]
hi @qinyou10621 , RedisInsight already has support for deleting in bulk - please use the bulk deletion in Browser.

<img width="1286" alt="Screenshot 2023-03-07 at 11 07 26" src="https://user-images.githubusercontent.com/99594890/223405377-7486f6d9-d4a4-45df-968b-67e6f807dc42.png">
