### ISSUE TITLE
[Bug]: Browser tab show "Something went wrong fetching the value of key:"

### ISSUE THREAD

**Issue by kpchu** [RedisInsight/RedisInsight#182]
**Preconditions** (Any important steps we need to know)
In `Browser tab`, i am able to fetch and display some of the `Hash`, but some of them cannot. The `Hash` size are both <1MB

**Steps to reproduce** (How to reproduce what you found step by step)
Click `Browser -> Hash key` 

**Actual behavior** (A short description of what you found)
Unable to fetch and show error `Something went wrong fetching the value of key`

**Expected behavior** (A short description of what you expected to find)
Able to fetch hash value and display

**Screenshots** (Paste or drag-and-drop a screenshot or a link to a recording)
![image](https://user-images.githubusercontent.com/16525461/148323896-f7fe9e23-607e-44fd-983d-4ee28e58ea8e.png)

**Additional context** (Operating system, version of RedisInsight, Redis database version, Redis module version, database type, connection type, logs, or any other information)

- RedisInsight on Kubernetes 
- RedisInsight version: redislabs/redisinsight:latest
- Redis database version: docker.io/bitnami/redis-cluster:6.2.6-debian-10-r21

**Comment by kpchu** [comment]
Also, when execute `HGETALL`, it is able to get the hash data which cannot be fetched on `Browser`

**Comment by kpchu** [comment]
Started `redis-cli monitor` on Redis cluster server when clicking failed fetching hash data, all the commands can execute witout any error

``` 
"TTL" "TS:Tunnel:{94540110910009999}:01312d01:c0a801c81:UA"
"TYPE" "TS:Tunnel:{94540110910009999}:01312d01:c0a801c81:UA"
"MEMORY" "USAGE" "TS:Tunnel:{94540110910009999}:01312d01:c0a801c81:UA"
"TYPE" "TS:Tunnel:{94540110910009999}:01312d01:c0a801c81:UA"
"TYPE" "TS:Tunnel:{94540110910009999}:01312d01:c0a801c81:UA"
"HLEN" "TS:Tunnel:{94540110910009999}:01312d01:c0a801c81:UA"
"MEMORY" "USAGE" "TS:Tunnel:{94540110910009999}:01312d01:c0a801c81:UA"
"HSCAN" "TS:Tunnel:{94540110910009999}:01312d01:c0a801c81:UA" "0" "MATCH" "*" "COUNT" "50"
"TTL" "TS:Tunnel:{94540110910009999}:01312d01:c0a801c81:UA"
"TYPE" "TS:Tunnel:{94540110910009999}:01312d01:c0a801c81:UA"
"MEMORY" "USAGE" "TS:Tunnel:{94540110910009999}:01312d01:c0a801c81:UA"
"TYPE" "TS:Tunnel:{94540110910009999}:01312d01:c0a801c81:UA"
"HLEN" "TS:Tunnel:{94540110910009999}:01312d01:c0a801c81:UA"
```

**Comment by GnaneshKunal** [comment]
@kpchu What did the data contain and Is it possible to provide a sample data?

**Comment by kpchu** [comment]
@GnaneshKunal thanks for help, the issue caused by hash field with empty string `""`, for example in my field `cpTeidIp`

```
hgetall TS:Tunnel:{94540110910009999}:01312d01:c0a801c81:UA
-> Redirected to slot [10847] located at 10.233.114.174:6379
1) "ueIp"
2) "0a4503039999"
3) "sessionKey"
4) "{94540110910009999}:01312d01:c0a801c81"
5) "rat"
6) "6"
7) "cpTeidIp"
8) ""
```

Also, `All fields are required` validation won't work after input some value and delete again(e.g. empty in `value` when click `ADD FIELD` button). And the error message can be reproduced.

![image](https://user-images.githubusercontent.com/16525461/148872635-f6e1c3ba-52fe-44f9-bf7e-31cb1c413bb0.png)

![image](https://user-images.githubusercontent.com/16525461/148872644-3a9b5fb8-832c-44d0-bafb-dd40c1dfe9a4.png)

**Comment by GnaneshKunal** [comment]
@kpchu 

Can you try with the latest version of redisinsight v1 (`1.11.0`). This issue is fixed in that.

**Comment by kpchu** [comment]
> @kpchu
> 
> Can you try with the latest version of redisinsight v1 (`1.11.0`). This issue is fixed in that.

Tested redisinsight v1 (1.11.0) fixed that
