### ISSUE TITLE
[Bug]:

### ISSUE THREAD

**Issue by ffckaburga** [RedisInsight/RedisInsight#1824]
redis insight does not see the redis I use with a docker container (I use official redis image which is from docker hub in it)

**Comment by ViktarStarastsenka** [comment]
@ffckaburga , can you please provide more details about your docker and RedisInsight configurations?
I guess there can be some configuration issues.

**Comment by ffckaburga** [comment]
I used the redis image with:  docker pull redis
I used the command:  docker run -d -p 6379:6379 --name redisapi redis

these below are the supplementary screenshots for my container and code
that utilize redis,

redisinsight does not see my redis database automatically, but also doesn't
see when I add it  manually

ViktarStarastsenka ***@***.***>, 10 Mar 2023 Cum, 20:19
tarihinde şunu yazdı:

**Comment by ViktarStarastsenka** [comment]
@ffckaburga , I can't find the screens, please re-attach them
also, did you try to connect to the Redis database via redis-cli just to be sure there is no connection/configuration issue?

**Comment by ffckaburga** [comment]
---------- Forwarded message ---------
Gönderen: Fuat Can Kaburga ***@***.***>
Date: 10 Mar 2023 Cum 21:24
Subject: Re: [RedisInsight/RedisInsight] [Bug]: (Issue #1824)
To: RedisInsight/RedisInsight <
***@***.***>


I used the redis image with:  docker pull redis
I used the command:  docker run -d -p 6379:6379 --name redisapi redis

these below are the supplementary screenshots for my container and code
that utilize redis,

redisinsight does not see my redis database automatically, but also doesn't
see when I add it  manually

ViktarStarastsenka ***@***.***>, 10 Mar 2023 Cum, 20:19
tarihinde şunu yazdı:

**Comment by ffckaburga** [comment]
when I use, "docker exec -it container_name redis-cli" there is no problem,
database works correctly but it doesnt seen in redisinsight

12 Mar 2023 Paz 00:39 tarihinde ViktarStarastsenka ***@***.***>
şunu yazdı:

**Comment by GnaneshKunal** [comment]
Hey @ffckaburga, which platform are you in?

Use `localhost` as host if the port is properly forwarded via the `-p` argument or use docker IP or your computer's IP. Also, RedisInsight is in its own network too so it can't find any other services if you are running it in docker.

Do use both services within a docker-compose so that you don't have to manually add networks to get it working.

Once you add both redisinsight and redis in your docker-compose file, you can reach redis just via redis's docker service name.

**Comment by ffckaburga** [comment]
Thanks for the answer.

Gnanesh ***@***.***>, 13 Mar 2023 Pzt, 04:24 tarihinde şunu
yazdı:

**Comment by ViktarStarastsenka** [comment]
please re-open the ticket if it is still relevant
