### ISSUE TITLE
[Bug]: LCS command not working from CLI tool in RedisInsight

### ISSUE THREAD

**Issue by SoulPancake** [RedisInsight/RedisInsight#1826]
**Preconditions** (Any important steps we need to know)

Tried to run the command as described in the docs https://redis.io/commands/lcs/
**Steps to reproduce** (How to reproduce what you found step by step)

**Actual behavior** (A short description of what you found)

**Expected behavior** (A short description of what you expected to find)

**Screenshots** (Paste or drag-and-drop a screenshot or a link to a recording)
"ERR unknown command `LCS`, with args beginning with: `key1`, `key2`, "
![image](https://user-images.githubusercontent.com/70265851/224332800-ac537062-22f7-47b8-8b7f-b7f1897bb68e.png)

**Additional context** (Operating system, version of RedisInsight, Redis database version, Redis module version, database type, connection type, logs, or any other information)

**Comment by ViktarStarastsenka** [comment]
@SoulPancake , check that your Redis database is 7.0.0 or higher (you can run `INFO SERVER` to check it). The command is available from 7.0.

**Comment by SoulPancake** [comment]
@ViktarStarastsenka Thanks and sorry for raising this, completely missed the config
