### ISSUE TITLE
[Feature Request]: History for key search

### ISSUE THREAD

**Issue by emberTrev** [RedisInsight/RedisInsight#1827]
It would be very nice to have a dropdown of recent searches. I find I am very often doing a certain search, then clearing it to see other stuff, then typing out or pasting that search again. It could even work similar to command line stuff where you can press up and down in the search box to walk through previous searches.

Example from visual studio:
![Screenshot_2023-03-10-11-19-47_devenv](https://user-images.githubusercontent.com/15948368/224406819-365b3511-a3ba-47cf-bbe1-268ff6a46b70.png)
![Screenshot_2023-03-10-11-19-56_devenv](https://user-images.githubusercontent.com/15948368/224406830-9980b4e9-53ee-4f0c-ae45-0ffaa17243e5.png)

**Comment by ViktarStarastsenka** [comment]
@emberTrev , please check it with 2.20 or 2.22 (released today), we added the history of previous searches.
