### ISSUE TITLE
[Bug]: UI does not provide visual feedback when Failover request fails

### ISSUE THREAD

**Issue by molshansky-zipwhip** [RedisInsight/RedisInsight#183]
**Preconditions** (Any important steps we need to know)
Need to have a cluster setup and the failover option visible under Cluster Management -> Shards -> Replica

**Steps to reproduce** (How to reproduce what you found step by step)
- Set up a Redis cluster with shards and replicas 
- Restrict the failover option to an elevated/special permission
- Connect to the cluster via RedisInsight using a non-privileged account
- Click Failover

**Actual behavior** (A short description of what you found)
- After clicking 'Failover' and 'Proceed', UI doesn't respond (though watching network activity in the browser shows the API fail-over-cluster-node call return 500)

**Expected behavior** (A short description of what you expected to find)
- UI indicates that call failed, preferably with Details indicating why

**Screenshots** (Paste or drag-and-drop a screenshot or a link to a recording)
<img width="1142" alt="Screen Shot 2022-01-05 at 8 59 36 PM" src="https://user-images.githubusercontent.com/54086792/148326366-093af98c-d7de-445c-add3-2f16d05ff6dd.png">

**Additional context** (Operating system, version of RedisInsight, Redis database version, Redis module version, database type, connection type, logs, or any other information)
RedisInsight version 1.11.0
Redis 6.0.5 - AWS ElastiCache
My particular issue occurred when connecting RedisInsight to AWS ElastiCache. Turns out that the role I was using didn't have permission to induce a failover, but this was non-obvious because the RedisInsight UI provided no visible user feedback.

**Comment by GnaneshKunal** [comment]
Hey @molshansky-zipwhip 

Can you tell us what the response was?

**Comment by GnaneshKunal** [comment]
@molshansky-zipwhip 

A fix has been raised that displays the error. Will be up in the very next release.
