### ISSUE TITLE
[Bug]:Doesn't connect to localhost or 127.0.0

### ISSUE THREAD

**Issue by StopGuardianDev** [RedisInsight/RedisInsight#1832]
![Screen Shot 2023-03-13 at 8 53 57 PM](https://user-images.githubusercontent.com/106351272/224864664-ac9cd785-dead-4a64-8283-4e7e7df949db.png)
Error

Could not connect to localhost:3060, please check the connection details.

**Comment by ViktarStarastsenka** [comment]
@StopGuardianDev , please check the connection details

**Comment by ViktarStarastsenka** [comment]
@StopGuardianDev , is this issue still relevant? can you please connect to the localhost via redis-cli to check that there is no connection issue?

**Comment by ViktarStarastsenka** [comment]
@StopGuardianDev , please re-open the ticket if it is still relevant with 2.24.
