### ISSUE TITLE
[Bug]: AUR: Plugins folder missing from building

### ISSUE THREAD

**Issue by SteinGaming** [RedisInsight/RedisInsight#1844]
**Preconditions** (Any important steps we need to know)
Didn't have RedisInsight installed previously (/opt/redisinsight should be missing)
(Not required, should be the same for all distrubutions) Use Arch Linux

**Steps to reproduce** (How to reproduce what you found step by step)
Install the RedisInsight package from the [AUR here](https://aur.archlinux.org/packages/redisinsight)

It uses the same way as the wiki, but it changes the behaviour of the electron-builder, so it doesn't create the .AppImage, .deb and the .snap files, making it much faster and not seeming like it changed anything (see Expected Behaviour).

**Actual behavior** (A short description of what you found)
Missing the `/opt/redisinsight/resources/static/plugins` (optional) and the `/opt/redisinsight/resources/static/resources/plugins` folder.
The ladder is mandatory, throwing the following error trying to create it and preventing any interaction with the app (see screenshot 1):
```20:05:13.508 › Available port: 5001
20:05:13.800 › Catch server error: Error: EACCES: permission denied, mkdir '*****/plugins'
    at Object.mkdirSync (node:fs:1336:3)
    at eval (webpack://redisinsight/./redisinsight/api/dist/src/app.module.js?:49:20)
    at Array.forEach (<anonymous>)
    at AppModule.onModuleInit (webpack://redisinsight/./redisinsight/api/dist/src/app.module.js?:47:25)
    at callModuleInitHook (webpack://redisinsight/./redisinsight/api/node_modules/@nestjs/core/hooks/on-module-init.hook.js?:51:35)
    at async NestApplication.callInitHook (webpack://redisinsight/./redisinsight/api/node_modules/@nestjs/core/nest-application-context.js?:178:13)
    at async NestApplication.init (webpack://redisinsight/./redisinsight/api/node_modules/@nestjs/core/nest-application.js?:96:9)
    at async NestApplication.listen (webpack://redisinsight/./redisinsight/api/node_modules/@nestjs/core/nest-application.js?:154:33)
    at async bootstrap (webpack://redisinsight/./redisinsight/api/dist/src/main.js?:37:5)```
```
Doing anything notifies the user of `ERROR! Something was wrong!` and it doesn't load any data from the configuration.
 
**Expected behavior** (A short description of what you expected to find)
This is how I build the package:
```
build() {
  cd "$srcdir/RedisInsight-$pkgver" # Go into the archive directory, downloaded from https://github.com/RedisInsight/RedisInsight/archive/VERSION.tar.gz"
  yarn install  # Follows the 1. instruction from the wiki.
  yarn --cwd redisinsight/api/      # Follows the 2. instruction from the wiki.
  NODE_OPTIONS=--openssl-legacy-provider yarn build:prod # Extracted the 1. command from "package:prod", to compile the code
  yarn electron-builder build --dir -p never  #  Extracted the 2. command from the previous, but making it so that it only makes the release "linux-unpacked"
}
```
After building, it copies every file to the /opt/redisinsight directory, which should contain the folders named in **Actual behaviour** with their corresponding subdirectories, but it doesn't exist in the first place.

Taking a quick look at the AppImage avalible on your website, it does contain those directories and the first directory (`/opt/redisinsight/resources/static/plugins`, optional) contains the actual plugins in subdirectories and the second directory (`/opt/redisinsight/resources/static/resources/plugins`, mandatory), contains fonts and css style files.
The mandatory one is allowed to be empty, and it works normally without any contents.

**Screenshots** (Paste or drag-and-drop a screenshot or a link to a recording)
Screenshot 1: ![image](https://user-images.githubusercontent.com/69219673/226000332-0f74903b-ba11-44b6-a274-84bc208aff4c.png)

**Additional context** (Operating system, version of RedisInsight, Redis database version, Redis module version, database type, connection type, logs, or any other information)
- OS: Arch Linux
- RedisInsight Version: 2.20.0
- The same information given in [this](https://aur.archlinux.org/packages/redisinsight#comment-906534) comment

**Comment by ViktarStarastsenka** [comment]
please check it with 2.48 and re-open the ticket if the issue still reproduces.
