### ISSUE TITLE
Issue with installing RedisInsight silently and for all users

### ISSUE THREAD

**Issue by manowar689** [RedisInsight/RedisInsight#1859]
**Preconditions**

We are looking for steps to install RedisInsight on an Amazon product called AppStream 2.0, We would usually create a PowerShell Session and then run the following:

`    Write-Output "Installing Redis Insights V2"
    $InstallerPath = "C:/Source/appstream/Systems/Installers/RedisInsights"
    $InstallerFile = "$InstallerPath/RedisInsight-v2-win-installer.exe"
    $Argumentlist = "/S /v/qn"
    Write-Output "FilePath: $InstallerFile"
    Start-Process -FilePath $InstallerFile -Wait -ArgumentList $Argumentlist
`
this would be accepted usually using a previous version of RDM but is failed on the newer RedisInsight.

**Steps to reproduce**
Set up and AD connected user and remote to an instance of Windows Server 2019 (version of the operating system used in AppStream 2.0)

**Actual behavior**

Not installed and when run manually would be installed for all users

**Expected behavior**
Would be silently installed and be available to all users

**Additional context**
Windows 2019 with the above mentioned version of RedisInsight-v2-win-installer.exe

**Comment by ViktarStarastsenka** [comment]
hi @manowar689 , you can select a custom installation directory for Windows OS starting from RedisInsight 2.32 (released today).
