### ISSUE TITLE
[Feature Request]:Windows Installer Multi User Support

### ISSUE THREAD

**Issue by rob-watson** [RedisInsight/RedisInsight#1862]
**Problem description** The existing Windows Installer will only install in single user mode. It does not support all user installation. 

**How often do you encounter this problem** On every attempt to Installi the software ( using an administrator account ) on a Windows machine accessed by many users.

**Alternatives considered** None

**Additional information** I believe there is support in NSIS to achieve this. See https://nsis.sourceforge.io/Docs/MultiUser/Readme.html

**Comment by ViktarStarastsenka** [comment]
hi @rob-watson , you can select a custom installation directory for Windows OS starting from RedisInsight 2.32 (released today).
