### ISSUE TITLE
[Bug]: RedisInsight-v2-win-installer - Couldn't accept the privacy agreement

### ISSUE THREAD

**Issue by RahulKannan12** [RedisInsight/RedisInsight#1869]
**Preconditions** (Any important steps we need to know)

**Steps to reproduce** 
1. run the win-installer
2. post successful completion - instead of auto-open, open the RedisInsight application manually
3. Try to accept the terms and conditions 
Step 3 fails

**Actual behavior** (A short description of what you found)
When Accepting the Terms and Conditions - Internal Server Error message is displayed

**Expected behavior** (A short description of what you expected to find)
Terms and conditions should be accepted and allow user to proceed using the application

**Screenshots** (Paste or drag-and-drop a screenshot or a link to a recording)
Found the following error message in internal error logs (redisinsight-errors-2023-03-25)

SQLITE_CONSTRAINT: UNIQUE constraint failed: agreements.id

**Additional context** (Operating system, version of RedisInsight, Redis database version, Redis module version, database type, connection type, logs, or any other information)
RedisInsight - V2

**Comment by ViktarStarastsenka** [comment]
please check this with the latest version (2.26), and re-open the ticket if relevant
