### ISSUE TITLE
Please support multiple languages

### ISSUE THREAD

**Issue by liuyi-stack** [RedisInsight/RedisInsight#1883]
Please support multiple languages

**Comment by ViktarStarastsenka** [comment]
hi @liuyi-stack , what language would you like to have?

**Comment by dukang2018** [comment]
> 你好@liuyi-stack, 你想要什么语言？
中文

**Comment by asxez** [comment]
一致观点，我也希望支持中文！

**Comment by ViktarStarastsenka** [comment]
let's track this request under this ticket - https://github.com/RedisInsight/RedisInsight/issues/1317.
