### ISSUE TITLE
[Bug]: Ping failed to Redis sentinel with no pass, RIAUTHPROMPT enabled

### ISSUE THREAD

**Issue by leqduyvp** [RedisInsight/RedisInsight#1884]
**Preconditions** (Any important steps we need to know)
- Deploy Redis Insight on K8S cluster with RIAUTHPROMPT enabled
- Add a redis sentinel database to database list.

**Steps to reproduce** (How to reproduce what you found step by step)
Access to the database from the Redis Insight web UI

**Actual behavior** (A short description of what you found)
A red "Error" is shown

**Expected behavior** (A short description of what you expected to find)
The authentication should be successfully completed

**Screenshots** (Paste or drag-and-drop a screenshot or a link to a recording)
![image](https://user-images.githubusercontent.com/47497512/228758278-2681ff7c-c685-4607-8b26-dfd1033cc7c6.png)
![image](https://user-images.githubusercontent.com/47497512/228758356-380fff65-c0b8-472e-bf9d-10b6b3d6b231.png)

**Additional context** (Operating system, version of RedisInsight, Redis database version, Redis module version, database type, connection type, logs, or any other information)
image: redislabs/redisinsight:1.13.1

**Comment by GnaneshKunal** [comment]
@leqduyvp This should be fixed in the latest release of RedisInsight v1 - `v1.14.0`. 

Please reopen the issue if it persists.
