### ISSUE TITLE
[Bug]: "Display on System Tray" not relevant on macOS

### ISSUE THREAD

**Issue by kfrymire** [RedisInsight/RedisInsight#1902]
**Preconditions** (Any important steps we need to know)
Present on macOS version

**Steps to reproduce** (How to reproduce what you found step by step)
Launch app in macOS, open the "Window" menu

**Actual behavior** (A short description of what you found)
Launch app, click "Window" menu item.  Menu item reads "Display On System Tray" which is a Windows-only feature.  The macOS Menu Bar or Control Center would be the macOS equivalent.

**Expected behavior** (A short description of what you expected to find)
Click "Window" menu item, see menu item that reads "Show in Menu Bar", or maybe "Show in Control Center"

**Screenshots** (Paste or drag-and-drop a screenshot or a link to a recording)
<img width="503" alt="Screenshot 2023-04-03 at 9 31 35 AM" src="https://user-images.githubusercontent.com/16312945/229540944-4fc8e4ac-1bf4-4d80-8b27-b083071db9bb.png">

**Additional context** (Operating system, version of RedisInsight, Redis database version, Redis module version, database type, connection type, logs, or any other information)
Evident on macOS

**Comment by ViktarStarastsenka** [comment]
hi @kfrymire , thank you for reporting this.
it will be renamed with the upcoming releases.

**Comment by ViktarStarastsenka** [comment]
@kfrymire , please check it with 2.24 (released today).
re-open the issue if it is still relevant.
