### ISSUE TITLE
[Feature Request]: Not able to parse RDB dump collected from Redis Engine Version 7

### ISSUE THREAD

**Issue by Munish629** [RedisInsight/RedisInsight#1908]
**Not able to parse RDB dump collected from Redis Engine Version 7** 

**We moved to Redis Engine Version 7 recently and older Redis Insight is not able to parse ** 

**
ERROR 2023-04-04 10:23:48,375 redisinsight Error in memory analysis job
Traceback (most recent call last):
  File "redisinsight\memory_analysis\services\analysis\__init__.py", line 297, in analyze_instance
  File "redisinsight\memory_analysis\services\analysis\lib.py", line 25, in generate_rsnap
  File "redisinsight\memory_analysis\services\analysis\lib.py", line 249, in process_rdb
redisinsight.memory_analysis.services.analysis.lib.RDBAnalysisError: rdbMemoryAnalysis() returned code -1:
c:\users\circleci\project\redisinsight\native\rdbtools.c:1115 -> Unknown RDB encoding type 16** (Add any other context or details here).

**Comment by GnaneshKunal** [comment]
@Munish629 What is the RedisInsight version you are using?

**Comment by Munish629** [comment]
@GnaneshKunal  I am using 1.10.0, today I installed the Redis Insight-v2 2.22.1, but I could not find out from where can I load rdb files in that which was easier for sure in 1.10.0

Please guide me.

**Comment by GnaneshKunal** [comment]
Hey @Munish629, Redisinsight V2 doesn't have offline analysis support yet.

Please install the latest V1 version which is v1.13.1.

**Comment by Munish629** [comment]
It worked like charm. Thanks a lot @GnaneshKunal !!
