### ISSUE TITLE
[Bug]: Cannot change port with RIPORT

### ISSUE THREAD

**Issue by sigurdhj** [RedisInsight/RedisInsight#1909]
Hi.

I've installed the latest Redis Insights on Fedora 37 using flatpak (https://flathub.org/apps/details/com.redis.RedisInsight). The default port is 5001 (docs say it should be 8001?) and I cannot get it to use any other port. I've tried setting the environment variable RIPORT to 8001 but it always ends up using 5001.

These are the steps I've done:
1. flatpak install flathub com.redis.RedisInsight
2. export RIPORT=8001
3. flatpak run com.redis.RedisInsight
4. netstat -tulpn | grep redis

**Comment by ViktarStarastsenka** [comment]
hi @sigurdhj , the documentation you mentioned describes environment variables for RedisInsight on Docker, but you use the desktop version.
Can you please describe the reason for changing the default port?

**Comment by sigurdhj** [comment]
Ah, that explains it. One of the several web apps I’m running when developing is setup to run on port 5001, so if Redis insights is already running I can’t start the application. It’s easier for me to change the port of Redis insights than reconfiguring all my other apps.

**Comment by ViktarStarastsenka** [comment]
you can install RedisInsight after setting up your web application. In this case, RedisInsight will automatically switch to 5002.

**Comment by ViktarStarastsenka** [comment]
please re-open the issue if it is still relevant
