### ISSUE TITLE
[Bug]: Add an Elasticache database that uses TLS 

### ISSUE THREAD

**Issue by mivasile** [RedisInsight/RedisInsight#1915]
Hello, I encountered this error related to the TLS certificate when attempting to add a Redis Elasticache database.

![Screenshot 2023-04-04 at 20 01 53](https://user-images.githubusercontent.com/25801619/230074641-2bdc21cc-ce64-496b-8f55-ef238d5ad7b0.png)

To obtain the CA certificate, I used the following command
`openssl s_client -connect clustercfg.***.euw1.cache.amazonaws.com:6379 -showcerts`

My question is whether there is an additional step that needs to be taken when adding a TLS-enabled Elasticache database to RedisInsight.

**Comment by GnaneshKunal** [comment]
Looks like the machine RI is installed might not have the CA certificates' issuer certificate or chain installed. Can you check if that's possible?

Also can you check if disabling the verification of certificate works?

**Comment by mivasile** [comment]
Disabling the verification works but we would like to have it enabled for security reasons.

RedisInsight was installed as a docker image, using this [tutorial](https://docs.redis.com/latest/ri/installing/install-k8s/#create-the-redisinsight-deployment-with-persistant-storage)

Based on my observation, the cache has public CA certificates and in theory, RI should be able to perform verification independently. I'm unconvinced why it's necessary to specify a CA certificate when adding a Redis database.

**Comment by GnaneshKunal** [comment]
@mivasile, Can you once check the validity of the certificate?

Please try out if a connection via `redis-cli` is successful - https://redis.io/docs/ui/cli/#ssltls. Try it from the same machine where RI is installed.

**Comment by ViktarStarastsenka** [comment]
please re-open the ticket if the issue is still relevant
