### ISSUE TITLE
[Bug]:  Check box "use SNI" often isn't saved while editing connection

### ISSUE THREAD

**Issue by uliana-palianytsia** [RedisInsight/RedisInsight#1927]
**Preconditions** (Any important steps we need to know)

**Steps to reproduce** (How to reproduce what you found step by step)
1.  Click " Add redis database"
2. Fill all connection information
3. Click "use TLS" and "use SNI"
4. Click "Apply changes"
5. Open the editor on saved connection

**Actual behavior** (A short description of what you found)
"use SNI" checkbox isn't saved

**Expected behavior** (A short description of what you expected to find)
"use SNI" checkbox is saved

**Additional context** (Operating system, version of RedisInsight, Redis database version, Redis module version, database type, connection type, logs, or any other information)
version 2.22.1

**Comment by ViktarStarastsenka** [comment]
hi @uliana-palianytsia , thank you for reporting this.

**Comment by Zesoman** [comment]
same issue on mac pro m1 OS 13.3.1 (22E261)

**Comment by ViktarStarastsenka** [comment]
@uliana-palianytsia , @Zesoman , please check it with 2.24 (released today).
re-open the issue if it is still relevant.
