### ISSUE TITLE
[Feature Request]:Allow wildcard * search of keys

### ISSUE THREAD

**Issue by cihanhizlikan** [RedisInsight/RedisInsight#1932]
CLI tool allows to search for keys using the wildcard *. As in KEYS *. Allow this feature to available in the key search text box.

**Comment by ViktarStarastsenka** [comment]
hi @cihanhizlikan , can you please describe your case in more detail? RedisInsight already supports wildcards.

**Comment by cihanhizlikan** [comment]
I probably was using an older version. Just updated my version today and saw that wildcards are indeed supported. Thank you for your time.
