### ISSUE TITLE
[Bug]:Redis Insight Build Image

### ISSUE THREAD

**Issue by alperensayar** [RedisInsight/RedisInsight#1943]
I download redisinsgiht 2.22.1.tar after that i build image with this code
docker build -t redisinsight:2.22.1 .
after that image builded. for run this docker image I run this code:
docker run -p 8001:8001 --name redisinsight2 redisinsight:2.22.1 
after working I got this two lines:
./docker-entry.sh: 19: ./docker-entry.sh: gnome-keyring-daemon: Operation not permitted
./docker-entry.sh: 21: ./docker-entry.sh: gnome-keyring-daemon: Operation not permitted
after that I closed gnome-keyring-daemon part from docker-entry.sh then rebuild
its works without any warning or error but I can't get any logs and it not opened on browser can't reach error for web browser.

thanks for your help

**Comment by ViktarStarastsenka** [comment]
hi @alperensayar , where did you download 2.22.1.tar?

**Comment by manikanta-cse** [comment]
I couldn't find  v2.x image on dockerhub, any plans to publish ?

**Comment by ViktarStarastsenka** [comment]
@manikanta-cse , there are no timelines for publishing it on the docker hub yet, but the updates will be posted in this ticket:
https://github.com/RedisInsight/RedisInsight/issues/519

**Comment by seebeen** [comment]
Until they manage to find time to publish official v2:

https://hub.docker.com/r/oblakstudio/redisinsight

**Comment by ViktarStarastsenka** [comment]
RedisInsight on Docker has been released - https://hub.docker.com/repository/docker/redis/redisinsight/general
