### ISSUE TITLE
[Bug]:RedisInsight v2 has no SNI support

### ISSUE THREAD

**Issue by laurentdroin** [RedisInsight/RedisInsight#199]
It needs to support SNI in order to connect to k8s databases accessible from outside k8s via ingress or routes.

When trying to connect to a database accessible via Ingress or Route, and even if the SNI name would be the same as the Hostname, trying to add the database will result in an error similar to:

```
Protocol error, got \"H\" as reply type byte
```

**Comment by ViktarStarastsenka** [comment]
Hi @laurentdroin , SNI support has been added to 2.0.6. Please check it.
