### ISSUE TITLE
Redis Insight drops selected database after connection edit

### ISSUE THREAD

**Issue by asharovarov** [RedisInsight/RedisInsight#1994]
Version: Redis Insight 2.20 

If you create a connection selecting a database >0, and then rename the connection or make any other changes to the connection properties the selected database is reset to 0.

It would be also nice to have option to change the DB.

**Comment by ViktarStarastsenka** [comment]
hi @asharovarov , please check it with 2.24 (released today).
re-open the issue if it is still relevant.
