### ISSUE TITLE
[Bug]: zrank return nil instead of 0

### ISSUE THREAD

**Issue by JohnReeson** [RedisInsight/RedisInsight#2001]
**Steps to reproduce** (How to reproduce what you found step by step)
use zrank to get the first element
e.g. zrank leader:exp jack

**Actual behavior** (A short description of what you found)
"(nil)"

**Expected behavior** (A short description of what you expected to find)
(integer) 0

**Screenshots** (Paste or drag-and-drop a screenshot or a link to a recording)

Cli shows the correct result

![Screenshot 2023-04-23 134650](https://user-images.githubusercontent.com/35160013/233822132-788209cb-92d3-4043-87e5-7904fb12eb20.png)

the insight shows

![Screenshot 2023-04-23 134230](https://user-images.githubusercontent.com/35160013/233822144-853a3730-9bf4-4638-9ba4-b97209cc61bb.png)

**Additional context** (Operating system, version of RedisInsight, Redis database version, Redis module version, database type, connection type, logs, or any other information)

RedisInsight 2.22.1，local redis 6.0.16

**Comment by ViktarStarastsenka** [comment]
@JohnReeson , this is fixed with 2.28 (released today). please re-open the ticket if it is still relevant.
