### ISSUE TITLE
[Bug]: Wildcard (*) is not working properly 

### ISSUE THREAD

**Issue by cihanhizlikan** [RedisInsight/RedisInsight#2008]
RedisInsight wildcard can not find all the keys in the database. The ones it finds seem random. Compare the following results between redis-cli and RedisInsight for the same query: E*
 
![image](https://user-images.githubusercontent.com/47969650/234223934-66aa99cc-9aa9-4b18-9b9a-d9f484568676.png)

![image](https://user-images.githubusercontent.com/47969650/234224072-21440756-399a-4327-a555-54d13af0213a.png)

However if you type in the full key, it's found as expected:

![image](https://user-images.githubusercontent.com/47969650/234224791-1c9b227b-4370-4888-8b92-08a539b7b054.png)

Redis version is 5.4

**Comment by ViktarStarastsenka** [comment]
hi @cihanhizlikan , RedisInsight uses the SCAN command to incrementally iterate over the list of keys, which does not significantly affect performance (compared with risks associated with the KEYS command - https://redis.io/commands/keys/). So RedisInsight scans per 10,000 keys in one iteration (as you can see on your second screen - "scanned 10 000/64 424 keys). You can click "Scan more" to scan additional keys.

**Comment by cihanhizlikan** [comment]
Well that worked thanks. But kind of misleading for a new user like me. There could be an option choose KEYS vs. SCAN when defining the connection. Anyway thank you for your time.
