### ISSUE TITLE
[Feature Request]:You cannot change the installation location during installation

### ISSUE THREAD

**Issue by yujiahan2018** [RedisInsight/RedisInsight#2041]
**Problem description** (Describe the problem you would like to solve with this feature request or suggested idea).

When installing the software, I do not want to install the software on the system disk. I'd like to change the installation location. However, in the current version v2 installation mode, I double-click the installation package and it will install automatically

**How often do you encounter this problem** (Describe how frequently this problem occurs).

It appears every time you install it

**Comment by ViktarStarastsenka** [comment]
hi @yujiahan2018 , what OS do you use?

**Comment by ViktarStarastsenka** [comment]
hi @yujiahan2018 , the custom installation directory is available for Windows OS (starting from RedisInsight 2.32)
