### ISSUE TITLE
Does RedisInsight allow access via ssl or only non-ssl ports? 

### ISSUE THREAD

**Issue by MacMcDell** [RedisInsight/RedisInsight#2061]
Using Azure Redis for all my development. I have observed in the past I need to allow non ssl port in order to use redis-cli locally. I was hoping RedisInsight would allow for SSL port access but it appears it does not. Is this correct? I was unable to access via the SSL port but as soon as I opend the non SSL, it connected up fine. 
Can you please clarify if there is some way to use RedisInsight with SSL port access? 
Thanks

**Comment by GnaneshKunal** [comment]
Hey @MacMcDell, can you check if you are using the right TLS certificates while trying to connect to Azure Redis with TLS option?

Please check this tutorial on how to build redis-cli with TLS access - https://www.franzramadhan.com/posts/11-enable-tls-for-redis-cli/

**Comment by ViktarStarastsenka** [comment]
please re-open the ticket if it is still relevant
