### ISSUE TITLE
redis port can not edit

### ISSUE THREAD

**Issue by CharlinChen** [RedisInsight/RedisInsight#2063]
![redis](https://user-images.githubusercontent.com/35521674/236420415-8b001c2a-6db0-499e-8fcc-bf943a81bee2.jpg)
show as the picture, the redis port was default to 6379 and can‘t edit. 
But, the port of redis-server has been set to a custom port(11171), so redisinsight can't connect because it can only detect port 6379. Is there any way to change default detect port?

Both of redis-server and redisinsight were running on a dcoker (redis/redis-stack-server:latest). 
The redis was start with command `/opt/redis-stack/bin/redis-server redis_bloom.conf` and the config file is:
```
port 11171
daemonize no
loadmodule /opt/redis-stack/lib/redisearch.so
loadmodule /opt/redis-stack/lib/redisgraph.so
loadmodule /opt/redis-stack/lib/redistimeseries.so
...
```
The redisinsight was start with command `/opt/redis-stack/nodejs/bin/node -r /opt/redis-stack/share/redisinsight/api/node_modules/dotenv/config /opt/redis-stack/share/redisinsight/api/dist/src/main.js dotenv_config_path=redisinsight.conf` and redisinsight.conf file looks like this:
```
SERVER_STATIC_CONTENT=1
API_PORT=8001
TEST_REDIS_PORT=11171
BUILD_TYPE=REDIS_STACK
NODE_ENV=production
STDOUT_LOGGER=false
APP_FOLDER_NAME=redisinsight
APP_FOLDER_ABSOLUTE_PATH=/redisinsight
REDIS_STACK_DATABASE_NAME="My Redis Stack Database"
```

**Comment by ViktarStarastsenka** [comment]
hi @CharlinChen , currently, there is no option to change the database port - you need to create a new database connection with a new port.
But you can quickly add a new one by copying your existing database connection. To do so, you need to:
1. go to the list of databases
2. click to edit your database connection
3. request to clone it (the screen is attached)
4. edit the database port (and any other details you would like to change)
5. delete the previous database connection.

<img width="457" alt="image" src="https://user-images.githubusercontent.com/99594890/236916369-265e9332-5ce5-4469-a96a-e29b63e15115.png">

**Comment by CharlinChen** [comment]
@ViktarStarastsenka Thank you for your clarification. But there is not 'Clone' button on my the screen. Is there any way to make it appear?

**Comment by ViktarStarastsenka** [comment]
@CharlinChen , oh, so you use the Redis Stack container, then please specify `REDIS_STACK_DATABASE_PORT` variable in the conf file.

**Comment by CharlinChen** [comment]
Thanks a lot! it works fine!!

**Comment by HelmerBarcos** [comment]
This needs to be documented. I also didnt found this env var in the docs https://redis.io/docs/install/install-stack/docker/

**Comment by ViktarStarastsenka** [comment]
@HelmerBarcos , this will be documented with a new docker image that will be released somewhere in January.
