### ISSUE TITLE
[Bug]: RedisInsight doesn't remember window size on Windows

### ISSUE THREAD

**Issue by Feniksovich** [RedisInsight/RedisInsight#2068]
**Preconditions** (Any important steps we need to know)
–

**Steps to reproduce** (How to reproduce what you found step by step)
1. Open app
2. Resize window (e.g. stretch to full screen)
3. Relaunch app, app didn't remember window size

**Actual behavior** (A short description of what you found)
App always opens with specified window size centered on the screen.

**Expected behavior** (A short description of what you expected to find)
App should remember last window size and open the next time it is launched with the same window size.

**Screenshots** (Paste or drag-and-drop a screenshot or a link to a recording)
–

**Additional context** (Operating system, version of RedisInsight, Redis database version, Redis module version, database type, connection type, logs, or any other information)
RedisInsight v2.24.0
OS Windows 11 22H2

**Comment by ViktarStarastsenka** [comment]
@Feniksovich , this has been enhanced with 2.46 (released today).
