### ISSUE TITLE
[Feature Request]:

### ISSUE THREAD

**Issue by Neha-Maurya95** [RedisInsight/RedisInsight#2071]
Hi ,

I want to enable authentication or RBAC for redisinsight . How i can achieve that . Do redisinsight support this feature ??

Thanks

**Comment by ViktarStarastsenka** [comment]
hi, here is a similar ticket: https://github.com/RedisInsight/RedisInsight/issues/1829

**Comment by Neha-Maurya95** [comment]
Thanks for the reply @ViktarStarastsenka
