### ISSUE TITLE
[Feature Request]: Search for local redis instances

### ISSUE THREAD

**Issue by edumaciel10** [RedisInsight/RedisInsight#2081]
**Problem description** (Describe the problem you would like to solve with this feature request or suggested idea).
I don't have an Redis Cloud database, and I run it locally

How I can search for values without go to the cloud?

I need to install the RedisSearch locally to handle it?

**Additional information** (Add any other context or details here).

**Comment by ViktarStarastsenka** [comment]
@edumaciel10 , yes, or you can just install Redis Stack - https://redis.io/docs/stack/get-started/install/
