### ISSUE TITLE
[Bug]:docker build problem

### ISSUE THREAD

**Issue by yarthur1** [RedisInsight/RedisInsight#2096]
**Preconditions** (Any important steps we need to know)

my step:

git clone https://github.com/RedisInsight/RedisInsight.git
cd RedisInsight
sudo docker build .

![image](https://github.com/RedisInsight/RedisInsight/assets/30923528/1ced765b-2f16-4351-83bc-a1432dd0f310)

![image](https://github.com/RedisInsight/RedisInsight/assets/30923528/6e68dcbd-9a63-4892-856b-edfa15281b75)

did i something wrong?  Thanks

**Comment by ViktarStarastsenka** [comment]
you can use the official Docker container (released today) - https://hub.docker.com/repository/docker/redis/redisinsight/general
