### ISSUE TITLE
Setting "Keys to Scan in List view" does nothing. Limit is always 10 000.

### ISSUE THREAD

**Issue by fillefrans** [RedisInsight/RedisInsight#2099]
As per the title, setting "Keys to scan in list view" under Advanced Settings to e.g. 50 000 does not change how many keys are read in every iteration. It is always 10 000 keys per scan.

**Comment by ViktarStarastsenka** [comment]
hi, the setting under the Advanced settings means another thing
by default, it returns 500 keys, but when you set filters per key name or key type, there can be cases when you cannot find 500 keys (e.g. when a pattern is rare), in this case, the value in the Advanced settings sets the cap for the number of keys to scan
basically, this means “scan per 500 until you find 500 keys OR you scanned X keys (and still found less than 500)”, where X is set in this setting
hope this helps

**Comment by sirago** [comment]
Can we get more flexibility here? My redis instance has 1.5m keys, and I'd like to load all of them so I can see how many keys are in each namespace.

**Comment by Kesmy** [comment]
Same, the default is utterly worthless, and not being able to just scan-all is terrible design. It would only take a minute to scan, but instead it takes 15 because you have to sit there mindlessly banging on "scan more"
