### ISSUE TITLE
Tree-view of databases and keys like RESP.app

### ISSUE THREAD

**Issue by ea167** [RedisInsight/RedisInsight#2104]
**Problem description** (Describe the problem you would like to solve with this feature request or suggested idea).
We have dozens of databases across several Redis servers. Current UI is totally impractical for our usage. Switching is too slow and there is no overview.

**How often do you encounter this problem** (Describe how frequently this problem occurs).
Every second :)

**Alternatives considered** (Describe any alternative features or products you've considered).
RESP.app has great UI... you just acquired it!

**Additional information** (Add any other context or details here).
Data is spread across the Redis databases for clarity and performance. Each database contains thousands to millions of keys.
Here is a snapshot of RESP.app tree-view UI:

<img width="381" alt="2023-05-16 at 11 17 AM" src="https://github.com/RedisInsight/RedisInsight/assets/571650/16bd68e6-ee6a-4b0e-b15e-ffa7edb424a8">

**Comment by ViktarStarastsenka** [comment]
hi @ea167 , thanks for the feedback
we are thinking about enhancing the Tree view, what do you think about the option attached?
RedisInsight will:
1. allow to switch between database indexes in the Tree view
1. allow to sort per key name
1. display only the key name part after the last delimiter to optimize space

<img width="951" alt="image" src="https://github.com/RedisInsight/RedisInsight/assets/99594890/8887ab67-a754-48d9-b618-ec0c7bae5007">

**Comment by ViktarStarastsenka** [comment]
a major improvement for the tree view has been released with 2.38.
