### ISSUE TITLE
[Feature Request]: Browser -> Value panel should use monospaced font when its a string

### ISSUE THREAD

**Issue by bffaro** [RedisInsight/RedisInsight#2110]
In the Browser section - Value viewer panel, the font should be monospaced when the value is a string, to make reading easier. The proportional font makes it look chaotic for JSON for example.

There doesn't seem to be an easily accessible way of changing this.

**Comment by ViktarStarastsenka** [comment]
hi, the font was changed to monospaced in 2.28, you can try it with 2.32 (released today).
