### ISSUE TITLE
[Bug]:Failed at running in a Non-Root environment

### ISSUE THREAD

**Issue by rojinebrahimi** [RedisInsight/RedisInsight#2111]
Is there a way to run the image in a non-root pod on Kubernetes? There seems to be issues with creating directories such as ".cache" or ".local" without root privileges.

**Comment by GnaneshKunal** [comment]
Hey @rojinebrahimi, Is the issue for v1?

Docker image for v1 is built to not require root access. So using it on non-root environments should not be an issue. Can you send any logs if available?

**Comment by ViktarStarastsenka** [comment]
please reopen the ticket if it is still relevant
