### ISSUE TITLE
[Feature Request]: Stop include password filed in Response body of register instance API.

### ISSUE THREAD

**Issue by guitarrapc** [RedisInsight/RedisInsight#2112]
**Problem description** (Describe the problem you would like to solve with this feature request or suggested idea).

Response body of `/api/instance/` API Endpoint includes `password` field when post body has `password` field. I assume `password` is too sensitive field to be included in response body.

> see: https://docs.redis.com/latest/ri/using-redisinsight/api/

**How often do you encounter this problem** (Describe how frequently this problem occurs).

Every time I register redis instance via API with password included.

**Alternatives considered** (Describe any alternative features or products you've considered).

Currently I'm masking reponse body's password value on my side. However if returning password is mandatory, reponse should mask by default. Alternative is better omit password field.

**Additional information** (Add any other context or details here).

Reproduce step with curl.

```sh
_REDISINSIGHT_ENDPOINT=http://localhost:8001
json="{ \"name\": \"docker\",\"connectionType\": \"STANDALONE\",\"host\": \"redis:6379\",\"port\": 6379,\"password\": \"mypassword\",\"tls\": { \"useTls\": false, \"clientAuth\": false, \"verifyServerCert\": false } }"
csrf=$(curl -s http://${_REDISINSIGHT_ENDPOINT}/api/instance -c cookies.txt && cat cookies.txt | cut -f 7 | tail -n 1)
# this response body includes password field.
curl -s -X POST -b cookies.txt -H "Content-Type: application/json" -H "X-CSRFToken:${csrf}" -d "${json}" http://${_REDISINSIGHT_ENDPOINT}/api/instance/
```

Reponse sample.

```
{"db":{"id":"12345678-1234-1234-1234-1234567890ab","type":"STANDALONE","name":"docker","host":"redis","port":6379,"tls":false,"verifyServerCert":false,"caCertName":null,"tlsClientAuthRequired":false,"tlsClientCertId":null,"username":null,"password":"mypassword"},"msg":"Instance created successfully."}
```

**Comment by ViktarStarastsenka** [comment]
hi @guitarrapc , thank you for the feedback.
this page (https://docs.redis.com/latest/ri/using-redisinsight/api/) describes documentation for RedisInsight v1 that reached its EOL and is not supported.
You can try RedisInsight v2, it does not expose database passwords.
