### ISSUE TITLE
[Bug]: docker build issue webpack 

### ISSUE THREAD

**Issue by jakub-kubera** [RedisInsight/RedisInsight#2117]
not able to docker build it hangs on

Step 17/52 : RUN yarn build:web
 ---> Running in 5b7baa28f9e9
yarn run v1.22.19
$ webpack --config ./configs/webpack.config.web.prod.babel.js

tried already on ubuntu and my mac

**Comment by ashoksimma** [comment]
facing the same issue  
Step 16/52 : ENV SEGMENT_WRITE_KEY=${SEGMENT_WRITE_KEY}
 ---> Using cache
 ---> acc9abbef4f2
Step 17/52 : RUN yarn build:web
 ---> Running in 7fc22ff64a83
yarn run v1.22.19
$ webpack --config ./configs/webpack.config.web.prod.babel.js

**Comment by ashoksimma** [comment]
It took long time but went through

**Comment by ViktarStarastsenka** [comment]
you can use the official Docker container (released today) - https://hub.docker.com/repository/docker/redis/redisinsight/general
