### ISSUE TITLE
[Bug]: CLI Garbled

### ISSUE THREAD

**Issue by ChengChuanxin94** [RedisInsight/RedisInsight#2124]
version:
<img width="281" alt="image" src="https://github.com/RedisInsight/RedisInsight/assets/15957049/679d6ab8-02f9-4180-ba8e-e22d2fba8dd6">
result:
<img width="584" alt="image" src="https://github.com/RedisInsight/RedisInsight/assets/15957049/1cad8e96-d156-4ba2-b699-9ee2db6af738">

is there any solution for it?

**Comment by ViktarStarastsenka** [comment]
hi @ChengChuanxin94 ,
1. you can go to Workbench (Workbench icon is attached)
2. enable the Raw Mode (-r) (screen is attached)
3. run your command

Currently, RedisInsight CLI does not support the `--raw` mode, but Workbench does

<img width="62" alt="image" src="https://github.com/RedisInsight/RedisInsight/assets/99594890/8492cc97-19a3-4bda-a864-f5941ad8fb65">

<img width="1083" alt="image" src="https://github.com/RedisInsight/RedisInsight/assets/99594890/a45c7aec-1970-40f5-b3da-e6c975610836">

**Comment by ChengChuanxin94** [comment]
Hi @ViktarStarastsenka , thanks for your kindly reply, it works good for me.  😊
