### ISSUE TITLE
[Feature Request]: Can the language be Chinese?

### ISSUE THREAD

**Issue by dantqf** [RedisInsight/RedisInsight#2137]
**Problem description** (Describe the problem you would like to solve with this feature request or suggested idea).

**How often do you encounter this problem** (Describe how frequently this problem occurs).

**Alternatives considered** (Describe any alternative features or products you've considered).

**Additional information** (Add any other context or details here).

**Comment by ViktarStarastsenka** [comment]
hi, currently, RedisInsight does not support Chinese, let's track this feature request under this ticket: https://github.com/RedisInsight/RedisInsight/issues/1317
