### ISSUE TITLE
[Feature Request]:[win] it opens a new window rather than the one display on system tray, when i click shortcut on taskbar

### ISSUE THREAD

**Issue by Jeandoom** [RedisInsight/RedisInsight#2141]
1. Chose the `display on system tray`  function
![image](https://github.com/RedisInsight/RedisInsight/assets/20264327/3afb9f73-9b32-4522-98f9-551513cb2dc0)
2. Hide window by click close button
![image](https://github.com/RedisInsight/RedisInsight/assets/20264327/64b1d5fd-41b3-4bbf-9100-7549faaeaf8f)
3. It display on system tray
![image](https://github.com/RedisInsight/RedisInsight/assets/20264327/190fbc9e-87e3-4edb-a0c7-027a49befcd0)
4. After clicked its shortcut on taskbar, it open new window, and system tray show another one
![image](https://github.com/RedisInsight/RedisInsight/assets/20264327/66f64536-7d4b-46bb-9dd2-ca4dca0db673)
5. Repeat 2-4, then
![image](https://github.com/RedisInsight/RedisInsight/assets/20264327/1faaebc2-509c-4346-8e5e-313cc8b066d9)

**Comment by ViktarStarastsenka** [comment]
@Jeandoom , please try it with 2.32 (released today).
