### ISSUE TITLE
[Feature Request]: Unzip gzipped content

### ISSUE THREAD

**Issue by plazmdk** [RedisInsight/RedisInsight#2155]
**Problem description** (Describe the problem you would like to solve with this feature request or suggested idea).
In RESP.APP it shows data uncompressed when an item is selected in a list and also supports for formating it as json

**How often do you encounter this problem** (Describe how frequently this problem occurs).
For the current application I am working on, for all keys and list items

**Alternatives considered** (Describe any alternative features or products you've considered).

**Additional information** (Add any other context or details here).

**Comment by ViktarStarastsenka** [comment]
@plazmdk , please try this:
https://github.com/RedisInsight/RedisInsight/issues/2123#issuecomment-1558817558
