### ISSUE TITLE
[Bug]: RIAUTHPROMPT login without any credentials

### ISSUE THREAD

**Issue by tregubov84** [RedisInsight/RedisInsight#2158]
![image](https://github.com/RedisInsight/RedisInsight/assets/82427238/88c8e59f-8c62-49d3-8312-b47cd06f246c)

I can login within redis instance by clicking ping when credentials are empty. How does RIAUTHPROMT works? Redisinsight v1.14.0

**Comment by GnaneshKunal** [comment]
@tregubov84 

Can you check if the instance was added with creds? (: 

You can go to edit database page and can find if there is username / password in the form entries. Alternatively, you can export the connections and assert the username / password in it.

**Comment by tregubov84** [comment]
> Hey @tregubov84
> 
> Can you cross check if the instance was added with creds? (:
> 
> You can go to edit database page and can find if there is username / password in the form entries. Alternatively, you can export the connections and assert the username / password in it.

Yes, i added my database with deafualt login and password. And i work in redis-cli only with auth by password

**Comment by tregubov84** [comment]
> Hey @tregubov84
> 
> Can you cross check if the instance was added with creds? (:
> 
> You can go to edit database page and can find if there is username / password in the form entries. Alternatively, you can export the connections and assert the username / password in it.

i did it! thnx!

**Comment by ViktarStarastsenka** [comment]
@tregubov84 , please re-open the ticket if it is still relevant

**Comment by fruitfish** [comment]
I had the same problem.  I added my database with username and password.  But I can login the instance only with username, and do not enter the password.  How does RIAUTHPROMT works? 
Redisinsight v1.14.0
