### ISSUE TITLE
[Bug]: Why is wildcarded key searches not working?

### ISSUE THREAD

**Issue by ahall72** [RedisInsight/RedisInsight#2167]
I just got this new client as an upgrade to REDIS.app.  In REDIS.app I could search by wildcarded key.  Example:  *Key1*
In this tool I get no results if I use any wildcard.  The "Scan More" button doesn't change the result.

**Comment by ViktarStarastsenka** [comment]
hi @ahall72 , when you filter with the wildcard, RedisInsight searches per 10,000 keys, so if you click the "Scan more", then RedisInsight scans additional 10,000 keys (which may not contain relevant keys).
Currently, if you filter with the wildcard, there is no option to scan the entire database at once.

**Comment by ahall72** [comment]
OH I see.  Yeah it tracks how many it has searched so far.  I had to click Scan quite a few times to find my key but it did work.  Thanks!
