### ISSUE TITLE
Tree View Enhancement - End of key visibility

### ISSUE THREAD

**Issue by luczejko10** [RedisInsight/RedisInsight#2171]
**Problem description**
When using tree view it is very difficult to see the end of the key in the second pane without scrolling.   Update the second pane to just show the the end of the key after the last delimiter.   Or add an option to view this way.

**How often do you encounter this problem** 
Everyday

**Alternatives considered** 
None

**Additional information**

**Comment by ViktarStarastsenka** [comment]
hi @luczejko10 , thanks for the feedback
we are thinking about enhancing the Tree view, what do you think about the option attached?
RedisInsight will:
1. display only the key name part after the last delimiter to optimize space
1. allow to switch between database indexes in the Tree view
1. allow to sort per key name

<img width="951" alt="image" src="https://github.com/RedisInsight/RedisInsight/assets/99594890/8887ab67-a754-48d9-b618-ec0c7bae5007">

**Comment by luczejko10** [comment]
that looks great!  thank you

**Comment by ViktarStarastsenka** [comment]
@luczejko10 , we have released a major improvement for the tree view, so it may also cover your use case.
Though, in some long key names, the end of the key name may still not be visible, you can hover over them to see the value.

**Comment by ViktarStarastsenka** [comment]
please re-open the ticket if you think it is still relevant after the changes delivered with 2.38
