### ISSUE TITLE
[Bug]:Something was wrong!

### ISSUE THREAD

**Issue by wenlincheng** [RedisInsight/RedisInsight#2179]
Can not get keys
v2.26.0 (11)
<img width="1204" alt="企业微信截图_0a6c917b-72ea-4e69-9e6d-fbe2dfd62913" src="https://github.com/RedisInsight/RedisInsight/assets/35648826/18dee611-b56e-48fe-970d-f269d1c3351a">

<img width="1165" alt="企业微信截图_09a29847-b738-4e96-89ea-04322a19777b" src="https://github.com/RedisInsight/RedisInsight/assets/35648826/3d187652-ca05-41f5-8f61-4ff3287205e6">

**Comment by ViktarStarastsenka** [comment]
@wenlincheng , can you please share the logs to look deeper into this?

**Comment by ViktarStarastsenka** [comment]
please try 2.32 and re-open the ticket if the issue still reproduces.
