### ISSUE TITLE
[Feature Request]: ctrl f implementation for values

### ISSUE THREAD

**Issue by armanashaboglu** [RedisInsight/RedisInsight#2180]
**Problem description** (Describe the problem you would like to solve with this feature request or suggested idea).
Some of my key values are very long strings, and I am trying to find a specific part of it to scrape but I am having trouble seeing exactly where that section is. Adding this find feature would be very helpful.

**How often do you encounter this problem** (Describe how frequently this problem occurs).
It happens every time I am inspecting the contents of long strings.

**Alternatives considered** (Describe any alternative features or products you've considered).

**Additional information** (Add any other context or details here).

**Comment by ViktarStarastsenka** [comment]
here is a similar request. Closing this thicket as a duplicate.
https://github.com/RedisInsight/RedisInsight/issues/1721
