### ISSUE TITLE
[Feature Request]:chinese language

### ISSUE THREAD

**Issue by 1Xiu-couder** [RedisInsight/RedisInsight#2181]
**Problem description** (Describe the problem you would like to solve with this feature request or suggested idea).

**How often do you encounter this problem** (Describe how frequently this problem occurs).

**Alternatives considered** (Describe any alternative features or products you've considered).

**Additional information** (Add any other context or details here).

**Comment by ViktarStarastsenka** [comment]
hi, let's track this request under this ticket https://github.com/RedisInsight/RedisInsight/issues/1317
