### ISSUE TITLE
[Bug/Question]: Possible incorrect representation of long type numbers in JSON view

### ISSUE THREAD

**Issue by Feniksovich** [RedisInsight/RedisInsight#2184]
**Preconditions** (Any important steps we need to know)
I'm not sure that such behavior is really incorrect.

**Steps to reproduce** (How to reproduce what you found step by step)
1. Create simple key-value record with any key and long number as value (e.g. `248480010225057793`).
2. Open record in RedisInsight and choose JSON view.
3. See `248480010225057800` instead of original `248480010225057793` value.
4. Choose another view (e.g. Unicode) and see original value.

**Actual behavior** (A short description of what you found)
Shown number is wrong in JSON view.

**Expected behavior** (A short description of what you expected to find)
Number shoud be the same across all views.

**Screenshots** (Paste or drag-and-drop a screenshot or a link to a recording)
![1](https://github.com/RedisInsight/RedisInsight/assets/33875970/79d4a290-12ad-443f-98d5-dc045792df2b)
![2](https://github.com/RedisInsight/RedisInsight/assets/33875970/70f1f2c0-f789-4336-93bb-895d5f091596)

**Additional context** (Operating system, version of RedisInsight, Redis database version, Redis module version, database type, connection type, logs, or any other information)
RedisInsight v2.26.0

**Comment by ViktarStarastsenka** [comment]
hi @Feniksovich , thank you for reporting this.
the issue should be fixed with 2.32 (released today).
Please reopen the ticket if it is still relevant.
