### ISSUE TITLE
[Feature Request]: Any chance of an arm64 debian/ubuntu, or appimage, or flatpak, or snap?

### ISSUE THREAD

**Issue by sfatula** [RedisInsight/RedisInsight#2197]
**Problem description** (Describe the problem you would like to solve with this feature request or suggested idea).
Want to run it on a Raspberry Pi 4, which uses a debian derivative OS, just arm64 architecture. 

**How often do you encounter this problem** (Describe how frequently this problem occurs).
Well, daily I guess since I don't find one

**Alternatives considered** (Describe any alternative features or products you've considered).
Maybe run in docker on a Truenas server using amd64, but, not as convenient. Assuming I can find a V2 docker. 

**Additional information** (Add any other context or details here).
Raspberry Pi and other arm64 based machines are getting more and more powerful. I run a lot of software on the Pi now, Audacity, Libreoffice, Visual Studio Code, Digikam, etc. etc. RedisInsight hsould easily be able to run. It might be possible to build my own, just saying you should consider providing arm64 deb files.

**Comment by seebeen** [comment]
I got you covered fam 💪💪💪
https://hub.docker.com/r/oblakstudio/redisinsight

**Comment by ViktarStarastsenka** [comment]
you can use the official Docker container (released today) - https://hub.docker.com/repository/docker/redis/redisinsight/general
