### ISSUE TITLE
[Bug]: Viewing JSON document errors with t.includes is not a function

### ISSUE THREAD

**Issue by jasonsturges** [RedisInsight/RedisInsight#2205]
**Steps to reproduce** (How to reproduce what you found step by step)

Have a 5k JSON document that when clicked in Redis Insight results in a blank screen with errors:

> TypeError: t.includes is not a function

Small, flat array of objects stored as:

```js
await client.json.set(`key`, "$", JSON.stringify(data));
```

**Screenshots** (Paste or drag-and-drop a screenshot or a link to a recording)

Minified code:

<img width="1501" alt="Screen Shot 2023-06-16 at 2 54 06 PM" src="https://github.com/RedisInsight/RedisInsight/assets/1213591/0d6c24c4-47c3-40a0-b737-92bcaf2c0c8d">

<img width="1501" alt="image" src="https://github.com/RedisInsight/RedisInsight/assets/1213591/036ff73a-916b-42ae-adbd-b767fbed461f">

<img width="682" alt="image" src="https://github.com/RedisInsight/RedisInsight/assets/1213591/0b65bc70-bdb3-40da-8df2-36b432c849d1">

**Additional context** (Operating system, version of RedisInsight, Redis database version, Redis module version, database type, connection type, logs, or any other information)

No real expectations here - maybe this is known, or fluke not worth exploring.  

- RedisInsight v2 Version 2.24.0 (9)
- Redis Cloud database, Redis Stack: 6.2.6
- macOS M1 Pro Monterey 12.6.5

**Comment by ViktarStarastsenka** [comment]
@jasonsturges , can you please send an example of this JSON? but please sanitize all the sensitive data

**Comment by jasonsturges** [comment]
@ViktarStarastsenka Yeah, tried to isolate a sample - realize what I provided is unusable to diagnose this.

Perhaps just a note for reference, in case others experience this.  When / if I can isolate something generic I'll come back to reopen.  Thanks.
