### ISSUE TITLE
[Bug]: API port not configurable by RIPORT

### ISSUE THREAD

**Issue by pecanw** [RedisInsight/RedisInsight#2224]
The RedisInsigt API always starts on port 5001 or the first higher available (version 2.26.0; changed to 5530 in current source code).

According to [the documentation](https://docs.redis.com/latest/ri/installing/configurations/) it should be configurable by the `RIPORT` environment variable.

Tested on Windows 10, RedisInsigt version 2.26.0.

**Comment by ViktarStarastsenka** [comment]
hi @pecanw , the documentation is for RedisInsight v1 (reached its EOL on April 30th), RedisInsight v2 does not support this environment variable for now.
Can you please describe your use case? why do you need to change the port?

**Comment by pecanw** [comment]
You can find the reasons in [my comment on a stackowerflow question](https://stackoverflow.com/questions/76268357/redisinsight-v2-always-locks-ports-5001-and-5002#comment134935631_76268357).

**Comment by ViktarStarastsenka** [comment]
@pecanw , the default port was changed to 5530 with 2.28 (released today), but for now, the default port is not configurable.
please re-open the issue if this is still relevant
