### ISSUE TITLE
[Bug]: redislabs/redisinsight:latest on Docker still pointing to version 1.X-Updated 2 months ago 

### ISSUE THREAD

**Issue by igoralves1** [RedisInsight/RedisInsight#2228]
**Preconditions** (Any important steps we need to know)
redislabs/redisinsight on Docker was updated 2 months ago but is not bringing the `RedisInsight 2.x`.

I am using `image: redislabs/redisinsight:latest` in my docker compose.
![Screenshot from 2023-06-22 19-03-47](https://github.com/RedisInsight/RedisInsight/assets/3280251/9680684f-1e5b-46ed-a5ef-1ad8232bdcd3)

**Steps to reproduce** (How to reproduce what you found step by step)
Use this in docker compose

```
redisinsight:
    image: redislabs/redisinsight:latest
    container_name: redisinsight
    restart: unless-stopped
    ports:
     - '8001:8001'
    volumes:
      - ./redisinsight:/db 
```

**Actual behavior** (A short description of what you found)
![Screenshot from 2023-06-22 19-10-57](https://github.com/RedisInsight/RedisInsight/assets/3280251/0419e263-7d1d-446c-b00c-745d629c5f12)

**Expected behavior** (A short description of what you expected to find)
Version 2.X

**Screenshots** (Paste or drag-and-drop a screenshot or a link to a recording)

**Additional context** (Operating system, version of RedisInsight, Redis database version, Redis module version, database type, connection type, logs, or any other information)

**Comment by ViktarStarastsenka** [comment]
hi @igoralves1 , currently, there is no standalone RedisInsight v2 on docker - the updates will be posted in this ticket - https://hub.docker.com/r/redis/redis-stack

As an option, you can use RedisInsight v2 on docker bundled with Redis Stack (but you won't be able to add other databases) - https://github.com/RedisInsight/RedisInsight/issues/519

**Comment by zibellon** [comment]
@ViktarStarastsenka 
Hello!
One question: can I clone source code of redisinsight (2.x), build docker image and run it ?
I try to do it -> redisinsight WORK (locally, docker image)

But - I want to persist my data (I have about 10 redis databases)
And - I cant find any instruction, how to build it with docker ?

Which docker-volume I need to mount ?
Forexample: In redis-stack -> ./MY-VOLUME:/data

**Comment by ViktarStarastsenka** [comment]
hi @zibellon , here is an example of setting persistence using environment variables for Redis Stack:
https://redis.io/docs/stack/get-started/install/docker/

**Comment by zibellon** [comment]
@ViktarStarastsenka
I know about redis-stack and it work very well

BUT
1. Clone repo - git clone https://github.com/RedisInsight/RedisInsight.git
2. run command - docker build . -t test-redisinsight:latest
3. run DOCKER - docker run -p 5001:5000 test-redisinsight:latest
4. Ok. Start
5. Open - http://localhost:5001
6. Accept terms and add one REDIS-DB
7. All is good. Search/Keys/pub/sub/etc
8. STOP docker container - CTRL+C
9. remove exited container - docker rm -f CONTAINER_ID
10. run DOCKER - docker run -p 5001:5000 test-redisinsight:latest
11. Open - http://localhost:5001
12. AND I need Accept terms and add DB one more time....

My question: which volume I need to persist ??
docker run -p 5001:5000 -v **./my-test-data:/?????** test-redisinsight:latest

**Comment by ViktarStarastsenka** [comment]
@zibellon , please try `/root/.redisinsight-v2`

**Comment by zibellon** [comment]
@ViktarStarastsenka 
THANK YOU !!!
All works very well

docker-compose.yaml

```
version: "3.9"

services:
  dev:
    container_name: redisinsight
    restart: unless-stopped
    image: test-redisinsight:latest
    ports:
      - 5001:5000
    volumes:
      - ./my-test-data:/root/.redisinsight-v2
```

One more question
1. Clone repo - git clone https://github.com/RedisInsight/RedisInsight.git
2. run command - docker build . -t test-redisinsight:latest
3. run DOCKER - docker run -p 5001:5000 test-redisinsight:latest
4. all start ok and work, **BUT in console two errors**

redisinsight  | ./docker-entry.sh: 19: gnome-keyring-daemon: Operation not permitted
redisinsight  | ./docker-entry.sh: 21: gnome-keyring-daemon: Operation not permitted

<img width="628" alt="Снимок экрана 2023-07-05 в 14 44 06" src="https://github.com/RedisInsight/RedisInsight/assets/29332488/404e64e9-1294-46ba-8b9c-ab35c5c5d84e">

**Comment by ViktarStarastsenka** [comment]
@zibellon , just ignore them for now, this is the mechanism to encrypt your data, but it may not work well on docker

**Comment by zibellon** [comment]
@ViktarStarastsenka 
Very good.
THANK YOU !!!
