### ISSUE TITLE
[Feature Request]: order keys in a bucket by name

### ISSUE THREAD

**Issue by Dergarcon** [RedisInsight/RedisInsight#2242]
**Problem description** (Describe the problem you would like to solve with this feature request or suggested idea).
It would be nice to be able to order keys in a bucket by name.
I generate new entries every so often and the keys are a timestamp.
so if i would be able to order the keys by name, i would have the entries in chronological order and not all over the place.

**How often do you encounter this problem** (Describe how frequently this problem occurs).
Every time i use redis insight

**Alternatives considered** (Describe any alternative features or products you've considered).
RESP.APP was able to do that

**Additional information** (Add any other context or details here).
None.

**Comment by prkemp** [comment]
Agree.  This is a must if I'm going to use this tool.

**Comment by ViktarStarastsenka** [comment]
@Dergarcon , @prkemp , you can sort keys by their names in the Tree view starting from 2.38 (released today).
