### ISSUE TITLE
[Bug]: Select Logical Database Display only at creation time

### ISSUE THREAD

**Issue by berkerdong** [RedisInsight/RedisInsight#2244]
![image](https://github.com/RedisInsight/RedisInsight/assets/36178221/eb37823f-645b-4562-b217-25452700e81d)

![image](https://github.com/RedisInsight/RedisInsight/assets/36178221/8b1367bd-30fb-4161-ae60-83b6444efa0f)

**If the database serial number is not specified when creating a connection, it cannot be modified on the editing page in the future，Or an incorrect serial number was specified, which cannot be modified later and can only be deleted and rebuilt**

**Comment by ViktarStarastsenka** [comment]
hi @berkerdong , this was done on purpose to avoid issues with closing and re-opening database connections. The safest way to change the default database index if you entered an incorrect one is to copy the database connection (screen attached) and change the default database index.

<img width="499" alt="image" src="https://github.com/RedisInsight/RedisInsight/assets/99594890/ef2a321c-fc37-4b18-93a3-c40693339d56">
