### ISSUE TITLE
[Bug]:*notice* 搜索匹配时,搜索结果没有

### ISSUE THREAD

**Issue by Hernan-T** [RedisInsight/RedisInsight#2254]
**Preconditions** (Any important steps we need to know)

**Steps to reproduce** (How to reproduce what you found step by step)

**Actual behavior** (A short description of what you found)

**Expected behavior** (A short description of what you expected to find)

**Screenshots** (Paste or drag-and-drop a screenshot or a link to a recording)

**Additional context** (Operating system, version of RedisInsight, Redis database version, Redis module version, database type, connection type, logs, or any other information)

**Comment by ViktarStarastsenka** [comment]
hi @Hernan-T , I assume that your database contains more than 10,000 keys. In this case, you need to click the "Scan more" button (screen attached).

<img width="478" alt="image" src="https://github.com/RedisInsight/RedisInsight/assets/99594890/40b45417-a0b3-4501-b731-515dd4494ed5">

**Comment by Hernan-T** [comment]
OK,Thanks
