### ISSUE TITLE
[Bug]:【python】the data appears as garbled characters on Redis.

### ISSUE THREAD

**Issue by YmaYeah** [RedisInsight/RedisInsight#2260]
**Preconditions** (Any important steps we need to know)
1.【not sure】pip install django-redis 
2.【must be】Configurate file configuration(in file `settings`)
CACHES = {
                "default": {
                    "BACKEND": "django_redis.cache.RedisCache",
                    "LOCATION": "redis://127.0.0.1:6379", 
                    "OPTIONS": {
                        "CLIENT_CLASS": "django_redis.client.DefaultClient",
                        "CONNECTION_POOL_KWARGS": {"max_connections": 100}
                    }
                }
            }

**Steps to reproduce** (How to reproduce what you found step by step)
1.[Configurate url]
urlpatterns = [path('redis_test/',RedisTestView.as_view())]

2.[Configurate view]
class RedisTestView(APIView):
    def get(self,request):
        cache.set('star',[1,2,3])
        return ApiResponse()

3.[Test in Postman]
http://127.0.0.1:8000/api/v1/home/redis_test/
**Actual behavior** (A short description of what you found)
the data appears as garbled characters on Redis
key:":1:star" val:'��]�(KKKe.'
**Expected behavior** (A short description of what you expected to find)
key:":1:star" val:"[1, 2, 3]"by pickle.loads

**Screenshots** (Paste or drag-and-drop a screenshot or a link to a recording)
<img width="1215" alt="image" src="https://github.com/RedisInsight/RedisInsight/assets/137759279/84b8bac0-6ad1-4398-845a-0022978f223d">

**Additional context** (Operating system, version of RedisInsight, Redis database version, Redis module version, database type, connection type, logs, or any other information)
Operating system:macOS Ventura 13.0
version of RedisInsight:2.26.0
Redis database version:7.0.11 (bottled), HEAD
Redis module version：redis 7.0.11_1
connection type：NoSQL
version of Django：3.2.12
version of django-redis：5.3.0

**Comment by YmaYeah** [comment]
pls make sure,thank you very much

**Comment by YmaYeah** [comment]
[luffy_api.zip](https://github.com/RedisInsight/RedisInsight/files/11893961/luffy_api.zip)
pls check luffy_api--->apps--->home--->views.py--->RedisTestView(APIView)

**Comment by YmaYeah** [comment]
> hi @YmaYeah , can you please share an example of this data (but please remove all the sensitive information）
done ，pls check

**Comment by ViktarStarastsenka** [comment]
@YmaYeah , can you please provide just an example of the data you see with garbled characters? it will be helpful to look at it in ASCII format

**Comment by YmaYeah** [comment]
> @YmaYeah , can you please provide just an example of the data you see with garbled characters? it will be helpful to look at it in ASCII format

okkkk, I write `[1,2,3]`it is a list,redis shows `8004950b000000000000005d94284b014b024b03652e` by HEX
`��]�(KKKe.` by Unicode

**Comment by DhanushR24** [comment]
Hi there,
I am facing this issue as well.

> Also, on hovering on the "garbled characters" it shows `Failed to convert to Pickle` message.

**Comment by rad-pat** [comment]
The problem I experience with this that results in the `Failed to convert to Pickle` is that my keys are stored pickled with Protocol 5 in Python and the library `pickleparser` used for RedisInsight does not currently support Protocol 5.
https://github.com/ewfian/pickleparser/blob/main/SUPPORTED_OPCODES.md

**Comment by GnaneshKunal** [comment]
Hey @rad-pat, 

You are right with it. The library we currently use doesn't support Pickle Protocol 5.

**Comment by ewfian** [comment]
Protocol 5 will be supported in https://github.com/ewfian/pickleparser/pull/4/files

**Comment by GnaneshKunal** [comment]
@YmaYeah and @rad-pat, the pickle parser library now supports pickle protocol 5. Can you please try out the views again?

**Comment by ViktarStarastsenka** [comment]
a new version (with support for pickle protocol 5) is not available right now, it will be released with 2.36 in 1-2 weeks.

**Comment by ViktarStarastsenka** [comment]
available with 2.36 (released today)
