### ISSUE TITLE
[Bug]: can not modify name when redis server can't connect

### ISSUE THREAD

**Issue by zhaobingss** [RedisInsight/RedisInsight#2266]
**Preconditions** (Any important steps we need to know)

**Steps to reproduce** (How to reproduce what you found step by step)

**Actual behavior** (A short description of what you found)

**Expected behavior** (A short description of what you expected to find)

**Screenshots** (Paste or drag-and-drop a screenshot or a link to a recording)

**Additional context** (Operating system, version of RedisInsight, Redis database version, Redis module version, database type, connection type, logs, or any other information)

**Comment by ViktarStarastsenka** [comment]
hi @zhaobingss , can you please provide more details?
If you need to change the database alias, you can just change it, there is no need to click the "Apply changes" at the bottom, so you can change the alias even when you cannot connect to the database.


<img width="512" alt="image" src="https://github.com/RedisInsight/RedisInsight/assets/99594890/dd41b867-ccef-47bd-a22f-579f1fbaaa07">
