### ISSUE TITLE
[Feature Request]: batch operate. delete key group.

### ISSUE THREAD

**Issue by 1164461842** [RedisInsight/RedisInsight#2277]
batch operate. delete key group.

**Comment by ViktarStarastsenka** [comment]
hi @1164461842 , you already can do that in Browser.
What you need to do is to set a filter by key name or key type, and then click the "Bulk Actions" button.
Added a screenshot for 2.28 (for 2.26 the button looks a bit different, but bulk deletion still exists).


<img width="1429" alt="image" src="https://github.com/RedisInsight/RedisInsight/assets/99594890/ef99714b-9c02-4ee2-97cb-b2626c5d41b9">
