### ISSUE TITLE
[Bug]: slow rendering after importing json data. 

### ISSUE THREAD

**Issue by ghost** [RedisInsight/RedisInsight#2282]
**Preconditions** (Any important steps we need to know)
after connecting to very fresh redis running on Docker in Macbook Pro M1 with RedisInsight at the same hardware. 
I loaded the attached JSON file. Whenever browsing an item of JSON data under event field, RedisInsight slowly renders the content of the key.  RedisInsight get slower than for any mouse click. 

**Steps to reproduce** (How to reproduce what you found step by step)
Install redisstack:latest on docker of Mac Pro M1
install redisInsight on the same hardwarre
Load the JSON data with Riot as attached.
Connect Redis DB via RedisInsight
browser data to display data elements. 

**Actual behavior** (A short description of what you found)

**Expected behavior** (A short description of what you expected to find)

**Screenshots** (Paste or drag-and-drop a screenshot or a link to a recording)

**Additional context** (Operating system, version of RedisInsight, Redis database version, Redis module version, database type, connection type, logs, or any other information)
[Korea_Concert_2023_info.json.zip](https://github.com/RedisInsight/RedisInsight/files/11966230/Korea_Concert_2023_info.json.zip)

**Comment by ViktarStarastsenka** [comment]
please try it with 2.52.
re-open the ticket if the issue still reproduces.
