### ISSUE TITLE
[Bug]: Snapshot Option Save Dialog

### ISSUE THREAD

**Issue by DarkModz-Official** [RedisInsight/RedisInsight#2287]
**Preconditions** (Any important steps we need to know)
Not that i know it was a fresh docker container.

**Steps to reproduce** (How to reproduce what you found step by step)

1) Go to the Database Configuration
2) Search for Snapshots
3) Add Save Intervall or Change Values
4) Click on "Apply Configuration Changes"
5) Here it is, Text is a little bit wrong. 

**Actual behavior** (A short description of what you found)

Dialog text says: "Click Save to push the configuration changes to the Redis server."
Button text says: "Apply"

**Expected behavior** (A short description of what you expected to find)

Dialog text says: "Click Save to push the configuration changes to the Redis server."
Button text says: "Save"

**OR**

Dialog text says: "Click Apply to push the configuration changes to the Redis server."
Button text says: "Apply"

**Screenshots** (Paste or drag-and-drop a screenshot or a link to a recording)
![yD5Ndrl](https://github.com/RedisInsight/RedisInsight/assets/87519233/c5d5247c-59f3-4ad7-be36-1241b056edf8)

**Additional context** (Operating system, version of RedisInsight, Redis database version, Redis module version, database type, connection type, logs, or any other information)

Dockerized, RedisInsight version 1.14.0

I know it's just a small thing. But I still wanted to draw attention to it.

**Comment by ViktarStarastsenka** [comment]
@DarkModz-Official , thank you for raising this issue, you are right.
but RedisInsight v1 reached its end-of-life in April 2023, so there will be no additional releases to fix this
