### ISSUE TITLE
[Bug]: Log level RILOGLEVEL

### ISSUE THREAD

**Issue by ur-gh** [RedisInsight/RedisInsight#2290]
**Preconditions** (Any important steps we need to know)
Set RILOGLEVEL to DEBUG does not produce debug logs to troubleshoot a seperate Proxy issue I am facing. I am hoping to get some clarity on why my PROXY settings are not working. I tried to set to TRACE even though official docs at https://docs.redis.com/latest/ri/installing/configurations/ don't really mention it. It didn't help either

**Steps to reproduce** (How to reproduce what you found step by step)
Set RILOGLEVEL env variable to DEBUG. 

**Actual behavior** (A short description of what you found)
I keep seeing only INFO logs

**Expected behavior** (A short description of what you expected to find)
Expected some debug logs in the log related to Proxy Path settings.

**Screenshots** (Paste or drag-and-drop a screenshot or a link to a recording)

**Additional context** (Operating system, version of RedisInsight, Redis database version, Redis module version, database type, connection type, logs, or any other information)
Ubuntu 20, Kubernetes using Docker image

**Comment by ebuildy** [comment]
dont see where `RILOGLEVEL` is used?

**Comment by ur-gh** [comment]
Here is how its set in  Helm chart 
          env:
            - name: "RITRUSTEDORIGINS"
              value: "mhost"
            - name: "RILOGLEVEL"
              value: "DEBUG"

**Comment by ur-gh** [comment]
Also justo be clear, I am using latest Docker image from https://hub.docker.com/r/redislabs/redisinsight/tags

**Comment by GnaneshKunal** [comment]
Hey @ur-gh,

Logs related to proxy are logged using `INFO` level only.


```
$ docker run -e RILOGLEVEL=DEBUG --net host redislabs/redisinsight:latest
INFO 2023-07-22 12:44:29,498 redisinsight_startup Registered SIGTERM handler
INFO 2023-07-22 12:44:29,498 redisinsight_startup Proxy enabled but 'RIPROXYPATH' is not set. Using proxy prefix as 'X-Forwarded-Prefix'. If a different prefix is needed, set 'RIPROXYPREFIX' variable.
```

**Comment by ur-gh** [comment]
@GnaneshKunal it would be useful to know what headers were received by Redisinsight. That is why I needed more insight via debug logs. I would have been able to fix this issue WAY quicker if I had access to logs that printed headers received by Redisinsight

**Comment by GnaneshKunal** [comment]
Hey @ur-gh, currently the logs doesn't have the headers received by RedisInsight.

I'm closing this issue. If the issue persists, please reopen.
