### ISSUE TITLE
[Bug]: Redis Insight not opening in windows 8.1 after update to latest version of redis insight.

### ISSUE THREAD

**Issue by annihilatorrrr** [RedisInsight/RedisInsight#2342]
**Preconditions** N/A

**Steps to reproduce**  Just update and try to open it.

**Actual behavior** Giving error instead of opening.

**Expected behavior** Should open up as normal.

**Screenshots** Attactched!
![redis error](https://github.com/RedisInsight/RedisInsight/assets/75305464/2c965118-71e1-42af-b1e6-04a7e793a8c4)

**Additional context** windows 8.1, latest version of redis insight.

**Comment by ViktarStarastsenka** [comment]
hi @annihilatorrrr , the updated Electron version does not support Windows 8.1 anymore
https://www.electronjs.org/blog/windows-7-to-8-1-deprecation-notice

**Comment by annihilatorrrr** [comment]
i see, sed can you tell from where i can download the old version ?

**Comment by ViktarStarastsenka** [comment]
@annihilatorrrr , is there an option to update the system? RedisInsight has automatic updates, so even if you install an old version, it will be updated to the latest when (given that there is an internet connection)

**Comment by annihilatorrrr** [comment]
> @annihilatorrrr , is there an option to update the system? RedisInsight has automatic updates, so even if you install an old version, it will be updated to the latest when (given that there is an internet connection)

currently i don't intend to update the os, ahh yeah i forgot, well i forgot is there a option to turn off auto update ?

**Comment by ViktarStarastsenka** [comment]
@annihilatorrrr , no, there is no such option to turn off auto updates for now
you can download 2.26 build here:
https://download.redisinsight.redis.com/releases/2.26.0/RedisInsight-v2-win-installer.exe

**Comment by ViktarStarastsenka** [comment]
@annihilatorrrr , if you do not close the application, then auto-updates will not be installed.
I'll close this ticket.
