### ISSUE TITLE
[Feature Request]: Autocomplete redisearch index attributes

### ISSUE THREAD

**Issue by dane-stevens** [RedisInsight/RedisInsight#2346]
Please add index field autocomplete to "Search by values of Keys" tab (redisearch).

For example: if you type "@", it would bring up a list of index attributes that could be searched:
 - @status
 - @country
 - @age

After you select an autocomplete attribute it would populate that into the search box along with the characters used for the field type.

For example, you select @status which is a tag type, it would enter "@status:{}".

**Comment by ViktarStarastsenka** [comment]
hi @dane-stevens , the auto-completion is released with 2.60 today.
