### ISSUE TITLE
[Bug]: RedisInsight hangs when attempting to view a larger key

### ISSUE THREAD

**Issue by soatley** [RedisInsight/RedisInsight#2367]
**Preconditions** (Any important steps we need to know)
Connect to the server that has the large key(s)

**Steps to reproduce** (How to reproduce what you found step by step)
Find a key that has a large amount of data.  In my most recent attempt, it was a 12MB value.
Click on the key to view the data.
First, it comes up with the word 'Empty' in the area where the data should be, then after a few additional seconds, it goes to a white screen and appears to hang/freeze.

**Expected behavior** (A short description of what you expected to find)
View the key data

**Screenshots** (Paste or drag-and-drop a screenshot or a link to a recording)

**Additional context** (Operating system, version of RedisInsight, Redis database version, Redis module version, database type, connection type, logs, or any other information)
Alternatively, if it's not a good idea to show the data, perhaps a 'copy' function to copy the key value to the clipboard so it can be inserted into another tool for review.

**Comment by tormit** [comment]
This happens when you write NodeJS bloat desktop apps. I miss the good old RESP app.

**Comment by soatley** [comment]
Alternatively, it would be great to have a button that  I could download the key into a file.  Then I can throw it into Notepad++ if need be.  But right now, when I click on the key, it won't bring up any options and hangs the app.

**Comment by ViktarStarastsenka** [comment]
hi @soatley , @tormit , thank you for the feedback, there is a ticket already to load strings in parts, we will aim to implement it in October, but I'll update here once timelines are certain.

**Comment by ViktarStarastsenka** [comment]
@soatley , please try RedisInsight 2.36 (released today).
there you can either load the entire value (not recommended) or download the value into a file.
