### ISSUE TITLE
[Bug]: 更换颜色主题后，重启在进入，又恢复到了之前的颜色主题

### ISSUE THREAD

**Issue by maguoliang888** [RedisInsight/RedisInsight#2377]
**Preconditions** (Any important steps we need to know)

**Steps to reproduce** (How to reproduce what you found step by step)

**Actual behavior** (A short description of what you found)

**Expected behavior** (A short description of what you expected to find)

**Screenshots** (Paste or drag-and-drop a screenshot or a link to a recording)

**Additional context** (Operating system, version of RedisInsight, Redis database version, Redis module version, database type, connection type, logs, or any other information)

**Comment by ViktarStarastsenka** [comment]
hi @maguoliang888 , can you please provide more information on how to reproduce this issue?
what RedisInsight version do you use? is it Electron or docker?

**Comment by ViktarStarastsenka** [comment]
please re-open the ticket if it is still relevant
