### ISSUE TITLE
RedisInsight 2.x as Web UI

### ISSUE THREAD

**Issue by fl0wx** [RedisInsight/RedisInsight#2384]
Hey all,

is it possible to run RedisInsight 2.x as a Web UI Application? If yes, how to do it exactly? And if no - is it possible to get that feature?

Thanks and regards
fl0w

**Comment by ViktarStarastsenka** [comment]
hi, currently, there is no such option
here is the relevant ticket, I'll provide updates there
https://github.com/RedisInsight/RedisInsight/issues/519

**Comment by seebeen** [comment]
@fl0wx It is now - https://github.com/RedisInsight/RedisInsight/issues/519#issuecomment-1682675339
