### ISSUE TITLE
[Bug]:Login issue for read-only user

### ISSUE THREAD

**Issue by PanMan** [RedisInsight/RedisInsight#2390]
**Preconditions** (Any important steps we need to know)
We have a read-only user that can read and subscribe to keys, but not alter data, for our production redis. 
This used to work, now it doesn't, it throws an `Internal server error` in redis insights when trying to connect.
Connecting via command line with these credentials does work..

**Steps to reproduce** (How to reproduce what you found step by step)
Have a read-only user, connect to a db

**Actual behavior** (A short description of what you found)
Connecting used to work

**Expected behavior** (A short description of what you expected to find)
Connection should work

**Screenshots** (Paste or drag-and-drop a screenshot or a link to a recording)
<img width="365" alt="image" src="https://github.com/RedisInsight/RedisInsight/assets/978501/1033929b-b96d-4f70-a473-3226cb2af2b5">

Is there any way to get the log of the connection? I think redisInsights does some commands it isn't allowed to..

**Comment by ViktarStarastsenka** [comment]
hi @PanMan , can you please share the list of commands available for this user?
to get the detailed logs, you can run the following command (this is for Windows):
`cmd /C “set DEBUG=ioredis* && .\RedisInsight-v2.exe”`

please sanitize them and remove any sensitive information before sharing logs

**Comment by PanMan** [comment]
@ViktarStarastsenka thanks for that command. I got this error in the logs:
```
Skipping the ready check because INFO command fails: "NOPERM this user has no permissions to run the 'INFO' command or its sub-commands". You can disable ready check with "enableReadyCheck". More: https://github.com/luin/ioredis/wiki/Disable-ready-check.
```

I guess that's the issue

**Comment by ViktarStarastsenka** [comment]
@PanMan , yes, you need the `INFO` command to connect to databases via RedisInsight

**Comment by PanMan** [comment]
Thanks, adding the "INFO" rights (for future reference: +info in the ACL) seems to have fixed this. I do think the error message could be better.

**Comment by ViktarStarastsenka** [comment]
@PanMan , this is not new actually, the `INFO` command was always required

**Comment by ViktarStarastsenka** [comment]
regarding the error - yes, this is a known issue, it will be enhanced with 2.32 (to be released in late August).

**Comment by PanMan** [comment]
> @PanMan , this is not new actually, the `INFO` command was always required

Interesting, as before the user worked and stopped working recently. I do think it would be good to add this to the documentation somewhere.
