### ISSUE TITLE
[Bug]: Failed to convert to Msgpack with valid Msgpack content

### ISSUE THREAD

**Issue by amtelekom** [RedisInsight/RedisInsight#2391]
**Preconditions**

**Steps to reproduce**
Create a List containing MsgPack serialized data with a somewhat complex structure, e.g.
`969297a4446f6e65a44e6f6e6599cd07e7ccce08240bce2aa8cc7900000099cd07e7ccce08240cce0489e5ae000000b26c73612f7069755f61737369676e5f7266738192ad637573746f6d65725f6e616d65c081aa556e7265736f6c766564a87b2e2f6e616d657d8097a4446f6e65a44e6f6e6599cd07e7ccce08240cce05e4cd7800000099cd07e7ccce08240cce2584338b000000a6636f6d6d69748080b07069755f6e65775f637573746f6d657292a74c697374416464b92f6366732d7069753a6366732d7069752f637573746f6d6572019291cd1d4191ce104e893b93b4736572766963652d6163636f756e742d73696d7393a8736477616e5f7277ae6f66666c696e655f616363657373b1756d615f617574686f72697a6174696f6ea453796e63` (as hex)

(this particular example was generated using [rmp-serde](https://crates.io/crates/rmp-serde), but should not matter)

**Actual behavior** (A short description of what you found)
When inspecting the list entry with Msgpack decoding enabled, the Unicode output is displayed, with a Tooltip showing `Failed to convert to Msgpack`.

**Expected behavior** (A short description of what you expected to find)
Show the JSON-representation of the Msgpack value, i.e., 

```json
[
    [
        [
            "Done",
            "None",
            [ 2023, 206, 8, 36, 11, 715705465, 0, 0, 0 ],
            [ 2023, 206, 8, 36, 12, 76146094, 0, 0, 0 ],
            "lsa/piu_assign_rfs",
            {
                "customer_name,": {
                    "Unresolved": "{./name}"
                }
            },
            {}
        ],
        [
            "Done",
            "None",
            [ 2023, 206, 8, 36, 12, 98880888, 0, 0, 0 ],
            [ 2023, 206, 8, 36, 12, 629420939, 0, 0, 0 ],
            "commit",
            {},
            {}
        ]
    ],
    "piu_new_customer",
    [
        "ListAdd",
        "/cfs-piu:cfs-piu/customer"
    ],
    1,
    [
        [ 7489 ],
        [ 273582395 ]
    ],
    [
        "service-account-sims",
        [ "sdwan_rw", "offline_access", "uma_authorization" ],
        "Sync"
    ]
]
```

**Screenshots** (Paste or drag-and-drop a screenshot or a link to a recording)
![image](https://github.com/RedisInsight/RedisInsight/assets/21334898/fd7c5fcd-d474-4da7-b999-87906848d83e)

**Additional context** 
Linux 6.4.3
redis Standalone 7.0.8
redisInsight 2.28.0 (running as electron app)

**Comment by ViktarStarastsenka** [comment]
hi @BGMP , do you use any data compressors?

**Comment by BGMP** [comment]
hey there @ViktarStarastsenka. No, not that I'm aware of at least. If Rails is doing something to the data being sent to Redis then I'm not aware of it, but that shouldn't be the case as far as I'm concerned.

**Comment by ViktarStarastsenka** [comment]
@amtelekom , can you check that your JSON was correctly converted in MessagePack? I checked the JSON you sent previously, and it worked fine.
I used this tool for conversion: https://converts.me/tools/conversion/data/json-to-message-pack

**Comment by BGMP** [comment]
> @BGMP , got it
> this case is also due to the limitation of the library that RedisInsight currently uses

@ViktarStarastsenka Oh... I see. Glad that I didn't was your time there haha. Is anyone already looking into the issue? or is it a general milestone for the project to update that library? I would be happy to test any offstream releases for a fix.

Thanks for your response!

**Comment by ViktarStarastsenka** [comment]
@BGMP , we briefly looked into this but didn't find any better library so far. So need to spend more time, but we lack capacity right now.
this point is in our backlog, but I cannot provide any certain timelines.

**Comment by GnaneshKunal** [comment]
Hey @amtelekom,

I have tried the same Message Pack data and there wasn't any issue viewing it in RedisInsight.

Can you make sure that the way you are storing it in redis is in bytes and not as a UTF-8 string. Chances are that the data is converted to a UTF-8 string at the application/library layer before storing it in the redis key.



Here's an example of storing the above message pack data as bytes in the redis. I'm using `xxd` command to do so. If you are using a redis rust library, make sure to store the data as bytes directly.

```
$ echo '969297A4446F6E65A44E6F6E6599CD07E7CCCE08240BCE2AA8CC7900000099CD07E7CCCE08240CCE0489E5AE000000B26C73612F7069755F61737369676E5F72667381AE637573746F6D65725F6E616D652C81AA556E7265736F6C766564A87B2E2F6E616D657D8097A4446F6E65A44E6F6E6599CD07E7CCCE08240CCE05E4CD7800000099CD07E7CCCE08240CCE2584338B000000A6636F6D6D69748080B07069755F6E65775F637573746F6D657292A74C697374416464B92F6366732D7069753A6366732D7069752F637573746F6D6572019291CD1D4191CE104E893B93B4736572766963652D6163636F756E742D73696D7393A8736477616E5F7277AE6F66666C696E655F616363657373B1756D615F617574686F72697A6174696F6EA453796E63' | xxd -r -p | redis-cli -x SET msg-pack-complex
```


Data is then stored in bytes in redis:
```
$ redis-cli GET msg-pack-complex                                                                                                                                                                                 
"\x96\x92\x97\xa4Done\xa4None\x99\xcd\a\xe7\xcc\xce\b$\x0b\xce*\xa8\xccy\x00\x00\x00\x99\xcd\a\xe7\xcc\xce\b$\x0c\xce\x04\x89\xe5\xae\x00\x00\x00\xb2lsa/piu_assign_rfs\x81\xaecustomer_name,\x81\xaaUnresolved\xa8{./name}\x80\x97\xa4Done\xa4None\x99\xcd\a\xe7\xcc\xce\b$\x0c\xce\x05\xe4\xcdx\x00\x00\x00\x99\xcd\a\xe7\xcc\xce\b$\x0c\xce%\x843\x8b\x00\x00\x00\xa6commit\x80\x80\xb0piu_new_customer\x92\xa7ListAdd\xb9/cfs-piu:cfs-piu/customer\x01\x92\x91\xcd\x1dA\x91\xce\x10N\x89;\x93\xb4service-account-sims\x93\xa8sdwan_rw\xaeoffline_access\xb1uma_authorization\xa4Sync"
```



### RedisInsight v2.30.0 (with format selected as MsgPack):
![image](https://github.com/RedisInsight/RedisInsight/assets/20211167/7e8409bf-f5aa-4e6d-bda2-9dd342521328)

**Comment by GnaneshKunal** [comment]
Hey @BGMP,

can you verify that the final data doesn't get transformed to UTF-8/signifying by the application/library layer before storing it in Redis? 

Can you confirm this in your mongoid code in Rails?

**Comment by amtelekom** [comment]
Hi @GnaneshKunal,

thanks for looking into it.
I've updated to 2.30 and tried your xxd insertion method, and strangely it works for me as well:

![image](https://github.com/RedisInsight/RedisInsight/assets/21334898/28c421bc-d08e-4879-b8c9-7a0371ce333e)

Sadly, I don't have the original DB entry anymore, so I cannot check if it would have worked there now, too.

While trying to narrow down the exact problem circumstances, I've encountered another valid msgpack blob that fails to decode - both when added by my application, as well as the xxd method:

```bash
echo '98A44E6F6E6581A15499CD07E7CCE9090408CE26DFE89700000081A15499CD07E7CCE9090409CE05B137F3000000B26C73612F7069755F61737369676E5F7266738192AD637573746F6D65725F6E616D65C081AA556E7265736F6C766564A87B2E2F6E616D657D8081A573746570739080' | xxd -r -p | redis-cli -x SET msg-pack-complex
```

![image](https://github.com/RedisInsight/RedisInsight/assets/21334898/266e1d32-5e99-41a1-aa6d-10161e5ebee7)

Programatically we're storing the data as raw bytes, so that should not be it. In fact the same codepath works for simpler structures, and the examples are exported from redisinsight using its Hex output formatting, so an additional UTF8-Encoding would have been visible there, too.

Is there a way to get an exception / error message from @msgpack/msgpack, instead of the generic "Failed to convert" message?

---

Things I've also tried:

After guessing the problem only occurs for list values, I've modified the xxd-line to run `rpush`, but that's not it either:

![image](https://github.com/RedisInsight/RedisInsight/assets/21334898/4d8c1862-359b-4b8a-81fc-c3cb53303a5e)

Getting my code to push a new structure works now as well, although through continued development, the format of the structure has changed:

![image](https://github.com/RedisInsight/RedisInsight/assets/21334898/1f34b7eb-108e-489e-ac87-a3c9b008a642)

**Comment by BGMP** [comment]
> Hey @BGMP,
> 
> can you verify that the final data doesn't get transformed to UTF-8/signifying by the application/library layer before storing it in Redis?
> 
> Can you confirm this in your mongoid code in Rails?

Hello there @GnaneshKunal ,

After a bit of research and experimenting with my implementation I came up with the following:

The Problem
---
I found out that Rails would store a serialised version of the data by default. For example, take the following function in my app. It would find a Car model through mongoid, and then cache it through Redis under a key with name "Car#car_id".
```ruby
def find_car(car_id)
  Rails.cache.fetch("Car##{car_id}") do
    Car.find { |c| c.id.eql?(car_id) }
  end
end
```

After executing the service which produced all of these cached models, I'd get this:
```cmd
127.0.0.1:6379> SCAN 0
1) "30"
2)  1) "Car#64c88b7f16365c384405fea3"
    2) "Car#64c88d4916365c384405fead"
    3) "Car#64c889e816365c384405fe9b"
    4) "Car#64c88c6016365c384405fea8"
    5) "Car#64c88c0016365c384405fea6"
    6) "Car#64c88b1316365c384405fea1"
    7) "Car#64c88af516365c384405fea0"
    8) "Car#64c88bd216365c384405fea5"
    9) "Car#64c8897416365c384405fe98"
   10) "Car#64c8938416365c384406016b"
```
```cmd
127.0.0.1:6379> GET Car#64c88b7f16365c384405fea3
"\x04\bo: ActiveSupport::Cache::Entry\t:\x0b@valueo:\bCar\t:\x17@__selected_fields0:\x10@attributes{\x11I\"\b_id\x06:\x06ETU:\x13BSON::ObjectId\"\x11d\xc8\x8b\x7f\x166\\8D\x05\xfe\xa3I\"\tname\x06;\nTI\"\nXM250\x06;\nTI\"\nspeed\x06;\nTf\t70.2I\"\naccel\x06;\nTf\t3.13I\"\x0bweight\x06;\nTf\b1.4I\"\x10folder_name\x06;\nTI\"\nxm250\x06;\nTI\"\nstock\x06;\nTFI\"\x0eseason_id\x06;\nTU;\x0b\"\x11d\xc8p\x99\x166\\\x1e\x8c!\xc8kI\"\x0fupdated_at\x06;\nTIu:\tTime\r%\xdc\x1e\xc0\xd8\xc4\xf3D\x06:\tzoneI\"\bUTC\x06;\nFI\"\x0fcreated_at\x06;\nTIu;\x0c\r$\xdc\x1e\xc0 \xad\xb5\x8c\x06;\r@\x1aI\"\rcategory\x06;\nTi\nI\"\x0fmultiplier\x06;\nTf\b0.8:!@attributes_before_type_cast{\x11@\b@\t@\x0b@\x0c@\r@\x0e@\x0f@\x10@\x11@\x12@\x13@\x14@\x15F@\x16@\x17@\x19@\x1b@\x1c@\x1d@\x1ei\n@\x1f@ :\x17@pending_callbackso:\bSet\x06:\n@hash}\x00F:\r@version0:\x10@created_atf\x151692681680.04298:\x10@expires_in0"
```

Rails stores a serialised [ActiveSupport::Cache::Entry](https://github.com/rails/rails/blob/291a3d2ef29a3842d1156ada7526f4ee60dd2b59/activesupport/lib/active_support/cache.rb#L792) instance, which includes a bit of extra info. which I suppose it uses to its advantage behind the scenes.

This way of directly caching the model is what produced the unsupported characters, so no wonder RedisInsight isn't able to render these instances correctly. That being said, it would be cool if this worked out of the box with ActiveSupport cache entries haha, but I guess that's out of scope?

Workaround?
---
So, if I force `Rails.cache` to store the data as `JSON` and I take care of handling it that way on my application's end:
```ruby
def find_cached_car(car_id)
  Rails.cache.fetch("Car##{car_id}", :raw => true) do
    Car.find { |c| c.id.eql?(car_id) }.to_json
  end
end

def find_car(car_id)
  car_json = find_cached_car(car_id)
  Car.new(JSON.parse(car_json))
end
```

Then yeah, the visualisation resolves correctly on RedisInsight:
![Capture](https://github.com/RedisInsight/RedisInsight/assets/26081543/956908ca-f798-435a-8a4e-c3b075f52090)

On Redis' end:
```cmd
127.0.0.1:6379> GET Car#64c88b7f16365c384405fea3
"{\"_id\":{\"$oid\":\"64c88b7f16365c384405fea3\"},\"accel\":3.13,\"category\":5,\"created_at\":\"2023-07-31T23:35:11.372-05:00\",\"folder_name\":\"xm250\",\"multiplier\":0.8,\"name\":\"XM250\",\"season_id\":{\"$oid\":\"64c8709916365c1e8c21c86b\"},\"speed\":70.2,\"stock\":false,\"updated_at\":\"2023-08-01T00:17:15.247-05:00\",\"weight\":1.4}"
```

Conclusion
---
I'm not sure what to draw from all of this. I think going through the hassle of storing the raw data as json goes against whatever Rails is trying to do to make my life easier? I suppose it stores that serialised object for a reason, and on the other hand I'm doing all of this just to have it be rendered as json.

I hope my comment helps, and don't hesitate to mention me back!

**Comment by GnaneshKunal** [comment]
Hey @BGMP,

Thank you for very much detailed response. It now makes sense that the added extra information from rails is causing the msgpack to break. It would be out of scope to cover this in RedisInsight. If there are many users requiring this, this can be looked into but in general, it is very hard to detect whether the msgpack data is malfored or is valid but has extra bit of information.

**Comment by BGMP** [comment]
> Hey @BGMP,
> 
> Thank you for very much detailed response. It now makes sense that the added extra information from rails is causing the msgpack to break. It would be out of scope to cover this in RedisInsight. If there are many users requiring this, this can be looked into but in general, it is very hard to detect whether the msgpack data is malfored or is valid but has extra bit of information.

Well, this *is* the way Rails handles caching by default, so I can see a lot more people going through the same issues I went through if they try to use RedisInsight to visualise cache keys.

There's a glimpse of hope though. As far as I'm concerned, the extra information added by Rails is, I believe, always the same, so I guess we could work around it to get the actual data to be displayed.

If you think it'd be a good idea, I could look into it.

**Comment by GnaneshKunal** [comment]
Hey @BGMP,

Please provide the redis msgpack byte data in hex format so that we can look into possible solutions. Hex format so that it can be added via the previously used `xxd` command.

**Comment by BGMP** [comment]
Hey there @GnaneshKunal ! I haven't forgot about this issue, I've just had a very busy schedule 😓.

I'll get back to you in some days, hopefully soonish.

**Comment by BGMP** [comment]
Hello, @GnaneshKunal ,

I finally have some free time at hand. Sorry it took this long.

OK. If I understand correctly, you want me to send you the visualisation of the data in **HEX** format. Here's the key I'll be working with, for context:
```bash
127.0.0.1:6379> SCAN 0
1) "56"
2)  1) "Track#64c877f416365c1e8c21c898"
    2) "User#LOQ"
    3) "Car#64c88a9016365c384405fe9e"
    4) "Car#64c88d0516365c384405feac"
    5) "Car#64c889c116365c384405fe9a"
    6) "Car#64c88cbc16365c384405feaa"
    7) "Car#64c889a016365c384405fe99"
    8) "Car#64c88d4916365c384405fead"
    9) "Car#64c88c0016365c384405fea6"
   10) "Car#64c88ba516365c384405fea4"
127.0.0.1:6379> GET Car#64c88a9016365c384405fe9e
"\x04\bo: ActiveSupport::Cache::Entry\t:\x0b@valueo:\bCar\t:\x17@__selected_fields0:\x10@attributes{\x11I\"\b_id\x06:\x06ETU:\x13BSON::ObjectId\"\x11d\xc8\x8a\x90\x166\\8D\x05\xfe\x9eI\"\tname\x06;\nTI\"\x13Dookur Special\x06;\nTI\"\nspeed\x06;\nTf\t75.2I\"\naccel\x06;\nTf\t2.47I\"\x0bweight\x06;\nTf\b3.5I\"\x10folder_name\x06;\nTI\"\x0fphim_dakar\x06;\nTI\"\nstock\x06;\nTFI\"\x0eseason_id\x06;\nTU;\x0b\"\x11d\xc8p\x99\x166\\\x1e\x8c!\xc8kI\"\x0fupdated_at\x06;\nTIu:\tTime\r%\xdc\x1e\xc0`O\xc5@\x06:\tzoneI\"\bUTC\x06;\nFI\"\x0fcreated_at\x06;\nTIu;\x0c\r$\xdc\x1e\xc0 B\xc2|\x06;\r@\x1aI\"\rcategory\x06;\nTi\nI\"\x0fmultiplier\x06;\nTf\b1.5:!@attributes_before_type_cast{\x11@\b@\t@\x0b@\x0c@\r@\x0e@\x0f@\x10@\x11@\x12@\x13@\x14@\x15F@\x16@\x17@\x19@\x1b@\x1c@\x1d@\x1ei\n@\x1f@ :\x17@pending_callbackso:\bSet\x06:\n@hash}\x00F:\r@version0:\x10@created_atf\x171693845342.6228833:\x10@expires_in0"
127.0.0.1:6379>
```

When trying to visualise this as HEX, I get the following:
```bash
04086f3a20416374697665537570706f72743a3a43616368653a3a456e747279093a0b4076616c75656f3a08436172093a17405f5f73656c65637465645f6669656c6473303a1040617474726962757465737b114922085f6964063a064554553a1342534f4e3a3a4f626a6563744964221164c88a9016365c384405fe9e4922096e616d65063b0a54492213446f6f6b7572205370656369616c063b0a5449220a7370656564063b0a54660937352e3249220a616363656c063b0a546609322e343749220b776569676874063b0a546608332e35492210666f6c6465725f6e616d65063b0a5449220f7068696d5f64616b6172063b0a5449220a73746f636b063b0a544649220e736561736f6e5f6964063b0a54553b0b221164c8709916365c1e8c21c86b49220f757064617465645f6174063b0a5449753a0954696d650d25dc1ec0604fc540063a097a6f6e65492208555443063b0a4649220f637265617465645f6174063b0a5449753b0c0d24dc1ec02042c27c063b0d401a49220d63617465676f7279063b0a54690a49220f6d756c7469706c696572063b0a546608312e353a2140617474726962757465735f6265666f72655f747970655f636173747b1140084009400b400c400d400e400f40104011401240134014401546401640174019401b401c401d401e690a401f40203a174070656e64696e675f63616c6c6261636b736f3a08536574063a0a40686173687d00463a0d4076657273696f6e303a1040637265617465645f61746617313639333834353334322e363232383833333a1040657870697265735f696e30
```

Not sure what I should be doing with `xxd`. Following the example you were talking about above, I came up with the following:
```bash
echo '04086f3a20416374697665537570706f72743a3a43616368653a3a456e747279093a0b4076616c75656f3a08436172093a17405f5f73656c65637465645f6669656c6473303a1040617474726962757465737b114922085f6964063a064554553a1342534f4e3a3a4f626a6563744964221164c88a9016365c384405fe9e4922096e616d65063b0a54492213446f6f6b7572205370656369616c063b0a5449220a7370656564063b0a54660937352e3249220a616363656c063b0a546609322e343749220b776569676874063b0a546608332e35492210666f6c6465725f6e616d65063b0a5449220f7068696d5f64616b6172063b0a5449220a73746f636b063b0a544649220e736561736f6e5f6964063b0a54553b0b221164c8709916365c1e8c21c86b49220f757064617465645f6174063b0a5449753a0954696d650d25dc1ec0604fc540063a097a6f6e65492208555443063b0a4649220f637265617465645f6174063b0a5449753b0c0d24dc1ec02042c27c063b0d401a49220d63617465676f7279063b0a54690a49220f6d756c7469706c696572063b0a546608312e353a2140617474726962757465735f6265666f72655f747970655f636173747b1140084009400b400c400d400e400f40104011401240134014401546401640174019401b401c401d401e690a401f40203a174070656e64696e675f63616c6c6261636b736f3a08536574063a0a40686173687d00463a0d4076657273696f6e303a1040637265617465645f61746617313639333834353334322e363232383833333a1040657870697265735f696e30' | xxd -r -p | redis-cli -x SET Car#64c88a9016365c384405fe9e
```

It doesn't change how the key value is being stored though... maybe I'm doing something wrong?

Thanks for your help!

**Comment by BGMP** [comment]
Any news? @GnaneshKunal

**Comment by GnaneshKunal** [comment]
@BGMP,

Since this is not considered as a valid MessagePack info, the parsers we use support only pure messagepack. It's very hard to understand and parse library specific content. What the library does is an extension to the message pack itself. It uses the message pack format as its core and extends it to add its own information, so the final message is not really a message pack.

We tried a bunch of libraries and online parsers and didn't find a very easy solution without forking the core message pack library to add the support, which is out of scope. We would suggest you to see if switching off this additional metadata on the rails app if it doesn't cause any side effects, or fallback to JSON based schema if there's no side effects.

**Comment by GnaneshKunal** [comment]
We are closing this issue, cause the core issue with the message pack content not being converted is fixed, and the rails is an extension to it. Please feel free to a new ticket if necessary.
