### ISSUE TITLE
[Feature Request]:Provide Docker image for latest Redis-insight ui

### ISSUE THREAD

**Issue by mayank14798** [RedisInsight/RedisInsight#2407]
**Problem description** (The docker image currently available for the redisInsight ui is an old one and not the latest one with the latest ui changes.).

**Comment by ViktarStarastsenka** [comment]
hi @mayank14798 , here is the ticket with the latest updates
https://github.com/RedisInsight/RedisInsight/issues/519

**Comment by seebeen** [comment]
Solved https://github.com/RedisInsight/RedisInsight/issues/519#issuecomment-1682675339
