### ISSUE TITLE
[Bug]:RedisInsight cannot see the Redis cache when used by the Spring boot application

### ISSUE THREAD

**Issue by minilunas** [RedisInsight/RedisInsight#2409]
when i use resdis as springboot application's cache, the resdis key can't find when i use RedisInsight ,but it can be find in redis manager desktop.

**Comment by ViktarStarastsenka** [comment]
hi @minilunas , if your database has more than 10,000 keys, you need to click the "Scan more" button to scan additional 10,000 keys.
or you can enter an exact key name without patterns (*), in this case, the entire database will be scanned at once.

<img width="615" alt="image" src="https://github.com/RedisInsight/RedisInsight/assets/99594890/6f2d4049-095f-48b2-b605-f40f49dbd62e">

**Comment by minilunas** [comment]
database is empty and only use for springboot application's cache

**Comment by ViktarStarastsenka** [comment]
@minilunas , please share additional details so I can look into this deeper:
1. run the `INFO Keyspace` and share the results
2. run the `INFO Cluster` and share the results
3. what is the Redis version that you use?
4. do you use any glob-style patterns? like ? *, etc.

**Comment by ViktarStarastsenka** [comment]
please re-open the ticket if the issue is still relevant
