### ISSUE TITLE
v2.30.0 After installation, there is no shortcut

### ISSUE THREAD

**Issue by danding-s** [RedisInsight/RedisInsight#2424]
v2.30.0 ，After installation, there is no shortcut

**Comment by ViktarStarastsenka** [comment]
hi @danding-s , what OS do you use? is there a shortcut but without logo or no shortcut at all?

**Comment by danding-s** [comment]
windows 11  22621.2070

**Comment by ViktarStarastsenka** [comment]
@danding-s , can you please check this path?
C:\Users\{user}\AppData\Roaming\Microsoft\Windows\Start Menu\Programs

or you can create a shortcut from this folder:
C:\Users\{user}\AppData\Local\Programs\redisinsight

**Comment by ViktarStarastsenka** [comment]
@danding-s , please try it with 2.32 (it was released today).

**Comment by danding-s** [comment]
latest version is cool
