### ISSUE TITLE
[Bug]:After Ubuntu upgrade, Redis UI don't show anything on screen

### ISSUE THREAD

**Issue by cristiangav** [RedisInsight/RedisInsight#2427]
Hello,

I recently upgraded my ubuntu 22.04 operating system via console, everything normal, the problem appears when I open the Redisinsight UI, the initial logo appears blank and after opening it shows absolutely nothing of my databases just a black screen.

Has it happened to anyone else?

![image](https://github.com/RedisInsight/RedisInsight/assets/129307693/619e2769-5f84-4551-9bc6-9422ffb81f05)

My operating system is Ubuntu 22.04 and my RedisInsight version is 2.30. All my drivers is up to date

**Comment by GnaneshKunal** [comment]
Hey @cristiangav, I tried in Ubuntu 22.04.3. Works fine without any issues.

Here's a screenshot of the same:
![ubuntu-22-03-copy-working](https://github.com/RedisInsight/RedisInsight/assets/20211167/280bbcea-32b4-4992-a02c-250b64ac6318)


Can you provide more info how whether you are using the AppImage or DEB version? Also, can you try reinstalling and see if there are any other issues with the system?

Also, from which version of ubuntu did you upgrade?

**Comment by GnaneshKunal** [comment]
Hey @cristiangav, closing this.

Please reopen the issue if needed.

**Comment by italoiz** [comment]
I'm facing the same issue but using the **Pop!_OS 22.04 LTS**. I installed it from Flathub. I tried to uninstall it and reinstall it many times, unfortunately, without success.

### Screenshot

![image](https://github.com/RedisInsight/RedisInsight/assets/8454560/df5b5070-b1ad-4112-b5e2-ffda0a407aba)

### Steps to Reproduce it

1. Install from Flathub (The version is 2.36.0.95775)
2. Try launch it
3. You should get a screen like the image above.
