### ISSUE TITLE
Mac App Store version still receiving updates?

### ISSUE THREAD

**Issue by hendrickson-tyler** [RedisInsight/RedisInsight#2428]
I've been using RedisInsight through the [Mac App Store](https://apps.apple.com/us/app/redisinsight/id6446987963?mt=12) for a couple of months now. I've noticed as of late that the version on the Mac App Store is a couple of releases behind (still 2.26). Is the Mac App Store version still being supported?

**Comment by ViktarStarastsenka** [comment]
hi @hendrickson-tyler , yes, it is still supported, and we are working with App Store to have the latest RedisInsight version available there, but it takes time.
I'll post an update here once the new version is available on App Store

**Comment by hendrickson-tyler** [comment]
Thanks for the update! Looking forward to the new version. And thank you for offering it on the App Store to begin with, I definitely appreciate that option

**Comment by ViktarStarastsenka** [comment]
@hendrickson-tyler , the latest version is available now.

**Comment by hendrickson-tyler** [comment]
Fantastic, thank you again!
