### ISSUE TITLE
[Bug]:Regarding the issue of garbled characters in the client display

### ISSUE THREAD

**Issue by M87X2z** [RedisInsight/RedisInsight#2429]
![屏幕快照 2023-08-03 03 18 13](https://github.com/RedisInsight/RedisInsight/assets/140151100/a68bebf5-5951-4db1-95a9-0c68f65ca020)

![屏幕快照 2023-08-03 03 19 38](https://github.com/RedisInsight/RedisInsight/assets/140151100/e679ac66-3188-435c-a8c4-2f2fc8ae7200)

![index](https://github.com/RedisInsight/RedisInsight/assets/140151100/1fc261b5-51e2-430f-966c-91c1984c471d)

![detail](https://github.com/RedisInsight/RedisInsight/assets/140151100/0be2ea15-a68c-4753-b507-604a6ebf3d16)

**Comment by ViktarStarastsenka** [comment]
hi @M87X2z , how do you generate your data? do you use any compressors?

**Comment by M87X2z** [comment]
@ViktarStarastsenka Thank you! Here's how I do it:
![屏幕快照 2023-08-03 12 41 54](https://github.com/RedisInsight/RedisInsight/assets/140151100/bbc72ad2-8bfe-40e2-a595-b4f0ce6c67e0)

![屏幕快照 2023-08-03 12 43 12](https://github.com/RedisInsight/RedisInsight/assets/140151100/a552c982-7a0f-4b24-8bd1-da2e4ab3cf8a)

**Comment by M87X2z** [comment]
Sure. Here it is:
![1](https://github.com/RedisInsight/RedisInsight/assets/140151100/e3e07606-ea5e-4865-bfa2-2b24f2676ab7)

![2](https://github.com/RedisInsight/RedisInsight/assets/140151100/65f90f5f-f104-4f64-9b83-8617d149437d)

**Comment by ViktarStarastsenka** [comment]
@M87X2z , thanks
regarding the key name - currently, RedisInsight uses Unicode to display key names, so some ASCII characters (as in your example) are non-printable.
regarding values of the key - can you run `GET {key name}` and share the results (but please sanitize them if they contain any sensitive data)?
do you use any data compressors for the values of keys?

**Comment by ViktarStarastsenka** [comment]
please check if any data decompression should be selected (the screen is attached below).
re-open the ticket if it is still relevant

<img width="501" alt="image" src="https://github.com/RedisInsight/RedisInsight/assets/99594890/3ac76057-f062-403c-a099-4b04f3ed3854">
