### ISSUE TITLE
Port Forwarded redis instance cannot be connected to

### ISSUE THREAD

**Issue by justinasfour04** [RedisInsight/RedisInsight#243]
I have a redis cluster running on docker with ports forwarded and redisInsight keeps giving me a connection timeout every time I try connecting to my redis cluster

![image](https://user-images.githubusercontent.com/6599551/151623379-1897075f-6c4c-4984-9642-b210fee3730e.png)
![image](https://user-images.githubusercontent.com/6599551/151623414-152b0f26-272c-4cf8-a514-fe8f4f2a1c3f.png)

**Comment by ViktorStarostenko** [comment]
Hi @justinasfour04, can you please provide me exact steps you are following to add this Redis Cluster (the image and all the commands run)?
We have just tested this case using a similar image and everything works fine.

Also could you please try connecting to this Cluster via redis-cli just to be sure that there are no connection issues?

**Comment by moluzhui** [comment]
@ViktorStarostenko  I have same problems. I create a cluster through [bitnami-docker-redis-cluster](https://github.com/bitnami/bitnami-docker-redis-cluster) and expose all container ports.I can go into redis and view through redis-cli of other servers. 
```
redis-cli -h <ip>-p 8001 -a bitnami
Warning: Using a password with '-a' or '-u' option on the command line interface may not be safe.
<ip>:8001> info replication
# Replication
role:master
connected_slaves:1
slave0:ip=172.22.0.5,port=6379,state=online,offset=924,lag=1
master_failover_state:no-failover
master_replid:c81f92ef6c3dcd3e2f081426159d5b34b9855c36
master_replid2:0000000000000000000000000000000000000000
master_repl_offset:924
second_repl_offset:-1
repl_backlog_active:1
repl_backlog_size:1048576
repl_backlog_first_byte_offset:1
repl_backlog_histlen:924
<ip>:8001> cluster nodes
8cbc3ac8948efd020426411497f8f1a1bca54dcb 172.22.0.2:6379@16379 master - 0 1648181433774 2 connected 5461-10922
8d786ec7f9ac1dacc27a69bc18ec3e7a23e261c1 172.22.0.5:6379@16379 slave 09034c60b880ca62860a2d40f0ec0272377366dd 0 1648181434000 1 connected
25b34e93f5676350b6b57821c347bee7913724ff 172.22.0.4:6379@16379 slave 2b903decfff9d68552c884a689b62e44c38a9ede 0 1648181432000 3 connected
09034c60b880ca62860a2d40f0ec0272377366dd 172.22.0.3:6379@16379 myself,master - 0 1648181429000 1 connected 0-5460
2b903decfff9d68552c884a689b62e44c38a9ede 172.22.0.6:6379@16379 master - 0 1648181433000 3 connected 10923-16383
362cf49368bf4e491e88dd53ee071120fa8ff653 172.22.0.7:6379@16379 slave 8cbc3ac8948efd020426411497f8f1a1bca54dcb 0 1648181434778 2 connected
<ip>:8001>
```
But I can't connect either one using `redisinsightv2.0.4-preview`. error is
```
{
    "statusCode": 400,
    "message": "Could not connect to <ip>:<port>, please check the connection details.",
    "error": "Bad Request"
}
```

**Comment by arthosofteq** [comment]
@justinasfour04 As I can see you exposed few ports (7009, 7010, etc.) from your docker. But it is not enough to connect to cluster. Basically RedisInsight client will try to connect to all nodes using private addresses like `172.28.2.3:6379` rather than `'localhost:7009`, localhost:7010`, etc. So you should configure you network in a way when you can PING `some_private_ip:port` without errors and RedisInsight will work then.

**Comment by ViktarStarastsenka** [comment]
please reopen this ticket if the question is still relevant
