### ISSUE TITLE
[Bug]:Can't delete or edit existing TLS Certificate

### ISSUE THREAD

**Issue by lordofriver** [RedisInsight/RedisInsight#2456]
How do I delete or edit existing TLS Certificate?
![e245019ea5e674b09b0c8894a8625582](https://github.com/RedisInsight/RedisInsight/assets/33858198/9e71911b-d0a5-4fcb-9132-10d8e91b9aa7)

No edit textarea after select existing one.
Can't find a delete button, it still exist even after a reinstall.

Tried to just add a new one, but Certificate Name repeated.
![db88d483f63fdc712deb498595b67e63](https://github.com/RedisInsight/RedisInsight/assets/33858198/dc22cf9a-ddfb-42d4-8bf8-a0eb1a9b230c)

Maybe I should label this as feature issue.
Is there some cache files that I can delete?

version: MacOs 2.26.0 (11)

**Comment by ViktarStarastsenka** [comment]
hi @lordofriver , currently, there is no option to do so from RedisInsight.
what I can recommend is:
1. open the RedisInsight folder (it is located under your current user, and the folder is usually hidden on MacOS)
2. open the redisinsight.db file
3. go to the "ca_certificate" table
4. make the changes

but avoid using this hack too often because it can cause issues if not done carefully

**Comment by lordofriver** [comment]
> hi @lordofriver , currently, there is no option to do so from RedisInsight. what I can recommend is:
> 
> 1. open the RedisInsight folder (it is located under your current user, and the folder is usually hidden on MacOS)
> 2. open the redisinsight.db file
> 3. go to the "ca_certificate" table
> 4. make the changes
> 
> but avoid using this hack too often because it can cause issues if not done carefully

thanks for your reply, @ViktarStarastsenka. 
I've managed to delete the certificates with the following steps.
```
sqlite3 ~/Library/Containers/com.redis.RedisInsight/Data/.redisinsight-v2/redisinsight.db
// Others who want to try should be careful with this delete sql
// since I just need to delete all, you should use sql that fit your demands
delete from ca_certificate;
.quit
```
As mentioned above, **"avoid using this hack too often because it can cause issues if not done carefully"**.
