### ISSUE TITLE
[Bug]: All text  on screen are selected when clicked on select all option

### ISSUE THREAD

**Issue by The-Quantum-Boy** [RedisInsight/RedisInsight#2501]
In browse section where list of all keys are showing, when i right click on any key it shows option of select all key when i click and select all option then all text on the screen are showing selected. below is screenshot attached for your reference.

![Screenshot 2023-08-21 221401](https://github.com/RedisInsight/RedisInsight/assets/101516983/58085985-2e26-4576-8bd7-8e215ff06ba8)

**Comment by ViktarStarastsenka** [comment]
hi @The-Quantum-Boy , this is not a bug, what you can see is a standard system pop-up, it does not relate to RedisInsight.
can you please describe your use case? what information you'd like to copy?

**Comment by The-Quantum-Boy** [comment]
video is attached after right clicking on key and selecting Select All it is showing all text selected on screen

https://github.com/RedisInsight/RedisInsight/assets/101516983/4fa79e27-5e87-490a-b596-e958e9d3e2ab

**Comment by ViktarStarastsenka** [comment]
@The-Quantum-Boy , the pop-up that you see when right-clicking on the key does not belong to RedisInsight - it is the system pop-up.
if you want to copy key names, you can run the `SCAN "0" "MATCH" "*" "COUNT" "{number_of_key}"` command.

**Comment by The-Quantum-Boy** [comment]
i can select one key and delete it i want to select two or more keys and delete it i dont have checkbox option here to select multiple key and delete.

**Comment by ViktarStarastsenka** [comment]
hi @The-Quantum-Boy , if you would like to delete multiple keys at once, you can use the bulk deletion. To do so, you need to set the filters per key type or key name.

<img width="1445" alt="image" src="https://github.com/RedisInsight/RedisInsight/assets/99594890/47abdde9-e9d4-4aee-9433-249ab559b61e">
