### ISSUE TITLE
[Bug]: RedisInsight crashes with EACCES error if a service named 'api' exists in Kubernetes

### ISSUE THREAD

**Issue by townsendduong** [RedisInsight/RedisInsight#2512]
**Preconditions** (Any important steps we need to know)
A service named `api` already exists in the same Kubernetes namespace where RedisInsight will be deployed.

**Steps to reproduce** (How to reproduce what you found step by step)
Deploy RedisInsight in a Kubernetes pod in the same namespace where a service named `api` already exists. For example, deploy the redis-stack image in a Kubernetes Deployment.
Check the logs of the container.

**Actual behavior** (A short description of what you found)
The Redis server starts successfully, but RedisInsight prints this error:
```
node:internal/errors:465
    ErrorCaptureStackTrace(err);
    ^

Error: listen EACCES: permission denied tcp://10.108.13.33:80
    at Server.setupListenHandle [as _listen2] (node:net:1355:21)
    at listenInCluster (node:net:1420:12)
    at Server.listen (node:net:1519:5)
    at ExpressAdapter.listen (/opt/redis-stack/share/redisinsight/api/node_modules/@nestjs/platform-express/adapters/express-adapter.js:88:32)
    at /opt/redis-stack/share/redisinsight/api/node_modules/@nestjs/core/nest-application.js:180:30
    at new Promise (<anonymous>)
    at NestApplication.listen (/opt/redis-stack/share/redisinsight/api/node_modules/@nestjs/core/nest-application.js:169:16)
    at async bootstrap (/opt/redis-stack/share/redisinsight/api/dist/src/main.js:43:5) {
  code: 'EACCES',
  errno: -13,
  syscall: 'listen',
  address: 'tcp://10.108.13.33:80',
  port: -1
}
```

The IP address referenced is the IP address of the `api` service.

**Expected behavior** (A short description of what you expected to find)
Redis server and RedisInsight start up with no errors.

**Screenshots** (Paste or drag-and-drop a screenshot or a link to a recording)

**Additional context** (Operating system, version of RedisInsight, Redis database version, Redis module version, database type, connection type, logs, or any other information)
This is not a bug. This is a consequence of the [Kubernetes service links](https://kubernetes.io/docs/tutorials/services/connect-applications-service/#accessing-the-service) being injected into the environment variables of the RedisInsight container. In particular, the `API_PORT` service link is interfering with the RedisInsight configuration. A workaround is to disable the service links with `spec.enableServiceLinks=false` in the Kubernetes pod. I'm submitting this because I did not find any existing issue mentioning this error.

**Comment by GnaneshKunal** [comment]
Hey @townsendduong,

`API_PORT` env is used by RedisInsight application in the redis-stack.

https://github.com/redis-stack/redis-stack/blob/94c2603443c5560d08d1c9661ca14da375d488ef/etc/envfiles/insight.docker.env#L2

Since `API_PORT` will already be being used by existing users, would suggest a different name for the api service. Renaming `API_PORT` might not be backward compatible. 


Instead of disabling the service links, a workaround would be to change the name of the service. This way, the `api` service will still be available with a new name. With this new name, the k8s population of port variable will also work without any issues. The new port env variable would be `<new-name>_PORT`.

**Comment by townsendduong** [comment]
@GnaneshKunal The `api` service already exists and has clients, so changing the name would not be a feasible solution. Maybe our engineers could have chosen a different service name, but they weren't expecting to run into conflicts in a namespace dedicated to their own service and its dependent redis server. Redis-stack has no need for the service links to our other services in any case, so it's better for us to disable their injection to avoid unintended misconfiguration like this.
