### ISSUE TITLE
[Feature Request]: Third option to sync the color theme with system in settings.

### ISSUE THREAD

**Issue by nocksock** [RedisInsight/RedisInsight#2515]
**Problem description** 

My system changes from light to dark automatically, and it'd be nice if RedisInsight followed along.

**How often do you encounter this problem**

Basically everyday.

**Alternatives considered** 

(not applicable)

**Additional information** 

https://www.electronjs.org/docs/latest/tutorial/dark-mode

**Comment by ViktarStarastsenka** [comment]
hi @nocksock , this is added with 2.34 (released today). You can find the Color Theme control in the "General" secton of the Settings page.

**Comment by nocksock** [comment]
Amazing! <3 Thanks!
