### ISSUE TITLE
[Bug]: The download button for redis insight tool is not clickable

### ISSUE THREAD

**Issue by srihari-cit** [RedisInsight/RedisInsight#2525]
**Preconditions** (Any important steps we need to know)

**Steps to reproduce** (How to reproduce what you found step by step)

**Actual behavior** (A short description of what you found)

**Expected behavior** (A short description of what you expected to find)

**Screenshots** (Paste or drag-and-drop a screenshot or a link to a recording)

**Additional context** (Operating system, version of RedisInsight, Redis database version, Redis module version, database type, connection type, logs, or any other information)

**Comment by ViktarStarastsenka** [comment]
hi @srihari-cit , the form is fixed, please try now.
