### ISSUE TITLE
[Bug]: Profiler log cannot download

### ISSUE THREAD

**Issue by panapol-p** [RedisInsight/RedisInsight#2533]
**Steps to reproduce** (How to reproduce what you found step by step)
1. try to profiling databases
2. pause and then try to download

**Actual behavior** (A short description of what you found)
in profiling log, download button is not working.
console log show : 401 unauthorized

FYI : i try to modify request header by add x-window-id and then it's work we can fetch log

**Screenshots** (Paste or drag-and-drop a screenshot or a link to a recording)
<img width="1605" alt="image" src="https://github.com/RedisInsight/RedisInsight/assets/34530268/3898d97a-ad8e-477c-994b-aa397eb4772e">
<img width="782" alt="image" src="https://github.com/RedisInsight/RedisInsight/assets/34530268/0c27c137-34b0-4862-9dcf-86c451bc575b">

**Additional context** (Operating system, version of RedisInsight, Redis database version, Redis module version, database type, connection type, logs, or any other information)
OS : mac
RedisInsight : 2.30.0
Redis db : 7.2

**Comment by ViktarStarastsenka** [comment]
@panapol-p , this is fixed with 2.32 (released today).
please re-open the ticket if it is still relevant
