### ISSUE TITLE
[Feature Request]:about the ordering of keys

### ISSUE THREAD

**Issue by ksymmy** [RedisInsight/RedisInsight#2546]
**Problem description** (Describe the problem you would like to solve with this feature request or suggested idea).
The type and name of keys are displayed in no order. Keys with the same prefix are displayed in different positions. When the number of keys increases, it is difficult to view them on the page

**How often do you encounter this problem** (Describe how frequently this problem occurs).
always

**Alternatives considered** (Describe any alternative features or products you've considered).
Consider sorting by key type and key name in ascending order

**Additional information** (Add any other context or details here).

**Comment by ViktarStarastsenka** [comment]
hi @ksymmy , you can sort keys by their names in the Tree view starting from 2.38 (released today).

**Comment by ksymmy** [comment]
Thanks for your reply.发自我的 iPhone在 2023年12月1日，02:28，ViktarStarastsenka ***@***.***> 写道：﻿
Closed #2546 as completed.
