### ISSUE TITLE
[Feature Request]: Fuzzy Search in Redis browser

### ISSUE THREAD

**Issue by hrithik098** [RedisInsight/RedisInsight#2560]
Problem description:
I frequently work with a Redis database containing a substantial number of keys (a couple of millions), which often have long and descriptive names. When searching for specific keys, even a small typo can yield zero results, leading to time-consuming and frustrating debugging efforts.

How often do you encounter this problem:
Regularly.  I need to search for and inspect keys in our Redis database quite frequently. The issue arises consistently due to the large number of keys and the potential for minor spelling errors.

**Comment by ViktarStarastsenka** [comment]
hi @hrithik098 , do you use filters per key name (screen 1 attached) or search (screen 2 attached)?
if you use filtering, there is an option to use global patterns, but in this case RedisInsight will scan only per 10,000 keys.

<img width="994" alt="image" src="https://github.com/RedisInsight/RedisInsight/assets/99594890/bee55ae9-87f2-4961-9355-92004f94a6f7">
<img width="1034" alt="image" src="https://github.com/RedisInsight/RedisInsight/assets/99594890/ce03f0d7-9a37-473a-98a9-cdf27a8ce687">
