### ISSUE TITLE
[Bug]:

### ISSUE THREAD

**Issue by mohamed-fazil-saleem** [RedisInsight/RedisInsight#2561]
HI,
I made a redis insight docker image by cloning the version 2.30.0 branch, then I used this yaml file to deploy it on my local k8s  cluster. I then accessed the ui and set the redis cluster information on the ui.
```kind: Deployment
apiVersion: apps/v1
metadata:
  name: redisinsight
  namespace: redis
  labels:
    app: redisinsight
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redisinsight
  template:
    metadata:
      labels:
        app: redisinsight
    spec:
      volumes:
        - name: db
          persistentVolumeClaim:
            claimName: redisinsight-pv-claim
      initContainers:
        - name: init
          image: busybox
          command:
            - /bin/sh
            - '-c'
            - |
              chown -R 1001 /db
          resources: {}
          volumeMounts:
            - name: db
              mountPath: /db
          imagePullPolicy: Always
      containers:
        - name: redisinsight
          image: redisinsight:redis-2-30-0
          ports:
            - containerPort: 5000
              protocol: TCP
          resources: {}
          volumeMounts:
            - name: db
              mountPath: /db
          imagePullPolicy: IfNotPresent
          securityContext:
            capabilities:
              add:
                - IPC_LOCK
  ```

however, when the pod restarts. It is losing all the configuration information, so I have to start from scratch. 
However, when I used the same deployment yaml and `redislabs/redisinsight:latest` docker image to deploy Redis Insight version 1.14.0, when the pod is restarted. redis insight is not losing data.
i also tried adding RIHOMEDIR=/db env too still same issue.

**Comment by ViktarStarastsenka** [comment]
@mohamed-fazil-saleem , please try using `APP_FOLDER_ABSOLUTE_PATH=/db` instead of `RIHOMEDIR=/db`

**Comment by mohamed-fazil-saleem** [comment]
@ViktarStarastsenka , thanks for the help setting APP_FOLDER_ABSOLUTE_PATH=/db env fixed the issue for me
