### ISSUE TITLE
[Bug]: Download Site Malfunction?

### ISSUE THREAD

**Issue by edelgado** [RedisInsight/RedisInsight#2577]
**Preconditions** (Any important steps we need to know)
None

**Steps to reproduce** (How to reproduce what you found step by step)
Visit https://redis.com/redis-enterprise/redis-insight/

**Actual behavior** (A short description of what you found)
The site looks visually strange (somewhat of a mobile version is rendered), and the for to download RedisInsight is not working properly. A `There has been a critical error on this website.` message is displayed at near the bottom of the page.

**Expected behavior** (A short description of what you expected to find)
Ability to browse to the site and download RedisInsight

**Screenshots** (Paste or drag-and-drop a screenshot or a link to a recording)
<img width="716" alt="image" src="https://github.com/RedisInsight/RedisInsight/assets/143209/d5cb0a21-8c8a-4010-b86d-d99d6fc0694b">

**Additional context** (Operating system, version of RedisInsight, Redis database version, Redis module version, database type, connection type, logs, or any other information)

**Comment by JonasMS** [comment]
I'm getting the same behavior.

**Comment by ViktarStarastsenka** [comment]
hi, @edelgado , @JonasMS , thank you for reporting the issue, it should be fixed by now.
