### ISSUE TITLE
[Feature Request]: Official RedisInsight v2 Image/Derestrict bundling with redis-stack

### ISSUE THREAD

**Issue by eric-musliner** [RedisInsight/RedisInsight#2589]
**Problem description** (Describe the problem you would like to solve with this feature request or suggested idea).
There is currently no official redisinsight v2 image provided by redis. The best we have is the one bundled with redis-stack. However, it is impossible to change connection settings for the db information from localhost:6379. Furthermore, it won't let you add more than one db connection. It's been highly restricted for some reason.

**How often do you encounter this problem** (Describe how frequently this problem occurs).
All the time

**Alternatives considered** (Describe any alternative features or products you've considered).
https://github.com/oblakstudio/redisinsight This project has created exactly what Redis should put out, and it would be awesome to have this functionality from official channels

**Additional information** (Add any other context or details here).

**Comment by ViktarStarastsenka** [comment]
hi, there is a relevant ticket:
https://github.com/RedisInsight/RedisInsight/issues/519

**Comment by seebeen** [comment]
@eric-musliner 
For some reason they're completely ignoring the issue and they act like my comments don't exist 🤔

**Comment by ViktarStarastsenka** [comment]
@seebeen, here is the status for the docker container - https://github.com/RedisInsight/RedisInsight/issues/519#issuecomment-1682650159
I can't provide anything new at the moment
