### ISSUE TITLE
[Bug]:Language settings

### ISSUE THREAD

**Issue by niubg** [RedisInsight/RedisInsight#2590]
The latest version does not support language selection? For example, Chinese, Japanese, etc. No language selection related functions can be seen in the settings now

**Comment by ViktarStarastsenka** [comment]
hi, there is a relevant ticket:
https://github.com/RedisInsight/RedisInsight/issues/1317

**Comment by ViktarStarastsenka** [comment]
but currently, RedisInsight supports only English
