### ISSUE TITLE
[Bug]: list view shows less results than tree view

### ISSUE THREAD

**Issue by redochka** [RedisInsight/RedisInsight#2618]
**Preconditions** (Any important steps we need to know)

**Steps to reproduce** (How to reproduce what you found step by step)
Enter a search term. Ex: `*tower*`

**Actual behavior** (A short description of what you found)
List view shows 2 records out of 8 (bug). Tree view shows 8 records (good)

**Expected behavior** (A short description of what you expected to find)
it should show 8 records.

**Screenshots** (Paste or drag-and-drop a screenshot or a link to a recording)

![ksnip_20230922-094406](https://github.com/RedisInsight/RedisInsight/assets/263297/2d306f42-e063-4f53-8829-5330f5a07b77)
![ksnip_20230922-094408](https://github.com/RedisInsight/RedisInsight/assets/263297/5a365e9f-7443-440b-ac59-1e88b8eee5c8)

**Additional context** (Operating system, version of RedisInsight, Redis database version, Redis module version, database type, connection type, logs, or any other information)

**Comment by ViktarStarastsenka** [comment]
hi @redochka, please try RedisInsight 2.36 (released today)
there you’ll have the “Scan more” button available to load more keys
re-open the ticket if the issue is still relevant.
