### ISSUE TITLE
[Bug]: Inquiries about Redis Insight's CPU usage calculation method

### ISSUE THREAD

**Issue by sdYoo** [RedisInsight/RedisInsight#2620]
**Preconditions** (Any important steps we need to know)
I am using redis-cluster on K8s.
I would like to inquire because there is a difference between the CPU usage rate of the redis-clster pod and the CPU usage rate seen in redisinsight.
I would like to know how the CPU usage shown in redisinsight is calculated and displayed.

**Steps to reproduce** (How to reproduce what you found step by step)
1) pod cpu usage 
It is calculated based on pod usage as shown below.
Calculated with Prometheus' container_cpu_usage_seconds_total()
---
max by (pod) (sum(rate(container_cpu_usage_seconds_total{pod=~"redis-cluster-0"}[5m])) / sum(kube_pod_container_resource_limits{pod=~"redis-cluster-0", resource="cpu"})) * 100
---

2) redisinsight
I checked the CPU usage at the top of the redisinsight UI.

**Actual behavior** (A short description of what you found)
There is a difference between the CPU usage of the redis-cluster pod and the CPU usage shown in redisinsight.

**Expected behavior** (A short description of what you expected to find)

**Screenshots** (Paste or drag-and-drop a screenshot or a link to a recording)

**Additional context** (Operating system, version of RedisInsight, Redis database version, Redis module version, database type, connection type, logs, or any other information)

**Comment by GnaneshKunal** [comment]
Hey @sdYoo,

Redis cluster POD's CPU usage and Redis's CPU info might be different.

In case of RedisInsight, the CPU info comes from the redis's `INFO` command.

```
# CPU
used_cpu_sys:145.375353
used_cpu_user:118.356843
used_cpu_sys_children:0.000000
used_cpu_user_children:0.000000
used_cpu_sys_main_thread:143.273311
used_cpu_user_main_thread:116.780131
```


But in case the the k8s pod, you'll be getting the CPU usage of the container itself  and the container might be running additional services as well.

**Comment by sdYoo** [comment]
@GnaneshKunal hi!
Thank you for your kind reply.

I have additional inquiries.
I have configured a redis-cluster with a total of 6 nodes(master3, replica3) running.
Therefore, 6 CPU usage rates should be shown for each node, but only 1 CPU is shown in redisinsight.

I would like to know why only 1 CPU is shown and what it means.

**Comment by GnaneshKunal** [comment]
@sdYoo 

I see all the instances in the overview page though.
![image](https://github.com/RedisInsight/RedisInsight/assets/20211167/d6060370-2dae-4089-b20e-0ee34a1152f3)


Also regarding INFO just showing one CPU info, if you are using `redis-cli`, you'll have to run `INFO` on each and every node manually to get the INFO mertrics of those nodes.

You can also use RedisInsight v1's CLI tool to run the command on all the nodes. Just visit the CLI tool and select "Run against ALL NODES" and execute the INFO command.
