### ISSUE TITLE
[Bug]:Memory analysis failing for particular redis cluster

### ISSUE THREAD

**Issue by mayank14798** [RedisInsight/RedisInsight#2628]
**Preconditions** (Any important steps we need to know)

**Steps to reproduce** (Export backup file to object storage(s3) , then use that rdb file to perform offline memory analysis on your cluster)

**Actual behavior** (On performing memory analysis on one of the clusters the analysis starts and the rdb file get's downloaded, but after that it abruptly fails and shows memory analysis fail error in redis-insight ui , even though it works for other clusters and rdb files)

**Expected behavior** (Expected the memory analysis to work as it is for other redis clusters)

**Screenshots** (
<img width="997" alt="image" src="https://github.com/RedisInsight/RedisInsight/assets/39562411/9bc204b4-176b-47fd-bcdb-b07028b50373">
)

**Additional context** (Our redis insight is working on docker , version- 1.14.0 )
This is happening with only one cluster and the rdb files of that cluster
in other clusters the memory analysis is working so there's no permission or access related issue.

Thanks

**Comment by mayank14798** [comment]
Any Updates

**Comment by mayank14798** [comment]
- How can i set the RILOGLEVEL?
- It is a AWS Elasticache redis cluster.
- The memory analysis works for other clusters.

**Comment by GnaneshKunal** [comment]
Hey @mayank14798,

https://docs.redis.com/latest/ri/installing/configurations/#riloglevel

**Comment by mayank14798** [comment]
[redisinsight.log](https://github.com/RedisInsight/RedisInsight/files/12848752/redisinsight.log)
Here is the log entry at the time i start memory anlysis and then the pod terminates after the rdb file is downloaded.

**Comment by mayank14798** [comment]
Hi i checked the version of the redis clusters for whom memory analysis is working and not working.
For the working one's enfine version is 6.2.6
For the one's where it's not working it's 6.0.5
is redis insight not supporting this version?

**Comment by GnaneshKunal** [comment]
@mayank14798, the issue from the logs doesn't seem to be due to memory analysis, though. Can you maybe add this instance with a new name and try out the analysis?

And thank you for the version, I'll check if the memory analysis works fine for the version you mentioned.

**Comment by GnaneshKunal** [comment]
@mayank14798, I tried running Memory Analysis on AWS ElastiCache version 6.0.5. Memory analysis runs fine without crashing or failing. The issue seems to be with the installation or the instance. Please try re-adding the instance with a new name and run the memory analysis.

**Comment by mayank14798** [comment]
It is a production instance/cluster can't add or readd 
can't understand why is it working for all other clusters and not for only this particular 
can we get support on call/meet to further debug this?
Help would be much much appreciated
Thanks

**Comment by mayank14798** [comment]
Even launched a replica of the instance with different name and tried the memory analysis 
Still failing

**Comment by GnaneshKunal** [comment]
@mayank14798 

Can you send the new logs? The old logs doesn't relate a failure in memory analysis but an invalid installation. Maybe there was an issue with the long-running redisinsight. Can you try to run it on a new redisinsight installed on a fresh EC2 machine?

**Comment by ViktarStarastsenka** [comment]
@mayank14798 , please re-open the ticket and attach new logs if the issue still persists on a new EC2 instance.
