### ISSUE TITLE
Failed to load RediSearch indices

### ISSUE THREAD

**Issue by deadmandrive** [RedisInsight/RedisInsight#267]
Hi. I've problem with redisinsight when i try to use redisearch module.
after install and load module in redis cluster. I click redisearch in redisinsight page and got "Failed to load RediSearch indices".
Anyway i can solve this problem?

redis 6.2.6
redisinsight 1.10.1
rediseach 2.0.0

Thank you.

**Comment by GnaneshKunal** [comment]
Hey @deadmandrive, RediSearch on RedisCluster is currently [not supported](https://oss.redis.com/redisearch/#cluster_support) on OSS Redis. While the module might get installed, the execution of commands are inconsistent and not cluster aware.

**Comment by deadmandrive** [comment]
@GnaneshKunal Thank you for reply. I will tell my Dev team.
