### ISSUE TITLE
[Bug]:SSH is unsupported for cluster databases

### ISSUE THREAD

**Issue by sakpinar1** [RedisInsight/RedisInsight#2670]
**Preconditions** (Any important steps we need to know)
We aim to connect Amazon MemoryDB for Redis via ssh tunnelling.

**Steps to reproduce** (How to reproduce what you found step by step)

**ADD REDIS DATABASE >** 

- Entered host and port (6379) of Redis cluster in AWS and DB alias
- Selected 'Use SSH Tunnel' option
- Entered host, port (22) and user name of the bastion host
- Selected 'Private Key' option
- Copied th private key pem content of the bastion host to the Private Key box
- Pressed 'Add Redis Database Button'

**Actual behavior** (A short description of what you found)
Error box appeared with content 'SSH is unsupported for cluster databases'.

**Expected behavior** (A short description of what you expected to find)
Successfull connection

**Screenshots** (Paste or drag-and-drop a screenshot or a link to a recording)
![image](https://github.com/RedisInsight/RedisInsight/assets/147488786/5990a96b-beb3-4d2a-8239-084129848667)

**Additional context** (Operating system, version of RedisInsight, Redis database version, Redis module version, database type, connection type, logs, or any other information)

**Comment by ViktarStarastsenka** [comment]
hi, here is the same ticket - https://github.com/RedisInsight/RedisInsight/issues/1831
