### ISSUE TITLE
[Feature Request]:Restricting redis-insight access

### ISSUE THREAD

**Issue by mayank14798** [RedisInsight/RedisInsight#2680]
**Problem description** (A developer mistakenly ran the flushdb command on of our prod redis clusters, and other dangerous commands get ran frequently).

**How often do you encounter this problem** (Quite frequently).

**Alternatives considered** Putting redis insight behind vpn access).

**Additional information** (So we're trying to restrict access to redis-insight , one way we have restricted is by putting it behind a vpn service so only our company employess can access , but some employees have mistakenly ran dangerous cli commands on the prod clusters in the past, i want to know if there's a way to restrict redis insight to only specific users or a way to restrict cli access from redis insigt)

Please help us with this as soon as possible , this has become a burning issue

Thanks and regards 
Mayank Singh

**Comment by ViktarStarastsenka** [comment]
hi @mayank14798 , you can restrict access to Redis commands and keys using Redis ACL - https://redis.io/docs/management/security/acl/

**Comment by mayank14798** [comment]
Any other way to restrict the redis insight web ui 
based on roles etc?

**Comment by ViktarStarastsenka** [comment]
if you use a docker container of RedisInsight v1 - https://hub.docker.com/r/redislabs/redisinsight (currently, there is a docker container for only RedisInsight v1, which reached its EOL and is not supported anymore), you can set up a reverse proxy and integrate it with LDAP, here is an example - https://github.com/RedisInsight/RedisInsight-reverse-proxy/.
But RedisInsight itself does not have any specific roll-based mechanism.
