### ISSUE TITLE
[Feature Request]: Add I18N

### ISSUE THREAD

**Issue by Ningzetao** [RedisInsight/RedisInsight#2695]
**Problem description** (Describe the problem you would like to solve with this feature request or suggested idea).
App Add I18N

**How often do you encounter this problem** (Describe how frequently this problem occurs).

**Alternatives considered** (Describe any alternative features or products you've considered).

**Additional information** (Add any other context or details here).

**Comment by ViktarStarastsenka** [comment]
here is a ticket to support multiple languages: https://github.com/RedisInsight/RedisInsight/issues/1317
