### ISSUE TITLE
[Feature Request]: Import/Export option for databases

### ISSUE THREAD

**Issue by deeptechs** [RedisInsight/RedisInsight#272]
**Problem description** 
We need to share/deliver our **many** Redis database connection configurations. It is very painful to add all databases fields for every developer's machines. The problem is lack of import/export option for databases.

**How often do you encounter this problem** 
When we need to share Redis configurations for each team member.

**Alternatives considered** 
I don't want to use non-official, non-defacto software. I always keep going with the official ones like PgAdmin for RDS. As I understand RedisInsight will be a well supported app for Redis world.

**Additional information** 
Just Import/Export option for databases :)

**Comment by ViktarStarastsenka** [comment]
Hi @deeptechs , thanks for raising this feature, we have plans for it, but not in the nearest releases.

**Comment by hypo-thesis** [comment]
This would be a really great feature. Makes the app almost complete in a sense.

**Comment by ViktarStarastsenka** [comment]
hello @deeptechs , @hypo-thesis , we will deliver this feature in December.
Could you please describe your use cases?
Will import/export database connections (host, port, username, password, but no certificates) be enough for you?

**Comment by melt7777** [comment]
Hello, I have configured my databases in the RedisInsights-V2 app for Mac. However, I wanted to have an easy way for my team to set it up too. 

Here are my use cases for the above feature request:

- Take a backup of the RedisInsights databases and connection details to a file for my own backup purpose, moving laptops, etc. Currently with the details stored in the keychain, the file cannot be used outside of the current laptop.
- Share the export file to my teammates who also support these databases, so they can import quickly and be all configured and ready to go.  


Note: I would like to have option to include or exclude passwords. That way we could share the file on a team share without exposing the passwords. 

> *Thanks, Simon P, for your support*

**Comment by ViktarStarastsenka** [comment]
hi @melt7777 , the feature to import database connections is already available, export database connections will be added in late February with 2.20, and you will be able to configure whether to export passwords and certificate keys or not.

**Comment by ViktarStarastsenka** [comment]
export database connections has been added with RedisInsight 2.20 (released today).

**Comment by gyucheonheo** [comment]
@ViktarStarastsenka Could you explain where I can find `export database connections`? I'm using RedisInsight 2.34.0 in MacOS.

**Comment by ViktarStarastsenka** [comment]
@gyucheonheo , you can select databases using checkboxes, and the control to export them will appear.

**Comment by gyucheonheo** [comment]
@ViktarStarastsenka Never thought of selecting DBs..🤦🏻‍♂️ Appreciated for very quick responses
