### ISSUE TITLE
[Feature Request]: Need official Docker image of RedisInsight v2.

### ISSUE THREAD

**Issue by apatozi** [RedisInsight/RedisInsight#2720]
**Problem description** (Describe the problem you would like to solve with this feature request or suggested idea).
Since released the v2 of redisinsight there is no docker image in the official redislabs on dockerhub. The latest official redisinsight image is 1.14. 

**Alternatives considered** (Describe any alternative features or products you've considered).
We can always build it ourselves but an official image in the official repo is always the best thing to have.

**Comment by ViktarStarastsenka** [comment]
hi, there is a ticket with updates regarding docker image: https://github.com/RedisInsight/RedisInsight/issues/519

**Comment by seebeen** [comment]
@apatozi https://hub.docker.com/r/oblakstudio/redisinsight
