### ISSUE TITLE
[Feature Request]:能否提供中文

### ISSUE THREAD

**Issue by yygyyds** [RedisInsight/RedisInsight#2722]
**Problem description** (Describe the problem you would like to solve with this feature request or suggested idea).

**How often do you encounter this problem** (Describe how frequently this problem occurs).

**Alternatives considered** (Describe any alternative features or products you've considered).

**Additional information** (Add any other context or details here).

**Comment by ViktarStarastsenka** [comment]
Hi, the multi-language support is not currently included in the upcoming releases.
I'll provide updates in this ticket: https://github.com/RedisInsight/RedisInsight/issues/1317
