### ISSUE TITLE
[Question]: why I can't add another redis server

### ISSUE THREAD

**Issue by neozhu** [RedisInsight/RedisInsight#2729]
<img width="665" alt="image" src="https://github.com/RedisInsight/RedisInsight/assets/1549611/8c03d89f-3fe3-459f-a437-dcab1b13538f">

Hi! I'm using Docker for the first time. I ran `docker run -d --name redis-stack -p 6379:6379 -p 8001:8001 redis/redis-stack:latest` to deploy the redis-stack server and RedisInsight. However, I'm having trouble adding other Redis servers. Can someone help me out?

**Comment by ViktarStarastsenka** [comment]
hi, RedisInsight bundled with the Redis Stack docker image can connect only to this Redis Stack database, this is a limitation of this image.
Standalone RedisInsight docker image will be delivered somewhere around January.

**Comment by neozhu** [comment]
> hi, RedisInsight bundled with the Redis Stack docker image can connect only to this Redis Stack database, this is a limitation of this image. Standalone RedisInsight docker image will be delivered somewhere around January.

I understand. Thank you.
