### ISSUE TITLE
[Bug]: Can't add cluster database using IPv6

### ISSUE THREAD

**Issue by yadav-sonu** [RedisInsight/RedisInsight#2754]
**Preconditions** 
Create a Redis cluster using IPv6 only - 3 Master Nodes with Authentication.

**Steps to reproduce**
1. Ensure Cluster is UP and Running
2. Try Adding this cluster to RedisInsight using one of IPv6 host and port
3. Upon clicking Add Redis Database button, user will be able to see same error as attached in screenshot

**Actual behavior** 
1. Unable to add db

**Expected behavior** (A short description of what you expected to find)
1. Cluster DB should have been added as it works for IPv4

**Screenshots** 

<img width="709" alt="image" src="https://github.com/RedisInsight/RedisInsight/assets/67704100/3503281c-aa64-4fe3-bd5e-c750d605f84c">

**Additional context** 
RedisInsight version 1.13.1.
RHEL 7

**Comment by ViktarStarastsenka** [comment]
@yadav-sonu , RedisInsight v1 reached its end of life and is no longer supported.
Please try the latest Redis Insight and re-open the issue if it reproduces.
