### ISSUE TITLE
[Bug]: Having a parenthesis in Windows username crashes RedisInsight

### ISSUE THREAD

**Issue by edokan** [RedisInsight/RedisInsight#2763]
**Preconditions** (Any important steps we need to know)

**Steps to reproduce** (How to reproduce what you found step by step)
* Have a username that contains `(` in it. The company I support uses `Name Surname (Role)` format. User profile directory is created by Windows like `C:\Users\LongNameSurname(Role`, limiting the user name to 20 characters for archaic reasons.
* Try to run RedisInsight

**Actual behavior** (A short description of what you found)
Throws an error saying Invalid Regular Expression: Unterminated Group
`/C:\Users\LongNameSurname(Role\.redisinsight-v2\logs\redisinsight-errors-2023-11-13.log/`

**Expected behavior** (A short description of what you expected to find)
* Show main screen

**Screenshots** (Paste or drag-and-drop a screenshot or a link to a recording)
![image](https://github.com/RedisInsight/RedisInsight/assets/1482410/42fdd0db-710a-407c-9e29-ab1b76ac5284)

**Additional context** (Operating system, version of RedisInsight, Redis database version, Redis module version, database type, connection type, logs, or any other information)
* RedisInsight-v2 v2.36.0.30218
* Windows 11

**Comment by ViktarStarastsenka** [comment]
@edokan , thank you for reporting this issue.
does the username include any other special characters? Tried with the username pattern you mentioned, and couldn't reproduce the issue

**Comment by edokan** [comment]
@ViktarStarastsenka nope. Beside `(` no other character. It probably tried to write an error to the log and then this one occurred.

**Comment by ViktarStarastsenka** [comment]
@edokan , please try with 2.38 (released today).
re-open the ticket if the issue still reproduces.
