### ISSUE TITLE
[Feature Request]: Don't clear query string from workbench query tool

### ISSUE THREAD

**Issue by tylerhutcherson** [RedisInsight/RedisInsight#2779]
**Problem description** (Describe the problem you would like to solve with this feature request or suggested idea).

Don't clear out the query from the workbench tool right after you execute it.

**How often do you encounter this problem** (Describe how frequently this problem occurs).

Daily.

**Alternatives considered** (Describe any alternative features or products you've considered).

I end up using the copy and paste tool to recopy the same command that was just run, and paste it back into the portal.

**Additional information** (Add any other context or details here).

This would dramatically increase usability and speed of development!

**Comment by zalenskiSofteq** [comment]
Hi @tylerhutcherson !
In the RedisInsight settings, you can turn off clearing out the query from the workbench tool
<img width="973" alt="image" src="https://github.com/RedisInsight/RedisInsight/assets/63463140/60738e14-11a7-4369-a75a-0338b8b13924">

**Comment by tylerhutcherson** [comment]
Amazing thank you!
