### ISSUE TITLE
[Bug]: Editing an exisiting value of a hash key changes the new one on refresh

### ISSUE THREAD

**Issue by poke646** [RedisInsight/RedisInsight#2791]
When editing a row in a hashkey, after clicking refresh the key value is replaced with the previously edited key content when the new key was added during the refresh. 

1. Editing a key that exists
![obraz](https://github.com/RedisInsight/RedisInsight/assets/595844/be3a8cc9-e226-4c72-a14b-bdc586401fde)

2. Clicking refresh - the new key has the value of a previous editing
![obraz](https://github.com/RedisInsight/RedisInsight/assets/595844/0e3f3a81-feeb-4185-9f25-44e56d99dafd)

Then you can accidentaly edit wrong key and save it.

**Comment by ViktarStarastsenka** [comment]
hi @poke646 , thank you for reporting this
tried to reproduce it and didn't manage to. Can you please describe the steps in detail?

**Comment by poke646** [comment]
https://github.com/RedisInsight/RedisInsight/assets/595844/cf70b7b5-b06f-4946-a51a-f32b41a1d1b0

Added sample screen recording.

**Comment by ViktarStarastsenka** [comment]
@poke646 , thank you, we'll look into this issue.

**Comment by ViktarStarastsenka** [comment]
hi @poke646 , we disabled an option to refresh values while editing them to avoid unintentional data changes.
Thank you for reporting this.
