### ISSUE TITLE
[Bug]: Field keys for [hash] datatype rendered incorrectly for msgpack

### ISSUE THREAD

**Issue by nightwolfz** [RedisInsight/RedisInsight#2798]
**Preconditions** (Any important steps we need to know)
N/A

**Steps to reproduce** (How to reproduce what you found step by step)
Insert numeric fields and chose msgpack renderer.

**Actual behavior** (A short description of what you found)
![image](https://github.com/RedisInsight/RedisInsight/assets/805022/c4790a6a-dca5-458f-8fac-eda449ded2ea)

**Expected behavior** (A short description of what you expected to find)
![image](https://github.com/RedisInsight/RedisInsight/assets/805022/9450f8ce-917a-4ec2-8def-d6cbcbaa553a)

**Screenshots** (Paste or drag-and-drop a screenshot or a link to a recording)
![image](https://github.com/RedisInsight/RedisInsight/assets/805022/fec0dcbb-5f96-48e2-b15f-f31000b6cfa6)

**Additional context** (Operating system, version of RedisInsight, Redis database version, Redis module version, database type, connection type, logs, or any other information)

**Comment by ViktarStarastsenka** [comment]
hi @nightwolfz , please provide more details about your expectations.

**Comment by nightwolfz** [comment]
@ViktarStarastsenka 

Whats showing up as 53, should show 5 .
49 as 1.
51 as 3.

I have no idea why the proper integers are not showing for some keys.  The blue ones are not correct.

**Comment by nightwolfz** [comment]
@ViktarStarastsenka 

OK I finally understand the issue,  my values are msgpack encoded but my fields are not. I suppose redis insight doesnt handle this scenario?

**Comment by ViktarStarastsenka** [comment]
hi @nightwolfz , yes, currently, RedisInsight applies MessagePack to both fields and values

**Comment by nightwolfz** [comment]
Well, no big deal I guess. It got me confused though. Closing the isssue...
