### ISSUE TITLE
[Feature Request]: Several optional installation instructions

### ISSUE THREAD

**Issue by gowizzard** [RedisInsight/RedisInsight#2842]
I just wanted to install RedisInsight on Arch Linux and unfortunately you currently only offer the AppImage or the Debian package. Sure, you can use the AppImage, but many would certainly be happy to have a .tar file with which they can install the project directly.

Did I just not find the option, or do you not offer it at all?

Thanks in advance!

**Comment by gowizzard** [comment]
@ViktarStarastsenka, all right, then I know for now. Then I will first build it from source or use the AppImage.

**Comment by gowizzard** [comment]
@ViktarStarastsenka Hi, is there a reason why the links are no longer accessible?

**Comment by ViktarStarastsenka** [comment]
hi @gowizzard , starting with 2.42 we do not build `RedisInsight-app-linux.x86_64.tar.gz`, the other 2 exist.
how important is this for you?
as an existing alternative, I can suggest using RedisInsight on Docker - https://hub.docker.com/r/redis/redisinsight
or you can use the previous version - https://download.redisinsight.redis.com/releases/2.40.0/redisstack/RedisInsight-app-linux.x86_64.tar.gz

**Comment by gowizzard** [comment]
Hi @ViktarStarastsenka, I have only built a small installation script for my computer, which downloads the .tar.gz directly, and stores it in the correct location etc. But then I will use https://download.redisinsight.redis.com/latest/redisstack/RedisInsight-app-darwin.x64.tar.gz in the future. Thanks for the help!
