### ISSUE TITLE
[Feature Request]: RedisInsight Copy Previous Command 

### ISSUE THREAD

**Issue by JoeChizmasTCG** [RedisInsight/RedisInsight#2858]
I'm using RedisInsight 2.38.0 on a Windows OS. 

It would be _extremely helpful_ to add a new button to the Workbench window such that we could COPY a given command either into the clipboard, or into a new command box such that we can reuse the command, after editing it. 

Currently, you have to go to a prior command, and select/highlight your previous command, right click/copy to clipboard, move the mouse to the new command line, and then paste the command. 

Your programmers could do this for us with a new button here: 
![image](https://github.com/RedisInsight/RedisInsight/assets/101277926/3c76c166-eb47-462e-bb98-e835acb03583)

It would be very helpful to just copy to clipboard - we can paste it ourselves if you don't wish to consider the automatic paste action.

Thank you for considering. I reuse commands all the time to save typing!

**Comment by ViktarStarastsenka** [comment]
also, if you usually run only one command, I recommend you disable the "Group Results" option, in this case, you'll be able to see visualizations of command results for several commands (e.g. Search and Query, TimeSeries, etc.)
<img width="871" alt="image" src="https://github.com/RedisInsight/RedisInsight/assets/99594890/3b92af1a-4e45-42b8-a665-6ed122a9e069">
