### ISSUE TITLE
[Feature Request]: Redis Insight Memory Analysis not working

### ISSUE THREAD

**Issue by jerfinj** [RedisInsight/RedisInsight#2877]
When trying to perform memory analysis(Online Mode) in our redis cluster through redis insight, it is failing with error.

<img width="1436" alt="Redis" src="https://github.com/RedisInsight/RedisInsight/assets/75537402/1ab27c28-6c6a-448c-b81c-eebac105d924">

**Comment by ViktarStarastsenka** [comment]
@jerfinj , please attach logs, you can find them:

Docker: In the /db/ directory inside the container.
Mac: In the /Users/<your-username>/.redisinsight directory.
Windows: In the C:\Users\<your-username>\.redisinsight directory.
Linux: In the /home/<your-username>/.redisinsight directory.

**Comment by jerfinj** [comment]
[Uploading redisinsight.log…]()

**Comment by jerfinj** [comment]
[redisinsight.log](https://github.com/RedisInsight/RedisInsight/files/13712786/redisinsight.log)

**Comment by jerfinj** [comment]
Yeah @GnaneshKunal Our redis-cluster setup is running in kubernetes.We will connect it through its hostname in redis insight

**Comment by GnaneshKunal** [comment]
Can you provide us more about your setup? Need to understand the redis config

**Comment by GnaneshKunal** [comment]
@jerfinj,

Does the redis.conf have this config set?

```
cluster-preferred-endpoint-type hostname
```

**Comment by jerfinj** [comment]
yes @GnaneshKunal redis.conf has this config.

**Comment by GnaneshKunal** [comment]
Hey @jerfinj, we currently don't have support for hostname for the online memory analysis level. You can still do the online analysis though.

Support exists only for `cluster-preferred-endpoint-type` is set to `ip`.

**Comment by jerfinj** [comment]
Where do the rdb dump to be imported for offline analysis? @GnaneshKunal

**Comment by ViktarStarastsenka** [comment]
@jerfinj , you need to select the "offline analysis" option, and then specify a path to the rdb file either in your file system or S3

<img width="595" alt="image" src="https://github.com/RedisInsight/RedisInsight/assets/99594890/37762bf9-df32-4fea-aeee-e04a191f8225">
<img width="602" alt="image" src="https://github.com/RedisInsight/RedisInsight/assets/99594890/828591a8-1dd7-4c9f-bbb4-86425ef8dacc">

**Comment by jerfinj** [comment]
Yeah @ViktarStarastsenka Where should we place the rdb file within redis-insight container or point the rdb path to local machine rdb file/folder?

**Comment by ViktarStarastsenka** [comment]
@jerfinj , place it within the container

**Comment by ViktarStarastsenka** [comment]
please re-open the ticket if it is still relevant
