### ISSUE TITLE
[Bug]: Can no longer connect to Database from RedisInsight running on MacBook

### ISSUE THREAD

**Issue by djptek** [RedisInsight/RedisInsight#2889]
**Preconditions** 
- RedisInsight was previously able to connect to the Database
- The Database has a password
- RedisInsight is running on MacOS

**Steps to reproduce**
- Try to connect to a database using a previously valid connection
- Try to connect using `redis-cli` from command line with exact same credentials 

**Actual behavior** (A short description of what you found)
- Command line connects successfully
- RedisInsight does not connect and there is be a red-pop up in the corner saying can't connect etc.

**Expected behavior** (A short description of what you expected to find)
- Ideally RedisInsight would connect

**Screenshots** (Paste or drag-and-drop a screenshot or a link to a recording)
- TBC (will capture next time)

**Additional context** 
- Operating system: MacOS

**Comment by djptek** [comment]
MacOS updates may invalidate the Keystore, where the password is stored for this OS

Solution: replace the password in the RedisInsight edit database connection dialog, try to connect again, should work

**Comment by ViktarStarastsenka** [comment]
just a note: not the password stored, but encryption keys to decrypt the password.
