### ISSUE TITLE
[Feature Request]:Multilingual setup

### ISSUE THREAD

**Issue by 449134904** [RedisInsight/RedisInsight#2912]
I see zh-CN.pak in the C:\Program Files\RedisInsight\locales directory, does that mean I can set up a Chinese interface

**Comment by ViktarStarastsenka** [comment]
hi @449134904 , currently, RedisInsight supports only English.
Any updates on additional languages will be posted in this ticket - https://github.com/RedisInsight/RedisInsight/issues/1317

**Comment by 449134904** [comment]
> 嗨，目前，RedisInsight 仅支持英文。有关其他语言的任何更新都将发布在此票证中 - #1317



> hi @449134904 , currently, RedisInsight supports only English. Any updates on additional languages will be posted in this ticket - #1317

So what's this file for? I thought it was multilingual

**Comment by ViktarStarastsenka** [comment]
looks like this is a standard Electron file
