### ISSUE TITLE
[Bug]: When using the monitor command, it may cause a white screen on the program interface

### ISSUE THREAD

**Issue by freeeverett** [RedisInsight/RedisInsight#2915]
When I use the monitor command in Workbench, it may cause the program page to appear white and the console to print error messages. 

I used two data sources, only one of which experienced this situation, while the other displayed the results normally, and there was no difference between the two data sources except for the amount of data

RedisInsight version: 2.40.0 (2.40.0.100657)
os: Mac mini M2
redis: 6.0.0 (Linux)

**Comment by freeeverett** [comment]
![Screenshot](https://github.com/RedisInsight/RedisInsight/assets/54989739/31a3adea-b6c8-49cb-b73f-6bfc7b5288a6)

**Comment by ViktarStarastsenka** [comment]
hi @freeeverett , can you share the exact steps on how you ran the `MONITOR` command in Workbench?
currently, this command is not supported in Workbench

<img width="1070" alt="image" src="https://github.com/RedisInsight/RedisInsight/assets/99594890/0d15e6b4-b879-483b-8d01-8fc7c4ccf963">

**Comment by freeeverett** [comment]
Continue clicking on Profiler, then click on Run Profiler in the new window
![2024-01-10 12 32 24](https://github.com/RedisInsight/RedisInsight/assets/54989739/1626e1a3-ad0a-4f44-92cf-7d08555fde69)
![2024-01-10 12 32 54](https://github.com/RedisInsight/RedisInsight/assets/54989739/6957175f-7eda-4412-8ae0-e1074feacb0b)

**Comment by ViktarStarastsenka** [comment]
@freeeverett , can you please record a small video reproducing this issue? I still cannot reproduce it.

**Comment by freeeverett** [comment]
Of course, not all connections on my end will have this bug, only specific connections will have it, but I don't think this connection is different from others

https://github.com/RedisInsight/RedisInsight/assets/54989739/6294c2e2-12a2-40a0-9840-c3f6e2469296

**Comment by ViktarStarastsenka** [comment]
@freeeverett , thank you for the recording, though I still cannot reproduce it. Can you please send the web socket messages from DevTools?
here is a short recording of how to do it.

Uploading Screen Recording 2024-01-15 at 13.37.35.mov…

**Comment by freeeverett** [comment]
I don't know if it's related to data rate

https://github.com/RedisInsight/RedisInsight/assets/54989739/028ba405-2005-4468-9116-e4ea25d369be

**Comment by GnaneshKunal** [comment]
Hey @freeeverett,

Can you please connect to the redis via CLI and send the output of the MONITOR command? We must understand if the timestamp is coming correctly in the redis response.

**Comment by freeeverett** [comment]
![image](https://github.com/RedisInsight/RedisInsight/assets/54989739/c9926c26-1952-4b8b-978c-633db6b993fe)

**Comment by GnaneshKunal** [comment]
Alright. It looks like there's an issue with Alibaba redis. There should be a space after the timestamp which is missing.

Here's sample data:
```
1623848394.239364 [0 127.0.0.1:59560] "SET" "key1" "value1"
1623848395.442329 [0 127.0.0.1:59561] "GET" "key1"
1623848396.629874 [0 127.0.0.1:59562] "DEL" "key1"
```
