### ISSUE TITLE
[Bug]:It's not work when i use a custom user with no dangerous

### ISSUE THREAD

**Issue by sailineg** [RedisInsight/RedisInsight#2949]
**Preconditions** (Any important steps we need to know)
Setting user ACLs
```shell
ACL SETUSER antirez on +@all -@dangerous >42a979 ~*
```

**Steps to reproduce** (How to reproduce what you found step by step)
Setting user ACLs
```shell
ACL SETUSER antirez on +@all -@dangerous >42a979 ~*
```
use redis-cli 
```shell
$ redis-cli
127.0.0.1:6379> AUTH antirez  42a979
OK
127.0.0.1:6379> ping
PONG
127.0.0.1:6379> info
(error) ERR unknown command `infot`, with args beginning with:
```
it work well except **dangerous** - Potentially dangerous commands (each should be considered with care for various reasons). This includes [FLUSHALL](https://redis.io/commands/flushall), [MIGRATE](https://redis.io/commands/migrate), [RESTORE](https://redis.io/commands/restore), [SORT](https://redis.io/commands/sort), [KEYS](https://redis.io/commands/keys), [CLIENT](https://redis.io/commands/client), [DEBUG](https://redis.io/commands/debug), [INFO](https://redis.io/commands/info), [CONFIG](https://redis.io/commands/config), [SAVE](https://redis.io/commands/save), [REPLICAOF](https://redis.io/commands/replicaof), etc.

i add redis database with user and name which setted by acl.
 
Connection is successful.

but there is a error when i connet it.

**Actual behavior** (A short description of what you found)
**Error**

NOPERM this user has no permissions to run the 'info' command or its subcommand

**Expected behavior** (A short description of what you expected to find)
it work well just like default user

**Screenshots** (Paste or drag-and-drop a screenshot or a link to a recording)

![image](https://github.com/RedisInsight/RedisInsight/assets/154946903/0111fcd1-ae03-432c-b4cf-a25c54ceabc4)

**Additional context** (Operating system, version of RedisInsight, Redis database version, Redis module version, database type, connection type, logs, or any other information)
```
Redis server v=6.2.7
RedisInsight 2.24.0
```

**Comment by ViktarStarastsenka** [comment]
hi @sailineg , RedisInsight requires the `INFO` command to connect to a database, though the `INFO` command is included in the "dangerous" list.
you need to allow the `INFO` command to use RedisInsight
