### ISSUE TITLE
[Feature Request]: Can I filter key using regex 

### ISSUE THREAD

**Issue by tungrix** [RedisInsight/RedisInsight#2961]
**Problem description**
I wish to filter out the key which starts with "account" using: `\b(?!account)\w+\b`, 
like my keys: "account:token", "account:rate", "account:credit" ...

**How often do you encounter this problem**
<img width="1225" alt="image" src="https://github.com/RedisInsight/RedisInsight/assets/90018514/79aedde0-6f12-42f0-8199-fbaa1df1b33a">

Very often

**Alternatives considered**
Is there any alternative for me to achieve it?

**Additional information**

**Comment by ViktarStarastsenka** [comment]
hi @tungrix , here is the list of supported glob-style patterns: https://redis.io/commands/keys/#:~:text=Supported%20glob%2Dstyle%20patterns%3A

in your case, you can use `account:*`
