### ISSUE TITLE
[Bug]: When using docker create and appendonly set to yes, cannot login through redis-stack container

### ISSUE THREAD

**Issue by Wnthr** [RedisInsight/RedisInsight#2971]
**Preconditions** (Any important steps we need to know)
I am creating my docker container as a separate process, rather than using docker run. I have also added --appendonly yes to my REDIS_ARGS.

**Steps to reproduce** (How to reproduce what you found step by step)
1. Run docker create as follows:
```
/usr/bin/docker create --privileged \
            --name redis-stack \
            -p ${REDIS_IP}:${REDIS_PORT}:6379 \
            -p ${INSIGHT_IP}:${INSIGHT_PORT}:8001 \
            -v /var/lib/redis/data:/data:rw \
            -e REDIS_ARGS="--requirepass mypassword --appendonly yes" \
          redis/redis-stack
```

2. Start docker container with `docker start redis-stack`
3. Try to login through port 8001 (behind nginx reverse proxy)
4. Get web UI failed authentication error messages regardless of username/password filled in

**Actual behavior** (A short description of what you found)
The web UI just won't log in, despite using the requirepass password

**Expected behavior** (A short description of what you expected to find)
The web UI should just log in, as long as the right credentials are used.

**Workaround**
5. Turn off container with `docker stop redis-stack`
6. `rm -rf /var/lib/redis/data; mkdir /var/lib/redis/data`
7. `docker start redis-stack`
8. Fixed! I can now login through the web UI.

**Additional context**
Running on almalinux 9.3 on an arm64 machine

**Comment by bruno-kakele** [comment]
Maybe related: https://github.com/RedisInsight/RedisInsight/issues/3022

**Comment by ViktarStarastsenka** [comment]
@Wnthr , ensure that you saved your password as described here https://github.com/RedisInsight/RedisInsight/issues/3022#issuecomment-1967371138.

Please re-open the ticket if the issue still persists.
