### ISSUE TITLE
[Bug]: Recover connections settings

### ISSUE THREAD

**Issue by snird** [RedisInsight/RedisInsight#3017]
The last update of RedisInsight was destructive and deleted all the previously saved connections settings.

I do hope this is just a bug and there is a way to recover it.

**Comment by ViktarStarastsenka** [comment]
@snird , what was your previous RedisInsight version?
what is your OS?

**Comment by snird** [comment]
Windows, 2.40

**Comment by ViktarStarastsenka** [comment]
@snird , can you please check if one of the following folders contains the `redisinsight.db` file?
- C:\Users\{user}\AppData\Local\Programs\redisinsight-app\
- C:\Users\{user}\AppData\Local\Programs\redisinsight-v2\

**Comment by snird** [comment]
It seems like it does not:
![image](https://github.com/RedisInsight/RedisInsight/assets/2139589/66c43f56-6359-4348-9430-7b05b8ac1fdb)

And the path for me was: `C:\Users\{user}\AppData\Local\Programs\redisinsight`

**Comment by ViktarStarastsenka** [comment]
@snird , thank you

also, please check if you have the following folders:
`C:\Users\{user}\.redisinsight-app`
`C:\Users\{user}\.redisinsight-v2`

and if they contain the `redisinsight.db` file

**Comment by snird** [comment]
I have all 3:
![image](https://github.com/RedisInsight/RedisInsight/assets/2139589/4cd794b0-d352-43a4-b9b4-4dfda590e2d4)

And all of them include a `redisinsight.db` file

**Comment by ViktarStarastsenka** [comment]
@snird , can you rename `.redisinsight-app` into something else (e.g. `.redisinsight-app-copy`), and then launch RedisInsight?
and check if you have all the databases previously added (before updating the app yesterday).

**Comment by ViktarStarastsenka** [comment]
this is needed to check the migration script (this migration script was used when the application was renamed a couple of months ago).

To revert the changes after this attempt, you can delete the new `.redisinsight-app`, and rename `.redisinsight-app-copy` back to `.redisinsight-app`.

If you want to restore the list of databases you had before updating, please copy the `redisinsight.db` from `.redisinsight-v2` to `redisinsight-app`.

But it is highly recommended to create copies before making changes.

**Comment by snird** [comment]
changing `.redisinsight-app` to `.redisinsight-app` fixed it.
Thank you @ViktarStarastsenka !
I hope this issue will also help other people that may encounter this issue.

**Comment by Moulde** [comment]
I just had this happen to me 3.2.0 -> 3.4.1
