### ISSUE TITLE
[Bug]: keys are not geeting deleted in bulk

### ISSUE THREAD

**Issue by nirupam-angelone** [RedisInsight/RedisInsight#3018]
**Preconditions** (Any important steps we need to know)

**Steps to reproduce** (How to reproduce what you found step by step)

**Actual behavior** (A short description of what you found)
<img width="807" alt="image" src="https://github.com/RedisInsight/RedisInsight/assets/115979207/ccda6319-8de2-40e0-a772-1514a661c358">

**Expected behavior** (A short description of what you expected to find)
keys should be deleted in bulk. i can individually delete keys one by one from the left panel

**Screenshots** (Paste or drag-and-drop a screenshot or a link to a recording)

**Additional context** (Operating system, version of RedisInsight, Redis database version, Redis module version, database type, connection type, logs, or any other information)

**Comment by ViktarStarastsenka** [comment]
@nirupam-angelone , please provide more information about your database - what database version do you use? Is it clustered?
What RedisInsight version do you use?
How many keys with the following pattern `redshift-client-profile-*` do you have (roughly)?
