### ISSUE TITLE
[Bug]: Authentication fails

### ISSUE THREAD

**Issue by w-biggs** [RedisInsight/RedisInsight#3022]
**Preconditions**

I have RedisInsight running through the `redis-stack` docker container.

**Steps to reproduce**

I'm passing in `REDIS_ARGS=--save 20 1 --loglevel debug --requirepass <password goes here>`, then going to RedisInsight and attempting to log in using the username `default` and the password specified in `REDIS_ARGS`.

**Actual behavior** (A short description of what you found)

RedisInsight always gives the error "Failed to authenticate, please check the username or password."

**Expected behavior** (A short description of what you expected to find)

I can log in.

**Screenshots** (Paste or drag-and-drop a screenshot or a link to a recording)

<img width="1129" alt="image" src="https://github.com/RedisInsight/RedisInsight/assets/3406010/62492559-dd26-4c2e-bb4b-f68c5b4a8ec0">

**Additional context** (Operating system, version of RedisInsight, Redis database version, Redis module version, database type, connection type, logs, or any other information)

The image I'm using is `redis/redis-stack:latest`.

Looking at `redisinsight-errors-2024-02-02.log.0`, I see:
```2/2/2024, 8:48:25 PM | ERROR | RedisConnectionFactory | Failed connection to the redis database. | {"stack":[{"message":"NOAUTH Authentication required.","command":{"name":"info"}}]}
2/2/2024, 8:48:25 PM | ERROR | RedisConnectionFactory | Failed connection to the redis database. | {"stack":[{"message":"NOAUTH Authentication required.","command":{"name":"info"}}]}
2/2/2024, 8:48:26 PM | ERROR | RedisConnectionFactory | Failed connection to the redis database. | {"stack":[{"message":"NOAUTH Authentication required.","command":{"name":"info"}}]}
2/2/2024, 8:48:26 PM | ERROR | RedisConnectionFactory | Unable to establish connection. | {"stack":[{"message":"NOAUTH Authentication required.","command":{"name":"info"}}]}
2/2/2024, 8:48:26 PM | ERROR | DatabaseConnectionService | Failed to create database client | {"stack":[{"message":"NOAUTH Authentication required.","command":{"name":"info"}}]}
```

Connecting on the command line outside of the container via `redis-cli -u redis://default:<password>@localhost:6380` works fine. Inside the container, `redis-cli -u redis://default:<password>@localhost:6379` also works as expected.

**Comment by SylvainAssemat** [comment]
Hi @w-biggs 

I have encountered the same problem today

Can you try to write your password (even if you see the hidden dot, set it anyway), and scroll down and click "**apply change**"

That's work for me now, tell me if it's ok for you too ?

Hope it helps :-)

**Comment by ViktarStarastsenka** [comment]
@w-biggs , please ensure that your password is entered correctly.
currently, the password is masked, but you can re-enter the password manually just to double-check.

please reopen the ticket if the issue persists.

**Comment by bruno-kakele** [comment]
I have to say that it took me a while to see there was this `apply changes` button, the UI was not clear, and clicking `test connection` or `open` does not automatically apply the changes. On my screen, the "Apply" button was all the way down:

![image](https://github.com/user-attachments/assets/c9d0b765-561a-421b-bbc8-61c540114486)
