### ISSUE TITLE
[Bug]: Autofill prevents the form from being submitted

### ISSUE THREAD

**Issue by michaeltch** [RedisInsight/RedisInsight#3026]
**Preconditions** (Any important steps we need to know)
you should generate / write a connection string (I used `redis://default:<password>@<cloud-host>:<port>`)

**Steps to reproduce** (How to reproduce what you found step by step)
from the start page, navigate to "Add connection details manually" > "Autodiscover Databases" > "Redis Enterprise Cluster".
Paste the connection string into the "cluster host" text box input.

**Actual behavior** (A short description of what you found)
the Submit button is greyed out and says "Enter a value for required fields (24):"

**Expected behavior** (A short description of what you expected to find)
the Submit button should no longer be greyed out because all of the fields have been filled out by autofill

**Screenshots** (Paste or drag-and-drop a screenshot or a link to a recording)
<img width="1186" alt="Screenshot 2024-02-06 at 1 50 31 PM" src="https://github.com/RedisInsight/RedisInsight/assets/123604463/eb67d857-b6ed-4420-967c-961d482db4a6">

**Additional context** (Operating system, version of RedisInsight, Redis database version, Redis module version, database type, connection type, logs, or any other information)
redis insight version: Version 2.42.0 (2.42.0.103315)
macos version: 14.1 (23B74)
RedisInsight was reinstalled recently

**Comment by ViktarStarastsenka** [comment]
hi, it should be fixed with 2.44.0 (released today).
Please reopen the ticket if the issue persists.
