### ISSUE TITLE
personal use

### ISSUE THREAD

**Issue by junweihui** [RedisInsight/RedisInsight#3056]
**Problem description** (Describe the problem you would like to solve with this feature request or suggested idea).

**How often do you encounter this problem** (Describe how frequently this problem occurs).

**Alternatives considered** (Describe any alternative features or products you've considered).

**Additional information** (Add any other context or details here).

**Comment by ViktarStarastsenka** [comment]
@junweihui , can you add more details?

**Comment by ViktarStarastsenka** [comment]
Re-open the ticket if it is still relevant. If so, please provide more details.
