### ISSUE TITLE
[Bug]: v2 docker image doesn't serve the webpage

### ISSUE THREAD

**Issue by SaadAhmedGit** [RedisInsight/RedisInsight#3062]
**Steps to reproduce**
1. Run `docker run -v redisinsight:/db -p 8001:8001 redislabs/redisinsight:v2`
2. Navigate to `http://localhost:8001`

**Actual behavior**
Webpage is not served.

**Expected behavior**
Webpage should be served.

**Additional context**
This problem only seems to be with the v2 image. `redislabs/redisinsight:1.14.0` works as expected.

**Comment by ViktarStarastsenka** [comment]
please try `docker run -v redisinsight:/db -p 5540:5540 redislabs/redisinsight:v2`

**Comment by ViktarStarastsenka** [comment]
@SaadAhmedGit , this command does not refer to RedisInsight v1, but to RedisInsight (aka v2), and RedisInsight runs on 5540 by default.
you need to use the `RI_APP_PORT` environment variable set to 8001 to use port 8001
