### ISSUE TITLE
How to connect exisitng project with Redis Cloud?

### ISSUE THREAD

**Issue by Takhirzhon** [RedisInsight/RedisInsight#3079]
Hi. 

I wanted to connect the Redis Cloud Database with my Python project. However I am getting error 
2/23/2024, 11:40:04 AM | ERROR | DatabaseService | Failed to add database. | {"stack":[{"message":"getaddrinfo EAI_AGAIN redis-18108.c299.asia-northeast1-1.gce.cloud.redislabs.com"}]}

I checked my DNS and it is fine. Used nslookup and DNS query was successfully resolved. But still it is not connecting. Tried through redis_cli, got error:
Error 11002 connecting to redis-18108.c299.asia-northeast1-1.gce.cloud.redislabs.com:18108. getaddrinfo failed.

Also tried to use command:
redis-cli -u redis://default:*******@redis-18108.c299.asia-northeast1-1.gce.cloud.redislabs.com:18018      

Windows user, I am running Redis through Docker. Anyone could help me with that problem?

**Comment by ViktarStarastsenka** [comment]
hi @Takhirzhon , please create a support ticket here - https://redislabs.zendesk.com/agent/dashboard
