### ISSUE TITLE
[Bug]: Failed to convert to json when loading JSON content in string field

### ISSUE THREAD

**Issue by PanMan** [RedisInsight/RedisInsight#3137]
**Preconditions** (Any important steps we need to know)
This used to work

**Steps to reproduce** (How to reproduce what you found step by step)
When opening a Redis string that contains 12KB of JSON, RedisInsights doesn't show it as json.
 
**Actual behavior** (A short description of what you found)
When selecting the JSON format from the picker (which is auto-selected), it says `failed to convert to JSON`
When checking with jsonlint.com, a local editor, or command line node.js the JSON value is valid json

**Expected behavior** (A short description of what you expected to find)
Show it as JSON, as this used to work with an older version

**Additional context** (Operating system, version of RedisInsight, Redis database version, Redis module version, database type, connection type, logs, or any other information)
Using the latest, 2.44.0 version. Not sure which version this worked on, but it did a few... weeks to months ago..

**Comment by PanMan** [comment]
Btw, perhaps this is related to larger strings now not fully loading? When I load a smaller JSON key, it does show as JSON formatted. However, also with a larger key, when "loading all" and switching manually to unicode/JSON it fails to show as (formatted) JSON. 
BTW, can I set the size/when it should not load/show a full key?

**Comment by PanMan** [comment]
I see those were added in [2.36](https://github.com/RedisInsight/RedisInsight/releases/tag/2.36.0) so it would then most likely be introduced by the changes in 
https://github.com/RedisInsight/RedisInsight/pull/2685 or https://github.com/RedisInsight/RedisInsight/pull/2686

**Comment by ViktarStarastsenka** [comment]
hi @PanMan , this indeed relates to changes introduced with https://github.com/RedisInsight/RedisInsight/pull/2685 to work with large keys to avoid OOM cases, the current limit is 5000 characters.

You just need to click "Load all" to upload the entire key and then apply the formatting.

**Comment by PanMan** [comment]
> hi @PanMan , this indeed relates to changes introduced with #2685 to work with large keys to avoid OOM cases, the current limit is 5000 characters.
> 
> You just need to click "Load all" to upload the entire key and then apply the formatting.

This.. Doesn't work. Also after the full content is loaded, it doesn't show as JSON, and manually switching to ascii and back to JSON also fails to show it as JSON.

**Comment by ViktarStarastsenka** [comment]
@PanMan , the only way I was able to reproduce this was by using a float number with at least 10 decimal places.
Do you use such numbers in your data?

**Comment by ViktarStarastsenka** [comment]
@PanMan , this relates to an issue with a library we use - https://github.com/sidorares/json-bigint/issues/49
it also reproduces with older builds before changes made with [#2685](https://github.com/RedisInsight/RedisInsight/pull/2685) or [#2686](https://github.com/RedisInsight/RedisInsight/pull/2686).
We'll sort it out, but I can't say the exact timeline for now.

**Comment by SpenceUK** [comment]
I am experiencing the same but it I think it's from the conversion of Java Instant resulting in a float, for example: "sessionExpiresAt": 1711108268.486864

**Comment by GnaneshKunal** [comment]
Hey @PanMan and @SpenceUK,

Are you still facing the issue? A fix was made recently for rendering floating point numbers on the Visualisation component.

**Comment by PanMan** [comment]
Thanks for asking @GnaneshKunal - I have tested a few cases, but I still get an error, I guess on a value like `110.19146419437342` - 
Also, I would like to set the 5KB default key length limit higher - we have a lot of 12KB keys, and I now always have to press "load all"

**Comment by ViktarStarastsenka** [comment]
@PanMan , the fix will be released with 2.52 this week (somewhere around Wednesday).

**Comment by ViktarStarastsenka** [comment]
@PanMan , with Redis Insight 2.52 (released today) the JSON format should work with float numbers with 10 or more decimal places.
Regarding the second point about uploading more than 5KB values of strings - 5KB is set to avoid OOM when working with large strings.
If you would like to customize this value - please create another ticket.

Re-open this ticket if the issue still persists.
