### ISSUE TITLE
[Feature Request]: Please allow for control of the Subscription in the Pub/Sub page

### ISSUE THREAD

**Issue by ProffP** [RedisInsight/RedisInsight#3138]
**Problem description**
Right now, if you want to see published messages in redis insight, you must subscribe to them all. This is a firehose in our solution as we are using it as a bus

**How often do you encounter this problem** (Describe how frequently this problem occurs).
Multiple times a week, I have opted for other tools to monitor specific channels

**Alternatives considered** (Describe any alternative features or products you've considered).
Tried issuing Subscribe commands in the Workbench but this is restricted

**Additional information** (Add any other context or details here).

**Comment by ViktarStarastsenka** [comment]
hi @ProffP , here is the relevant ticket
https://github.com/RedisInsight/RedisInsight/issues/1671
