### ISSUE TITLE
[Bug]:We need the Chinese version

### ISSUE THREAD

**Issue by xiangdaojizhi** [RedisInsight/RedisInsight#3142]
We need the Chinese version
We need the Chinese version
We need the Chinese version
We need the Chinese version
We need the Chinese version
We need the Chinese version
We need the Chinese version
We need the Chinese version
We need the Chinese version
We need the Chinese version
We need the Chinese version
We need the Chinese version
We need the Chinese version
We need the Chinese version
We need the Chinese version
We need the Chinese version
We need the Chinese version
We need the Chinese version
We need the Chinese version
We need the Chinese version
We need the Chinese version
We need the Chinese version
We need the Chinese version
We need the Chinese version
We need the Chinese version
We need the Chinese version
We need the Chinese version
We need the Chinese version
We need the Chinese version
We need the Chinese version
We need the Chinese version
We need the Chinese version
We need the Chinese version
We need the Chinese version
We need the Chinese version
We need the Chinese version
We need the Chinese version
We need the Chinese version
We need the Chinese version
We need the Chinese version
We need the Chinese version
We need the Chinese version
We need the Chinese version
We need the Chinese version
We need the Chinese version
We need the Chinese version
We need the Chinese version
We need the Chinese version

**Comment by ViktarStarastsenka** [comment]
duplicates https://github.com/RedisInsight/RedisInsight/issues/1317
