### ISSUE TITLE
[Bug]: Can NOT support Redis7 Stream's 0-* ID

### ISSUE THREAD

**Issue by CyrusNG** [RedisInsight/RedisInsight#3146]
<img width="689" alt="SCR-20240308-ueqr" src="https://github.com/RedisInsight/RedisInsight/assets/16208525/c25ab89e-35ee-4785-b120-f1fda99bd03a">

As the screenshot shown, Entry ID field does NOT support Redis7 Stream's 0-* ID.

reference link about 0-* ID: https://redis.io/docs/data-types/streams/#entry-ids

**Comment by ViktarStarastsenka** [comment]
@CyrusNG , can you check that there are no entry IDs greater than 0 in your stream?
e.g. 1-1

**Comment by CyrusNG** [comment]
@ViktarStarastsenka for sure there are no entry IDs greater than 0.
And I use CLI to use following command, and the command can add new entry, but ResignInsight CANT.
`xadd firstStream 0-* name tom age 22` 

However, create one new stream key and add 0-* entry is OK at first time, but I want to add second one, RedisInsight will show error as I capture screen.

RedisInsight V2.44.0

**Comment by ViktarStarastsenka** [comment]
@CyrusNG , thanks, managed to reproduce this
we'll try to deliver a fix with the next release

**Comment by ViktarStarastsenka** [comment]
@CyrusNG , this has been fixed with 2.46 (released today).
