### ISSUE TITLE
[Feature Request]: Memory Analysis in Offline Mode (existed in the Old UI)

### ISSUE THREAD

**Issue by SallyBlichG** [RedisInsight/RedisInsight#3147]
**Problem description** 
I want to analyze my Redis snapshot files (RDB files) offline, creating an RSnap file for SQLite use.

**How often do you encounter this problem** 

I want to analyze the snapshots every few months.

**Alternatives considered** 

I don't see other alternatives for this kind of solution in the new UI. 
My production Redis instance is large, with millions of keys, so scanning 10K keys isn't sufficient for me.

**Additional information**
This feature was present in the previous UI a few months ago.

![image](https://github.com/RedisInsight/RedisInsight/assets/129067029/d3680d24-0d59-4931-a7a2-1064f6d69c2a)
![image](https://github.com/RedisInsight/RedisInsight/assets/129067029/526d15c3-17c7-4936-ae1c-c7335d17429a)

**Comment by ViktarStarastsenka** [comment]
hi @SallyBlichG , here is a relevant ticket - https://github.com/RedisInsight/RedisInsight/issues/480
