### ISSUE TITLE
[Bug]: Document bug

### ISSUE THREAD

**Issue by nethippo** [RedisInsight/RedisInsight#3148]
**Preconditions** (Any important steps we need to know)

 invalid syntax of a sample query at Range query 4

**Steps to reproduce** (How to reproduce what you found step by step)
FT.SEARCH idx:bicycle "@price:[-inf 2000] SORTBY price LIMIT 0 5"

**Actual behavior** (A short description of what you found)
No results found

**Expected behavior** (A short description of what you expected to find)
ft.search idx:bicycle "@price:[-inf (2000]" SORTBY price limit 0 5

**Screenshots** (Paste or drag-and-drop a screenshot or a link to a recording)

**Additional context** (Operating system, version of RedisInsight, Redis database version, Redis module version, database type, connection type, logs, or any other information)

**Comment by ViktarStarastsenka** [comment]
thank you for noticing that.
the issue has already been fixed, please re-start RedisInsight to see the changes.
