### ISSUE TITLE
Data is not getting stored in 'LIST' format.

### ISSUE THREAD

**Issue by SherkingAtm** [RedisInsight/RedisInsight#3201]
I am a student of Whitehat Jr. While using MIT App Inventor to create an app, I used store value (function) to store data. But it is getting stored in 'string' form but I want it in 'list' form. And there is no such option to change the style. I can create a new one but I have already stored my data. Please check🙏🙏.
![img-1](https://github.com/RedisInsight/RedisInsight/assets/126082107/cf473cfd-8716-42fe-b30c-99982c03946d)
![img-2](https://github.com/RedisInsight/RedisInsight/assets/126082107/17c003d4-503e-400a-b48d-4caa1393abcb)

**Comment by ViktarStarastsenka** [comment]
hi, please ask this question here - https://community.appinventor.mit.edu/
