### ISSUE TITLE
[Feature Request]: Enable RBAC in redisinsight

### ISSUE THREAD

**Issue by minex970** [RedisInsight/RedisInsight#3259]
Lack of authentication, can we have RBAC-based authentication for UI?

Recently, we launched the UI on the docker container, but it was publicly accessible, my use cases needed mainly two users and one admin, we contain all access & another for the developer or sys-admin to just use to analyze reports.

**Comment by ViktarStarastsenka** [comment]
you can set up Redis Insight on Docker behind a reverse proxy and integrate it with LDAP.
A sample setup to access Redis Insight behind a reverse proxy is here - https://github.com/RedisInsight/RedisInsight-reverse-proxy.
Also, starting from 2.48, Redis Insight supports subpath proxies using the RI_PROXY_PATH environment variable.
