### ISSUE TITLE
[Feature Request]: Start with initial redis connection

### ISSUE THREAD

**Issue by motiejuss** [RedisInsight/RedisInsight#3261]
Maybe it's already possible, I just haven't found the specs. It would be useful to define initial redis connection upon the launch of Redis Insights. Possible [Dockerfile](https://github.com/RedisInsight/RedisInsight/blob/main/Dockerfile) or some sort of configuration stored locally on disk?

**Comment by motiejuss** [comment]
Possible duplicate https://github.com/RedisInsight/RedisInsight/issues/2785

**Comment by ViktarStarastsenka** [comment]
currently, there is no such feature in Redis Insight, but I'll post an update in https://github.com/RedisInsight/RedisInsight/issues/2785
