### ISSUE TITLE
[Bug]: Fail to add redis database programmatically

### ISSUE THREAD

**Issue by rgaduput** [RedisInsight/RedisInsight#3267]
**Preconditions** (Any important steps we need to know)
When working with v1 of `redisinsight` we have an option to add `redis` database programmatically using the API POST `/api/instance/`.
But while we are upgrading to v2 from v1 observed that this API does not exists (throws 404), also I could not find any API docs as well.
Is it deprecated in v2 ? Is there any different ways to add database programmatically instead from UI ? Appreciate any suggestions.

**Steps to reproduce** (How to reproduce what you found step by step)

- Install redisinsight
- Add database using API` /api/instance/` (POST)

**Actual behavior** (A short description of what you found)
404 not found.

**Expected behavior** (A short description of what you expected to find)

**Screenshots** (Paste or drag-and-drop a screenshot or a link to a recording)

**Additional context** (Operating system, version of Redis Insight, Redis database version, Redis module version, database type, connection type, logs, or any other information)

**Comment by ViktarStarastsenka** [comment]
hi @rgaduput , currently, RedisInsight does not support this API.
here is a similar ticket where I'll post relevant updates: https://github.com/RedisInsight/RedisInsight/issues/2785

**Comment by arthosofteq** [comment]
hi @rgaduput
I think it happens because Redis Insight doesn't know anything about encryption strategy at that moment
Encryption setting is available on "EULA and Privacy Settings" popup on first start on UI. That is why after visiting and accepting EULA everything starts work

I could recommend you to trigger additional endpoint (only once on first startup) via `curl` before adding database

Based on your input, here is an endpoint:

`PATCH /api/settings`

with payload

```
{
  "agreements": {
    "eula": true, // mandatory
    "analytics": true/false, // mandatory. whether you want to send analytics data to make Redis Insight better
    "notifications": true/false, // mandatory. whether you want to receive in-app notifications
    "encryption": true/false, // mandatory. If you want to encrypt sensitive information. (if you want to enable this, please look into "Configuration" table from here https://hub.docker.com/r/redis/redisinsight before)
  }
}
```
Example:
```
curl -XPATCH 'http://localhost:5540/api/settings' \
  -H 'Content-Type: application/json' \
  --data-raw '{"agreements":{"eula":true,"analytics":true,"notifications":true,"encryption":false}}
```

**Comment by rgaduput** [comment]
Hi @arthosofteq ,
that helped, Thank you.
