### ISSUE TITLE
[Bug]:Could not connect to ddbb RedisInsight

### ISSUE THREAD

**Issue by LuisenLou** [RedisInsight/RedisInsight#3276]
**Preconditions** (Any important steps we need to know)
I've done every step as the tutorial 'RU101 Introduction to Redis Data Structures' explains but I cannot pass the next step cause there no connection to database I made.

**Steps to reproduce** (How to reproduce what you found step by step)
RedisInsight Setup steps to connect your database.

**Actual behavior** (A short description of what you found)
Error
Could not connect to 'database', please check the connection details.

**Expected behavior** (A short description of what you expected to find)

Might connect and then 'You should see a list of configured Redis databases. Click "OK" to dismiss the "Database has been added" dialog:' 

**Screenshots** (Paste or drag-and-drop a screenshot or a link to a recording)
![Captura de pantalla 2024-04-17 110430](https://github.com/RedisInsight/RedisInsight/assets/146094381/096fd538-4636-4402-9c4b-8d47f1925918)

**Additional context** (Operating system, version of Redis Insight, Redis database version, Redis module version, database type, connection type, logs, or any other information)
I'm currently doing the RU101 Introduction to Redis Data Structures course.

**Comment by LuisenLou** [comment]
Sorry but , maybe its because im trying it on windows and its unable on it?
O not?

**Comment by ViktarStarastsenka** [comment]
you are connecting to the Redis Cloud instance, it is available on all OS.

**Comment by LuisenLou** [comment]
Okay but i cannot install Redis CLI on windows, well i have to do it
installing wsl2.
But i don't know why it is not working because I tried the way you told me
but nothing.

**Comment by ViktarStarastsenka** [comment]
@LuisenLou , here is a guide on how to install redis-cli on Windows - https://redis.io/blog/get-redis-cli-without-installing-redis-server/

have you tried the first part of the instructions I sent before?
Do you still see the connection error?
