### ISSUE TITLE
[Bug]: Redisinsight should change `theme` key of local storage

### ISSUE THREAD

**Issue by atuk721** [RedisInsight/RedisInsight#3282]
When Redisinsight runs subpath mode and share origin with multiple applications and uses same local storage key, it became not to work.

As my experience, external application uses `theme` key in local storage and parses its value as JSON, but Redisinsight saves just a string value to `theme` as below.

https://github.com/RedisInsight/RedisInsight/blob/main/redisinsight/ui/src/services/theme.ts#L38

So I think this should change key name more specific like "redisinsight-theme" because Redisinsight can run by subpath mode.

**Comment by atuk721** [comment]
2.62 seems to work perfectly!
I appreciate to fix it.

**Comment by ViktarStarastsenka** [comment]
kudos to @GnaneshKunal  :)
