### ISSUE TITLE
[Feature Request]:能不能把这里改成下拉选择，并在下拉的数据库列表中显示每个数据库里键值的数量

### ISSUE THREAD

**Issue by xiaoliang-liu** [RedisInsight/RedisInsight#3323]
**Problem description** (Describe the problem you would like to solve with this feature request or suggested idea).

能不能把下图中框选的地方改成下拉选择，并在下拉的数据库列表中显示每个数据库里键值的数量

**Alternatives considered** (Describe any alternative features or products you've considered).
<img width="599" alt="image" src="https://github.com/RedisInsight/RedisInsight/assets/63272413/ffea40c9-9ee3-4916-8c8e-e269aa0f5f28">

**Comment by ViktarStarastsenka** [comment]
this is a duplicate of https://github.com/RedisInsight/RedisInsight/issues/1857
