### ISSUE TITLE
[Feature Request]: Adding base URL, predefined db connections and remove banner using configs for running in container

### ISSUE THREAD

**Issue by arian-press2015** [RedisInsight/RedisInsight#3324]
**Problem description** I need to create containers of Redis insight with arbitrary base URL and predefined db connections and also (if possible) remove the initial banner, so when user creates a container and I pass the configs related to that user, user can start using Redis Insight immediately, do their work, and kill the container.

**How often do you encounter this problem** this occurs anytime that a user wants to run a new container(almost daily)

**Alternatives considered** I'm thinking about some initial docker environment variables to be set that do such thing.

**Additional information** thanks in advance.

**Comment by arian-press2015** [comment]
I'm sorry for my inconvenience. I found RI_PROXY_PATH that fixed my first issue.

I couldn't find any docs that help me with my problem. if there isn't any doc, I'm willing to write one.

**Comment by ViktarStarastsenka** [comment]
hi @arian-press2015 , currently, there is no feature to pre-setup the db connections, this is something that can be added in the upcoming releases, but the feature is not prioritized for any release yet.

**Comment by ViktarStarastsenka** [comment]
a workaround is described here - https://github.com/RedisInsight/RedisInsight/issues/289
and any updates for the feature will be posted in this ticket as well

**Comment by arian-press2015** [comment]
is there any docs related to env variables we can use? I can write one if needed!

**Comment by ViktarStarastsenka** [comment]
@arian-press2015 , thank you for your initiative :)
here is the documentation - https://redis.io/docs/latest/operate/redisinsight/install/env-variables/
please let me know if you need any other details
