### ISSUE TITLE
[Bug]: Change Wiki for Development

### ISSUE THREAD

**Issue by yldrmali** [RedisInsight/RedisInsight#3334]
**Preconditions** (none)

**Steps to reproduce** (How to reproduce what you found step by step)

I tried to run api and ui services locally after cloning the repo to my local PC.
After running the `yarn --cwd redisinsight/api/ start:dev` command I tried to run `yart start:ui` command. There's no such command.
[Wiki-Development](https://github.com/RedisInsight/RedisInsight/wiki/How-to-build-and-contribute#development-3) needs to be edited.

**Actual behavior** (This command is no longer available inside package.json)
```sh
yarn start:ui
```

**Expected behavior** (It should be the command below)
```sh
yart start:web
```

**Additional context** (none)

**Comment by zalenskiSofteq** [comment]
Thanks for letting us know
In the current main branch to start the frontend you need to run the command `yarn dev:ui`
Updated the Wiki
