### ISSUE TITLE
[Bug]: Missing latest label on 2.48 release

### ISSUE THREAD

**Issue by pk2** [RedisInsight/RedisInsight#3338]
![Screenshot from 2024-05-04 11-50-12](https://github.com/RedisInsight/RedisInsight/assets/8936105/0e14f85c-6075-44dc-b345-983027ec50a7)
**Actual behavior** Release 2.46 is latest version
**Expected behavior** Release 2.48 should be latest version

**Comment by ViktarStarastsenka** [comment]
thanks, fixed
