### ISSUE TITLE
[Feature Request]:

### ISSUE THREAD

**Issue by Jeetendra1** [RedisInsight/RedisInsight#3370]
Getting error "Server Error (Try restarting redis insight)" when trying to Login using "Gmail".

**Comment by ViktarStarastsenka** [comment]
@Jeetendra1 , please provide the following additional information:
1. when exactly do you see this error - before or after navigating to your native browser?
2. what OS do you use?
3. do you have only one Redis Insight instance open?
4. do you work in a private network?
5. can you attach logs? (but please remove any sensitive data from them)

**Comment by ViktarStarastsenka** [comment]
Re-open the issue with additional information described above if this still reproduces.
