### ISSUE TITLE
RedisInsight for 6.0 not available

### ISSUE THREAD

**Issue by 11days** [RedisInsight/RedisInsight#3378]
How to update RedisInsight for 6.0 in Windows, my default under Github is 5.0, many functions are not supported, such as GEO

becasue I'm learning Redis on a Blibli vedio, I want to try as much as operations to familiarise with redis

Blibli vedio address: 
![1](https://github.com/RedisInsight/RedisInsight/assets/122618722/06404cc9-c884-41e3-bca4-a02874b8d285)
https://www.bilibili.com/video/BV1Jj411D7oG/?p=13&spm_id_from=pageDriver&vd_source=b5be1aecd4ef69a7c3cf0217f39574c1

**Comment by ViktarStarastsenka** [comment]
@11days , you need to update your Redis database, not Redis Insight.
