### ISSUE TITLE
[Feature Request]: Browser view sorting

### ISSUE THREAD

**Issue by idrissehitoglu2** [RedisInsight/RedisInsight#3381]
Sorting by Key name and size  etc.

**Comment by ViktarStarastsenka** [comment]
@idrissehitoglu2 , there is sorting by key name in the Tree view.
<img width="947" alt="image" src="https://github.com/RedisInsight/RedisInsight/assets/99594890/c37c5a28-020e-4f9e-9ae5-a7423fbe53e0">
