### ISSUE TITLE
Hope to add language switching function

### ISSUE THREAD

**Issue by sudo-keke** [RedisInsight/RedisInsight#341]
such as :  setting - language 
or add language plugins
or import language package

**Comment by ViktarStarastsenka** [comment]
Hello @yan-qiang , thank you for raising this idea. This feature has not been included into the upcoming releases yet, but we are open to contributions.

**Comment by ViktarStarastsenka** [comment]
hi, let's track this request under this ticket - https://github.com/RedisInsight/RedisInsight/issues/1317.
