### ISSUE TITLE
If only we could set up different languages.

### ISSUE THREAD

**Issue by GitHub-Link** [RedisInsight/RedisInsight#3418]
**Problem description** (Describe the problem you would like to solve with this feature request or suggested idea).

**How often do you encounter this problem** (Describe how frequently this problem occurs).

**Alternatives considered** (Describe any alternative features or products you've considered).

**Additional information** (Add any other context or details here).

**Comment by ViktarStarastsenka** [comment]
hi @GitHub-Link , the updates for adding more languages will be posted in this ticket - https://github.com/RedisInsight/RedisInsight/issues/1317
