### ISSUE TITLE
[Feature Request]: Plase allow index upto 100 in database connection index, 

### ISSUE THREAD

**Issue by hiteshpatelic** [RedisInsight/RedisInsight#342]
**Problem description** (Describe the problem you would like to solve with this feature request or suggested idea).
Should not exceed 15.
in company i have database index number is 62 for my game

**How often do you encounter this problem** (Describe how frequently this problem occurs).
on connection time

**Alternatives considered** (Describe any alternative features or products you've considered).

**Additional information** (Add any other context or details here).

**Comment by loserdog-err** [comment]
+1

**Comment by ViktarStarastsenka** [comment]
Hi @hiteshpatelic , @loserdog-err , what database do you use?

**Comment by hiteshpatelic** [comment]
local redis

**Comment by K-Jo** [comment]
@hiteshpatelic out of curiosity, did you modify the source code yourself?

```
127.0.0.1:6379> info server
# Server
redis_version:6.2.6
redis_git_sha1:00000000
redis_git_dirty:0
redis_build_id:5a8a87e24a1578b
redis_mode:standalone
os:Linux 5.10.104-linuxkit x86_64
arch_bits:64
multiplexing_api:epoll
atomicvar_api:c11-builtin
gcc_version:9.4.0
process_id:15
process_supervised:no
run_id:af5b370f3ad5d0778ec1b9a9f7354c062c994dd3
tcp_port:6379
server_time_usec:1650487822661692
uptime_in_seconds:565294
uptime_in_days:6
hz:10
configured_hz:10
lru_clock:6320654
executable:/opt/redis-stack/bin/redis-server
config_file:
io_threads_active:0
127.0.0.1:6379> select 16
(error) ERR DB index is out of range
127.0.0.1:6379> select 15
OK
127.0.0.1:6379[15]>
```

**Comment by uglide** [comment]
@K-Jo oss redis has setting `databases 16` in the redis.conf which is usually changed to something bigger on shared hostings, etc

**Comment by goozp** [comment]
Some cloud platform may support db index exceed 15.

Regardless of those platform's architecture or configuration, If RI support this should be better. For some developers, they are just facing a redis on a cloud platform.

**Comment by ViktarStarastsenka** [comment]
We will remove this limitation in the upcoming releases (planned in 2.0.7).
