### ISSUE TITLE
[Bug]:Cannot Connect to Aws ElastiCache Redis cluster using TLS

### ISSUE THREAD

**Issue by WeberKuo** [RedisInsight/RedisInsight#3429]
**Preconditions** (Any important steps we need to know)

Configuration for Aws Elasticache:
* Redis Version: 7.1
* Cluster Mode: Enabled
* Encryption in Transit: Enabled
* Access Control: User Group Access Control

RedisInsight Configuration:
* Use TLS: Enabled
* Use SSH Tunnel: Enabled

**Problem Description**
After enabling TLS in RedisInsight, attempts to connect to the ElastiCache Redis cluster through an SSH tunnel from an AWS EC2 instance have been unsuccessful. 
The SSH tunnel is established, but connections to the Redis cluster fail, impeding access to the data stored within.

The following scenarios have been attempted:
1. Cluster mode: Disabled, TLS: Disabled - Connection successful.
2. Cluster mode: Enabled, TLS: Disabled - Connection successful.
3. Cluster mode: Disabled, TLS: Enabled - Connection successful.
4. Cluster mode: Enabled, TLS: Enabled - Connection failed.

**RedisInsight Log**
<img src="https://github.com/RedisInsight/RedisInsight/assets/63902533/ad27e0d2-11a1-4ff4-ac52-f983cc2c0aff"  width="700"/>

By the way, regarding the same configuration in Table Plus, the connection is successfully established.
<img src="https://github.com/RedisInsight/RedisInsight/assets/63902533/ae6877c6-edf0-4ff8-8272-eae8db411e09"  width="400"/>

**Comment by ViktarStarastsenka** [comment]
hi, this can be relevant - https://github.com/RedisInsight/RedisInsight/issues/3416#issuecomment-2135686024

**Comment by WeberKuo** [comment]
Hello, @ViktarStarastsenka  
I believe the issue may stem from a timeout duration that is too short. 
By adding `slotsRefreshTimeout: 5000` [here](https://github.com/RedisInsight/RedisInsight/blob/main/redisinsight/api/src/modules/redis/connection/ioredis.redis.connection.strategy.ts#L84), I managed to build the program successfully on my end, and it was able to connect to my Redis cluster without any issues. 
The default timeout here is set to 1 second, which might result in the connection being terminated before the acknowledgment of successful connection establishment is received.
 
 Ref: https://github.com/redis/ioredis/issues/1003

**Comment by ViktarStarastsenka** [comment]
thanks, we will change the default value for `slotsRefreshTimeout`.

**Comment by alextaymx** [comment]
How do you build you own version? I have the same issue.

**Comment by WeberKuo** [comment]
Try this
https://github.com/RedisInsight/RedisInsight/wiki/changed-from-%22yarn-start:ui%22-to-%22yarn-dev:ui%22

**Comment by zalenskiSofteq** [comment]
page was renamed to:
https://github.com/RedisInsight/RedisInsight/wiki/How-to-build-and-contribute

**Comment by ViktarStarastsenka** [comment]
```slotsRefreshTimeout``` has been changed to 5000 with 2.52.
