### ISSUE TITLE
[Bug]: Link broken for download desktop version for Mac M1

### ISSUE THREAD

**Issue by canofm** [RedisInsight/RedisInsight#3444]
**Preconditions** (Any important steps we need to know)
Open a browser and go to: https://redis.io/

**Steps to reproduce** (How to reproduce what you found step by step)
Try to download the desktop version for Mac M1

**Actual behavior** (A short description of what you found)
Be forwarded into thank-you page and nothing happens. If you click on the link that says "If the download didn't started, click here" that link redirects to the main page.

**Expected behavior** (A short description of what you expected to find)
Download the app

**Screenshots** (Paste or drag-and-drop a screenshot or a link to a recording)

**Additional context** (Operating system, version of Redis Insight, Redis database version, Redis module version, database type, connection type, logs, or any other information)
I tried it with Chrome browser, clean cache and stuff, even with incognito mode on.

**Comment by ViktarStarastsenka** [comment]
thank you for reporting the issue
should be fixed by now (Mac m1 has been renamed to Apple silicon)
