### ISSUE TITLE
[Bug]: Restart in the "New version is now available" doesn't restart or update the app

### ISSUE THREAD

**Issue by joshrotenberg** [RedisInsight/RedisInsight#3461]
**Preconditions** (Any important steps we need to know)

Running Redis Insight Version 2.48.0 (2.48.0.109204) on MacOS 14.3.1 (23D60). 

**Steps to reproduce** (How to reproduce what you found step by step)

While running the app, the modal appeared (see screensot). Clicked "Restart". The app quits but nothing else happens. Restarting the app, I see the modal right away, but the same behavior persists.

**Actual behavior** (A short description of what you found)

The app appears to quit but no update takes place, and it never restarts.

**Expected behavior** (A short description of what you expected to find)

The app should quit, install the update, and restart.

**Screenshots** (Paste or drag-and-drop a screenshot or a link to a recording)

<img width="1512" alt="Screenshot 2024-06-04 at 5 16 01 PM" src="https://github.com/RedisInsight/RedisInsight/assets/3231/2b075d5c-56f8-414a-bcb0-0c32908aa456">

**Additional context** (Operating system, version of Redis Insight, Redis database version, Redis module version, database type, connection type, logs, or any other information)

* Redis Insight Version 2.48.0 (2.48.0.109204) 

* MacOS 14.3.1 (23D60).

**Comment by joshrotenberg** [comment]
Restarted but that didn't seem to fix it, same behavior. Explicitly quitting via the menu bar `Quit` worked, though.

**Comment by ViktarStarastsenka** [comment]
@joshrotenberg , Redis Insight has updated to 2.50, right?
