### ISSUE TITLE
[Bug]: Lowercase HGETALL returns (empty list or set)

### ISSUE THREAD

**Issue by rmirzojonov** [RedisInsight/RedisInsight#3465]
**Preconditions** (Any important steps we need to know)
Redis Insight 2.50.0

**Steps to reproduce** (How to reproduce what you found step by step)
Run command "hset cars name bmw price 30000" to create the hash

**Actual behavior** (A short description of what you found)
When I run command "hgetall cars" the result is (empty list or set).

**Expected behavior** (A short description of what you expected to find)
It should work similar as if I was running "HGETALL cars" which returns the result correctly. This issue persists in both CLI and Workbench

**Screenshots** (Paste or drag-and-drop a screenshot or a link to a recording)
![image](https://github.com/RedisInsight/RedisInsight/assets/18455507/fdc4d3d1-31c6-4a2d-86bc-65365d93988c)
![image](https://github.com/RedisInsight/RedisInsight/assets/18455507/16a3100c-1ef7-404f-8fa1-b14c56b7b939)

**Additional context** (Operating system, version of Redis Insight, Redis database version, Redis module version, database type, connection type, logs, or any other information)
Redis version: 7.2.3, Redis Insight version: 2.50.0

**Comment by rmirzojonov** [comment]
I managed to check the request and response, which RedisInsight was sending, request body: 
`{"command":"hgetall cars","outputFormat":"RAW"}` and the response was correctly received from api: `{"response":{"name":"bmw","price":"30000"},"status":"success"}`, but somehow the application is ignoring it.

**Comment by ViktarStarastsenka** [comment]
we will release a fix in July with 2.54.

**Comment by ViktarStarastsenka** [comment]
hi @rmirzojonov , this has been fixed with 2.54 (released today).
Please re-open the ticket if it still reproduces.
