### ISSUE TITLE
[Bug]: Search filter is not working

### ISSUE THREAD

**Issue by RazvanModex** [RedisInsight/RedisInsight#3466]
**Preconditions** (Any important steps we need to know)
None

**Steps to reproduce** (How to reproduce what you found step by step)
![image](https://github.com/RedisInsight/RedisInsight/assets/97091990/150b7127-628d-421a-a0fe-66dbec40c10a)

In addition, I get 0 search results whatever I type, including any 1 character and then Enter.

**Actual behavior** (A short description of what you found)
See above image

**Expected behavior** (A short description of what you expected to find)
```
Results: 150. Scanned 5575/5575
```
And something like the following:
![image](https://github.com/RedisInsight/RedisInsight/assets/97091990/2a6004c2-a34c-46fd-83f7-85b3d90c0405)

**Screenshots** (Paste or drag-and-drop a screenshot or a link to a recording)
Already provided.

**Additional context** (Operating system, version of Redis Insight, Redis database version, Redis module version, database type, connection type, logs, or any other information)
Windows 10 Business - 19045.4412
Redis Insight - 2.50.0
Redis Docker - bitnami/redis:7.2.5

Also, there is no documentation about how the search filter should work: https://redis.io/docs/latest/develop/connect/insight#search-features

In case this really is a bug, please focus on the actual product and not on the other 90% of code related to marketing features. This is the kind of functionality I needed when I installed Redis Insight **one hour** ago. Also, there is no way to copy the entire HASH data as raw text or JSON. Consider having a look over [this kick-ass project](https://dbeaver.io/) for DB management. And yes, the community version is still kick-ass.

**Comment by ViktarStarastsenka** [comment]
@RazvanModex, by default, it filters per exact match.
In your case, you need to use asterisks. Here is the list of supported glob-style patterns - https://redis.io/docs/latest/commands/keys/#:~:text=Supported%20glob%2Dstyle%20patterns%3A

**Comment by RazvanModex** [comment]
I can confirm that `*send-notification*` filter works. Thanks for providing documentation about how to use the search filter.
