### ISSUE TITLE
[Feature Request]:could you add offline analyze again in version2?

### ISSUE THREAD

**Issue by RGBCat** [RedisInsight/RedisInsight#3469]
**Problem description** (Describe the problem you would like to solve with this feature request or suggested idea).

**How often do you encounter this problem** (Describe how frequently this problem occurs).

**Alternatives considered** (Describe any alternative features or products you've considered).

**Additional information** (Add any other context or details here).

**Comment by ViktarStarastsenka** [comment]
hi @RGBCat , currently, this is not prioritized for the upcoming released. Updates will be posted in this ticket - https://github.com/RedisInsight/RedisInsight/issues/480
