### ISSUE TITLE
Reached the max retries per request limit (which is 1)Refer to "maxRetriesPerRequest" option for details.

### ISSUE THREAD

**Issue by xuruibin1234** [RedisInsight/RedisInsight#3475]
how to resolve this problem

**Comment by GnaneshKunal** [comment]
Hey @xuruibin1234,

Can you describe when exactly you are getting this error? 


Also, are you running RedisInsight behind a proxy? If so, can you provide us with the proxy configuration so we can look into it further?

**Comment by SumalathaC** [comment]
Enabling both **Use TLS** and **Use SNI** options while adding the database resolved the error for me.

**Comment by DoubleGInViet** [comment]
> Enabling both **Use TLS** and **Use SNI** options while adding the database resolved the error for me.
can you tell me exactly how you resolved the error, please?

**Comment by SumalathaC** [comment]
Hi, I was getting this error because SNI (Server Name Indicator) option was disabled. Please find attached the screenshot. 
<img width="1393" alt="Screenshot 2024-07-01 at 11 51 24" src="https://github.com/RedisInsight/RedisInsight/assets/44141131/06e3f3f7-3b72-4c4e-8490-b588c79ab329">

Enabled the SNI and provided the host name, then it fixed the error.

**Comment by ViktarStarastsenka** [comment]
@xuruibin1234 , please re-open the issue if you still have it.

**Comment by TheOtherRealm** [comment]
I am getting this all of a sudden after I needed to put down my docker ( `redis/redis-stack:latest & redis:latest` ) instance and spin it up again.  Looking at [node.redis.connection.strategy.ts](https://github.com/redis/RedisInsight/blob/main/redisinsight/api/src/modules/redis/connection/node.redis.connection.strategy.ts), in Function `getRedisOptions` on line 72 `// maxRetriesPerRequest: REDIS_CLIENTS_CONFIG.maxRetriesPerRequest,` is commented out.  Will try some more debugging, but it seems like a bug.

**Comment by TheOtherRealm** [comment]
> I am getting this all of a sudden after I needed to put down my docker ( `redis/redis-stack:latest & redis:latest` ) instance and spin it up again. Looking at [node.redis.connection.strategy.ts](https://github.com/redis/RedisInsight/blob/main/redisinsight/api/src/modules/redis/connection/node.redis.connection.strategy.ts), in Function `getRedisOptions` on line 72 `// maxRetriesPerRequest: REDIS_CLIENTS_CONFIG.maxRetriesPerRequest,` is commented out. Will try some more debugging, but it seems like a bug.

I will make a new issue
