### ISSUE TITLE
[Bug]: Msgpack preview doesn't seem to work with vmihailenco/msgpack/v5

### ISSUE THREAD

**Issue by shwarcu** [RedisInsight/RedisInsight#3478]
**Preconditions** (Any important steps we need to know)
Ideally ability to run simple GO program

**Steps to reproduce** (How to reproduce what you found step by step)

Use https://github.com/go-redis/cache to store some structs in Redis (it uses https://github.com/vmihailenco/msgpack)
Then check preview of the value in redisinsight.

Example code

```go
type example struct {
	ExampleString string `json:"example" msgpack:"example"`
	ExampleBool   bool   `json:"example_bool" msgpack:"example_bool"`
}

func Repro(redis *redis.Client) error {
	ctx := context.Background()
	c := cache.New(&cache.Options{
		Redis: redis,
	})

	example := example{ExampleString: "example", ExampleBool: true}
	if err := c.Set(&cache.Item{
		Ctx:   ctx,
		Key:   "example",
		Value: example,
		TTL:   5 * time.Minute,
	}); err != nil {
		return err
	}

	return nil
}

```

Gives preview 

![Screenshot 2024-06-10 at 13 22 18](https://github.com/RedisInsight/RedisInsight/assets/58426925/35155eb9-e247-4851-a8cc-1159e262b734)

**Actual behavior** (A short description of what you found)
I can't read preview of the data, preview for JSONs work fine but with messagepack preview contains errors.
Here is example after storing `true` boolean .
![Screenshot 2024-06-10 at 12 46 06](https://github.com/RedisInsight/RedisInsight/assets/58426925/66e0739a-4bef-493d-96d9-3fa1f5d5f00a)

Same goes for structs. Using tag `msgpack` to rename fields doesn't solve the problem.

**Expected behavior** (A short description of what you expected to find)
I expect ability to peek data stored in redis when they are encoded with messagepack. Ideally if it was displayed like json

**Screenshots** (Paste or drag-and-drop a screenshot or a link to a recording)
Added in steps above

**Additional context** (Operating system, version of Redis Insight, Redis database version, Redis module version, database type, connection type, logs, or any other information)
Redis: `redis:7` docker image
RedisInsight: `Version 2.50.0 (2.50.0.113336)`
OS: MacOS 14.5 (23F79)

**Comment by flyinghail** [comment]
@shwarcu I have the same problem with [tinylib/msgp](https://github.com/tinylib/msgp), how did you solve this problem?

**Comment by shwarcu** [comment]
This is caused by compression inside the library. You need to pass messagepack methods to cache constructor to override default marshal/unmarshal method. After this preview will work
