### ISSUE TITLE
[Bug]: Not saving/persisting connections between app runs v2.50.0.113335

### ISSUE THREAD

**Issue by richard-stafflink** [RedisInsight/RedisInsight#3491]
**Preconditions** (Any important steps we need to know)

Install using flatpak:
`flatpak install flathub com.redis.RedisInsight`

Version installed: v2.50.0.113335

**Steps to reproduce** (How to reproduce what you found step by step)

1. Start the application
2. Accept EULA & privacy settings
4. "Welcome" view is shown
3. "Add connection details manually" to local redis instance
5. "Test connection" ✅
6. Click button "Add Redis Database"
7. Close Add
8. Open App again
9. Old connections are shown very briefly (250ms)
10. EULA splash is shown again - This shouldn't happen

**Actual behavior** (A short description of what you found)

After step (10) clicking on accept again shows the "Welcome" view.
The connection to the local instance is gone

My thoughts: EULA splash is ignoring the previously saved state, then overrides the save connections.

**Expected behavior** (A short description of what you expected to find)

After step (8) I should see my saved connections

**Additional context** (Operating system, version of Redis Insight, Redis database version, Redis module version, database type, connection type, logs, or any other information)

Redis Insight: v2.50.0.113335
Ubuntu: 24.04
Redis: Docker image "redis:7.2-alpine"

**Comment by ArtemHoruzhenko** [comment]
@richard-stafflink Thank you for reporting this! 
As a workaround: could You try to create a folder inside user's home directory `mkdir ~/.redis-insight` until we fix this issue?

**Comment by richard-stafflink** [comment]
Thanks @ArtemHoruzhenko, that work-around fixed the issue.

**Comment by ViktarStarastsenka** [comment]
this issue should be fixed on FlatHub now with https://github.com/flathub/com.redis.RedisInsight/pull/52.
