### ISSUE TITLE
[Feature Request]: Hope to add a new color theme of follow system

### ISSUE THREAD

**Issue by zzzzail** [RedisInsight/RedisInsight#350]
In macOS or Windows 11, we can change the color theme with dark and light automatically.

I Hope RedisInsight has the feature could to set the color theme to follow the system color theme.

You guys are very good to us. Thanks so much.

**Comment by zzzzail** [comment]
That is not a bug. How to change?

**Comment by ViktarStarastsenka** [comment]
hi @zzzzail , this is added with 2.34 (released today). You can find the Color Theme control in the "General" secton of the Settings page.
