### ISSUE TITLE
[Bug]: Authorization server encountered a misconfiguration error and was unable to complete your request.

### ISSUE THREAD

**Issue by Ting817** [RedisInsight/RedisInsight#3501]
**Preconditions** (Any important steps we need to know)

**Steps to reproduce** (How to reproduce what you found step by step)

**Actual behavior** (A short description of what you found)

**Expected behavior** (A short description of what you expected to find)

**Screenshots** (Paste or drag-and-drop a screenshot or a link to a recording)

**Additional context** (Operating system, version of Redis Insight, Redis database version, Redis module version, database type, connection type, logs, or any other information)

**Comment by aka-mj** [comment]
I'm seeing the same error.

Ubuntu 20.04
Redis Insight 2.50.0

**Comment by ViktarStarastsenka** [comment]
can you add more details on how to reproduce this issue?

**Comment by ViktarStarastsenka** [comment]
@aka-mj , @Ting817 , you are trying to authenticate to Redis Cloud using your GitHub account, right?
If yes, can you please check that your GitHub account has a public email address?

**Comment by weilinzung** [comment]
it looks like Google Sign-in has no issue. If I don't want my email exposed on GitHub, any workarounds?

**Comment by ViktarStarastsenka** [comment]
@weilinzung , only Google Sign-in as an alternative

**Comment by Ting817** [comment]
hey, i can't sign in by Github account and Google account, both of them.

**Comment by Ting817** [comment]
At the beginning, it showed i didn't write the last name in google email. I did, but it still didn't work.

**Comment by Ting817** [comment]
Version 2.52.0 (2.52.0.116526)

**Comment by Ting817** [comment]
i checked my public email account in GitHub and Google, but it still didn't work. It showed "Server Error".

**Comment by ViktarStarastsenka** [comment]
@Ting817 , please check that you can authenticate directly via the website.
https://app.redislabs.com/#/
