### ISSUE TITLE
[Bug]: need to use upper case  letters in hgetall command in CLI

### ISSUE THREAD

**Issue by alexlalexl** [RedisInsight/RedisInsight#3525]
**Preconditions** (Any important steps we need to know)

**Steps to reproduce** (How to reproduce what you found step by step)
hset my:hash field1 value1 field2 value2 field3 value3

**Actual behavior** (A short description of what you found)
hgetall my:hash
(empty list or set)

**Expected behavior** (A short description of what you expected to find)
1) "field1"
2) "value1"
3) "field2"
4) "value2"
5) "field3"
6) "value3"

**Screenshots** (Paste or drag-and-drop a screenshot or a link to a recording)
![image](https://github.com/RedisInsight/RedisInsight/assets/6899867/1990c9ce-f562-4e4c-b07a-ca84d643c9d4)

**Additional context** (Operating system, version of Redis Insight, Redis database version, Redis module version, database type, connection type, logs, or any other information)

Redis Insight 2.50.0

**Comment by ViktarStarastsenka** [comment]
hi @alexlalexl , here is a similar ticket - https://github.com/RedisInsight/RedisInsight/issues/3465
I'll post an update there once the issue is fixed.
