### ISSUE TITLE
[Bug]: Redirect After Login Doesn't Work on Fedora 39 Silverblue

### ISSUE THREAD

**Issue by budiharyonoo** [RedisInsight/RedisInsight#3526]
**Preconditions** (Any important steps we need to know)
Have not login to the Redis Cloud account

**Steps to reproduce** (How to reproduce what you found step by step)
I tried to log in using the Cloud Sign In button, there were 2 options to log in using a Google or GitHub account. I clicked Sign Up with Google. After that, a new tab opened for Google Sign Up. I choose my Google account and everything was successful. But after the popup that had the text of `Thank you. You may close this window and navigate back to Redis Insight.` nothing happened even when I clicked the `Open Redis Insight` button.

**Actual behavior** (A short description of what you found)
Button Open Redis Insight on the web after login doesn't work

**Expected behavior** (A short description of what you expected to find)
My account can be signed in to my Redis Insight application

**Screenshots** (Paste or drag-and-drop a screenshot or a link to a recording)
![image](https://github.com/RedisInsight/RedisInsight/assets/91255312/2b5ea0d7-9ec6-4675-9fdc-1f650070f8f5)

**Additional context** (Operating system, version of Redis Insight, Redis database version, Redis module version, database type, connection type, logs, or any other information)
OS: Fedora 39 Silverblue
![image](https://github.com/RedisInsight/RedisInsight/assets/91255312/4f1e110b-1fb2-48b8-9294-b4a7391cd8cd)

**Comment by ViktarStarastsenka** [comment]
@budiharyonoo , how did you install Redis Insight? what Redis Insight package type do you use?

**Comment by budiharyonoo** [comment]
Hi Viktar, i installed Redis Insight using Flathub

**Comment by budiharyonoo** [comment]
> @budiharyonoo , currently, it does not work on FlatHub. we will look into this, but for now, you can install Applmage using https://github.com/TheAssassin/AppImageLauncher/wiki Deep linking should work there.

Oke thank you @ViktarStarastsenka I will try using AppImage
