### ISSUE TITLE
[Bug]: redis cluster don't show replicas nodes

### ISSUE THREAD

**Issue by raphaelauv** [RedisInsight/RedisInsight#3529]
I can't see replicas nodes of my redis cluster

![image](https://github.com/RedisInsight/RedisInsight/assets/10202690/ab65ddc8-2177-46f6-879b-5d59bfbc7b94)

**Comment by ViktarStarastsenka** [comment]
here is the same ticket, closing this as a duplicate - https://github.com/RedisInsight/RedisInsight/issues/3035
