### ISSUE TITLE
[Bug]:Page does not redirect after clicking on "Open Redis Insight" after clicking on signup with google.

### ISSUE THREAD

**Issue by im3dabasia** [RedisInsight/RedisInsight#3544]
**Preconditions** (Any important steps we need to know)

**Steps to reproduce** (How to reproduce what you found step by step)
1. Open Redis Insights App-image on a Linux Ubuntu. 
2. Connect to your database
3. login with your google id
4. Now you'd be redirected to your browser and a google oauth form will pop up
5. Select your email id 
6. Sign up will be done 
7. then you'd get to a page in which it'll say thank you and click on button to redirect to the redis insight app. 
8. Clicking the button does not re-direct back to the app where we had originally started from

**Actual behavior** (A short description of what you found)
After button click the app does not redirect us to the actual app in our host machine 

**Expected behavior** (A short description of what you expected to find)
After button click we should get back to the redis insight app on our host machine

**Screenshots** (Paste or drag-and-drop a screenshot or a link to a recording)

![image](https://github.com/RedisInsight/RedisInsight/assets/76681468/12db602b-181c-48e0-966b-6abc0a6dd97b)

**Additional context** (Operating system, version of Redis Insight, Redis database version, Redis module version, database type, connection type, logs, or any other information)
OS: Ubuntu Linux

**Comment by ViktarStarastsenka** [comment]
@im3dabasia , try installing AppImage using https://github.com/TheAssassin/AppImageLauncher/wiki
Deep linking should work there.

**Comment by ViktarStarastsenka** [comment]
the reason for this behavior is that deep linking does not work on AppImage. The alternative is to install AppImage via AppImageLauncher - deep linking should work with such a setup.
