### ISSUE TITLE
[Bug]: Regression: Ordering of key names containing numbers don't consider the number length

### ISSUE THREAD

**Issue by saadbruno** [RedisInsight/RedisInsight#3581]
## Preconditions

Running redis-stack on Docker

Seems like this is a regression between RedisInsight v2.46 and v2.50

## Steps to reproduce

- Create a Redis database and index
- Create a few items with key names using numbers (1 to 100)
- Open RedisInsight, select an index, and sort by Key Name (either ASC or DESC)

## Actual behavior
Keys are ordered as strings rather than numbers
0, 1, 10, 11, 12, ... , 2, 20, 21, 22

## Expected behavior
Keys should be ordered as numbers
0, 1, 2, 3, ..., 9, 10, 11, 12 ...

## Screenshots
✅ On v2.46, this bug does not happen:
![image](https://github.com/RedisInsight/RedisInsight/assets/23201434/53d234d2-db6b-45ae-ad5f-9c692df8ee64)

❌ On v2.50, keys are out of order
![image](https://github.com/RedisInsight/RedisInsight/assets/23201434/d60abef2-9f76-48ca-a585-86d386f29212)

## Additional context
I also have some keys with negative numbers (-100, -101), i don't know if this is tricking RedisInsight into considering all key names as strings, rather than numbers.

**Comment by ViktarStarastsenka** [comment]
hi, this is not a bug, the sorting order was changed to lexicographical with 2.50.
