### ISSUE TITLE
[Bug]: Copilot auth failed

### ISSUE THREAD

**Issue by dusty-cjh** [RedisInsight/RedisInsight#3593]
<img width="1223" alt="image" src="https://github.com/RedisInsight/RedisInsight/assets/45847340/aea7fd88-61f3-4ee8-bc62-330f4fdb552a">

**Comment by ViktarStarastsenka** [comment]
hi @dusty-cjh , try this - https://github.com/RedisInsight/RedisInsight/issues/3501#issuecomment-2208839583
re-open the ticket if the issue still persists.
