### ISSUE TITLE
[Feature Request]: Supports modifying host addresses .  proactively canceling connections when unable to connect.

### ISSUE THREAD

**Issue by hui411** [RedisInsight/RedisInsight#3598]
**Problem description** (Describe the problem you would like to solve with this feature request or suggested idea).
1、Does it support modifying Redis IP or host addresses
2.、How to cancel the connection when the ip or port is invalid. Because he will keep trying to connect, causing him to be unable to operate

**Comment by ViktarStarastsenka** [comment]
hi @hui411 ,
1. You can't modify the host once a database connection has been successfully added. To do so, you can add a new database connection.
2. There is no way, you need to wait till the connection times out.
