### ISSUE TITLE
[Bug]:Cannot be Authorized by Github account successfully

### ISSUE THREAD

**Issue by DataCreator0216** [RedisInsight/RedisInsight#3600]
After the GitHub account is authorized to log in, the following error is displayed after opening the Redis Insight button to jump to the Redis Insight client: "Misconfiguration Authorization server encountered a misconfiguration error and was unable to complete your request. Try again later.", the login is not authorized successfully

**Comment by Criquet234** [comment]
I am having the same issue.

**Comment by ViktarStarastsenka** [comment]
please check that your GitHub account has an email that is publicly available.

**Comment by DataCreator0216** [comment]
> please check that your GitHub account has an email that is publicly available.

There was an email with the subject line: "A third-party OAuth application has been added to your account" from The GitHub Team

**Comment by ViktarStarastsenka** [comment]
@DataCreator0216 , but can you check that you have a publicly available email address on GitHub?
as an alternative, you can use the Google sign-in option.

**Comment by DataCreator0216** [comment]
> @DataCreator0216 , but can you check that you have a publicly available email address on GitHub? as an alternative, you can use the Google sign-in option.

I have unchecked this option: "Keep my email addresses private". Is that ok? 
And I'm already logged in with my Google account, thanks for your reply!

**Comment by ViktarStarastsenka** [comment]
@DataCreator0216 , yep that option should be enough to log in with your GitHub account.
Also, we'll see options to make the error more meaningful.

**Comment by DataCreator0216** [comment]
> @DataCreator0216 , yep that option should be enough to log in with your GitHub account. Also, we'll see options to make the error more meaningful.

Uh oh, I don't know why the Github account is still not authorized to log in, but that doesn't matter, thanks again

**Comment by Criquet234** [comment]
Good afternoon.  My email address in Github is not private and when I attempt to use Google log in option, I keep getting "Authorization failed" message.  Any suggestions?

**Comment by MzWong0216** [comment]
> Good afternoon. My email address in Github is not private and when I attempt to use Google log in option, I keep getting "Authorization failed" message. Any suggestions?

Uh-oh, I've never been in that situation before, sorry. When I was authorized to log in with my Google account, my email address in Github is also not private. Here's only what I can tell you

**Comment by Criquet234** [comment]
It is ok and thanks anyways. :)

**Comment by ViktarStarastsenka** [comment]
@Criquet234 , can you try signing in via a website to validate that there are no issues with Redis Insight?

https://app.redislabs.com/
