### ISSUE TITLE
[Bug]: Google and Github SSO not working

### ISSUE THREAD

**Issue by jcaw07** [RedisInsight/RedisInsight#3619]
**Preconditions** (Any important steps we need to know)
New instance of Redis Insight

**Steps to reproduce** (How to reproduce what you found step by step)
1. Open Redis Insight
2. Click "create a free cloud database"
3. Select Github

**Actual behavior** (A short description of what you found)
A browser window opens with this text:
Thank you
You may close this window and navigate back to Redis Insight.
Click open Redis Insight below, if you don’t see a dialog.

When I click back into Redis Insight I get this text:
Misconfiguration
Authorization server encountered a misconfiguration error and was unable to complete your request.
Try again later.
If the issue persists, [report the issue.](https://github.com/RedisInsight/RedisInsight/issues)

**Expected behavior** (A short description of what you expected to find)
It creates a database I can use.

**Screenshots** (Paste or drag-and-drop a screenshot or a link to a recording)

**Additional context** (Operating system, version of Redis Insight, Redis database version, Redis module version, database type, connection type, logs, or any other information)

**Comment by ViktarStarastsenka** [comment]
hi @jcaw07 , can you try logging in via a website using Google or Github?
this is needed to understand if there is an issue with Redis Insight
https://app.redislabs.com/

**Comment by jcaw07** [comment]
I tried logging in using Github, and it gives me the error listed in the ticket.

**Comment by ViktarStarastsenka** [comment]
@jcaw07 , please check that you have a publicly available email address on GitHub.
as an alternative, you can use the Google sign-in option.

**Comment by ViktarStarastsenka** [comment]
here is a duplicate thread - https://github.com/RedisInsight/RedisInsight/issues/3600#issuecomment-2222508981
please re-open the ticket with additional information if this does not help
