### ISSUE TITLE
[Bug]: Redis Insight does not work on Windows 8.1

### ISSUE THREAD

**Issue by bialix** [RedisInsight/RedisInsight#3626]
**Preconditions** (Any important steps we need to know)
Install on Windows 8.1 with all updates.

**Steps to reproduce** (How to reproduce what you found step by step)
Run the program.

**Actual behavior** (A short description of what you found)
Error message says: function DiscardVirtualMemory does not found.

**Expected behavior** (A short description of what you expected to find)

**Screenshots** (Paste or drag-and-drop a screenshot or a link to a recording)

**Additional context** (Operating system, version of Redis Insight, Redis database version, Redis module version, database type, connection type, logs, or any other information)

**Comment by ViktarStarastsenka** [comment]
hi @bialix , Electron deprecated support for Windows 8.1 - https://www.electronjs.org/blog/windows-7-to-8-1-deprecation-notice.
Please update your Windows version.
