### ISSUE TITLE
[Bug]: Ubuntu Redis Insights crashes every time type in a text field

### ISSUE THREAD

**Issue by Coastis** [RedisInsight/RedisInsight#3636]
**Steps to reproduce** (How to reproduce what you found step by step)
Step 1 - Open redis insights on Ubuntu
Step 2 - Click +Add Redis Database in the top left
Step 3 - Start typing in any of the text fields

**Actual behavior** (A short description of what you found)
redis insights immediately freezes and then crashes after registering the first character in a field

**Expected behavior** (A short description of what you expected to find)
it should not crash

**Additional context** (Operating system, version of Redis Insight, Redis database version, Redis module version, database type, connection type, logs, or any other information)
Ubuntu 24
Redis Insights - 2.52.0
Redis Server - 7.0.15

**Comment by Coastis** [comment]
Well, this in strange... I've been trying to get it working again, and each time the "force quit or wait" dialog comes up i've been pressing wait. After repeating this for a dozen times, it actually started working. Curious, i restarted the laptop and it worked again without having to press wait a dozen times!

So, as it stands, insights is now working as expected. My best guess is, it was doing something on first boot that locked the process up. Hopefully this will help someone else experiencing the same issue. Cheers :)

**Comment by ViktarStarastsenka** [comment]
@Coastis , so the best recommendation ever to restart your laptop helps here :)

**Comment by kgromov** [comment]
> Well, this in strange... I've been trying to get it working again, and each time the "force quit or wait" dialog comes up i've been pressing wait. After repeating this for a dozen times, it actually started working. Curious, i restarted the laptop and it worked again without having to press wait a dozen times!
> 
> So, as it stands, insights is now working as expected. My best guess is, it was doing something on first boot that locked the process up. Hopefully this will help someone else experiencing the same issue. Cheers :)

The same issue is reproduced for me on Ubuntu 24.
redis insight version = 2.66
