### ISSUE TITLE
[Bug]:

### ISSUE THREAD

**Issue by jcaw07** [RedisInsight/RedisInsight#3666]
**Preconditions** (Any important steps we need to know)
Copilot encountered an error and requested to restart. Once I restarted, it still didn't work.

**Steps to reproduce** (How to reproduce what you found step by step)

**Actual behavior** (A short description of what you found)

**Expected behavior** (A short description of what you expected to find)

**Screenshots** (Paste or drag-and-drop a screenshot or a link to a recording)
![image](https://github.com/user-attachments/assets/8bc6e929-c8f5-48df-b24c-5c7871f890a3)

**Additional context** (Operating system, version of Redis Insight, Redis database version, Redis module version, database type, connection type, logs, or any other information)

**Comment by ViktarStarastsenka** [comment]
@jcaw07 , can you provide more details on how to reproduce this?

**Comment by ViktarStarastsenka** [comment]
Please reopen the ticket if this still persists.
