### ISSUE TITLE
[Bug]: v2 api missing ?

### ISSUE THREAD

**Issue by raphaelauv** [RedisInsight/RedisInsight#3677]
Where can I find the openapi of the v2 ?

with the v1 I could do 

```shell
curl --location --request POST 'redisinsight:5540/api/instance/' \
        --header 'Content-Type: application/json' \
                                  --data-raw '{
          \"name\": \"CLUSTER-LOCAL\",
          \"connectionType\": \"CLUSTER\",
          \"seedNodes\": [
            {
              \"host\": \"redis-main-1\",
              \"port\": 6379
            }
          ]
        }'
```

and it do not work with the v2 , thank you

**Comment by ViktarStarastsenka** [comment]
hi @raphaelauv , please check this thread - https://github.com/RedisInsight/RedisInsight/issues/289.
currently, there is no such documentation, but I'll take a note

**Comment by raphaelauv** [comment]
thanks @ViktarStarastsenka , yeah an openapi or swagger would be great

so for the v2 it's : 
```shell
curl --location --request POST 'redisinsight:5540/api/databases/' \
        --header 'Content-Type: application/json' \
                                  --data-raw '{
          \"name\": \"CLUSTER-LOCAL\",
          \"host\": \"redis-main-1\",
          \"port\": 6379
        }'
```

**Comment by ViktarStarastsenka** [comment]
@raphaelauv , yes, this should work.

**Comment by raphaelauv** [comment]
Why did you please ? There is no documentation of the api or a swagger or an openapi file

**Comment by ViktarStarastsenka** [comment]
@raphaelauv , agreed. The ticket will be closed once the documentation is out.

**Comment by zalenskiSofteq** [comment]
@raphaelauv 
only docker version of redis insight contains swagger
by default you can find docs on this url:
`http://localhost:5540/api/docs`

**Comment by raphaelauv** [comment]
@zalenskiSofteq thanks !!!!!!!

![image](https://github.com/user-attachments/assets/242b54ef-a721-4c1e-9d45-752de21f5fe6)

okay , so let's put that in the readme and documentation and also a link from the UI

**Comment by ViktarStarastsenka** [comment]
added this information to the repository (https://github.com/RedisInsight/RedisInsight), Docker (https://hub.docker.com/r/redis/redisinsight), and it will be mentioned on redis.io.
