### ISSUE TITLE
[Bug]: Unable to use transactions

### ISSUE THREAD

**Issue by fbozhang** [RedisInsight/RedisInsight#3690]
![image](https://github.com/user-attachments/assets/11f4df3e-dad5-45c7-9cc9-2349068d5e2e)

When I use transactions in the RedisInsight CLI window, I am unable to add two commands. The transaction can only be executed successfully if it contains exactly one command.

```
[db15] > multi
"OK"

[db15] > get a
"QUEUED"

[db15] > exec
1) "null"

[db15] > multi
"OK"

[db15] > get a
"QUEUED"

[db15] > get b
"Too many Cluster redirections. Last error: ReplyError: MOVED 3300 30.127.78.238:2504"

[db15] > exec
"EXECABORT Transaction discarded because of previous errors."

[db15] > exec
"ERR EXEC without MULTI"
```

Expected result as follows

![image](https://github.com/user-attachments/assets/18303f95-5b13-4996-a370-44a614feda23)

```
127.0.0.1:6379> MULTI
OK
127.0.0.1:6379> get a
QUEUED
127.0.0.1:6379> get b
QUEUED
127.0.0.1:6379> get c
QUEUED
127.0.0.1:6379> exec
1) (nil)
2) (nil)
3) (nil)
127.0.0.1:6379>
```

**Comment by fbozhang** [comment]
This issue is caused by the same machine. It cannot be reproduced on other machines.  #3689

**Comment by ViktarStarastsenka** [comment]
@fbozhang , please provide more information - https://github.com/RedisInsight/RedisInsight/issues/3689#issuecomment-2329240542

**Comment by ViktarStarastsenka** [comment]
please re-open the ticket if the issue still reproduces with Redis Insight 2.58.
