### ISSUE TITLE
[Feature Request]: Color assignment for connections.

### ISSUE THREAD

**Issue by cemilcelik** [RedisInsight/RedisInsight#3693]
**Problem description**
Colors might be assigned to connections. For example; red for prod, orange for stage, green for local etc. Thank you.

**How often do you encounter this problem**
N/A

**Alternatives considered**
N/A

**Additional information**
N/A

**Comment by ViktarStarastsenka** [comment]
hi, here is a duplicate ticket - https://github.com/RedisInsight/RedisInsight/issues/2911
