### ISSUE TITLE
[Bug]:Cannot be Authorized by Github account successfully

### ISSUE THREAD

**Issue by zc19990624** [RedisInsight/RedisInsight#3698]
**Preconditions** (Any important steps we need to know)

I've disabled the setting that keeps my email private, but I'm still unable to complete GitHub account authorization.
**Steps to reproduce** (How to reproduce what you found step by step)

**Actual behavior** (A short description of what you found)

**Expected behavior** (A short description of what you expected to find)

**Screenshots** (Paste or drag-and-drop a screenshot or a link to a recording)

**Additional context** (Operating system, version of Redis Insight, Redis database version, Redis module version, database type, connection type, logs, or any other information)

**Comment by ViktarStarastsenka** [comment]
hi @zc19990624 , can you please share this URL?

<img width="1339" alt="image" src="https://github.com/user-attachments/assets/5963d750-83fa-4bba-8d00-68c15a1f258b">

**Comment by AdityaJha012** [comment]
i am also not able to login trough github..

I believe it is because of the error=access_denied.
I used my correct github password

Here is the Link:-

https://auth.redisinsight.redis.com/callback.html?state=dNtREUn55qZcw42v2WQoMvcncpkyQTIxuVLBUtDpTfwOQ3rURITVkNX7YK9NPtJZ&error=access_denied&error_description=The+following+required+property+is+missing%3A+%27email%27.#success

**Comment by samarth3301** [comment]
even i am facing the same issue !

**Comment by ViktarStarastsenka** [comment]
@AdityaJha012 , the error says that your email is not set to public in your GitHub account.

**Comment by ArtemHoruzhenko** [comment]
@AdityaJha012 @samarth3301 You can go to github profile settings https://github.com/settings/profile and select public email from the list 
![image](https://github.com/user-attachments/assets/9b0b1494-7d23-422c-8bb1-99223db48565)

**Comment by ViktarStarastsenka** [comment]
Please check Redis Insight 2.56 (released today), the error message should be clearer now.
Reopen the ticket if any unclear error persists.

**Comment by samarth3301** [comment]
yupp

**Comment by zc19990624** [comment]
https://auth.redisinsight.redis.com/callback.html?state=zNXH1JeO0ddZGjQ8oREA83O2wLMYneQtKwO6piJFfMb9DVQLs29TnW12SCgdvBnn&error=access_denied&error_description=The+following+required+property+is+missing%3A+%27email%27.#success

**Comment by ViktarStarastsenka** [comment]
@zc19990624 , your email address is not public
