### ISSUE TITLE
[Feature Request]: Able to quickly delete a folder

### ISSUE THREAD

**Issue by zhang8473** [RedisInsight/RedisInsight#3700]
**Problem description** (Describe the problem you would like to solve with this feature request or suggested idea).
I have to type lots of text to bulk delete a folder. and click on "load more" multiple times in case of too many keys. There's no easy way.

**How often do you encounter this problem** (Describe how frequently this problem occurs).
Always.

**Alternatives considered** (Describe any alternative features or products you've considered).

**Additional information** (Add any other context or details here).
RESP.app has this feature.

**Comment by ViktarStarastsenka** [comment]
hi @zhang8473 , you can use the bulk actions (top right corner). To delete keys in bulk, set filters per key name first.

<img width="1430" alt="image" src="https://github.com/user-attachments/assets/b698db8a-1b94-43ae-8910-76c278cdd287">

**Comment by ViktarStarastsenka** [comment]
please re-open the ticket if the solution above does not work for you
