### ISSUE TITLE
 Redis insight Mac auto update to a new version which do not support mac10.13

### ISSUE THREAD

**Issue by vitechliu** [RedisInsight/RedisInsight#3707]
I was using redis insight 2.52.0 and one day I found the app icon become inaccessable which means it auto update to a new version.
clicking the app icon shows it only support mac 10.15+ while I'm using mac 10.13
I want to know how to disable auto update

**Comment by ViktarStarastsenka** [comment]
hi @vitechliu , desktop application always automatically updates. As an alternative, you can use Redis Insight on Docker - https://hub.docker.com/r/redis/redisinsight

**Comment by GeekHF** [comment]
Could you add a function to stop auto update
