### ISSUE TITLE
[Bug]: Cannot login through software

### ISSUE THREAD

**Issue by SwyfterThanU** [RedisInsight/RedisInsight#3722]
I keep getting a "server error" when trying to sign into my account through google via "cloud sign in".

The expected behavior should be to log me in..

https://cdn.discordapp.com/attachments/1053046679777054751/1275165684216758272/chrome_nT5cQpxCOp.mp4?ex=66c4e616&is=66c39496&hm=4618ffed18b84372b0221fb5872698181a824ab1d8d19db7490459d62d2197fb&

Insight Version (Or database info, not sure): 
![Redis_Insight_hITwXEmIiI](https://github.com/user-attachments/assets/8c93a365-7912-4fa8-8d90-b84274f5eef4)

**Comment by ViktarStarastsenka** [comment]
@SwyfterThanU , can you send logs? Please sanitize any sensitive data before sending them.
You can find logs in the ".redis-insight" folder under your user.

**Comment by SwyfterThanU** [comment]
Hi, @ViktarStarastsenka.

I cleared the logs file to see what I get. When repeating the same steps, I get two JSON files and two '.log.0' files.

The '.log.0' files have no data (0 KB), there is nothing in them when I open them in notepad.

The JSON files have some information, but I don't know how helpful it will be. 

JSON File 1:
![Code_2YsEDmXixk](https://github.com/user-attachments/assets/c53e439a-cb91-4585-a801-9bfb165fae31)

JSON File 2:
![Code_6aR5Bw53zZ](https://github.com/user-attachments/assets/6e40d47a-ca61-45f2-90e5-1391f8846f27)

Thanks you for any assistance.

**Comment by sahilr2050** [comment]
Same for me

![image](https://github.com/user-attachments/assets/b6c68401-ef88-4da6-8317-b8241f37f739)

**Comment by ViktarStarastsenka** [comment]
Please check Redis Insight 2.56 (released today), the error message should be clearer now.
Reopen the ticket if any unclear error persists.
