### ISSUE TITLE
[Bug]: Cannot Login with oAuth

### ISSUE THREAD

**Issue by red-color001** [RedisInsight/RedisInsight#3770]
**Preconditions** (Any important steps we need to know)

**Steps to reproduce** (How to reproduce what you found step by step)

**Actual behavior** (A short description of what you found)

**Expected behavior** (A short description of what you expected to find)

**Screenshots** (Paste or drag-and-drop a screenshot or a link to a recording)

**Additional context** (Operating system, version of Redis Insight, Redis database version, Redis module version, database type, connection type, logs, or any other information)

**Comment by ViktarStarastsenka** [comment]
Please check Redis Insight 2.56 (released today), the error message should be clearer now.
Reopen the ticket if any unclear error persists.
