### ISSUE TITLE
[Bug]: unable to login in redis insights with github

### ISSUE THREAD

**Issue by ashikurrb** [RedisInsight/RedisInsight#3775]
Showing server error
![image](https://github.com/user-attachments/assets/8459d013-da9e-41eb-bb86-834f9360cd37)

**Comment by ma-pony** [comment]
<img width="555" alt="image" src="https://github.com/user-attachments/assets/7372cddf-83ed-44df-8da8-5774e49df9ed">

**Comment by kailih** [comment]
Seeing similar error:

![Screenshot 2024-09-01 232922](https://github.com/user-attachments/assets/122f0cda-b9ab-4596-b0fb-849c7ba6c571)

**Comment by baikov** [comment]
> Seeing similar error:
> 
> ![Screenshot 2024-09-01 232922](https://private-user-images.githubusercontent.com/40885486/363581577-122f0cda-b9ab-4596-b0fb-849c7ba6c571.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUzNzAwNjgsIm5iZiI6MTcyNTM2OTc2OCwicGF0aCI6Ii80MDg4NTQ4Ni8zNjM1ODE1NzctMTIyZjBjZGEtYjlhYi00NTk2LWIwZmItODQ5YzdiYTZjNTcxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTAzVDEzMjI0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA3ZGYxOGMyMmUwODEyNzk3ZDBhNDEzMTc3MWI2YmM0OWExZDA0ZTQyNDIxMmY4OTkzYmE0NmZiZDgyNWM3ZDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.aFshWU7FEljUXpp7V6S0tJnt2w0rlvuxg05JZsd05WE)

same error

**Comment by mldisibio** [comment]
On Redis 2.54.0

> Seeing similar error:
> 
> ![Screenshot 2024-09-01 232922](https://private-user-images.githubusercontent.com/40885486/363581577-122f0cda-b9ab-4596-b0fb-849c7ba6c571.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU1NjU2OTAsIm5iZiI6MTcyNTU2NTM5MCwicGF0aCI6Ii80MDg4NTQ4Ni8zNjM1ODE1NzctMTIyZjBjZGEtYjlhYi00NTk2LWIwZmItODQ5YzdiYTZjNTcxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA1VDE5NDMxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVhYjhmMTRmZmZhMWQ4ZGJkYmQ5ODA2NDZlNWQ3MDNmYjI1NjY3ZWU5ODc3MGU0YzIzNzllYzYxYzgwMjA1NzgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.oH9wga0ccRpoxOX--Nn-Uk8u42InW4e1YflLzciH_ms)

**Comment by ViktarStarastsenka** [comment]
here is a relevant thread - https://github.com/RedisInsight/RedisInsight/issues/3600#issuecomment-2222508981

**Comment by mldisibio** [comment]
> here is a relevant thread - [#3600 (comment)](https://github.com/RedisInsight/RedisInsight/issues/3600#issuecomment-2222508981)

I think this should still be reported as an issue. I have several GitHub authorized applications that used OAuth just fine without the email being marked as public. Seems like requiring users to change their privacy settings in GitHub should not be necessary.

**Comment by ViktarStarastsenka** [comment]
@mldisibio , there is nothing that Redis Insight can do - a public email is required by Redis Cloud to be authenticated.

**Comment by ViktarStarastsenka** [comment]
also, please check Redis Insight 2.56 (released today), the error message should be clearer now.
Reopen the ticket if any unclear error persists.
