### ISSUE TITLE
[Feature Request]: Ordering of the list of keys.

### ISSUE THREAD

**Issue by RattleSneek** [RedisInsight/RedisInsight#3777]
When you open the app and access a specific database, you get a list of keys, which are unordered. I would like it when these keys would be ordered by alphabet. When you have a lot of keys which are mostly similar (containing ID's for instance), you can then easily find a range of values or maybe look for missing ID's.

**Comment by ViktarStarastsenka** [comment]
hi, you can sort keys by their names in the Tree view.
