### ISSUE TITLE
[Bug]: Cannot connect to localhost database, with the Redis-server DB running

### ISSUE THREAD

**Issue by hungkien05** [RedisInsight/RedisInsight#378]
**Preconditions** (Any important steps we need to know)
Start redis-server on local machine

**Steps to reproduce** (How to reproduce what you found step by step)
Connect to the local Redis db through RedisInsight

**Actual behavior** (A short description of what you found)
Error returned "Could not connect: Error 111 connecting to 127.0.0.1:6379. Connection refused."

**Expected behavior** (A short description of what you expected to find)
Connect successfully

**Screenshots** (Paste or drag-and-drop a screenshot or a link to a recording)

**Additional context** (Operating system, version of RedisInsight, Redis database version, Redis module version, database type, connection type, logs, or any other information)
Redis server v=5.0.7
Redisinsight:latest

**Comment by GnaneshKunal** [comment]
Hey @hungkien05, Looks like you are running redis on you local machine and RedisInsight on docker. Try connecting to the redis via its local IP address that starts with 192.xxx

**Comment by hungkien05** [comment]
> Hey @hungkien05, Looks like you are running redis on you local machine and RedisInsight on docker. Try connecting to the redis via its local IP address that starts with 192.xxx
> 
> Here's a demo video: https://streamja.com/WL01j

Thanks a lot !

**Comment by fresonn** [comment]
Link isn't working

Value from `ipconfig getifaddr en0` didn't help

**Comment by ViktarStarastsenka** [comment]
@fresonn , please create a new ticket and describe your setup.
