### ISSUE TITLE
[Bug]:UI Bugs Prevent Editing Value in Redis Insight

### ISSUE THREAD

**Issue by jb-dev1** [RedisInsight/RedisInsight#3783]
**Preconditions** (Any important steps we need to know)
Not aware of any.

**Steps to reproduce** (How to reproduce what you found step by step)
Using Next.js 14 with a Redis db in Docker, I have a basic db setup with a simple KV structure. I send an array of messages from a chat app to the database. I am using a clone of Vercel's ai-chatbot at https://github.com/vercel/ai-chatbot with a local Redis db on Docker rather than the Vercel KV (aka Upstash Redis).

**Actual behavior** (A short description of what you found)
Occasionally I need to edit the message array for testing, and I choose to do so via Redis Insight. When I click on the value for the record (hash) that contains the array (in JSON structure), and it contains more than 50K characters made up of multiple chat messages in a JSON array, the UI prevents me from editing and winds up in a very odd state.  

See screenshots.

**Expected behavior** (A short description of what you expected to find)
I expect to be able to edit the array without the UI bug that prevents me from editing, and prevents me from clicking the checkbox to save.

**Screenshots** (Paste or drag-and-drop a screenshot or a link to a recording)
1. Clicked the pencil icon to edit, everything looks normal so far and I can usually directly edit the contents of the JSON (text hidden on purpose):

![image](https://github.com/user-attachments/assets/e3555670-4051-4cba-8744-f6760e313c2c)

2. I then drag the cursor over a large selection of text (let's say, more than 25K characters) to delete it and replace with new text. When I press a key to start overwriting the text or when I press the delete button to delete part of the text so I can start entering new text, the cell in the UI immediately shrinks, I am unable to edit or add text, and the X and checkmark buttons are out of view.

![image](https://github.com/user-attachments/assets/b5261caa-4dc8-4005-bcb4-4e176d334326)

This only happens on very long values when editing via the UI. I do not recall it ever happening in the last version of Redis Insight, and I've been using it for months and happily editing values all the time until now.

**Additional context** (Operating system, version of Redis Insight, Redis database version, Redis module version, database type, connection type, logs, or any other information)
MacOS Sonoma 14.6.1, Redis Insight 2.54.0.119099 (I don't recall having this issue before the recent update)

**Comment by ViktarStarastsenka** [comment]
@jb-dev1 , thank you for reporting this issue
Please try it with Redis Insight 2.56 (released today).
Reopen the ticket if the issue still persists.
