### ISSUE TITLE
[Feature Request]: doc - how disable telemetry ?

### ISSUE THREAD

**Issue by raphaelauv** [RedisInsight/RedisInsight#3784]
How can we disable the telemetry ? thanks

**Comment by ViktarStarastsenka** [comment]
hi, the control is available on the Settings page

<img width="1005" alt="image" src="https://github.com/user-attachments/assets/6b00fdc7-2658-45f2-b07f-22a7055f5354">

**Comment by raphaelauv** [comment]
thanks @ViktarStarastsenka , is there an option to disable it programmatically , with a venv ?

**Comment by ViktarStarastsenka** [comment]
currently, there is no option - only via UI
