### ISSUE TITLE
Make binary available on GitHub

### ISSUE THREAD

**Issue by WeihanLi** [RedisInsight/RedisInsight#3791]
Related to https://github.com/RedisInsight/RedisInsight/issues/110

Is it possible to download the installer or binary from the github release directly?

**Comment by ViktarStarastsenka** [comment]
hi @WeihanLi , Redis Insight installers are available on redis.io, Microsoft Store, Apple Store, Snapcraft, and FlatHub. Additionally, you can use Docker Hub.
Currently, there is no plan to distribute them also via GitHub.
