### ISSUE TITLE
[Bug]:the open is redis Insight button isn't working

### ISSUE THREAD

**Issue by 04monstar** [RedisInsight/RedisInsight#3793]
**Preconditions** (Any important steps we need to know)

**Steps to reproduce** (How to reproduce what you found step by step)

**Actual behavior** (A short description of what you found)

**Expected behavior** (A short description of what you expected to find)

**Screenshots** (Paste or drag-and-drop a screenshot or a link to a recording)

**Additional context** (Operating system, version of Redis Insight, Redis database version, Redis module version, database type, connection type, logs, or any other information)

**Comment by ViktarStarastsenka** [comment]
@04monstar , can you please provide more details?

**Comment by 04monstar** [comment]
When I connect my redis insight with my redis cloud account, after
verifying my account the button( open redis insight) button isn't working

**Comment by ViktarStarastsenka** [comment]
@04monstar , what Redis Insight build do you use and on what OS?

**Comment by 04monstar** [comment]
I'm using manjora Linux and redis insight-linux-x86_64.appimage

**Comment by ViktarStarastsenka** [comment]
@04monstar , deep linking does not work on AppImage. The alternative is to install AppImage via AppImageLauncher - deep linking should work with such a setup.
or try Debian

**Comment by 04monstar** [comment]
Thanks, I'll check it out.
