### ISSUE TITLE
[Bug]: When using Redis Copilot and login with two authenticator factor before acepting agree terms, login fails

### ISSUE THREAD

**Issue by CristianAcevedo1989** [RedisInsight/RedisInsight#3798]
This are the stepts I did:

-Click on start using Redis Copilot.
-Sign in with Github
-A new window in my laptop is opened suggesting to use two authenticator factor.
-I inserted google authentication for github.
-This window appears in my browser:
![image](https://github.com/user-attachments/assets/e07daf4f-e00a-4719-bf6c-abb34be6bbb4)
-But finally the communication between fails
![image](https://github.com/user-attachments/assets/9e6b8e4f-50d8-4de9-be54-f9642ca40a2e)

Redis Insight version: 2.54.0

**Comment by ViktarStarastsenka** [comment]
@CristianAcevedo1989 , here is a relevant thread - https://github.com/RedisInsight/RedisInsight/issues/3600#issuecomment-2222508981

**Comment by ViktarStarastsenka** [comment]
also, please check Redis Insight 2.56 (released today), the error message should be clearer now.
Please reopen the ticket if any unclear error persists.

**Comment by CristianAcevedo1989** [comment]
Thanks you so much @ViktarStarastsenka, after to set my email to public the login was successfull.
