### ISSUE TITLE
[Bug]:Last field hidden in UI when looking at a Hash's Fields

### ISSUE THREAD

**Issue by jb-dev1** [RedisInsight/RedisInsight#3826]
**Preconditions** (Any important steps we need to know)
None

**Steps to reproduce** (How to reproduce what you found step by step)
Open Redis Insight, click on a Hash, look at the list of Fields.

In my screenshot you can see that there is a hidden Field named `color1` that has a value `orange` that I can get to show if I hover very close to the bottom of the screen. Also, since there is no feature like #3825, I cannot re-sort the fields to manually change the value of this for testing. 

**Actual behavior** (A short description of what you found)
The last Field is obscured from view in every Hash I click on.

**Expected behavior** (A short description of what you expected to find)
I should be able to see all Fields.

**Screenshots** (Paste or drag-and-drop a screenshot or a link to a recording)
![image](https://github.com/user-attachments/assets/9e4efb90-5d88-42b0-823c-00f713a2757c)

**Additional context** (Operating system, version of Redis Insight, Redis database version, Redis module version, database type, connection type, logs, or any other information)

This issue seems to have started after my last bug #3783 was fixed.

MacOS Sonoma 14.6.1, Redis Insight 2.56.0.122214

**Comment by jb-dev1** [comment]
@ViktarStarastsenka hopefully you can fix this one too. 😅

**Comment by Aoikumo41** [comment]
I also encountered this problem.

**Comment by ViktarStarastsenka** [comment]
hi, this should be fixed with 2.58 (released today). Please re-open the ticket if the issue still reproduces.
