### ISSUE TITLE
[Bug]: `Use SNI` option saving, however not showing as ticked on subsequent edit's (also affects importing of databases)

### ISSUE THREAD

**Issue by EB-Teampeak** [RedisInsight/RedisInsight#3833]
**Preconditions**
Set up a redis database accessible via TLS that is routed to via SNI

**Steps to reproduce**
1. Manually add the database and tick `Use TLS` and `Use SNI`
2. Verify that you can connect to the database
3. Click edit the connection
4. See that the `Use SNI` tickbox is now unchecked
5. Click Apply changes
6. Get an error

**Additional context**
Using RedisInsightas a docker container via docker compose `redis/redisinsight:latest` at (2024-09-16) (I can't seem to find the actual version being used in the UI)

This also causes issues when exporting the database configuration and subsequently importing it ( `tlsServername` field is present in the export, however it is not being applied on save, resulting in the imported database being inaccessible, same error you get when at 6. )

**Comment by ViktarStarastsenka** [comment]
hi @EB-Teampeak , this should be fixed with 2.58 (released today). Please re-open the ticket if the issue still reproduces.
