### ISSUE TITLE
[Bug]:使用GitHub登录服务器遇到配置错误，一直登录不上

### ISSUE THREAD

**Issue by Dinopell** [RedisInsight/RedisInsight#3841]
**Preconditions** (Any important steps we need to know)

**Steps to reproduce** (How to reproduce what you found step by step)

**Actual behavior** (A short description of what you found)

**Expected behavior** (A short description of what you expected to find)

**Screenshots** (Paste or drag-and-drop a screenshot or a link to a recording)

**Additional context** (Operating system, version of Redis Insight, Redis database version, Redis module version, database type, connection type, logs, or any other information)
![image](https://github.com/user-attachments/assets/6217875a-05fe-40f3-aff5-6b40b84ef702)

**Comment by ViktarStarastsenka** [comment]
@Dinopell , I think that your email address is not public.
You also can try Redis Insight 2.56, it provides more detailed error messages.

**Comment by ViktarStarastsenka** [comment]
please re-open the ticket if the issue still reproduces with Redis Insight 2.58
