### ISSUE TITLE
[Feature Request]:

### ISSUE THREAD

**Issue by systemview2018** [RedisInsight/RedisInsight#385]
**Problem description** (Describe the problem you would like to solve with this feature request or suggested idea).
Please make the key list as tree list. Like "Another Redis Destop Manager". It is very easy to collapse the use used keys.

**How often do you encounter this problem** (Describe how frequently this problem occurs).

**Alternatives considered** (Describe any alternative features or products you've considered).

**Additional information** (Add any other context or details here).

**Comment by ViktarStarastsenka** [comment]
Hello @systemview2018 , the Tree view has been added with the latest release. You can download it here: https://redis.com/redis-enterprise/redis-insight/#insight-form
