### ISSUE TITLE
[Bug]: Button "Load all" for large strings is not showing up in the latest versions.

### ISSUE THREAD

**Issue by gonchor** [RedisInsight/RedisInsight#3867]
**Preconditions** (Any important steps we need to know)
Create a string key with a very large data. Could be a large json string.

**Steps to reproduce** (How to reproduce what you found step by step)
1. Create a string key
2. Fill it with enough data so that RedisInsight will clip the whole string
3. Attempt to retrieve the whole value

**Actual behavior** (A short description of what you found)
You will never be able to retrieve the whole value, since the button 'Load all' doesn't show up anymore.

**Expected behavior** (A short description of what you expected to find)
The button Load all appears and clicking on it the whole value of the key is retrieved.

**Screenshots** (Paste or drag-and-drop a screenshot or a link to a recording)
![image](https://github.com/user-attachments/assets/b836a0e9-e636-40eb-bcad-9c83e357f43f)

**Additional context** (Operating system, version of Redis Insight, Redis database version, Redis module version, database type, connection type, logs, or any other information)
Windows 11 64 Bit
Redis 8.0-M01 released

Current workaround is to revert RedisInsight to older versions.

**Comment by developersahab** [comment]
@gonchor There’s a UI issue with Redis Insight: the buttons are partially hidden behind the CLI bar at the bottom. You can still click on them, but they’re hard to see. I hope this gets fixed in a future update.

<img width="805" alt="image" src="https://github.com/user-attachments/assets/16c240a6-5b14-44ab-bea1-409b7d1bd076">

**Comment by ViktarStarastsenka** [comment]
hi @gonchor , this should be fixed with 2.58 (released today). Please re-open the ticket if the issue still reproduces.
