### ISSUE TITLE
[Bug]: RedisInsight 2.54 Docker Initialization Errors

### ISSUE THREAD

**Issue by SStranks** [RedisInsight/RedisInsight#3886]
**Preconditions** 
Running RedisInsight 2.54 Docker Image, on Docker Rootless, Node v.20.9.0, WSL2/Ubuntu

**Steps to reproduce**
Created a container with the redisinsight image file - running other containers (redis, postgres, etc)

**Actual behavior**
During the initialization of the container, the Docker Daemon is reporting 30 or so errors that seem to indicate outgoing requests that are failing.

**Expected behavior**
No errors in the docker daemon console

**Screenshots** 
![image](https://github.com/user-attachments/assets/d332e571-7381-4d2a-b12b-de6164a78b74)

Looking at the RedisInsight logs, there was only one logged error during the initialization captured in the image above; 
![image](https://github.com/user-attachments/assets/07cc9629-b51e-4afc-b7c7-5baf9a56a86c)

Are all these outgoing requests regarding the update of 'commands' as the logs perhaps indicate? They all seem to be pointing towards github (raw, object, etc) but it doesn't specify the full request so I can't discern what is happening.

As far as I can tell RedisInsight is working fine, it interacts with my Redis container, the browser UI has no obvious errors or anything.

**Comment by ViktarStarastsenka** [comment]
@SStranks , you can ignore such errors. In this case, some data (e.g., Redis command syntax) will not be updated automatically.
Just do not forget to update the Redis Insight version once in a while to have everything up to date.
