### ISSUE TITLE
[Bug]: Setting "Set the amount of keys to scan per one iteration" doesn't work

### ISSUE THREAD

**Issue by KateTyush** [RedisInsight/RedisInsight#3889]
**Steps to reproduce**:

1. Open "Settings" -> "Advanced"
2. Set the amount of keys to scan per one iteration to 200.000
![image](https://github.com/user-attachments/assets/84cdc970-6152-40bb-b7f9-da0b2fb93394)

3. Open any database 

**Actual behavior** 

Just 10.000 keys are scanned

![image](https://github.com/user-attachments/assets/e6b76104-df25-4572-b491-263859a64433)

**Expected behavior** (A short description of what you expected to find)
200.000 keys should be scanned

**Additional context**
MacOS
Redis Insight version 2.58.0 (2.58.0.124100)

**Comment by ViktarStarastsenka** [comment]
hi @KateTyush , the "keys to scan setting" means a bit different thing. And I agree that the name is confusing.
Here is a description of what it does - https://github.com/RedisInsight/RedisInsight/issues/526#issuecomment-1728437429
