### ISSUE TITLE
[Feature Request]: Export key/value data from Browser tab

### ISSUE THREAD

**Issue by tzographos** [RedisInsight/RedisInsight#3910]
**Problem description** (Describe the problem you would like to solve with this feature request or suggested idea).
Unable to easily export a subset of keys and their corresponding values to a popular format e.g. csv, xml etc.

**How often do you encounter this problem** (Describe how frequently this problem occurs).
Always

**Alternatives considered** (Describe any alternative features or products you've considered).
redis-cli 

**Additional information** (Add any other context or details here).
-

**Comment by ViktarStarastsenka** [comment]
here is the same request - https://github.com/RedisInsight/RedisInsight/issues/3819
