### ISSUE TITLE
[Bug]: duplicate database entries after upgrade in <Redis Databases>

### ISSUE THREAD

**Issue by yan-hic** [RedisInsight/RedisInsight#3926]
Using RI 2.58.0.

Upgraded existing db from free to paid. 
See the same db - same exact url+port and content - twice.

Hesitant to delete one entry as it may drop the db altogether.

Can provide screenshot and account # in email.

**Comment by ViktarStarastsenka** [comment]
hi @yan-hic , do you see the same URL+port in Redis Insight or on Redis Cloud?

**Comment by yan-hic** [comment]
> hi @yan-hic , do you see the same URL+port in Redis Insight or on Redis Cloud?

Only Redis Insight (2.58.0). In RCloud it's ok.

**Comment by ViktarStarastsenka** [comment]
got it, @yan-hic , you can remove the duplicate database connection in Redis Insight, this is completely safe and will not affect Redis Cloud.
Please re-open this ticket if you have any other concerns or questions.
