### ISSUE TITLE
[Bug]: Protocol error, got "H" as reply type byte.

### ISSUE THREAD

**Issue by PurdueDude** [RedisInsight/RedisInsight#3944]
**Preconditions** (Any important steps we need to know)
Bring up Redis databases software

**Steps to reproduce** (How to reproduce what you found step by step)
Manually enter the "port" value and the "Database Alias" 
click "Add Redies Database" and got the "Protocol error, got "H" as reply type byte. Please report this." error

**Actual behavior** (A short description of what you found)
Got this error message popup ->  "Protocol error, got "H" as reply type byte. Please report this." 

**Expected behavior** (A short description of what you expected to find)
Expect to see it would connect to the database and display the results

**Screenshots** (Paste or drag-and-drop a screenshot or a link to a recording)

**Additional context** (Operating system, version of Redis Insight, Redis database version, Redis module version, database type, connection type, logs, or any other information)

**Comment by ViktarStarastsenka** [comment]
@PurdueDude , try using SNI to connect to your database
<img width="516" alt="image" src="https://github.com/user-attachments/assets/45ef40b3-4800-40eb-9415-183d14379d15">

**Comment by ViktarStarastsenka** [comment]
@PurdueDude , did you try SNI?

**Comment by ViktarStarastsenka** [comment]
please re-open the ticket if the issue still reproduces
