### ISSUE TITLE
[Feature Request]: Have the ability to visualise balance between master shards 

### ISSUE THREAD

**Issue by pierrelambert** [RedisInsight/RedisInsight#395]
**Problem description** (Describe the problem you would like to solve with this feature request or suggested idea).
When using Redis Enterprise (or any) with clustered database, using tags in key names, it would be nice from a developer standpoint to have the information on how the master shards are balanced.
Database Memory used: 10G
Shard 1 Memory Used: 2G
Shard 2 Memory Used: 3G
Shard 3 Memory Used: 2.5G
Shard 4 Memory Used: 2.5G 

&/or Shard Repartition: 20%/30%/25%/25%

**Comment by ViktarStarastsenka** [comment]
Hi @pierrelambert , thank you for bringing this feature up. Currently, we will not be able to fit this into upcoming releases, but we are open to contributions.
