### ISSUE TITLE
[Feature Request]:Support multiple delimeters (OR condition) or Regex delimeter

### ISSUE THREAD

**Issue by peweetheman** [RedisInsight/RedisInsight#3989]
**Problem description** (Describe the problem you would like to solve with this feature request or suggested idea).
Support has been added for setting custom delimiter. However many Redis usages have multiple delimiters ":", "/" in same database. Add support for Regex expression for delimiter or for setting multiple delimiters.

**How often do you encounter this problem** (Describe how frequently this problem occurs).
Daily PITA.

**Alternatives considered** (Describe any alternative features or products you've considered).
Updating my database to use single delimiter... Hoping many other ppl also have multiple delimiters so that the change can be on the UI end though.

**Additional information** (Add any other context or details here).

**Comment by ViktarStarastsenka** [comment]
hi @peweetheman , this has been added with Redis Insight 2.62, released today.
