### ISSUE TITLE
[Feature Request]: Support of Monitor command

### ISSUE THREAD

**Issue by ollopaci** [RedisInsight/RedisInsight#40]
**Problem description**

I would like to stream all the commands executed within the Redis database so that I can understand what is happening to it for debugging purposes. 

Currently monitor command is not supported in RedisInsight workbench or cli.

**Additional information** 

It would be good to be able to filter executed commands per client, command or some other text string.

**Comment by ViktarStarastsenka** [comment]
Profiler tool has been added to monitor commands executed within databases.
