### ISSUE TITLE
[Feature Request]:Default Redis Connection Configuration via Environment Variables

### ISSUE THREAD

**Issue by xuean** [RedisInsight/RedisInsight#4045]
**Problem description** (Describe the problem you would like to solve with this feature request or suggested idea).
I have deployed RedisInsight into an Amazon EKS cluster and intend to use it as a Redis reviewer for the Redis instances running within the cluster. However, I found that I cannot configure a default Redis connection automatically; I must manually create the connection each time.

It would be highly beneficial to support the configuration of a default Redis connection via environment variables. This feature would streamline the deployment process, particularly in Kubernetes environments like EKS, by allowing users to predefine Redis connection details (e.g., host, port, authentication credentials) during the setup phase.
REDIS_HOST
REDIS_PORT
REDIS_USERNAME
REDIS_PASSWORD
REDIS_TLS (to enable TLS if required)
**How often do you encounter this problem** (Describe how frequently this problem occurs).

**Alternatives considered** (Describe any alternative features or products you've considered).

**Additional information** (Add any other context or details here).

**Comment by ViktarStarastsenka** [comment]
here is a duplicate ticket - https://github.com/RedisInsight/RedisInsight/issues/289
