### ISSUE TITLE
[Bug]: Database Analysis Report doesn't list key sizes for Elasticache Serverless with Redis 7.2

### ISSUE THREAD

**Issue by mbstroud** [RedisInsight/RedisInsight#4051]
**Preconditions** (Any important steps we need to know)

**Steps to reproduce** (How to reproduce what you found step by step)
Run a report against a serverless elasticache

**Actual behavior** (A short description of what you found)
the report lists the keys and length, but not size

**Expected behavior** (A short description of what you expected to find)
in all over servers the report lists key sizes

**Screenshots** (Paste or drag-and-drop a screenshot or a link to a recording)
![image](https://github.com/user-attachments/assets/23bfdbcb-432b-4b2e-b10d-d03674860d9b)

**Additional context** (Operating system, version of Redis Insight, Redis database version, Redis module version, database type, connection type, logs, or any other information)
Win 11, Redis Insight 2.60, Redis 7.2, AWS Elasticache Serverless, TLS.

**Comment by ViktarStarastsenka** [comment]
@mbstroud , can you run this command to check the outcome?
"MEMORY" "usage" "{keyName}" "samples" "0"

**Comment by mbstroud** [comment]
![image](https://github.com/user-attachments/assets/4c5f951c-0904-4415-b21c-7770e24341d7)

**Comment by ViktarStarastsenka** [comment]
@mbstroud , so the "MEMORY" command is not available for your serverless instance.

**Comment by mbstroud** [comment]
Wow, mem is not available.
https://docs.aws.amazon.com/AmazonElastiCache/latest/dg/SupportedCommands.html

**Comment by mbstroud** [comment]
Clearly, the issue is with Serverless.
