### ISSUE TITLE
[Feature Request]: Bloom datatype?

### ISSUE THREAD

**Issue by patchthecode** [RedisInsight/RedisInsight#4073]
Message says 
<img width="599" alt="Screenshot 2024-11-07 at 8 49 33 PM" src="https://github.com/user-attachments/assets/eb69e76a-7e77-42aa-a6f2-5c94832621e5">

Any time Estimate?

**Comment by ViktarStarastsenka** [comment]
hi @patchthecode , currently, it is not on our Roadmap.
we need to update the text.

**Comment by ViktarStarastsenka** [comment]
here is the same request - https://github.com/RedisInsight/RedisInsight/issues/379
closing this ticket as a duplicate
