### ISSUE TITLE
Congrats for the preview release!

### ISSUE THREAD

**Issue by slemeur** [RedisInsight/RedisInsight#41]
Hi everyone! 

Congrats for the preview release. 
I'm very very glad and excited to see the awesome job that has been done on this new version of RedisInsight.  

Well done to everyone who worked on that new version 👍 

Keep up the great work!
Stévan.

**Comment by K-Jo** [comment]
Assigning this to @ollopaci :-)

**Comment by mikhailredis** [comment]
Congrats! Well done!

**Comment by ollopaci** [comment]
Thank you! :)
