### ISSUE TITLE
Request to Add 'Main Key Delete' (Namespace Delete) Feature in Redis Insight

### ISSUE THREAD

**Issue by wessisaac** [RedisInsight/RedisInsight#4139]
Request to Add 'Main Key Delete' (Namespace Delete) Feature in Redis Insight

I kindly request that you add the 'Main Key Delete' feature for HashSet in Redis Insight.

**Comment by ViktarStarastsenka** [comment]
hi @wessisaac , you can set a filter per key type or key name, and use bulk actions to delete them.
<img width="1399" alt="image" src="https://github.com/user-attachments/assets/d7ea5846-0c85-4fdd-866a-ccfe4be8611a">

**Comment by wessisaac** [comment]
Thank you ViktarStarastsenka, it is working as expected.
