### ISSUE TITLE
[Feature Request]:Support for searching List elements and Hash values by their content in RedisInsight

### ISSUE THREAD

**Issue by linyuan-design** [RedisInsight/RedisInsight#4163]
**Problem description**:
Currently, RedisInsight supports accessing List elements by index, but does not allow searching List elements by value. Similarly, in Hashes, we can search for fields by name but not by the field values. For Lists with many elements or Hashes with multiple fields, searching by value is much more efficient and user-friendly. Without this feature, users are forced to manually scan large sets of data to find specific elements or field values.

**How often do you encounter this problem**:
This problem occurs quite often when working with large data sets. As Redis is frequently used in environments with high volumes of data (e.g., caching, message queues), the inability to quickly search for elements or values makes it more difficult to manage and troubleshoot data in Redis. 

**Alternatives considered**:
I have considered using external tools or scripts, such as running custom Lua scripts to perform value searches or exporting the data to search locally. However, these alternatives are not as efficient as having a built-in search function within RedisInsight itself. Additionally, they may not be as intuitive for users who are unfamiliar with scripting or data exports.

**Additional information**:
Adding the ability to search List elements by value and Hash field values by their content would significantly improve the user experience in RedisInsight. It would allow users to quickly find specific data without needing to know the index or field name in advance. This feature would be especially useful in cases where Lists or Hashes have thousands of elements or fields.

**Comment by ViktarStarastsenka** [comment]
hi @linyuan-design , thank you for this request.
I think there is a duplicate one so I am closing this ticket - https://github.com/RedisInsight/RedisInsight/issues/1721.
