### ISSUE TITLE
[Question]:Is there any documentation or code for redisinsight-v1 still available？

### ISSUE THREAD

**Issue by caijillx** [RedisInsight/RedisInsight#4167]
**Problem description** (Describe the problem you would like to solve with this feature request or suggested idea).
I am currently using redisinsight-v1.14.0 deployed via Docker, as it offers functionalities for managing Redis clusters, such as add-node and rebalance slots, which are not available in v2. I would like to inquire whether there is any documentation or open-source code for redisinsight-v1 still available? Also, why were these features removed in v2? Thank you for your hard work!

**Comment by ViktarStarastsenka** [comment]
hi @caijillx , to the best of my knowledge, there is no longer documentation available for RedisInsight v1, and the v1 code was never open-sourced.
Feel free to ask your questions about v1 here, we'll do our best to assist you.

**Comment by caijillx** [comment]
hi @ViktarStarastsenka, I tried to expose my redisInsight instance externally using a domain name, but I unexpectedly ran into access issues. Luckily, I found the RITRUSTEDORIGINS environment variable on internet, which has solved my problem. Now, I'm curious to know what other environment variables or configurations are available in redisInsight v1. 
Besides, I want to know what the highest version of redis-server is that redisInsight v1 can support.

**Comment by ViktarStarastsenka** [comment]
## RedisInsight environment variables

The following environment variables can be set to configure RedisInsight:

### RIPORT

**Description:** Which port should RedisInsight listen on.

**Type:**        Number

**Default:**     `8001`

### RIHOST

**Description:** Which host should RedisInsight bind to.

**Type:**        String

**Default:**     `"0.0.0.0"` on Docker and `"127.0.0.1"` on Windows, Mac, and Linux.

### RIHOMEDIR

**Description:** Sets the storage directory where RedisInsight stores application data (such as local database, log files and snapshot files).

**Type:**        String

**Default:**     `"~/.redisinsight"` on desktop, `"/db"` on docker.

### RILOGDIR

**Description:** Sets the logging storage directory where RedisInsight stores application logs.

**Type:**        String

**Default:**     `"~/.redisinsight"` on desktop, `"/db"` on docker.


### RILOGLEVEL

**Description:** Configures the log level of the application. Possible values are - `"DEBUG"`, `"INFO"`, `"WARNING"`, `"ERROR`" and `"CRITICAL"`.

**Type:**        String

**Default:**     `"WARNING"`


### RITRUSTEDORIGINS

**Description:** Configures the trusted origins of the application.

**Type:**        String

**Default:**     `""`

**Examples:**     `"https://my-website.com,https://my-another-website.com,http://my-third-website.com"`
 
### RIPROXYENABLE

**Description:** Enables Subpath Proxy for the application.

**Type:**        Bool

**Default:**    `False`


### RIPROXYPATH

**Description:** Configures Subpath Proxy path for the application. 

**Type:**        String

**Default:**     `""`

**Examples:**     `"/redisinsight"`, `"/myapp"`

### RIPROXYPREFIX

**Description:** Sets the Subpath proxy prefix HTTP header field name for the application. The application uses the value from this HTTP header key as proxy subpath. 

**Type:**        String

**Default:**     `"X-Forwarded-Prefix"`

**Examples:**     `"X-Forwarded-Prefix"`, `"X-Forwarded-Path"` 

### RIAUTHPROMPT

**Description:** Enables authentication prompt that asks for authentication before opening an instance or when the user is idle.

**Type:** Bool

**Default:** `false`


### RIAUTHTIMER

**Description:** Idle timer value for authentication prompt, in minutes.

**Type:** Bool

**Default:** `30`

**Comment by ViktarStarastsenka** [comment]
I think the latest Redis version that RedisInsight v1 was tested with is 7.0.11.
