### ISSUE TITLE
[Bug]: The string long is not displayed

### ISSUE THREAD

**Issue by conifercone** [RedisInsight/RedisInsight#4208]
**Preconditions** (Any important steps we need to know)

I stored a json object in which the id attribute is a long serialized into a string, but it is still of type long

**Steps to reproduce** (How to reproduce what you found step by step)

stored a json object in which the id attribute is a long serialized into a string

**Actual behavior** (A short description of what you found)

I stored a json object in which the id attribute is a long serialized into a string, but it is still of type long

**Expected behavior** (A short description of what you expected to find)

I hope it shows correctly

**Screenshots** (Paste or drag-and-drop a screenshot or a link to a recording)
RedisInsight Display：
![image](https://github.com/user-attachments/assets/40cd8fee-6d64-411d-9429-4838f7ae89ab)
DataGrip  Display：
![image](https://github.com/user-attachments/assets/bd34bb5e-d000-48d5-9e00-7a56b64b6632)

**Additional context** (Operating system, version of Redis Insight, Redis database version, Redis module version, database type, connection type, logs, or any other information)
Operating system version：Windows 11 24H2
Redis Insight version：2.62.0
Redis info：
![image](https://github.com/user-attachments/assets/2b62f4cc-5869-4242-94ea-7d8f3f745dab)

**Comment by ViktarStarastsenka** [comment]
hi @conifercone , thanks for reporting this.
It should have been fixed with 2.64 (released today).
Please re-open the ticket if the issue still reproduces.
