### ISSUE TITLE
[Bug]: cannot sign in 

### ISSUE THREAD

**Issue by piyushpratek** [RedisInsight/RedisInsight#4231]
**Preconditions** (Any important steps we need to know)

**Steps to reproduce** (How to reproduce what you found step by step)

**Actual behavior** (A short description of what you found)

**Expected behavior** (A short description of what you expected to find)

**Screenshots** (Paste or drag-and-drop a screenshot or a link to a recording)

**Additional context** (Operating system, version of Redis Insight, Redis database version, Redis module version, database type, connection type, logs, or any other information)

**Comment by ViktarStarastsenka** [comment]
@piyushpratek , please provide more information about this issue.

**Comment by piyushpratek** [comment]
The issue has been resolved. Initially, I encountered errors during the
first few hours, but I am now able to log in successfully.
