### ISSUE TITLE
[Feature Request]:need  docker image for arm64 in docker hub

### ISSUE THREAD

**Issue by xiaobing395845388** [RedisInsight/RedisInsight#448]
**Problem description** (Describe the problem you would like to solve with this feature request or suggested idea).

**How often do you encounter this problem** (Describe how frequently this problem occurs).

**Alternatives considered** (Describe any alternative features or products you've considered).

**Additional information** (Add any other context or details here).

**Comment by Niek** [comment]
Should be quite trivial to add as a matrix to https://github.com/RedisInsight/RedisInsight/blob/main/.circleci/config.yml

**Comment by GnaneshKunal** [comment]
@xiaobing395845388 

We are working on an ARM build.

**Comment by nerg4l** [comment]
Since 1.13.0 (2022 Aug 25) an ARM64 version is published as well.

**Comment by seebeen** [comment]
It's not trivial to build v2 for arm64 read #519...

Anyways - https://hub.docker.com/r/oblakstudio/redisinsight

**Comment by ViktarStarastsenka** [comment]
here is a ticket to track updates regarding the v2 docker image: https://github.com/RedisInsight/RedisInsight/issues/519
