### ISSUE TITLE
[Question]: How do I set the RedisInsight Log level

### ISSUE THREAD

**Issue by moluzhui** [RedisInsight/RedisInsight#449]
> Sorry to ask here because I didn't find a Q&A forum.

Although it provides api/docs/ to view the API list, but I would like to check the `specific API called` during interface operations. In general it is associated with the `level of logging`, I look at the journal found that level for the INFO, whether by lowering the level can see the interface call API, If yes, could you please tell me how to change the setting? I did not find any explanation about the logger level setting

**Comment by ViktarStarastsenka** [comment]
Hello @moluzhui , currently "INFO" is the most detailed level of logging that we have.
Can you please describe your use case so I can try to help?
