### ISSUE TITLE
[Feature Request]: Support Unicode display on STRING value

### ISSUE THREAD

**Issue by doggy8088** [RedisInsight/RedisInsight#464]
**Problem description** (Describe the problem you would like to solve with this feature request or suggested idea).

I know the STRING type in Redis is binary-compatible. I'd like to know that is there possible to display Unicode characters in the value field if there is only "Text" value in it. Or provide an options to show Unicode text in the editor.

**How often do you encounter this problem** (Describe how frequently this problem occurs).

always.

**Alternatives considered** (Describe any alternative features or products you've considered).

N/A

**Additional information** (Add any other context or details here).

This is an HTML content. I'd like to see "Tags" in it.

![image](https://user-images.githubusercontent.com/88981/160159938-7d2e919b-be76-4539-9a87-1f0763f5a0d7.png)

**Comment by ViktarStarastsenka** [comment]
hi @doggy8088 , Unicode is supported by default in Browser/Tree View. with 2.8.0 (released recently) you can see it in ASCII as well.
