### ISSUE TITLE
[Feature Request]: browser support change db

### ISSUE THREAD

**Issue by rogey** [RedisInsight/RedisInsight#466]
version : v2
when a connection has been created ,then i can not change db in browser.
we use different db to separate different data .  i must create many connections.

**Comment by ViktarStarastsenka** [comment]
Hi @rogey ,
indeed currently it is not possible to change the database index, once the database has been added.
As a workaround, you can open the desktop application in different windows and work with different database indexes in them. Does this work for you?

**Comment by phillipgsmith** [comment]
@ViktarStarastsenka, I think you may have misunderstood the question. I think what @rogey is asking is it possible to change from one DB to another in the UI.

**Comment by dhdbuwl** [comment]
this feature is work in v1, but not implement in v2. why?

**Comment by ViktarStarastsenka** [comment]
@phillipgsmith , I believe that logical databases ("Select" command) are in question here.

The reason why we do not allow to change them in V2 (you can only add a new database with the same host and port, but a different database index) is that they may cause problems - these databases are not isolated and running commands on database 0 will freeze database 1.

But we may re-condiser this decision in V2 given the feedback here.

**Comment by dhdbuwl** [comment]
@ViktarStarastsenka Thanks for your answer, and i will keep looking forward to this.

**Comment by phillipgsmith** [comment]
@ViktarStarastsenka, thanks for your reply. So is there a way to use the browser to specify/display a specific database? Or does it only display database 0 (zero)? Maybe I am missing something obvious.

**Comment by dhdbuwl** [comment]
> 

When you create a new connection, there is a checkbox[Database Index] to select the db index. Once selected, it can‘t be changed.

**Comment by dhdbuwl** [comment]
> @ViktarStarastsenka, thanks for your reply. So is there a way to use the browser to specify/display a specific database? Or does it only display database 0 (zero)? Maybe I am missing something obvious.

When you create a new connection, there is a checkbox[Database Index] to select the db index. Once selected, it can‘t be changed.

**Comment by phillipgsmith** [comment]
@ViktarStarastsenka, I must be missing something... Can you provide a screenshot? Just to be clear... When I enter http://localhost:8001/redis-stack/browser in my browser, I am wanting to specify a different virtual database. I assume that by default, it is database zero (0). I don't see anywhere in the UI in RedisInsight where I can specify a database index or to create a new connection. There is a "Edit Database" option but it does not have anything to specify the database index.

**Comment by phillipgsmith** [comment]
Okay. Thanks so much for the feedback.

**Comment by LordSuricato** [comment]
I thought it was an issue, but I see that it is a deliberate decision. I personally find V1 more comfortable precisely because of the database selector. I work with more than 10 different Redis in different projects, each one uses 5 different databases. That in V2 is more than 50 connections to create 


If, finally, it is not allowed to change the database in real time, at least the option of duplicating a connection in a simple way would be good.


Thank you very much for this excellent tool.

**Comment by ViktarStarastsenka** [comment]
hi, added support for switching database indexes (control next to the database alias) in RedisInsight 2.18 (released today)
<img width="1288" alt="Screenshot" src="https://user-images.githubusercontent.com/99594890/215866324-c4080f1c-3d36-4e2f-9b43-303bd3583974.png">
