### ISSUE TITLE
[Feature Request]: Format the value as json

### ISSUE THREAD

**Issue by CryptoTradee** [RedisInsight/RedisInsight#472]
![Screenshot 2022-03-29 085959](https://user-images.githubusercontent.com/45982911/160500805-132927dc-7d38-4a79-b3a8-e92d79c84667.png)

For a regular value, have an option (that defaults to true) to format the value as json to see it better

**Comment by esanabria-tricks** [comment]
I vote for this. It would be great to have this feature.

**Comment by ViktarStarastsenka** [comment]
Hello @CryptoTradee , @esanabria-tricks , what data structures do you usually use?
are there any use cases when you will need different formatters for one key? e.g. MessagePack for one Hash value and JSON for another value of the same Hash?

**Comment by esanabria-tricks** [comment]
Hello and thanks for thinking about implementing this feature.
In our case, no. Some keys have a JSON content but for all values.

**Comment by CryptoTradee** [comment]
Yes, we would also just have same formatter for every value in the hash.
Tbh, 99% of my values are Json

**Comment by PabloEmidio** [comment]
I started to use RedisInsight instead RedisDesktopManager today, and miss this option.
I also vote for this

**Comment by ViktarStarastsenka** [comment]
formatting the key value as JSON will be added with the next release (2.8.0) at the end of August.

**Comment by ViktarStarastsenka** [comment]
hi @CryptoTradee , @PabloEmidio , @esanabria-tricks , please try it in 2.8.0 (recently released).

**Comment by CryptoTradee** [comment]
Could you make json be the default? Even if I view one as json and change
keys and then come back, it defaults back to Unicode.

Could either remember my setting or better still, if you can parse it as
json, show it as json?

**Comment by ViktarStarastsenka** [comment]
@CryptoTradee , we will definitely add a feature to remember the format selected (so that if you select if for one key, you will see the same format selected when another key is selected) in the upcoming releases.

**Comment by ViktarStarastsenka** [comment]
@CryptoTradee , the format selected will be remembered starting in RedisInsight 2.10.0 (released today)
