### ISSUE TITLE
[Bug]: RedisInsight v2.0 missing memory analyzer from v1

### ISSUE THREAD

**Issue by chrisgo** [RedisInsight/RedisInsight#480]
**Preconditions** (Any important steps we need to know)
Download RedisInsight v2

**Steps to reproduce** (How to reproduce what you found step by step)
- Add new database

**Actual behavior** (A short description of what you found)
- missing button for Memory Analyzer
- used to be here https://developer.redis.com/explore/redisinsight/memoryanalyzer

**Expected behavior** (A short description of what you expected to find)
- need a place to access Memory Analyzer

**Screenshots** (Paste or drag-and-drop a screenshot or a link to a recording)

**Additional context** (Operating system, version of RedisInsight, Redis database version, Redis module version, database type, connection type, logs, or any other information)

**Comment by drahnieR** [comment]
> Hello @chrisgo , the article is for RedisInsight V1, V2 does not have Memory Analyzer yet (though it is already prioritised).

Is there any date or version estimate on this feature? Personally, I think Memory Analyzer was the feature that makes redisinsight really useful and unique.

**Comment by ViktarStarastsenka** [comment]
@drahnieR , we are looking for ways to add Memory Analyzer in the upcoming months (~September-October). Can you please share your use cases how you usually use it?

**Comment by ViktarStarastsenka** [comment]
@chrisgo , could you please share your use cases how you use Memory Analyzer as well?

**Comment by drahnieR** [comment]
@ViktarStarastsenka Yes, Memory Analyzer provides a pretty intuitive way to look around the whole key space. Summary with customizable pattern is extremely handy, combined with dynamic filter, it's very easy to spot the key that takes most space. And saved snapshots helped a lot to monitoring change as the project iterates.

**Comment by relgames** [comment]
@ViktarStarastsenka Hi, we also use Memory Analyzer a lot. I see this issue is closed, but I'm still not able to find Memory Analyzer in v2.8.0 - perhaps it was closed by mistake?

We use it when we notice that too much memory is used in Redis by our application. We use Redis Streams a lot (100+ different streams), and Memory Analyzer helps to spot memory leaks. In the past, it helped with production issues as well (when Redis goes OOM in production, then we download the memory dump and analyze it).

**Comment by ViktarStarastsenka** [comment]
hi @relgames , yes, you are right, Memory Analyzer has not been implemented yet, but it will be released with 2.12.0 (October).
Though currently, RedisInsight V2 will support only online analysis (no analysis of RDB files) up to 10,000 keys.

**Comment by drahnieR** [comment]
> Though currently, RedisInsight V2 will support only online analysis (no analysis of RDB files) up to 10,000 keys.

ouch, that doesn't sound very helpful... pretty sure there're ppl have way more keys than that

**Comment by LeoSko** [comment]
I'm using 2.32.0 but it still doesn't have Memory Analyzer. I have to use v1 (which wasn't easy to obtain) in order to do offline analysis of my production DB.

**Comment by mgasco83** [comment]
Hi, I was using offline memory analysis on a regular basis with the redis-insight v1 but it is not compatible with Redis 7.0 snapshot. When you have a huge database, offline analysis is very important to detect keys that take too much memory or keys that were left over by code refactoring
Is there any chance that this feature gets into the v2 version ?

**Comment by ViktarStarastsenka** [comment]
Hi @mgasco83 , This feature is on our radar, but no release timeline has been defined yet.
I’ll post an update here as soon as a timeline is determined.

**Comment by dimitar-tsonev** [comment]
Hello @ViktarStarastsenka  do you have an update when we can expect the memory analyzer feature to v2?
Meanwhile can you share where we could download v1 for MacOS so we could use the analyze feature?
