### ISSUE TITLE
[Feature Request]: Plans to migrate redis monitoring functions

### ISSUE THREAD

**Issue by hballangan-mdsol** [RedisInsight/RedisInsight#493]
Hi, just wanted to ask what the plans are for migrating the monitoring features like:
[Elasticache Autodiscovery](https://developer.redis.com/explore/redisinsight/autodiscover/)
[Memory Analyzer](https://developer.redis.com/explore/redisinsight/memoryanalyzer/) 
[Slowlog Debugging](https://developer.redis.com/explore/redisinsight/slowlog/)
[Profiler](https://developer.redis.com/explore/redisinsight/profiler/)

Is there a timeline specific for the migration of these functionalities?

Also is there plans to be able to off features? Like for example I'd like to turn off management functionalities in production and only get the monitoring functionalities.

**Comment by ViktarStarastsenka** [comment]
Hi @hballangan-mdsol , thanks for the question.

Elasticache Autodiscovery - not planned in the next few months, but please describe your use cases if this feature is very important for you
Memory Analyzer - this feature is definitely on the list, but is not in the upcoming releases
Slowlog Debugging - the feature is in design, hopefully will be available in May
Profiler - we already have a Profiler that works in real-time. Is there anything specific you would like to have in Profiler? Can you provide use cases?

I believe you can turn off management functionalities by providing users with read-only access, does it cover your request?

**Comment by hballangan-mdsol** [comment]
Thank you @ViktarStarastsenka for the response.
Elasticache autodiscovery is indeed not on top of our use case priority but it would be a good thing to have eventually as we are managing a lot of redis instances in AWS. The most important function that we are looking for is the memory analyzer since our use-case is to have a tool that we can use to evaluate if we need to resize our redis instances.

For the profiler, I forgot that it is already in v2 so nvm. 

Thanks for the suggestion on how to turn off the management functionality, that does seem feasible in our use-case.

**Comment by ViktarStarastsenka** [comment]
@hballangan-mdsol , Slow Log is currently at the design stage.
Do you have any particular requests or use cases that you would like to get covered with Slow Log?
