### ISSUE TITLE
[Feature Request]: RedisInsight 1.0

### ISSUE THREAD

**Issue by hballangan-mdsol** [RedisInsight/RedisInsight#494]
Are there any plans to put up RedisInsight 1.0 here in github? It would make it easier to contribute to the codebase, or at least for users to modify the functionalities while the monitoring functionalities hasn't been ported yet to 2.0

**Comment by ViktarStarastsenka** [comment]
Hi @hballangan-mdsol , thanks for reaching out. Currently, there are not plans to add RedisInsight V1 to GitHub.
