### ISSUE TITLE
[Bug]: Graph shows wrong relationship

### ISSUE THREAD

**Issue by streamnsight** [RedisInsight/RedisInsight#500]
**Preconditions** (Any important steps we need to know)
redis_version:6.2.6
module:name=graph,ver=20811,api=1,filters=0,usedby=[],using=[],options=[]

**Steps to reproduce** (How to reproduce what you found step by step)
```
GRAPH.QUERY iam "CREATE (:Node {id:1})-[:REL {a: 1}]->(:Node {id:2})"
GRAPH.QUERY iam "MATCH (a:Node {id:1}), (b:Node {id:2}) CREATE (a)-[:REL {b: 1}]->(b)" 
GRAPH.QUERY iam "MATCH (a:Node {id:1}) CREATE (a)-[:REL {b: 1}]->(:Node {id: 3})" 
```

With these, we have 3 nodes, and 3 relationships. Node id:1 and id:2 have 2 relationships with properties {a: 1} and {b: 1}, while id:1 to id:3 has only {b:1}

**Actual behavior** (A short description of what you found)

When visualizing the graph with the query:
```
GRAPH.QUERY iam "MATCH (a:Node)-[:REL {b: 1}]->(b:Node) RETURN a, b"
```
I expect to see 3 nodes, and the relationship with {b:1} between them.
However, I see the 3 nodes, and one relationship shows the {a: 1} property, and the other the {b:1} 
Not even sure how I am seeing relationships in the graph since I'm not returning anything about them.

**Expected behavior** (A short description of what you expected to find)
I expect to see 3 nodes, and the relationship with {b:1} between them.

**Screenshots** (Paste or drag-and-drop a screenshot or a link to a recording)
<img width="655" alt="image" src="https://user-images.githubusercontent.com/10981776/162095133-ff5573eb-05b0-4d36-8771-4f2a4b730ca2.png">

**Additional context** (Operating system, version of RedisInsight, Redis database version, Redis module version, database type, connection type, logs, or any other information)

**Comment by ViktarStarastsenka** [comment]
Hi @streamnsight , thanks, investigating this.

**Comment by GnaneshKunal** [comment]
@streamnsight 

By default we automatically show all the edges between two nodes. We often find users forgetting to return edges between nodes so we have added the capability to automatically pull edges while the graph is loading.

Is the experience fine to you?

**Comment by streamnsight** [comment]
@GnaneshKunal 
IMO Anything you do on behalf of the user without their knowledge / understanding will be odd and source of confusion.

If I want to see nodes and purposely don't return edges, why should I see edges? If i have no way to control this behavior, that's not good.
If you think users want to see edges and often forget to return them, then at the very least the edges shown should match the query. Returning all edges is confusing: if I query a specific type of edge, or filter by a specific property, that's what I want to see. If I forgot to return edges, showing no edges will clearly tell me I forgot to return edges, while if you take the initiative to fill in 'all' edges for me, I just get confused when I see edges I don't expect to see.

If users forget to return edges, it might be more logical to return a visual warning / cue to indicate no edges were returned. Showing count of Nodes / Edges returned would be a useful feature and double as the appropriate warning, while not costing anything.
