### ISSUE TITLE
[Feature Request]: Graph overlay is always in the way

### ISSUE THREAD

**Issue by streamnsight** [RedisInsight/RedisInsight#501]
**Problem description** (Describe the problem you would like to solve with this feature request or suggested idea).
When hovering over node or relationship properties, the overlay covers everything, and it does not go away unless i click the close button, but if the graph is dense, it immediately picks up something else and covers everything again. It is especially terrible when I have dozens of properties.

It should be a tooltip that goes away when moving away, or it should show only when clicked on an element, not on hover.
if it has to be static, it should at least disappear when I click outside of it on an area when I don't have elements that will trigger it again.

**How often do you encounter this problem** (Describe how frequently this problem occurs).
all the time!

**Alternatives considered** (Describe any alternative features or products you've considered).

**Additional information** (Add any other context or details here).

**Comment by ViktarStarastsenka** [comment]
Hello @streamnsight , thank you for raising this, we are working on it.

**Comment by GnaneshKunal** [comment]
A PR #713 has been raised which solves this issue.

In new behaviour, only clicking on the node/edge will show the graph info overlay. Clicking on "X" on the info overlay will close it. 


Is this the expected vehabiour?

**Comment by GnaneshKunal** [comment]
@streamnsight 


Merging the PR. Reopen the issue if you are still facing problems.
