### ISSUE TITLE
[Bug]: Cluster connection problem

### ISSUE THREAD

**Issue by gyr9i** [RedisInsight/RedisInsight#515]
**Steps to reproduce** 
Create redis-cluster with 3 nodes(6379, 6380, 6381). Try to connect those ports. 

**Actual behavior** 
While trying to connect to 6379 port it connects to 6380, while trying to connect to port 6380 it connects to 6381 and 6381 connects to 6380. Through CLI it connects without any problems

**Expected behavior** 
It must connect to port defined on field "Port" 6379->6379, 6380->6380, 6381->6381

**Screenshots** 
<img width="1299" alt="Screenshot 2022-04-09 at 10 36 09" src="https://user-images.githubusercontent.com/6648023/162562063-49f88fc5-8d18-44e1-b80c-76a1f324185a.png">

**Additional context** 
MacOS Monterey 12.3.1 (21E258), RedisInsight  2.0.5 (2.0.5.27100), redis_version:6.2.6, redis_mode:cluster

**Comment by ViktarStarastsenka** [comment]
Hi @gyr9i , the reason for this behaviour is that currently the Browser tool displays the list of keys per the entire cluster (not per a node) with the redirection between nodes enabled, so when you add a cluster, connection is created to the first endpoint received (with redirection enabled).
Though CLI has more flexibility here.
Can you please describe a use case when you need to create a connection to the exact node?

**Comment by gyr9i** [comment]
> Hi @gyr9i , the reason for this behaviour is that currently the Browser tool displays the list of keys per the entire cluster (not per a node) with the redirection between nodes enabled, so when you add a cluster, connection is created to the first endpoint received (with redirection enabled). Though CLI has more flexibility here. Can you please describe a use case when you need to create a connection to the exact node?

Thank you, I've checked and it really have keys from whole cluster. Use case, for example: understand in what node key was placed

**Comment by ViktarStarastsenka** [comment]
to cover this case please use CLI
