### ISSUE TITLE
[Bug]: cluster support for OSS

### ISSUE THREAD

**Issue by raphaelauv** [RedisInsight/RedisInsight#53]
**Preconditions** (Any important steps we need to know)

The V1 have a full OSS redis cluster support

https://registry.hub.docker.com/r/redislabs/redisinsight

**Steps to reproduce** (How to reproduce what you found step by step)

the V2 do no show anymore any info about the redis cluster or nodes

**Actual behavior** (A short description of what you found)

missing so many feature in the V2 present in the V1

**Expected behavior** (A short description of what you expected to find)

the V2 should not miss any feature of the V1

**Screenshots** (Paste or drag-and-drop a screenshot or a link to a recording)

V2 ->

![Screenshot from 2021-11-29 11-18-51](https://user-images.githubusercontent.com/10202690/143850890-b1f98fb8-d5b6-49aa-9271-18e68396c16f.png)
![Screenshot from 2021-11-29 11-18-56](https://user-images.githubusercontent.com/10202690/143850910-43e55b0a-8fe7-4a60-9dbc-02a190eaa00c.png)

v1 ->
![Screenshot from 2021-11-29 11-20-27](https://user-images.githubusercontent.com/10202690/143850954-f167dea0-dba3-40a3-8cd5-43c68f88c332.png)
![Screenshot from 2021-11-29 11-20-33](https://user-images.githubusercontent.com/10202690/143850966-f19f5273-8388-4178-9ca6-d181ba0c552e.png)
![Screenshot from 2021-11-29 11-20-52](https://user-images.githubusercontent.com/10202690/143851011-2e5a0789-5a41-4079-8b0f-94788df39680.png)
![Screenshot from 2021-11-29 11-20-54](https://user-images.githubusercontent.com/10202690/143851022-c601d4c7-3c9c-471e-9018-241673482d6c.png)

Thanks

**Comment by huiwanggo** [comment]
Has this problem been fixed?

**Comment by jaredmcqueen** [comment]
+1 support for OSS cluster would be great.  Not sure why it was removed

**Comment by ViktarStarastsenka** [comment]
Cluster Management is planned to be added in several months (~August).

**Comment by ViktarStarastsenka** [comment]
@raphaelauv , @jaredmcqueen , @huiwanggo , can you please share your use cases? how do you currently use the OSS cluster support?

**Comment by ViktarStarastsenka** [comment]
hi @raphaelauv , @huiwanggo , @jaredmcqueen , 

There are plans to add support for OSS Cluster monitoring in RedisInsight V2, I’d like to receive your feedback regarding the following questions:
1. there are plans to display memory/slots/keys allocation in rings to visually represent all the details (screen 1), so a few questions:

- would this representation be clear for you?
- do you think displaying memory/slots/keys allocation is useful? any other information to display in this ring?

2. also, the shard structure will be displayed as well (screens 1 and 2) with an option to see the physical layout:
- do you have any comments about this visualization?
- is it useful to display any other information here?

3. the feature will also contain cluster statistics (screen 3). There is an idea to display all the node parameters on one screen, so to monitor everything at once and find min/max values
- do you think it is valuable or it is better to display all/parts of this information on the shard layout (screens 1-2)?
- is there any other information you would like to see while monitoring the OSS Cluster? (cluster epoch, cluster_stats_messages_sent/received, something else?)

<img width="1120" alt="Screenshot 2022-08-15 at 11 18 00" src="https://user-images.githubusercontent.com/99594890/184861517-d3b0f5ca-10ba-45eb-b4fe-7f95a6b97a48.png">
ges_sent/received, something else?)
<img width="1119" alt="Screenshot 2022-08-15 at 11 17 49" src="https://user-images.githubusercontent.com/99594890/184861614-b3177592-b5e4-42d1-bb8f-1e27d551a92e.png">
<img width="1121" alt="Screenshot 2022-08-15 at 11 18 14" src="https://user-images.githubusercontent.com/99594890/184861660-49eab2b8-4083-41e1-a9ba-9fcf530d86e5.png">

**Comment by jaredmcqueen** [comment]
whoa, neat screenshots.  statistics galore.  I'm always a fan of more information being presented to the administrators.

A ring is a nice visual representation of keyslots.  I'm not sure how it will look once you get to 5+ slots, but for the average customer it conveys enough information.

physical layout -- have you seen how elasticsearch shows their primaries/replicas?  They've gone through a ton of iterations and I quite like how they represent it in a UI.  [example here](https://www.elastic.co/guide/en/elasticsearch/reference/current/add-elasticsearch-nodes.html#add-elasticsearch-nodes).  It may get a little too repetitive with lots of clusters / shards in the grid fashion.  Maybe get rid of one of the dimensions - like keyslots, and move it instead to a mouse hover/click?

same feedback for the stats.  Getting rid of the keyslots dimension would add to the readability.  A click/hover may allow a user to "drill down", or "pivot" to more precise information.

Whatever the case - users will certainly welcome the changes and I'm sure you can solicit feedback and make improvements as adoption grows.  I'd really have to kick the tires on this to get a better understanding of UI/UX.

**Comment by ViktarStarastsenka** [comment]
hi @raphaelauv , @jaredmcqueen , @huiwanggo , please try RedisInsight 2.10.0 (released today) - we have the shard balance visualization and the data per shard on a separate "Analysis Tools" page.

**Comment by raphaelauv** [comment]
@ViktarStarastsenka I can't find the docker image of 2.10.0 

https://registry.hub.docker.com/r/redislabs/redisinsight/tags?page=1&name=2.10

**Comment by ViktarStarastsenka** [comment]
@raphaelauv , currently, there is no separate docker for RedisInsight v2 (we are working on it). There is a [docker RI for Redis Stack](https://hub.docker.com/r/redis/redis-stack/tags), but 2.10.0 will be released there somewhere next week.

**Comment by raphaelauv** [comment]
conclusion : I can't test 2.10.0 with a docker image

**Comment by ViktarStarastsenka** [comment]
ticket to track the progress on docker image:
https://github.com/RedisInsight/RedisInsight/issues/519
