### ISSUE TITLE
[Feature Request]:add serach feature in "my redis databases" list

### ISSUE THREAD

**Issue by joeleclems** [RedisInsight/RedisInsight#536]
**Problem description** (Describe the problem you would like to solve with this feature request or suggested idea).
I have a lot of databases (>100) in redis databases list. It's unconfortable to find the one i want to open without search feature 

**How often do you encounter this problem** (Describe how frequently this problem occurs).
Each time i use redis insight

**Alternatives considered** (Describe any alternative features or products you've considered).
none

**Comment by ViktarStarastsenka** [comment]
Hi @joeleclems , thanks for raising this, very valid request.

**Comment by ViktarStarastsenka** [comment]
@joeleclems , added with 2.4.0
