### ISSUE TITLE
[Bug]: add a new database,show error

### ISSUE THREAD

**Issue by NielJun** [RedisInsight/RedisInsight#540]
**Preconditions** (Any important steps we need to know)
<img width="320" alt="image" src="https://user-images.githubusercontent.com/19709109/163747411-6e68c567-d287-4382-bf25-720e9fbb4ef6.png">

**Steps to reproduce** (How to reproduce what you found step by step)

add a cloud redis path,then press add redis database .
**Actual behavior** (A short description of what you found)

**Expected behavior** (A short description of what you expected to find)

**Screenshots** (Paste or drag-and-drop a screenshot or a link to a recording)

**Additional context** (Operating system, version of RedisInsight, Redis database version, Redis module version, database type, connection type, logs, or any other information)

**Comment by ViktarStarastsenka** [comment]
Hi @NielJun , can you try to connect to this database via Redis CLI?
seems like a connection issue
