### ISSUE TITLE
[Bug]: Failed to initialize keytar module error appears in docker running log

### ISSUE THREAD

**Issue by moluzhui** [RedisInsight/RedisInsight#575]
**Preconditions** (Any important steps we need to know)

**Steps to reproduce** (How to reproduce what you found step by step)
Using docker to build redisinsight:v2.0.4-preview, there is an error when running

**Actual behavior** (A short description of what you found)
```
[Nest] 19   - 04/24/2022, 6:41:59 PM   [NestFactory] Starting Nest application...
[Nest] 19   - 04/24/2022, 6:41:59 PM   [KeytarEncryptionStrategy] Failed to initialize keytar module +206ms
[Nest] 19   - 04/24/2022, 6:41:59 PM   [InstanceLoader] TypeOrmModule dependencies initialized +21ms
[Nest] 19   - 04/24/2022, 6:41:59 PM   [InstanceLoader] CoreModule dependencies initialized +1ms
[Nest] 19   - 04/24/2022, 6:41:59 PM   [InstanceLoader] EnablementAreaModule dependencies initialized +0ms
......
```
It seems that the [keytar is not found](https://github.com/RedisInsight/RedisInsight/blob/f2819d05f839eb123da144284d79d775ce35bdd8/redisinsight/api/src/modules/core/encryption/strategies/keytar-encryption.strategy.ts#L36)
But the keytar package exists when I search in the api directory
```
cd redisinsight/api/
[root@xxxxxxxxx api]# npm list | grep keytar
├─┬ keytar@7.7.0
npm ERR! peer dep missing: @nestjs/common@^8.0.0, required by @nestjs/platform-socket.io@8.2.4
npm ERR! peer dep missing: @nestjs/common@^8.0.0, required by @nestjs/websockets@8.2.4
npm ERR! peer dep missing: @nestjs/core@^8.0.0, required by @nestjs/websockets@8.2.4
npm ERR! peer dep missing: rxjs@^7.1.0, required by @nestjs/platform-socket.io@8.2.4
npm ERR! peer dep missing: rxjs@^7.1.0, required by @nestjs/websockets@8.2.4
```

**Expected behavior** (A short description of what you expected to find)
no error

**Screenshots** (Paste or drag-and-drop a screenshot or a link to a recording)

**Additional context** (Operating system, version of RedisInsight, Redis database version, Redis module version, database type, connection type, logs, or any other information)

**Comment by arthosofteq** [comment]
@moluzhui Could you run your docker container with `--cap-add ipc_lock` argument as described here https://github.com/RedisInsight/RedisInsight/wiki/How-to-build-and-contribute#create-docker-image?

**Comment by ViktarStarastsenka** [comment]
@moluzhui, is this issue closed?

**Comment by ViktarStarastsenka** [comment]
Please reopen the ticket if the question is still relevant.
