### ISSUE TITLE
[Bug]: Type "NONE" key with 2s expiry time for binary key names

### ISSUE THREAD

**Issue by antonum** [RedisInsight/RedisInsight#589]
**Steps to reproduce** 
```
127.0.0.1:6379> set "\x02\x00\x00\x00zipcode\x04\x00\x00\x00\x04\x00\x00\x002\x9b\x00\x00creditscore" 1
OK

127.0.0.1:6379> set "\x02\x00\x00\x00zipcode\x04\x00\x00\x00\x04\x00\x00\x002\x9b\x00\x00creditscore" 1
OK
```

**Actual behavior** (A short description of what you found)

Open the database in RedisInsight - it will be displayed as "NONE" with the 2 sec. expiration time

**Expected behavior** (A short description of what you expected to find)

"STRING" No Limit

**Screenshots** (Paste or drag-and-drop a screenshot or a link to a recording)
<img width="1144" alt="Screen Shot 2022-04-26 at 12 24 27 PM" src="https://user-images.githubusercontent.com/13168232/165347830-5d83e7ae-507d-4cd4-a9ca-c3256975df86.png">

**Additional context** (Operating system, version of RedisInsight, Redis database version, Redis module version, database type, connection type, logs, or any other information)

RI Version 2.0.5 (2.0.5.27100)

Server - Redis Stack run locally on Mac M1.

redis_version:6.2.6
Modules
module:name=timeseries,ver=10609,api=1,filters=0,usedby=[],using=[],options=[handle-io-errors]
module:name=graph,ver=20809,api=1,filters=0,usedby=[],using=[ReJSON],options=[]
module:name=search,ver=20210,api=1,filters=0,usedby=[],using=[ReJSON],options=[handle-io-errors]
module:name=ReJSON,ver=20007,api=1,filters=0,usedby=[search|graph],using=[],options=[handle-io-errors]
module:name=bf,ver=20214,api=1,filters=0,usedby=[],using=[],options=[]

**Background**

Feast feature store routinely generates keys with names like this of Redis as Online Store.

**Comment by ViktarStarastsenka** [comment]
Thank you, we are working on this.

**Comment by ViktarStarastsenka** [comment]
@antonum, please check RI 2.2.0 (released today) - we will display the key type, size and ttl, but there is still no way to see Key details - will try to cover this later.

**Comment by ViktarStarastsenka** [comment]
Please reopen the ticket if the issue still persists

**Comment by antonum** [comment]
RI 2.2 is a big improvement. It correctly displays type and TTL for all the keys, previously displayed as NONE, 2 sec, but still fails to display key content for some (see screenshot).

Key to reproduce on 2.2:
`set "\x02\x00\x00\x00zipcode\x04\x00\x00\x00\x04\x00\x00\x00\x93o\x00\x00creditscore" 1`

All failing keys seem to have <?> in the key name display.

<img width="1250" alt="Screen Shot 2022-05-27 at 9 56 51 AM" src="https://user-images.githubusercontent.com/13168232/170715087-41bfcefb-cb7e-4d82-8b9d-a67fbcd52189.png">

**Comment by ViktarStarastsenka** [comment]
@antonum , right now all the binary key names are properly handled. It should be fixed in later releases.
