### ISSUE TITLE
RedisInsight docker image installing the RedisInsight version 1.11.1 not the latest ersion

### ISSUE THREAD

**Issue by khanakia** [RedisInsight/RedisInsight#590]
**Preconditions** (Any important steps we need to know)
https://hub.docker.com/r/redislabs/redisinsight
I am installing the redisinsight latest version using docker it installs the old version

**Steps to reproduce** (How to reproduce what you found step by step)
`docker run -d -p 8001:8001 redisinsight:/db redislabs/redisinsight:latest`

**Actual behavior** (A short description of what you found)
Installs the older version, not the newest version 2.0

**Expected behavior** (A short description of what you expected to find)
Should install the newest version 2.0 https://redis.com/blog/introducing-redisinsight-2/

**Screenshots** (Paste or drag-and-drop a screenshot or a link to a recording)
<img width="962" alt="Screenshot 2022-04-27 at 12 14 18 AM" src="https://user-images.githubusercontent.com/2174170/165370184-6f2ab5ca-70fc-4af0-af1d-c2951e228b90.png">

**Additional context** (Operating system, version of RedisInsight, Redis database version, Redis module version, database type, connection type, logs, or any other information)
Ubuntu 20

**Comment by ViktarStarastsenka** [comment]
Hi @khanakia , RedisInsight V2 does not have docker container so far (though it is planned).
But you also can install Redis Stack using Docker which includes web-version of RedisInsight V2 (works only with Redis Stack - you cannot add other databases here): https://redis.io/docs/stack/get-started/install/docker/

**Comment by khanakia** [comment]
@ViktarStarastsenka Will, i be able to connect the Amazon ElasticCache Redis Database with the V2.0 web version 

NOTE: V1 is working perfectly with ElasticCache redis.
