### ISSUE TITLE
[Bug]: Delete key dialog shows when it should not

### ISSUE THREAD

**Issue by worldspawn** [RedisInsight/RedisInsight#600]
**Preconditions** (Any important steps we need to know)
Have a keyboard with a delete key. I imagine all you trendy redis devs are on macs with a minimal keyboard :P

**Steps to reproduce** (How to reproduce what you found step by step)
While viewing the Browser page. Focus is unimportant. Push the delete key and you will be presented with a dialog "Are you sure you want to delete a key ?". Its super annoying.

**Actual behavior** (A short description of what you found)
Dialog pops up on every single delete press regardless of the context.

**Expected behavior** (A short description of what you expected to find)
I don't really know what the intended behaviour was but i imagine I should have a key selected and have focus on that list at the time i push delete for this dialog to show up. 

**Screenshots** (Paste or drag-and-drop a screenshot or a link to a recording)
![image](https://user-images.githubusercontent.com/819581/165861746-d50d1381-290b-4134-8e3c-467582714974.png)

**Additional context** (Operating system, version of RedisInsight, Redis database version, Redis module version, database type, connection type, logs, or any other information)

v1.1.1 accessed in chrome.

**Comment by ViktarStarastsenka** [comment]
Hi @worldspawn, just to double check - you do not want to see the "delete key" pop-up when you try to delete a value of the key via keyboard, correct?

**Comment by worldspawn** [comment]
Hi @ViktarStarastsenka . I do want that behaviour. The problem is it happens even when no key is selected. It also happens when focus is on the search text field which is not desirable.

**Comment by GnaneshKunal** [comment]
Hi @worldspawn,

We have pushed a fix for the same. Here's the docker tag: `redislabs/redisinsight:fix-key-deletion-dialog`. Please do test it and let us know if this fixes the issue.

Also, do let us know if you need an OS specific build.

**Comment by worldspawn** [comment]
Change looks good to me @GnaneshKunal. Thanks 💯
