### ISSUE TITLE
[Feature Request]: Missing the Code of Conduct

### ISSUE THREAD

**Issue by FahimFBA** [RedisInsight/RedisInsight#606]
**Problem description** 
The project is currently missing the Code of Conduct which defines standards for how to engage in a community. 
**How often do you encounter this problem** 
Not applicable.
**Alternatives considered**
If you would want to add that, then I would add a PR including the Code of Conduct.
**Additional information** 
Not applicable.

**Comment by ViktarStarastsenka** [comment]
here is the code of conduct:
https://github.com/RedisInsight/RedisInsight/blob/main/CONDUCT
