### ISSUE TITLE
[Bug]: Quick Guides Time Series returns index.js not found error after following the steps

### ISSUE THREAD

**Issue by bpamos** [RedisInsight/RedisInsight#611]
**Preconditions** (Any important steps we need to know)
Running through TimeSeries tutorial on RedisInsight v2

**Steps to reproduce** (How to reproduce what you found step by step)

Redis Enterprise Fixed plan Redis Stack DB > Connect to Redis Insight V2 > Workbench > Time Series > follow steps till page 4 of 6 > Filtering section, Filtering by label "TS.MRANGE - + FILTER area_id=32" > returns error "/static/plugins/redistimeseries-app/dist/index.js not found. Check if it has been renamed or deleted and try again."

**Actual behavior** (A short description of what you found)
TimeSeries tutorial returns error when running through the steps. 

**Expected behavior** (A short description of what you expected to find)
TimeSeries tutorial to run through the steps without producing an error.

**Screenshots** (Paste or drag-and-drop a screenshot or a link to a recording)
NA

**Additional context** (Operating system, version of RedisInsight, Redis database version, Redis module version, database type, connection type, logs, or any other information)

RedisInsight version: RedisInsight-v2 Version 2.0.6 (2.0.6.35134)
Redis Database Version: 6.2.3
Redis Module version: Redis Fixed plan Redis Stack TimeSeries v 1.6.9
OS: macOS Monterey Version 12.3.1 (1.4 GHz Quad-Core Intel Core i5)

**Comment by ViktarStarastsenka** [comment]
Hi @bpamos , it will be fixed with the next release (the end of May).

**Comment by ViktarStarastsenka** [comment]
@bpamos , please check RI 2.2.0 (released today) - the issue should be fixed.

**Comment by ViktarStarastsenka** [comment]
Please reopen the ticket if the issue still persists
