### ISSUE TITLE
[Bug]: Gauge icon in header doesn't have tooltip

### ISSUE THREAD

**Issue by mavenius** [RedisInsight/RedisInsight#622]
**Preconditions** (Any important steps we need to know)
Connect to a redis instance

**Steps to reproduce** (How to reproduce what you found step by step)
- Connect to an instance
- Open Browser

**Actual behavior** (A short description of what you found)
All of the values at the top bar have a tooltip indicating what they mean, but the second one only has a number without a description or units.

**Expected behavior** (A short description of what you expected to find)
Each value has a description and units, if applicable.

**Screenshots** (Paste or drag-and-drop a screenshot or a link to a recording)
![image](https://user-images.githubusercontent.com/6155908/167930933-c3f2476d-6c91-4007-87de-4fecab7f6593.png)

**Additional context** (Operating system, version of RedisInsight, Redis database version, Redis module version, database type, connection type, logs, or any other information)
Windows 10, RedisInsight 2.0.6, Redis Standalone v6.0.1.4

**Comment by ViktarStarastsenka** [comment]
HI @mavenius, can you please provide results of the "INFO STATS" command?
Is this reproducible with other databases?

**Comment by mavenius** [comment]
> INFO STATS
# Stats
total_connections_received:6740069
total_commands_processed:67832520
instantaneous_ops_per_sec:44
bytes_received_per_sec:2353
bytes_sent_per_sec:2681
bytes_received_per_sec_human:2.30K
bytes_sent_per_sec_human:2.62K
rejected_connections:0
expired_keys:0
evicted_keys:0
keyspace_hits:2690701
keyspace_misses:8556405
pubsub_channels:88
pubsub_patterns:0
total_oom_messages:0


Based on the numbers, it looks to coincide with instantaneous_ops_per_second.

**Comment by mavenius** [comment]
Oh, and yes, this is occurring with both of my databases. They are both in Azure and are the same version.

**Comment by ViktarStarastsenka** [comment]
@mavenius , thanks, we will look into this.

**Comment by mavenius** [comment]
@ViktarStarastsenka Looks good; thank you!
