### ISSUE TITLE
[Feature Request]: Any ETA on stream support?

### ISSUE THREAD

**Issue by dallin-defimono** [RedisInsight/RedisInsight#630]
**Problem description** (Describe the problem you would like to solve with this feature request or suggested idea).
I currently cannot view and debug stream items from the GUI client like I can via the CLI. Any ETA on stream support? Ideally to see registered consumers, and message contents.

**How often do you encounter this problem** (Describe how frequently this problem occurs).
Every single time I use redis, I use streams pretty exclusively.

**Comment by ViktarStarastsenka** [comment]
@dallin-defimono , support for streams (without consumer groups) will be added with the release at the end of May (~2 weeks or less), consumer groups will be added at the end of June.
