### ISSUE TITLE
[Bug]:All keys in the pipeline should belong to the same slots allocation group

### ISSUE THREAD

**Issue by yandatou** [RedisInsight/RedisInsight#631]
When I connect a Redis database .Type is cluster.

"All keys in the pipeline should belong to the same slots allocation group"

<img width="1303" alt="截屏2022-05-13 15 54 06" src="https://user-images.githubusercontent.com/21006814/168287425-b52fdf58-d2f9-4a60-8c2c-ccf9922816f8.png">

**Comment by ViktarStarastsenka** [comment]
Hi @yandatou , can you please attach the logs?

**Comment by yandatou** [comment]
> Hi @yandatou , can you please attach the logs?
[Trinity-SIT-1652448755724-1652448762904.txt](https://github.com/RedisInsight/RedisInsight/files/8688262/Trinity-SIT-1652448755724-1652448762904.txt)

**Comment by ViktarStarastsenka** [comment]
@yandatou , please attach the RedisInsight logs as well (<home>/.redisinsight-v2/logs)

**Comment by yandatou** [comment]
> @yandatou , please attach the RedisInsight logs as well (/.redisinsight-v2/logs)
OS : Mac OS Monterey 12.3.1  CPU: Apple M1 Max
RedisInsight-v2: version 2.0.6 (2.0.6.35134)
I installed app with dmg. I don't know the log path.

**Comment by ViktarStarastsenka** [comment]
try this path:
Users/<userHomeDir>/.redisinsight-v2/logs

.redisinsight-v2 can be a hidden folder on Mac

**Comment by yandatou** [comment]
> try this path: Users//.redisinsight-v2/logs
> 
> .redisinsight-v2 can be a hidden folder on Mac
[redisinsight-2022-05-13.log](https://github.com/RedisInsight/RedisInsight/files/8692845/redisinsight-2022-05-13.log)
[redisinsight-errors-2022-05-13.log](https://github.com/RedisInsight/RedisInsight/files/8692847/redisinsight-errors-2022-05-13.log)

**Comment by ViktarStarastsenka** [comment]
@yandatou , please check RI 2.2.0 (release today) - the issue should be fixed.

**Comment by yandatou** [comment]
@ViktarStarastsenka ,I have checked, it is working, thx.
