### ISSUE TITLE
[Feature Request]: Show values with protobuf, messagepack

### ISSUE THREAD

**Issue by czd890** [RedisInsight/RedisInsight#635]
**Problem description** (Describe the problem you would like to solve with this feature request or suggested idea).

**How often do you encounter this problem** (Describe how frequently this problem occurs).

**Alternatives considered** (Describe any alternative features or products you've considered).

**Additional information** (Add any other context or details here).

**Comment by czd890** [comment]
Here is a software to refer: https://github.com/qishibo/AnotherRedisDesktopManager/

![1656069820421](https://user-images.githubusercontent.com/4011549/175524952-ce6fc649-340b-43d5-bb54-43d1dba94979.png)
![1656069906395](https://user-images.githubusercontent.com/4011549/175525152-56ba1a01-759b-4a00-82b5-88b001becd23.png)

**Comment by ViktarStarastsenka** [comment]
hi @czd890 , MessagePack is already available in 2.8.0. Protobuf will be supported with 2.10.0

**Comment by czd890** [comment]
Great to hear this and looking forward to the release of 2.10.0. 👍

**Comment by ViktarStarastsenka** [comment]
@czd890 , in 2.10.0 there will be protobuf support, but without options to specify the definition (upload the .proto file) - so only a field value (without a field name) will be displayed.
How important it is for you to specify the definition?

**Comment by czd890** [comment]
@ViktarStarastsenka, The field name is not important to me. 
it would be better if can upload the proto file to show filed names. nobody can say no to a better user experience. 😂

**Comment by ViktarStarastsenka** [comment]
@czd890 , please try protobuf formatter in RedisInsight 2.10.0 (released today).

**Comment by czd890** [comment]
Thanks, @ViktarStarastsenka 👍, I will upgrade to 2.10.0
