### ISSUE TITLE
[Bug]: Dynamic output issue in the Overview tab

### ISSUE THREAD

**Issue by zmrdltl** [RedisInsight/RedisInsight#653]
**Preconditions** (Any important steps we need to know)
k8s v1.22.2 cluster
redis cluster(clustersize : 3) pods, svc
redis insight pod(latest image), svc

**Steps to reproduce** (How to reproduce what you found step by step)
situation
1. deploy redis cluster and redis insight
![image](https://user-images.githubusercontent.com/22141521/168968968-f2e4c11d-357b-4236-bb8d-44edd8ab861b.png)

2. verifying redis cluster status
![image](https://user-images.githubusercontent.com/22141521/168969102-a85a6b01-d2c4-47d9-9c46-29977a659316.png)

3. Enter some values in browser of redis insight
![image](https://user-images.githubusercontent.com/22141521/168968010-a8fbf5c2-0f92-4ce1-838c-5366b3e45e69.png)

4. insight found redis cluster with pod ip
![image](https://user-images.githubusercontent.com/22141521/168968079-941b9366-d8dd-441b-a801-ea0faf40afcd.png)

5. connect success
![image](https://user-images.githubusercontent.com/22141521/168968712-51abda1c-d3ea-4911-ac07-c17f06095ddf.png)

6. delete pod named redis-cluster-leader-1
![image](https://user-images.githubusercontent.com/22141521/168969608-deeb13b6-215c-4347-8db9-240c7ea41287.png)
![image](https://user-images.githubusercontent.com/22141521/168969720-3faf88c8-a0c6-4ecd-ba7f-e181dae1385b.png)

7. redis-cluster-leader-1 pod revived with new pod ip
![image](https://user-images.githubusercontent.com/22141521/168969984-a12c4337-ae01-4aaa-b6d5-161f732c1856.png)

8. redis insight overview tab
![image](https://user-images.githubusercontent.com/22141521/168969912-6242ad21-3397-4782-8f1b-b737576beb46.png)

**Actual behavior** (A short description of what you found)
If one of the pods in the connected redis cluster is deleted and then revived, there is a problem that the metric information cannot be loaded in the overview.

**Additional context** (Operating system, version of RedisInsight, Redis database version, Redis module version, database type, connection type, logs, or any other information)
OS ProLinux 8 is similar as CentOS 8
![image](https://user-images.githubusercontent.com/22141521/168968485-3a16d461-21a4-47e4-92af-50fe3778fe91.png)

**Comment by ViktarStarastsenka** [comment]
@zmrdltl , could you check the Overview in a couple of minutes after reviving the node? Once Redis Cluster recovers from the failure, the overview page should start working.

**Comment by zmrdltl** [comment]
Browser and CLI functions can recognize the replayed pods. However, the OVERVIEW function only shows a white screen for over 10 minutes.

**Comment by ViktarStarastsenka** [comment]
@zmrdltl , you can restart RedisInsight as a temporary solution, and we are looking for the fix.

**Comment by ViktarStarastsenka** [comment]
RedisInsight v1 is no longer supported, please create a new issue or re-open this one if you have the same issue with RedisInsight v2.
