### ISSUE TITLE
[Feature Request]: Dark mode

### ISSUE THREAD

**Issue by worldspawn** [RedisInsight/RedisInsight#674]
**Problem description** (Describe the problem you would like to solve with this feature request or suggested idea).

Dark mode for a less darker insights experience.

**How often do you encounter this problem** (Describe how frequently this problem occurs).

100%

**Alternatives considered** (Describe any alternative features or products you've considered).

🤔 

**Additional information** (Add any other context or details here).

White backgrounds are so 2020. The eye's of tired programmers working in the dark would benefit from less shine coming from their monitor.

**Comment by ViktarStarastsenka** [comment]
Hi @worldspawn , you use RedisInsight v1, right?
Check V2 - it has dark theme support.

**Comment by worldspawn** [comment]
Ok @ViktarStarastsenka. I've got it provisioned in k8s. Am i right in that theres no v2 docker image?

**Comment by ViktarStarastsenka** [comment]
V2 is desktop application for now. But it has SNI support to add databases from k8s.
