### ISSUE TITLE
[Bug]: There is no way to select DB index.

### ISSUE THREAD

**Issue by molarro** [RedisInsight/RedisInsight#687]
RedisInsight automatically connects to DB with index 0, but there is no way to select DB with another index.

**Comment by ViktarStarastsenka** [comment]
Hi @molarro , when you add a database via host and port, there is a checkbox "Select Logical Database" where you can specify the database index to connect to.
Currently, this database index cannot be changed once the database is added (as a workaround, you can add another database with the same host and port, but different database index).

**Comment by SeriousM** [comment]
> Currently, this database index cannot be changed once the database is added (as a workaround, you can add another database with the same host and port, but different database index).

Hi, this is very news. This client is supposed to work as replacement for RESP.app and this worked well.
Any plans to introduce this feature in the near future?

**Comment by ViktarStarastsenka** [comment]
hi @SeriousM , the support for switching database indexes was added in January

**Comment by SeriousM** [comment]
I installed yesterday for the first time RedisInsight. The switch was not there.
Today I got the notification for an update and after that it was there.
Thanks for the info.
