### ISSUE TITLE
Error thrown when issuing Count Relationships in Working with Graphs

### ISSUE THREAD

**Issue by schoon** [RedisInsight/RedisInsight#709]
Redis Insight v2.0.6, Redis Stack Database locally installed via docker with RedisGraph 2.8.9

Click on Workbench
Expand Graph Section
Click on Working with Graphs
Click Create Nodes and Execute the query
Click Create Relationships and Execute the query
Click Count Relationships and Execute the query - ERROR THROWN
"errMsg: Invalid input ']': expected a relationship type line: 1, column: 13, offset: 12 errCtx: MATCH ()-[r:]->() RETURN COUNT(r) errCtxOffset: 12"

Query to have an edge name added to it, the following works:
GRAPH.QUERY movies "MATCH ()-[r:ACTED_IN]->() RETURN COUNT(r)"

**Comment by ViktarStarastsenka** [comment]
Hi @schoon , the command description is fixed, please restart the application and try agan.

**Comment by ViktarStarastsenka** [comment]
Please reopen the ticket if the issue still persists.
