### ISSUE TITLE
[Bug]: Serialized JAVA objects appear as scrambled text in RedisInsight V2.20

### ISSUE THREAD

**Issue by Longwater1234** [RedisInsight/RedisInsight#744]
**Preconditions** (Any important steps we need to know)
Saving JAVA Serialized Objects to redis.

**Steps to reproduce** (How to reproduce what you found step by step)
Simply create a Java Class implements Serializable, then store it to Redis. Then view it in RedisIngsight

**Actual behavior** (A short description of what you found)
This problem is not present in RedisInsight V1.12 or earlier, only now in newer V2.20. In older versions, the text appear as readable JSON , (see screenshots below). Now in version 2,  it's all scrambled text. In fact, in both these instances, i use the same redis version
v5.0.14.1. I have tested this with both versions of RedisInsight installed.

**Expected behavior** (A short description of what you expected to find)
I expect for it to appear as JSON stucture, labeled as 'JAVA' (as in older Insight V1).

**Screenshots** (Paste or drag-and-drop a screenshot or a link to a recording)
![new_one](https://user-images.githubusercontent.com/33986524/171987588-2d5be15b-5226-4e73-9c0b-c8ff1f7cbc14.PNG)
(V2 ABOVE- THE PROBLEM)
,
![old_one](https://user-images.githubusercontent.com/33986524/171987605-90a66660-e569-413d-815b-3c0f0d4ca4e4.png)
(V1.12 above, everything is OK)

**Additional context** (Operating system, version of RedisInsight, Redis database version, Redis module version, database type, connection type, logs, or any other information)
Windows 10, RedisInsight v2.20, redis 5.0.14.1, localhost connection

**Comment by ViktarStarastsenka** [comment]
Hi @Longwater1234 , thanks, this is a known issue and we are looking into ways to fix it.

**Comment by ViktarStarastsenka** [comment]
@Longwater1234 , please try it with RedisInsight 2.10.0 (released today).
