### ISSUE TITLE
[Bug]:Connect failed

### ISSUE THREAD

**Issue by yandatou** [RedisInsight/RedisInsight#747]
<img width="1183" alt="image" src="https://user-images.githubusercontent.com/21006814/172156588-da24f49e-ebed-4ea7-9fed-d20b0611c742.png">
[redisinsight-2022-06-06.log](https://github.com/RedisInsight/RedisInsight/files/8844233/redisinsight-2022-06-06.log)
[redisinsight-errors-2022-06-06.log](https://github.com/RedisInsight/RedisInsight/files/8844239/redisinsight-errors-2022-06-06.log)

**Comment by yandatou** [comment]
版本2.2.0 (2.2.0.41213)
V2

**Comment by arthosofteq** [comment]
@yandatou Thank you for the bug report. I have a few questions here.
1. What is the Redis Cluster setup? (number of shards)
2. As I can see there are 12 keys only. If you provide us these key names (!only. without values) it will help a lot, if it is possible

**Comment by ViktarStarastsenka** [comment]
@yandatou , this issue relates to ioredis, here is the corresponding ticket: https://github.com/luin/ioredis/issues/1602.
We will try to come up with a workaround in RI and see if it is possible to fix it with July release.

**Comment by ViktarStarastsenka** [comment]
@yandatou , the workaround was delivered, please let me know if this issue is still relevant.

**Comment by yandatou** [comment]
Thank you. This issue can be closed.
