### ISSUE TITLE
[Bug]: Redis Streams entry display with duplicate field names

### ISSUE THREAD

**Issue by kamran-redis** [RedisInsight/RedisInsight#757]
Redis Stream entry can have duplicate field names e.g. 
```
127.0.0.1:6379> xadd a * a 1 a 2
"1654678140381-0"
127.0.0.1:6379> xrange   a - +
1) 1) "1654678140381-0"
   2) 1) "a"
      2) "1"
      3) "a"
      4) "2"
127.0.0.1:6379>
```
RI treats an entry as a dictionary and only shows one field.
<img width="1420" alt="Cursor_and_db1_-_Browser" src="https://user-images.githubusercontent.com/20688198/172574586-dfa3b501-29ad-454e-9e53-8c015fc56b24.png">

**Comment by ViktarStarastsenka** [comment]
fixed with 2.4.0 (released today).
