### ISSUE TITLE
[Bug]:couldn't connect:command "DBSIZE"is not allowed

### ISSUE THREAD

**Issue by Harris6666** [RedisInsight/RedisInsight#769]
because some commands are not allowed that couldn't connect to redis
![image](https://user-images.githubusercontent.com/13151111/173326261-3d7f6a33-78f0-4c56-8fbc-6c1a67962e3a.png)

**Comment by ViktarStarastsenka** [comment]
@Harris6666 , thank you for raising this, we will see what we can do here.

**Comment by ViktarStarastsenka** [comment]
hi @Harris6666 , please try 2.8.0 (recently released).
