### ISSUE TITLE
[Bug]: New Docker distribution does not include tools necessary to implement healthcheck

### ISSUE THREAD

**Issue by zam6ak** [RedisInsight/RedisInsight#771]
Until I updated to new Docker image of RedisInsight I was able to use following in my `docker-compose.yml`

```
        healthcheck:
            test: ["CMD-SHELL", "curl --fail --silent --request GET http://localhost:8001/healthcheck/ || exit 1"]
```

After the update, the above fails because "curl" is no longer part of the container image (neither is "wget")
I know I can customize the container with my own Dockerfile but this used to work just fine...

Here is the image I am using:

```
docker pull redislabs/redisinsight:latest

latest: Pulling from redislabs/redisinsight
Digest: sha256:8af58038684f7c2ddb54e6044333cbc656c0137b4fa7b2aa85daf58d029ced56
Status: Image is up to date for redislabs/redisinsight:latest
docker.io/redislabs/redisinsight:latest
```

**Comment by zam6ak** [comment]
@GnaneshKunal Removing `curl`, made simple, one line healtchecks not possible. If project preference is to use python, then why not provide official script that others who need healtcheck can just use?

Also, please note that `curl` removal didn't only impact healtcheck. 
Simple calls to preregister servers (by invoking POST to `/api/instance/` for example) from inside container are not possible either.

For now, I am using older version (1.10) that still contains `curl` but please consider making the container distro easier to use.

Thanks
z

**Comment by TristanB1994** [comment]
@zam6ak I would offer using the redis-cli binary which should be available in any redis module / server as a solution for the healthcheck. This is what I use.
`CMD-SHELL redis-cli -h your.host.ip.addr -p your_port ping || exit 1`

**Comment by zam6ak** [comment]
@TristanB1994  if I am not mistaken, that command is useful to perform healthcheck of >**Redis**< container.
This issue is for healthcheck command of >**RedisInsight**< container.

**Comment by GnaneshKunal** [comment]
@zam6ak 

I'll add a package to the container to make the healthcheck easier. Either curl or other light weight package.

**Comment by zam6ak** [comment]
@GnaneshKunal  my vote would be for `curl` and that would cover both healtchcheck and API integration scenarios.
But in either case, thanks for looking into this!

**Comment by GnaneshKunal** [comment]
Hey @zam6ak 

`curl` is added back in the latest version. 


Closing the issue. Open if having any issues.
