### ISSUE TITLE
[Bug]: Autodiscover Sentinel instance

### ISSUE THREAD

**Issue by aurril** [RedisInsight/RedisInsight#804]
**Preconditions** (Any important steps we need to know)
None

**Steps to reproduce** (How to reproduce what you found step by step)

1. Start application and select "ADD REDIS DATABASE"
2. Select Autodiscover Database
3. Select Redis Sentinel in the radio selection
4. Fill out connection information
5. Check "Use TLS"
6. Keep "No CA Certificate" selection
7. Click on "Discover database"

**Actual behavior** (A short description of what you found)
Error window with the following text: "ERR unknown command 'quit', with args beginning with:"

**Expected behavior** (A short description of what you expected to find)
A list of available Redis servers.

**Screenshots** (Paste or drag-and-drop a screenshot or a link to a recording)

**Additional context** (Operating system, version of RedisInsight, Redis database version, Redis module version, database type, connection type, logs, or any other information)
RedisInsight: 2.2.0
Redis: 7.0.2
OS: Windows 10

**Comment by ViktarStarastsenka** [comment]
Hi @aurril , thanks for reporting this, we are investigating the issue.

**Comment by ToshY** [comment]
@aurril I'm curious on what do you fill in for the host/port? I'm getting the exact same error message.

**Comment by ViktarStarastsenka** [comment]
@aurril , @ToshY , please try it with 2.8.0. - should be fixed with this version.
