### ISSUE TITLE
[Bug]: Column lable

### ISSUE THREAD

**Issue by yaronlevi** [RedisInsight/RedisInsight#81]
Hi (-:

![CleanShot 2021-12-06 at 09 47 35@2x](https://user-images.githubusercontent.com/5398977/144807484-8997e3ea-a042-40f1-98b8-60a3626ab335.jpg)

Not sure if it's a bug, but it's very confusing.
Especially when it's near the size column.
Should be, for example, 172 minutes/seconds...

**Comment by ViktorStarostenko** [comment]
Hi @yaronlevi , thanks, this has already been prioritized and taken to work.

**Comment by ollopaci** [comment]
This issue has been addressed in the latest update of RedisInsight 2.0.3.

**Comment by yuvital-render** [comment]
Thank you!
