### ISSUE TITLE
[Bug]:All keys in the pipeline should belong to the same slots allocation group

### ISSUE THREAD

**Issue by l42606525** [RedisInsight/RedisInsight#826]
When I connect a Redis database .Type is cluster.
version:2.4.0

![QQ截图20220628170926](https://user-images.githubusercontent.com/47105149/176140887-bff4da96-ddee-4eec-96af-a4e9197b971b.png)

![QQ图片20220628170813](https://user-images.githubusercontent.com/47105149/176140680-e4ddcdf1-436f-4681-8d37-635bc4b7ab3d.png)

**Comment by ViktarStarastsenka** [comment]
Hi @l42606525 , thanks, this is a known issue that we currently work on, hopefully will be fixed with July release.

**Comment by l42606525** [comment]
OK, thanks for your reply
