### ISSUE TITLE
[Feature Request]: Publicly publish image on dockerhub or other Container Library

### ISSUE THREAD

**Issue by Sylvain-Royer** [RedisInsight/RedisInsight#836]
My team is currently using RedisInsight 1.X, and I'm interested in moving over to 2.X. However, I don't see any publicly available images for 2.X currently.

Is there any plan/timeout regarding when a docker image of 2.X will be publicly available?

**Comment by ViktarStarastsenka** [comment]
Hi @Sylvain-Royer , we are planning to out docker image of 2.X in August/September.

**Comment by Sylvain-Royer** [comment]
Awesome, thank you very much! Looking forward to migrating over to the 2.X version then.

**Comment by Ashtonian** [comment]
Excited

**Comment by ViktarStarastsenka** [comment]
hey, currently, we are working on the architecture to provide the best experience, so the timelines shift a little - to ~November.

**Comment by deeaitche** [comment]
> Docker RedisInsight 2.X will be released in early 2023.

I saw this message in the ``RedisInsight 1.X End of Life Cycle`` prompt box.

**Comment by ViktarStarastsenka** [comment]
@deeaitche , yep, this is the correct timeline - the release date shifted to early 2023.

**Comment by NikonNLG** [comment]
Looks like 2.x version still not released.
Can you please provide new date for 2.x?

**Comment by Ashtonian** [comment]
Whats the hold up, this is just a dockerfile change right? The application in question is on v 2.24 with the last release being in april of 2023 and the original v2 was in april of 2022.
