### ISSUE TITLE
[Bug]:Request Timeout

### ISSUE THREAD

**Issue by jamespauly** [RedisInsight/RedisInsight#841]
**Preconditions** (Any important steps we need to know)
Azure Redis Cache
Docker

**Steps to reproduce** (How to reproduce what you found step by step)
Add a Azure Redis DB in Redis Insights
Click to connect to the Redis DB

**Actual behavior** (A short description of what you found)
Sometimes  when clicking the link to connect to the DB you get a Request Timeout Error.  See the image. 

**Expected behavior** (A short description of what you expected to find)
No request timeout error.  Maybe making configurable

**Screenshots** (Paste or drag-and-drop a screenshot or a link to a recording)
![image](https://user-images.githubusercontent.com/5694319/176703363-80b5be93-c1b7-4fbd-82b6-37d3aa5dcfee.png)

**Additional context** (Operating system, version of RedisInsight, Redis database version, Redis module version, database type, connection type, logs, or any other information)

redis 6.0.14
redisinsights 2.2.0

6/29/2022, 1:38:54 PM | ERROR | TimeoutInterceptor | Request Timeout. GET /api/instance/b7f0931d-317d-4add-ac79-1eba0bb021ac/connect | {"stack":[{}]}
6/29/2022, 1:38:55 PM | ERROR | RedisService | Failed connection to the redis database. | {"stack":[{"message":"connect ETIMEDOUT"}]}
6/29/2022, 1:38:59 PM | ERROR | RedisService | Failed connection to the redis database. | {"stack":[{"message":"connect ETIMEDOUT"}]}
6/29/2022, 1:38:59 PM | ERROR | InstancesBusinessService | Failed connection to database instance b7f0931d-317d-4add-ac79-1eba0bb021ac | {"stack":[{"message":"connect ETIMEDOUT"}]}
6/29/2022, 1:39:00 PM | ERROR | RedisService | Failed connection to the redis database. | {"stack":[{"message":"connect ETIMEDOUT"}]}
6/29/2022, 1:39:07 PM | ERROR | RedisService | Failed connection to the redis database. | {"stack":[{"message":"connect ETIMEDOUT"}]}
6/29/2022, 1:39:12 PM | ERROR | RedisService | Failed connection to the redis database. | {"stack":[{"message":"connect ETIMEDOUT"}]}
6/29/2022, 1:39:15 PM | ERROR | RedisService | Failed connection to the redis database. | {"stack":[{"message":"connect ETIMEDOUT"}]}
6/29/2022, 1:39:17 PM | ERROR | RedisService | Failed connection to the redis database. | {"stack":[{"message":"connect ETIMEDOUT"}]}
6/29/2022, 1:39:29 PM | ERROR | RedisService | Failed connection to the redis database. | {"stack":[{"message":"connect ETIMEDOUT"}]}
6/29/2022, 1:39:31 PM | ERROR | RedisService | Failed connection to the redis database. | {"stack":[{"message":"connect ETIMEDOUT"}]}
6/29/2022, 1:39:47 PM | ERROR | RedisService | Failed connection to the redis database. | {"stack":[{"message":"connect ETIMEDOUT"}]}
6/29/2022, 1:40:04 PM | ERROR | RedisService | Failed connection to the redis database. | {"stack":[{"message":"connect ETIMEDOUT"}]}

**Comment by ViktarStarastsenka** [comment]
can you please try this?
https://github.com/RedisInsight/RedisInsight/issues/525#issuecomment-1156317256

**Comment by ViktarStarastsenka** [comment]
Hi @jamespauly , did you happen to try configuring the timeout?

**Comment by ViktarStarastsenka** [comment]
@jamespauly , you can customize the connection timeout with RedisInsight 2.20 (released today).
