### ISSUE TITLE
[Feature Request]: Be able to set Default Sort Column of the DatabaseList View

### ISSUE THREAD

**Issue by jamespauly** [RedisInsight/RedisInsight#843]
**Problem description** (Describe the problem you would like to solve with this feature request or suggested idea).

**How often do you encounter this problem** (Describe how frequently this problem occurs).

**Alternatives considered** (Describe any alternative features or products you've considered).

**Additional information** (Add any other context or details here).
Be able to set Default Sort Column of the DatabaseList View

**Comment by ViktarStarastsenka** [comment]
hi @jamespauly , can you please briefly describe your use case? how many databases do you have?

**Comment by jamespauly** [comment]
In the DatabasesList.tsx I made a change so that the Databases always list by "name". ~ Line 83

  const sort: PropertySort = {
    field: 'name',
    direction: 'asc',
  }

![image](https://user-images.githubusercontent.com/5694319/176805112-d43161e6-e1ae-4b4d-8a04-60e033b515dc.png)

I was just wondering if that could be made configurable because right now it is hard coded to lastConnection.

Thanks,
James

**Comment by ViktarStarastsenka** [comment]
Hi @jamespauly , this has been added with 2.6.0 (released yesterday).
Thanks for your idea.
