### ISSUE TITLE
[Feature Request]: Sort keys in browser view, and delete multi-items one time

### ISSUE THREAD

**Issue by Simbafa** [RedisInsight/RedisInsight#866]
**Problem description** (Describe the problem you would like to solve with this feature request or suggested idea).

The keys in browser view are listed without sorting. It's hard to find one key.
And key items can only be deleted one by one.

**How often do you encounter this problem** (Describe how frequently this problem occurs).

**Alternatives considered** (Describe any alternative features or products you've considered).

**Additional information** (Add any other context or details here).

**Comment by ViktarStarastsenka** [comment]
Hi @Simbafa , the reason for not having sorting is that RedisInsight gets unsorted data from Redis with each scan.
Will filter by key name help you find the key you need?
Also if you use namespaces in your key names, you can use the Tree View to group the keys by namespaces.

We are planning to deliver Bulk delete feature with the July release - in this case you will need to set filters per key name or key type in Browser to delete the keys in bulk. Will this cover your use case?

**Comment by Simbafa** [comment]
Hi @ViktarStarastsenka ,
Filter by key name is helpful. 
Although it doesn't matter much, if sorted, it's more comfortable.

**Comment by Tomicapo** [comment]
I would like to be able to sort by storage space to find the biggest keys and hashes. This would be really useful.

**Comment by Tomicapo** [comment]
Also, if keys are big enough, the app will hang, so being able to delete without loading the content would be great.

**Comment by KemikalGeneral** [comment]
A filter/sort would be AMAZING! 

Currently, trying to find a key, or a list of keys by a certain criteria is a small nightmare.

I don't see that Sorting and Filtering by key ID is any good as we often don't know then, and certainly not off by heart to be able to know which is which.

For instance, sort by a 'createdBy' field, would be so helpful.

**Comment by TomasTokaMrazek** [comment]
Comming from RESP.app, this is a dealbreaker. I am forced to downgrade back. Tree view mitigates the issue slightly, but still does not allow me to quickly glance at added keys and makes searching for a specific key needlessly annoying.

**Comment by richard-d-vindico** [comment]
This seems like such a menial feature, that I can't believe it's an actual issue?

**Comment by emberTrev** [comment]
I want to put my vote behind a sort feature as well.

We are naming our keys with a `:` separator for "folders" or "categories". It would be wonderful to be able to sort the categories alphabetically to make it faster to get to the data I want.

I understand this request may not be reasonable since some databases contain so many keys that a sort would take a long time. I am still going to put this out there in case the devs decide it is feasible. Even just having a way to toggle sort on if you want it would be great! (so large databases can choose to just never enable it)

**Comment by snotmare** [comment]
You'll get another vote in favor of a sort feature to me. That's the first issue I noticed when I tried out this app. Having the ability to sort with headings would also be nice to have.

**Comment by ViktarStarastsenka** [comment]
thanks for the feedback

we are thinking about enhancing the Tree view, what do you think about the option attached?
RedisInsight will:
1. allow to switch between database indexes in the Tree view
1. allow to sort per key name
1. display only the key name part after the last delimiter to optimize space

<img width="951" alt="image" src="https://github.com/RedisInsight/RedisInsight/assets/99594890/8887ab67-a754-48d9-b618-ec0c7bae5007">

**Comment by snotmare** [comment]
I kinda like the tree with the dbs. As long as you can sort within each db so the keys are alphabetical, I think you'd satisfy this feature request.

This is probably another feature request, but would it be possible to set up an alias for the dbs? Sometimes it's hard to remember what DB we've set up for what purpose.

**Comment by ViktarStarastsenka** [comment]
@snotmare , you mean to add aliases for database indexes (aka logical databases), not Redis database connection, right?

**Comment by snotmare** [comment]
@ViktarStarastsenka correct. For example: DB0 = "My name", DB1 = "My other name", etc. Sorry for the confusion on terms.

**Comment by ViktarStarastsenka** [comment]
@snotmare , I can't commit, but I took note

**Comment by emberTrev** [comment]
That new tree view looks really nice. I like it.

**Comment by ViktarStarastsenka** [comment]
sorting is available in the Tree view (released in 2.36 as a part of major Tree view improvements).

**Comment by Misiu** [comment]
@ViktarStarastsenka thank you for the update, but what about deleting multiple items at once?
I'm not sure if there is a dedicated issue/feature request for that, if not, then this one should still be open.

**Comment by ViktarStarastsenka** [comment]
@Misiu , there is a multi-deletion available in bulk actions. You can set a filter per key name or key type, then open bulk actions (a control next to adding a key), and delete all the keys that match the filter set

**Comment by Misiu** [comment]
@ViktarStarastsenka found it 😄 
I was trying to select multiple items in the list view using Ctrl or Shift Key and clicking Delete. I also checked in the context menu, but there are only two options available:
![image](https://github.com/RedisInsight/RedisInsight/assets/1741838/d647217f-e4e3-468f-bd26-39e31d228349)
(first selects all text on the screen, and the second opens dev tools, probably both are not needed)

What do you think about adding an option to select multiple items with Ctrl or Shift and be able to delete them with Delete?
Should I create a new issue?

**Comment by ViktarStarastsenka** [comment]
@Misiu , we already have a couple of similar issues open.
But currently, these improvements are not prioritized for any upcoming releases, maybe sometime in the future.
