### ISSUE TITLE
[Quesion]: Memory means in Memory Analyzer (RedisInsight v1)

### ISSUE THREAD

**Issue by CaiusBallad** [RedisInsight/RedisInsight#867]
In Memory Analysis ——> Memory Analyzer with default status, we can see the **Total Memory**, eg is 340M, however when i use **info memory** command in redis-cli, the used_memory_dataset is 440M, so what is the difference value of 100M?

The same key of memory in Memory Analyzer and MEMORY USAGE command has very very small difference which is also something that i am not very understand.

for example, a string key in Memory Analyzer show 2494749, and  in MEMORY USAGE is 2494767

so I want to know the memory in Memory Analyzer is pure value memory? or hope give me anything I can read to understand this.

**Comment by GnaneshKunal** [comment]
@CaiusBallad 


`MEMORY USAGE` command gives the entire information required to store the key. The entire information includes the key storage, value storage, key metadata and other details that includes encoding details, compression details, internal data structure type expiry, last time the key was accessed and more.

Memory analysis gives just the memory of key + key metadata + value. It doesn't account for expiry, last time accessed, encoding and other stuffs. 

Also a note, the key metadata size isn't updated to the latest version of redis. So the approximate data type metadata sizes are of redis 5 (early version) so the metadata size is not pretty accurate if the datatype's internal data structure is a new one.

**Comment by CaiusBallad** [comment]
@GnaneshKunal  thanks for the details, that means the extra memory (which not include the memory of key + key metadata + value) will grow with the number of key in Redis.

And also when I found the difference is too big, that means I have too many keys!

**Comment by GnaneshKunal** [comment]
@CaiusBallad 

Okay. Could you let us know with which key and it's datatype is having huge disparity.

**Comment by CaiusBallad** [comment]
@GnaneshKunal 
We have a node in cluster which is 32G.

**Memory Analyzer** of .rdb shows **Total Memory** is 7.87GB, and **Total Keys** is 20.5M, at the same time the dataset is 12.63GB.
**Keyspace Summary** with * Key Pattern shows  as following:
- ZSET 3.04GB
- HASH 2.69GB
- STRING 1.65GB
- SET 415MB
- LIST 81MB

**Comment by GnaneshKunal** [comment]
@CaiusBallad 

Hmm. Which datatype has huge disparity? Do you have any idea on how the distribution of the datatypes are in the db?

This would help us figure out and see if could update the metadata of the datatypes.

**Comment by ViktarStarastsenka** [comment]
please re-open the ticket if the question is still relevant
