### ISSUE TITLE
[Bug]: garbled.  "\xac\xed\x00\x05t\x00\x0ctokenSession". -> 

### ISSUE THREAD

**Issue by buptzyf** [RedisInsight/RedisInsight#873]
version:
<img width="283" alt="image" src="https://user-images.githubusercontent.com/11564966/178142478-3a0ee39d-32cb-4870-9841-7d24bcb97a0f.png">

description:

key:  \xac\xed\x00\x05t\x00\x0ctokenSession

<img width="613" alt="image" src="https://user-images.githubusercontent.com/11564966/178142424-a0d79e2d-10fd-4c3c-a520-befb505f8791.png">

when tounch it:
<img width="320" alt="image" src="https://user-images.githubusercontent.com/11564966/178142395-be9c18f7-b460-480f-b47e-d7cdbeb4416f.png">

**Comment by ViktarStarastsenka** [comment]
Hi @buptzyf , thanks for reporting this. It is a known issue that we are currently working on, hopefully will be fixed with August/September release.

**Comment by ViktarStarastsenka** [comment]
hi, please try 2.8.0 - this should be fixed with this version, you will be able to see keys and their details, but please use CLI or Workbench to edit the data - to prevent data loss.
Please reopen the ticket if it is still relevant.
