### ISSUE TITLE
[Bug]: Taiwan and Hong Kong Is Part of China. Downlaod page show error country.

### ISSUE THREAD

**Issue by SetGeek** [RedisInsight/RedisInsight#874]
**Preconditions** (Any important steps we need to know)
Taiwan and Hong Kong Is Part of China. [Downlaod page](https://redis.com/redis-enterprise/redis-insight/#insight-form) show error country.

**Steps to reproduce** (How to reproduce what you found step by step)
Taiwan and Hong Kong Is Part of China.  [Downlaod page](https://redis.com/redis-enterprise/redis-insight/#insight-form) show error country.

**Actual behavior** (A short description of what you found)
Taiwan and Hong Kong Is Part of China.  [Downlaod page](https://redis.com/redis-enterprise/redis-insight/#insight-form) show error country.
![image](https://user-images.githubusercontent.com/23478148/178177005-2d95a38d-d30f-4888-8801-a678d01adf35.png)

**Expected behavior** (A short description of what you expected to find)
Taiwan and Hong Kong Is Part of China.  [Downlaod page](https://redis.com/redis-enterprise/redis-insight/#insight-form) show error country.

**Screenshots** (Paste or drag-and-drop a screenshot or a link to a recording)
Taiwan and Hong Kong Is Part of China.  [Downlaod page](https://redis.com/redis-enterprise/redis-insight/#insight-form) show error country.

**Additional context** (Operating system, version of RedisInsight, Redis database version, Redis module version, database type, connection type, logs, or any other information)
Taiwan and Hong Kong Is Part of China.  [Downlaod page](https://redis.com/redis-enterprise/redis-insight/#insight-form) show error country.

**Comment by SetGeek** [comment]
Taiwan and Hong Kong Is Part of China.  Downlaod page show error country.

**Comment by SetGeek** [comment]
https://redis.com/redis-enterprise/redis-insight/#insight-form

**Comment by HayateLaTech** [comment]
Isn't China part of Taiwan and Hong Kong instead? O:

The **Downlaod** page surely shows China as a option, yet it's obviously a error country.

this do be important and bug bug bug, I am all for Taiwan yada yada :3
