### ISSUE TITLE
[Feature Request]:RedisInsight v2 windows installer MSI package 

### ISSUE THREAD

**Issue by sraza1983** [RedisInsight/RedisInsight#895]
Redisinsight v2.0 is only available in exe format for Windows. This is an issue as the installation lacks,

1. Full control of the desktop
2. Manage upgrades.
3. Installing shortcuts to appdata causes roaming issues
4. Launch executables from standard Windows folders

Also, there is no way to customize the installation directory. (Installation in c:/program files.

**Comment by XChikuX** [comment]
Please add this feature.
I understand that you would like information on how companies use redisinsights.
But I would like to pull automatic latest images to avoid bugging my devs to keep upgrading for new features.
