### ISSUE TITLE
[Bug]:redis.exceptions.ResponseError: unknown command `MODULE`, with args beginning with: `LIST`,

### ISSUE THREAD

**Issue by shyam-ks** [RedisInsight/RedisInsight#902]
Not able to get past this screen 
![image](https://user-images.githubusercontent.com/88625905/179184110-9500fbc9-92db-4d22-bace-29a6d1415360.png)

Kubernetes based deployment - https://docs.redis.com/latest/ri/installing/install-k8s/#create-the-redisinsight-deployment-and-service

Latest version is having issues, Version redislabs/redisinsight:1.12.0  works fine

Below the error given while deploying latest version
```
ERROR:rediscluster.client:BaseException
10
Traceback (most recent call last):
9
  File "/usr/local/lib/python3.7/site-packages/rediscluster/client.py", line 631, in _execute_command
8
    return self.parse_response(connection, command, **kwargs)
7
  File "/usr/local/lib/python3.7/site-packages/redis/client.py", line 915, in parse_response
6
    response = connection.read_response()
5
  File "/usr/local/lib/python3.7/site-packages/redis/connection.py", line 756, in read_response
4
    raise response
3
redis.exceptions.ResponseError: unknown command `MODULE`, with args beginning with: `LIST`,
2
WARNING 2022-07-15 07:49:37,726 redisinsight Failed to get module list for database 1. Proceeding with empty module list.
1
WARNING:redisinsight:Failed to get module list for database 1. Proceeding with empty module list.
```

**Comment by GnaneshKunal** [comment]
Hey @shyam-ks 

Is the application running behind a proxy? How is the application hosted?

Can you please check the network console and see what exactly the error is?

**Comment by GnaneshKunal** [comment]
Also @shyam-ks 

If the server is behind a proxy, the issue might be related to https://github.com/RedisInsight/RedisInsight/issues/879 and not related to `MODULE` command's availability.

**Comment by iWuYc** [comment]
"ERR unknown command 'memory'"![pic](https://github.com/iWuYc/pic/blob/main/Snipaste_2022-08-26_17-06-25.png?raw=true);;;
when I using '\[' Character to query data.

**Comment by ViktarStarastsenka** [comment]
@iWuYc , could you please run `memory stats` in CLI and send the results (successful run or an error)?

**Comment by iWuYc** [comment]
wrong! Show this message "ERR unknown command 'memory'"

**Comment by iWuYc** [comment]
> @iWuYc , could you please run `memory stats` in CLI and send the results (successful run or an error)?

Redis Server Version: 3.2.8,
Cluster mode.

**Comment by ViktarStarastsenka** [comment]
RedisInsight v1 is no longer supported, please create a new issue or re-open this one if you have the same issue with RedisInsight v2.
