### ISSUE TITLE
[Feature Request]:TCP/IP over SSH?

### ISSUE THREAD

**Issue by iamnobodysir** [RedisInsight/RedisInsight#914]
Problem description
- No SSH options to choose connection method

**Comment by hao159** [comment]
U can use another redis desktop manager

**Comment by ViktarStarastsenka** [comment]
@iamnobodysir , @hao159 , currently RedisInsight does not have the SSH options, but let me see if it is possible to add them in the nearest releases (around October).

**Comment by dyaskur** [comment]
Looking forward for this feature

**Comment by jaspal747** [comment]
Look forward to having this feature. Thanks

**Comment by gghez** [comment]
unusable without this feat. should be a must have on any database client.

**Comment by Budapresst** [comment]
Must have!

**Comment by nisart007** [comment]
Now RESP is planning to integrate into redisInsight :
https://redis.com/blog/respapp-joining-redis/
We will expect this feature will be availabe soon.

**Comment by Vincz** [comment]
Looking forward for this feature too!

**Comment by ViktarStarastsenka** [comment]
hi, added support for SSH tunnel on the form to add a new database connection in RedisInsight 2.18 (released today)

**Comment by 6utt3rfly** [comment]
@ViktarStarastsenka  This is great! Is there a reason to have to paste the private key vs providing a file path?

**Comment by ViktarStarastsenka** [comment]
hi @6utt3rfly , the file path selector will be added a bit later
