### ISSUE TITLE
[Feature Request]: Allow to leave the query in-place after running it

### ISSUE THREAD

**Issue by avifatal** [RedisInsight/RedisInsight#916]
**Problem description** 
When running a query in the graph, the query editor deletes the query and you need to click on "arrow up" to bring it back.
It would be nice if  I would be able to decide if the query should be removed or not. (small switch button).
When working on complex queries you want sometimes to comment things and run queries  without losing the context.
Like standard SQL editor.

**How often do you encounter this problem** (Describe how frequently this problem occurs).
Every time I run a query.

Thanks

**Comment by ViktarStarastsenka** [comment]
hi @avifatal , this feature will be added to Workbench (RedisInsight V2) with 2.10.0 (September)

**Comment by ViktarStarastsenka** [comment]
hello @avifatal , please use Workbench in RedisInsight 2.10.0 - you can configure this behavior in Settings.
