### ISSUE TITLE
[Bug]: django.request Forbidden

### ISSUE THREAD

**Issue by michaelswierszcz** [RedisInsight/RedisInsight#966]
**Preconditions** (Any important steps we need to know)

running in kubernetes following the installation steps documented here: https://docs.redis.com/latest/ri/installing/install-k8s/

**Steps to reproduce** (How to reproduce what you found step by step)

- Navigate to redis insight
- click on a redis cluster
- click on CLI

**Actual behavior** (A short description of what you found)

The following error is displayed on the screen:
Connecting...
Pinging Redis server on redis:6379... error pinging Redis server (edited) 

**Expected behavior** (A short description of what you expected to find)

The CLI should load correctly

**Screenshots** (Paste or drag-and-drop a screenshot or a link to a recording)

**Additional context** (Operating system, version of RedisInsight, Redis database version, Redis module version, database type, connection type, logs, or any other information)

Redis connection works, and clicking on browser shows the keys correctly, its only the CLI that fails. The following error is displayed in the pod 

/db$ tail -f redisinsight.log
WARNING 2022-07-27 12:55:13,845 django.request Forbidden: /api/instance/<instance id>/cli/ping/
WARNING 2022-07-27 12:55:24,335 django.request Forbidden: /api/instance/<instance id>/cli/send-command/

**Comment by GnaneshKunal** [comment]
Hi @michaelswierszcz 

Can you try the build mentioned in the following comment - https://github.com/RedisInsight/RedisInsight/issues/879#issuecomment-1191790107

That should fix the issue. Also, please use FQDN or or other static address/host that won't change.

**Comment by michaelswierszcz** [comment]
worked! ty
