### ISSUE TITLE
[Bug]: Workbench blank screen when opening

### ISSUE THREAD

**Issue by gerhardcit** [RedisInsight/RedisInsight#986]
**Preconditions** (Any important steps we need to know)
Download and Install RedistInsight-V2 

**Steps to reproduce** (How to reproduce what you found step by step)
Click on Workbench icon or find a timeseries and click on the View in Workbench link.

**Actual behavior** (A short description of what you found)
Blank screen.

**Expected behavior** (A short description of what you expected to find)
Workbench should show.

**Screenshots** (Paste or drag-and-drop a screenshot or a link to a recording)
<img width="1593" alt="Screenshot 2022-08-07 at 12 19 43" src="https://user-images.githubusercontent.com/5508278/183286274-0acd1956-63a6-4586-a7a6-4df91c1fcb16.png">

**Additional context** (Operating system, version of RedisInsight, Redis database version, Redis module version, database type, connection type, logs, or any other information)

TypeError: Cannot read properties of null (reading 'split')
    at vg (renderer.prod.js:formatted:11171:27)
    at XEe (renderer.prod.js:formatted:96319:25)
    at uNe (renderer.prod.js:formatted:96583:25)
    at Cs (renderer.prod.js:formatted:270839:21)
    at La (renderer.prod.js:formatted:271635:21)

MacBook Pro (16-inch, 2019)
Mac OS BigSur

RedisInsight V2
Version 2.6.0 (2.6.0.54052)

**Comment by ViktarStarastsenka** [comment]
@gerhardcit , please try it with 2.8.0. - should be fixed with this version.

**Comment by xraid** [comment]
on M1 with Version 2.8.0 (2.8.0.59623) workbench is blank !!! ???

**Comment by gerhardcit** [comment]
same here Intel Mac. Redis workbench blank.

MacBook Pro (16-inch, 2019)
Mac OS BigSur

<img width="1001" alt="Screenshot 2022-08-24 at 14 27 52" src="https://user-images.githubusercontent.com/5508278/186418512-e5efcc81-93a5-4452-a91b-00fd3f3e2f38.png">

**Comment by gerhardcit** [comment]
It still breaks here:

<img width="1576" alt="Screenshot 2022-08-24 at 14 33 26" src="https://user-images.githubusercontent.com/5508278/186419373-e3807048-c896-4f04-ae5f-59d639588ff8.png">

```
renderer.prod.js:formatted:274635 TypeError: Cannot read properties of null (reading 'split')
    at jNe (renderer.prod.js:formatted:98048:27)
    at Cs (renderer.prod.js:formatted:274026:21)
    at xl (renderer.prod.js:formatted:277805:25)
    at vu (renderer.prod.js:formatted:277037:25)
    at bu (renderer.prod.js:formatted:277030:21)
```

**Comment by ViktarStarastsenka** [comment]
@xraid , @gerhardcit , could you please open the redisinsight.db file (located in the .redisinsight-v2 folder), and remove everything from the command_execution table?
This should help.

**Comment by gerhardcit** [comment]
@ViktarStarastsenka , i might be missing something "open the redisinsight.db"? could you explain more? how to do that?

**Comment by gerhardcit** [comment]
My installation was fresh.. so I just deleted redisinsight.db thx.. that solves it.
