### ISSUE TITLE
Connection timeout while connecting Redis DB 

### ISSUE THREAD

**Issue by Jeevananthan-23** [RedisInsight/RedisInsight#989]
**Connection timeout while connecting Redis DB**

Hi, 
While connecting Redis DB from docker image which is running in locally with port default: 6379 the respective error follows.
![image](https://user-images.githubusercontent.com/71455761/183413236-1d98eb55-5eec-4d07-8b71-c11d4edb6403.png)

**Comment by ViktarStarastsenka** [comment]
hi @Jeevananthan-23 , could you please run the following command in redis-cli and send the results?
echo "ping" | redis-cli -h 127.0.0.1 -p 6379 -x

**Comment by Jeevananthan-23** [comment]
hi @ViktarStarastsenka, I have connected the DB via IP which is found in my docker networks. But I can't able to see the data.
![image](https://user-images.githubusercontent.com/71455761/183656079-f190a455-10c8-4db7-96fe-1abde0b025bc.png)

**Comment by GnaneshKunal** [comment]
@Jeevananthan-23 

Can you please confirm that you have keys in the database and are not able to see them in the "Browser" tab?

You can connect to the redis in the container via redis-cli and run `KEYS *` command and check it.

If you are still facing issues, can you please share the logs from '/db/redisinsight.log' in the docker container.

**Comment by Jeevananthan-23** [comment]
@GnaneshKunal 
Can't find anything in redis-cli while running `KEYS * `returns empty set.
not find anything in redisinsight logs

**Comment by Jeevananthan-23** [comment]
@ViktarStarastsenka , @GnaneshKunal 
I able to connect in my clinet but in redisinsight not able to see anything.
